### ISSUE TITLE
[doc] 9.1.2.3  Using RBD with Dynamic Persistent Volumes

### ISSUE THREAD

**Issue by jsegitz** [SUSE/doc-caasp#1005]
9.1.2.3  Using RBD with Dynamic Persistent Volumes:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_RBD-dynamic-persistent-volumes

Also for the other examples: Don't use the admin key for allowing access to the SES cluster. Create a dedicated user for this

**Comment by r0ckarong** [comment]
@c3y1huang Could you provide the steps needed to create a dedicated user for this scenario?
