### ISSUE TITLE
[doc] 3.1.2.1  Installing Helm - caasp v5 and helm 2 is default??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1007]
3.1.2.1  Installing Helm:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#helm-tiller-install

---------------
--> Helm 2 is the default for SUSE CaaS Platform 5. Helm 3 is offered as an alternate tool and may be installed in parallel to aid migration.

I believe this is wrong... helm 3 is the default and CaaSP is version 4.5

**Comment by r0ckarong** [comment]
@jordimassaguerpla What is the actual default used in 4.5?

**Comment by jordimassaguerpla** [comment]
helm2

**Comment by Martin-Weiss** [comment]
This is really strange - I just did a new deployment of CaaSP 4.5 and on the admin node with the management pattern helm3 was the default..

**Comment by r0ckarong** [comment]
@jodavis-suse Which one is currently being installed by default? I know this is being changed for 4.5.1 but shouldn't have been deployed at the time of writing.

**Comment by jodavis-suse** [comment]
It should not be changed until a future version.  4.5.1 should still default to Helm 2.

I'll look up the issue numbers and comment. I wish I'd seen this issue sooner, but I haven't been watching doc issues.

joseph
________________________________

**Comment by jodavis-suse** [comment]
According to our plan for the Helm 3 epic https://github.com/SUSE/avant-garde/issues/1600 the default version should not change until well after 4.5.1.  See also https://confluence.suse.com/display/CaaSP/ADR%3A+Helm+3+transitional+packaging

In my testing I found the helm2 package should be installed by default, and even if helm3 package is installed then the helm2 alternative in update-alternatives has a higher priority and will be selected by default.  @Martin-Weiss if you are seeing different behavior then please file an issue in avant-garde.

**Comment by r0ckarong** [comment]
https://github.com/SUSE/avant-garde/issues/1949#issuecomment-705539605

> The switch to "helm3 as default" should be done later this year. The exact date is tbd.

**Comment by Martin-Weiss** [comment]
FYI - have found the root cause why the customers server had helm3 as default!

S | Name                  | Type    | Version                         | Arch   | Repository
--+-----------------------+---------+---------------------------------+--------+--------------------------------------
i | helm                  | package | 3.0.3-bp152.1.25                | x86_64 | SUSE-PackageHub-15-SP2-Backports-Pool
  | helm-mirror           | package | 0.3.0-1.10.1                    | x86_64 | SLE-Module-Containers15-SP2-Pool
  | helm2                 | package | 2.16.9-1.4                      | x86_64 | SUSE-CAASP-4.5-Pool
  | helm3                 | package | 3.2.4-1.3                       | x86_64 | SUSE-CAASP-4.5-Pool
  | rook-ceph-helm-charts | package | 1.2.7+git0.g1acfd182-bp152.1.58 | noarch | SUSE-PackageHub-15-SP2-Backports-Pool

--> the customer had the PackageHub connected and due to that helm 3 got installed:

dehwllk8sadm01:~ # rpm -q helm
helm-3.0.3-bp152.1.25.x86_64

Any idea why we have a completely different helm version in packagehub and how we can avoid this problem in the future?

**Comment by r0ckarong** [comment]
> FYI - have found the root cause why the customers server had helm3 as default!
> 
> S | Name | Type | Version | Arch | Repository
> --+-----------------------+---------+---------------------------------+--------+--------------------------------------
> i | helm | package | 3.0.3-bp152.1.25 | x86_64 | SUSE-PackageHub-15-SP2-Backports-Pool
> | helm-mirror | package | 0.3.0-1.10.1 | x86_64 | SLE-Module-Containers15-SP2-Pool
> | helm2 | package | 2.16.9-1.4 | x86_64 | SUSE-CAASP-4.5-Pool
> | helm3 | package | 3.2.4-1.3 | x86_64 | SUSE-CAASP-4.5-Pool
> | rook-ceph-helm-charts | package | 1.2.7+git0.g1acfd182-bp152.1.58 | noarch | SUSE-PackageHub-15-SP2-Backports-Pool
> 
> --> the customer had the PackageHub connected and due to that helm 3 got installed:
> 
> dehwllk8sadm01:~ # rpm -q helm
> helm-3.0.3-bp152.1.25.x86_64
> 
> Any idea why we have a completely different helm version in packagehub and how we can avoid this problem in the future?

@jordimassaguerpla Do you know who can answer this?

**Comment by Martin-Weiss** [comment]
> 
> 
> Well, the first simple answer is for the customer to not install additional repos.

I partially agree - but from a cross product compatibility and interoperability point of view I think the current status is not acceptable. If we as SUSE deliver different versions in valid SLES modules - we have to manage the dependencies and priorities better and maybe deliver the same versions ;-) (remember the terraform in CaaSP channel vs. Public Cloud channel).

> 
> The second answer is that we modified the packaging for helm to support migration from Helm 2 to Helm 3, something that the SLE and kubic repos don't have in place. In process of that, we have also updated versions. So I can go take a look at updating the SLE version to 3.3.4 (which includes some security fixes over 3.0.3), but if the customer wants to use the officially supported versions for CaaSP they should install the ones from the CaaSP repos.
> 

The customer did not even realize that the one from the "wrong" channel got installed instead the one from the CaaSP channel.. somehow the CaaSP management pattern installation must have taken the wrong helm.

> Note the CaaSP helm3 package is set up to be installed in parallel with helm2, and that helm2 has Provides and Obsolete tags in the RPM .spec so it will upgrade a lower version (but helm3 does not yet, by design). So if zypper was just choosing the latest "helm", the SLE 3.0.3 was selected over the CaaSP helm2 2.16.9 as having a higher number, but CaaSP helm3 3.2.4 was not selected as it is effectively a different package.

Yes - so the "zypper in -t pattern ... caasp..management" installs the helm from packagehub instead from CaaSP channel and I believe we have to address this.. maybe by replacing the helm (3.x) in packagehub with helm2 and helm3 packages?

**Comment by jordimassaguerpla** [comment]
@Martin-Weiss Could you open a bug in bugzilla about it? I think this is something that should be handled with package hub team. Thanks.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss Could you open a bug in bugzilla about it? I think this is something that should be handled with package hub team. Thanks.

No problem - https://bugzilla.suse.com/show_bug.cgi?id=1177795 created
