### ISSUE TITLE
[doc] 3.1.2.3.1  Preconditions - airgap is a must to be supported

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1008]
3.1.2.3.1  Preconditions:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_preconditions

-------------------
--> The procedure below requires an available internet connection to install the 2to3 plugin. If the installation is in an air gapped environment, the system may need to be moved back out of the air gapped environment.

Could we add the explanation on how to download and install the plugin in airgap mode?

**Comment by Martin-Weiss** [comment]
Maybe a similar process like this can work "offline"?

$ wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
$ tar xzf helm-v3.0.0-linux-amd64.tar.gz
$ ./linux-amd64/helm plugin install https://github.com/helm/helm-2to3

**Comment by Martin-Weiss** [comment]
I assume that instead of helm plugin install a 

wget -N https://github.com/helm/helm-2to3/releases/download/v0.7.0/helm-2to3_0.7.0_linux_amd64.tar.gz
and extraction to the right path might already be sufficient

**Comment by r0ckarong** [comment]
@jodavis-suse Have you tested this migration in an air gap env? Could you provide the steps required?

**Comment by jodavis-suse** [comment]
Actually, I did test installing the plugin as @Martin-Weiss described but it failed.  The problem is that the 2to3 plugin itself is written to require an active internet connection back to github.  It can be done manually, but the install script inside the plugin has to be modified.

**Comment by jodavis-suse** [comment]
Reference https://github.com/helm/helm-2to3/blob/master/scripts/install_plugin.sh

**Comment by jodavis-suse** [comment]
@Martin-Weiss Do you want to discuss a bit about how this effects customers?
- Do we have any air-gapped customers who would need to do a helm 2 to helm 3 migration and would not be simply doing a fresh CaaSP 4.5 install in an air-gapped environment and could go straight to helm3 without migrating chart releases?
- Is having a mobile admin node (ie a laptop) for an air-gapped migration not acceptable?
- What would be a better user experience if 'helm plugin install <url to 2to3>' isn't possible?  Would a set of instructions that match the steps in install-plugin.sh be enough?  Or a script that does those steps?

There are also some notes from my earlier investigation on https://github.com/SUSE/avant-garde/issues/1674

**Comment by jodavis-suse** [comment]
> Maybe a similar process like this can work "offline"?
> 
> $ wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
> $ tar xzf helm-v3.0.0-linux-amd64.tar.gz
> $ ./linux-amd64/helm plugin install https://github.com/helm/helm-2to3

And just to be clear, the "helm3" package is included in our CaaSP 4.5 (and very soon 4.2) repos and can be installed with "zypper in helm3" for fresh installs (as documented). It is just the 2to3 plugin that is not packaged.

**Comment by Martin-Weiss** [comment]
Maybe we have to deliver the addon as additional RPM and adjust the plugin not to download and update itself?
