### ISSUE TITLE
[doc] 5  Upgrading SUSE CaaS Platform - whats new?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1012]
5  Upgrading SUSE CaaS Platform:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_upgrading_suse_caas_platform

--------------------

It is really difficult or even impossible to follow the changes of the documentation vs. previous versions.
Basically it is required to re-read the whole documentation to try to find out whats new or changed.
Especially if there are changes i.e. in yaml examples or commands - customers will not have a chance to find that out and adopt the changes in their running clusters.

--> could we add a "whats new / what changed" section that gives a customer exactly that "diff" with a timeline so that they can follow up with their deployments?

**Comment by r0ckarong** [comment]
I'm not entirely sure how to accomodate you here. We added the full docs changelog in the past but got feedback that this was bloating the documents and wasn't helpful. The changelog was the same list we include on the [releases](https://github.com/SUSE/doc-caasp/releases/tag/release-4.5.0-1) page.

Could you give me an example for what you would expect the contents of this section to look like other than the commit message? I need to think about how I could do this without adding unreasonable overhead. Please remember, I'm the only one working on CaaSP docs for the foreseeable future.

**Comment by Martin-Weiss** [comment]
It would be great to have a What´s new / What´s changed chapter for release changes.. going through the git changes is not something we should ask a customer to do..

I mean something similar to such a guide https://www.novell.com/documentation/open-enterprise-server-2018/oes_readme/data/t493kntlp56u.html

Such a guide would give a clear overview over the changes from i.e. 4.2.3 to 4.5.0

**Comment by r0ckarong** [comment]
I don't understand. How is this different from what we provide in our release notes? 

https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4.5/#_what_is_new_in_4_5_0

You want the docs changes to be described in this detail?

**Comment by Martin-Weiss** [comment]
I can not find the list of helm charts that are new/updated and this is very high level - where can I find all the details?

**Comment by r0ckarong** [comment]
> I can not find the list of helm charts that are new/updated and this is very high level - where can I find all the details?

I don't think this information is currently being compiled anywhere. We need to discuss with the remaining release engineers what places this information could be generated. I'm doubtful this will happen.
