### ISSUE TITLE
CaaSP 4.5 Release notes to include the updated addons versions (Cilium, etc)

### ISSUE THREAD

**Issue by adianas** [SUSE/doc-caasp#1014]
https://susedoc.github.io/caasp-release-notes/master/single-html/release-notes/

I think is going to be helpful to include the updated addons versions in the release notes of CaaSP 4.5, especially for customers that they are planning to upgrade from CaaSP 4.2.
One good example is Cilium that with CaaSP 4.5 has been updated to 1.7.6 which includes new features such as:
Transparent Encryption - https://docs.cilium.io/en/v1.8/gettingstarted/encryption/
~Networking and security observability with Hubble - https://docs.cilium.io/en/v1.8/gettingstarted/hubble/~
~Hubble support appears to have been added with Cilium 1.7 and included in core of Cilium 1.8.~
[@mrostecki we don't have Hubble support in CaaSP]

Thanks

**Comment by r0ckarong** [comment]
@jordimassaguerpla

**Comment by mmnelemane** [comment]
Needed for https://github.com/SUSE/avant-garde/issues/1936

**Comment by r0ckarong** [comment]
@jordimassaguerpla This is part of the recurring request to give more info on the changes between releases. Can we have a chat about how and who can provide these? I would think that updating the component/addon/container would need an additional item on the "todo" list that includes adding the info on what is new.

**Comment by jordimassaguerpla** [comment]
Let's include this in our automation plans but not manually, or we will have issues maintaining this information.
