### ISSUE TITLE
[doc] 13.7  Error <code class="literal">Invalid client credentials</code>

### ISSUE THREAD

**Issue by mkiss-katacoda** [SUSE/doc-caasp#1017]
13.7  Error <code class="literal">Invalid client credentials</code>:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_error_invalid_client_credentials

Bad syntax in kubectl commands:
kubectl get configmap oidc-dex-config > oidc-dex-config.yaml
kubectl get configmap oidc-gangway-config > oidc-gangway-config.yaml

In action:
kubectl get configmap oidc-dex-config > oidc-dex-config.yaml
Error from server (NotFound): configmaps "oidc-dex-config" not found

Missing namespace, fixed:
kubectl -n kube-system get configmap oidc-dex-config > oidc-dex-config.yaml
cat oidc-dex-config.yaml
NAME              DATA   AGE
oidc-dex-config   1      109d

Missing output definition, fixed:
kubectl -n kube-system get configmap oidc-dex-config -o yaml > oidc-dex-config.yaml

So, multiple missing parameters for kubectl in 2 commands.

**Comment by r0ckarong** [comment]
@jenting Can you confirm these are wrong? What would be the correct parameters?

**Comment by jenting** [comment]
The problem is we missed the namespace parameter, I'll file a PR to fix it.

**Comment by r0ckarong** [comment]
> The problem is we missed the namespace parameter, I'll file a PR to fix it.

If the problem is just the missing namespace params I'll do this. Quicker this way.
