### ISSUE TITLE
Add helm3 package notes to 4.2.4 release notes

### ISSUE THREAD

**Issue by jodavis-suse** [SUSE/doc-caasp#1020]
As we have been asked to include Helm 3 in CaaSP 4.2 (see https://github.com/SUSE/avant-garde/issues/1949 ) there needs to be a bit of notice in the release notes to let users know it is available.

The original intention was to bring over helm3 and helm2 packaging to match CaaSP 4.5, in which case any doc changes would also need to be backported.  But it was pointed out that the 4.2 branch should be for maintenance only, so renaming the helm2 package could be confusing.  As such, a simple release note with install instructions and a warning should be sufficient.

UPDATE: the update-alternatives and version bump for 2.16.12 have been backported but the "helm" package was not renamed.  As a result, the release note has been adjusted, and documentation changes associated with update-alternatives have been backported to the 4.2 doc-caasp repo.

Associated Issue
https://github.com/SUSE/avant-garde/issues/1949

**Comment by jodavis-suse** [comment]
Note: if helm2 package naming is included in 4.2.4, then the release note would need to be revised and full doc changes backported.

**Comment by jodavis-suse** [comment]
PR for release note - https://github.com/SUSE/caasp-release-notes/pull/80

**Comment by jodavis-suse** [comment]
Documentation changes associated with this backporting are now in https://github.com/SUSE/doc-caasp/pull/1027.
The release note is no longer valid, so I'll go revise that.

**Comment by r0ckarong** [comment]
RN PR is "On-Hold" waiting for this to clear.

**Comment by dannysauer** [comment]
@r0ckarong - is this still blocked?

**Comment by r0ckarong** [comment]
> @r0ckarong - is this still blocked?

Wasn't aware the related avant-garde issue had closed now. I will take another look.

**Comment by r0ckarong** [comment]
Done.
