### ISSUE TITLE
[doc] 5.1.2  Upgrade the cluster

### ISSUE THREAD

**Issue by pgavro** [SUSE/doc-caasp#1021]
5.1.2  Upgrade the cluster:

https://documentation.suse.com/suse-caasp/4.5/html/caasp-admin/_upgrading_suse_caas_platform.html#_upgrade_the_cluster
Note: If you have metrics-server deployed before , delete it's deployment before step "skuba addon upgrade apply " , otherwise the error occured : 

E1001 14:02:08.082455   10828 addons.go:425] failed to run kubectl apply: serviceaccount/metrics-server unchanged
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/system:metrics-server unchanged
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader unchanged
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server unchanged
service/metrics-server configured
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io configured
The Deployment "metrics-server" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"metrics-server"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
E1001 14:02:08.083223   10828 addons.go:179] failed to apply "metrics-server" addon (exit status 1)
Unable to Apply addons upgrade: [apply] Failed to deploy addons: exit status 1

**Comment by r0ckarong** [comment]
@innobead @jenting Can you confirm this behavior? What are the correct steps that need to be done to properly perform the upgrade when you have this deployed?

**Comment by innobead** [comment]
@r0ckarong ref https://github.com/SUSE/caasp-release-notes/pull/79

**Comment by r0ckarong** [comment]
> @r0ckarong ref [SUSE/caasp-release-notes#79](https://github.com/SUSE/caasp-release-notes/pull/79)

Thank you, I just found this again too.

**Comment by r0ckarong** [comment]
Since this is a temporary problem and will be fixed in the later versions, we will add this to the release notes. Closing this issue.
