### ISSUE TITLE
[doc] 13.4.2  Backup Kubernetes Cluster - how to trust a custom/self-signed CA?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1026]
13.4.2  Backup Kubernetes Cluster:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_backup_kubernetes_cluster

-----

When specifying the S3 target for backup - we need to add the trusted CA somehow or we have to specify insecure-no-verify or similar but I can not find an explanation on this in the documentation nor in the helm chart 2.12.2

For the backup target I found the option insecureSkipTLSVerify: "true" but that does not seem to be honored by restic..

**Comment by r0ckarong** [comment]
@innobead Since this is backup/velero, could you help with this?

**Comment by innobead** [comment]
This feature is already introduced in Velero 1.4.x, and we are working on the release and regression. If it's ready, we will have a doc to enhance this.

ref: https://github.com/vmware-tanzu/velero/issues/1027

cc @jenting @maximenoel8

**Comment by jenting** [comment]
> 13.4.2 Backup Kubernetes Cluster:
> 
> https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_backup_kubernetes_cluster
> 
> When specifying the S3 target for backup - we need to add the trusted CA somehow or we have to specify insecure-no-verify or similar but I can not find an explanation on this in the documentation nor in the helm chart 2.12.2
> 
> For the backup target I found the option insecureSkipTLSVerify: "true" but that does not seem to be honored by restic..

Velero 1.4 includes adding trusted CA to both S3 & restic, we're going to release Velero 1.4 and it's helm chart recently.

**Comment by jenting** [comment]
It's preparing to be released along with `4.5.2` https://github.com/SUSE/avant-garde/issues/1786#issuecomment-708140741
