### ISSUE TITLE
[doc] 1.1  Platform missing Azure

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-caasp#1031]
1.1  Platform:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-deployment/#_platform

Missing Azure as on Release notes: https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4.5/#_supported_platforms
"Microsoft Azure (technological preview)"

**Comment by r0ckarong** [comment]
This was added by mistake. Azure support is still being worked on and is also not available as tech preview at the moment. We will correct the release notes.
