### ISSUE TITLE
[doc] 7.4.4  Deployment

### ISSUE THREAD

**Issue by chentex** [SUSE/doc-caasp#1032]
7.4.4  Deployment:

https://documentation.suse.com/suse-caasp/4.5/html/caasp-admin/_logging.html#_deployment

`Helm` commands are missing the `namespace` parameter.

**Comment by r0ckarong** [comment]
Both commands in this section have the `--namespace kube-system` parameter. Is that not what you mean?

**Comment by chentex** [comment]
Is for the status/delete/uninstall commands.
