### ISSUE TITLE
[doc] 13.8.2  Cluster Migration

### ISSUE THREAD

**Issue by phegedus83** [SUSE/doc-caasp#1035]
13.8.2  Cluster Migration:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/index.html#_cluster_migration
Check gangway configuration:
Download gangway.yaml
kubectl get configmap oidc-gangway-config -o yaml > oidc-gangway-config.yaml
Edit oidc-gangway-config.yaml to desired
vim oidc-gangway-config.yaml
Apply new oidc-gangway-config.yaml
kubectl apply -f oidc-gangway-config.yaml --force
Restart oidc-gangway deployment
kubectl delete pod -l **app=oidc-dex**

Correctly: kubectl delete pod -l **app=oidc-gangway**

**Comment by jenting** [comment]
nice catch! Thanks.

**Comment by phegedus83** [comment]
Missing namespace:
kubectl delete pod -l app=oidc-gangway **-n kube-system**
