### ISSUE TITLE
[doc] Release Notes 4.5.1

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-caasp#1038]
6.9  Release Notes:

https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4.5

Can 4.5 included in the same release notes document as now it missing all the important changes what happened on 4.5?

**Comment by r0ckarong** [comment]
@kkaempf @jordimassaguerpla Is this useful?

**Comment by otuominen** [comment]
Why this has been changed with 4.5 in first place?
4.2.x it is included and easier to follow.
https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4/

**Comment by r0ckarong** [comment]
I actually think this was removed by mistake. I will add it back.

@jordimassaguerpla I just added https://github.com/SUSE/caasp-release-notes/commit/860b318264d55bfab56bbfd7f1dd2b673a32911e, could you please rebuild the RN package?

**Comment by jordimassaguerpla** [comment]
We are working on 4.5.2. Let's put that new R/N into 4.5.2.
