### ISSUE TITLE
Re-add PR #919 (New command: skuba addon refresh localconfig)

### ISSUE THREAD

**Issue by jenting** [SUSE/doc-caasp#1040]
Prematurely merged #919 and reverted. Needs to be added back.

**Comment by jenting** [comment]
Ref to https://github.com/SUSE/avant-garde/issues/1765
Ref to https://github.com/SUSE/avant-garde/issues/2032

**Comment by r0ckarong** [comment]
4.5.2 done with 877850f
4.2.5 prepared with 176dd5a
