### ISSUE TITLE
Include new skuba command on v4.2.4 release

### ISSUE THREAD

**Issue by davidcassany** [SUSE/doc-caasp#1046]
The command `skuba addon refresh localconfig` has been backported from v4.5 in skuba for v4.2.4 release thus the documentation for it needs to be backported in some way.

The specific commit that requires a backport is 8de42734

**Comment by jenting** [comment]
I think it's be backported already https://github.com/SUSE/doc-caasp/issues/1040#issuecomment-717092982
However, the original issue label on `4.2.5`, not `4.2.4` which is incorrect labeling.

**Comment by davidcassany** [comment]
> I think it's be backported already [#1040 (comment)](https://github.com/SUSE/doc-caasp/issues/1040#issuecomment-717092982)
> However, the original issue label on `4.2.5`, not `4.2.4` which is incorrect labeling.

Thanks!

**Comment by r0ckarong** [comment]
> I think it's be backported already [#1040 (comment)](https://github.com/SUSE/doc-caasp/issues/1040#issuecomment-717092982)
> However, the original issue label on `4.2.5`, not `4.2.4` which is incorrect labeling.

So this was only part of the 4.2.5 release. I now also backported this to 4.2.4 with 3548e6b
