### ISSUE TITLE
Update docs to reflect Helm 3 as new default

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#1047]
Caused by: https://github.com/SUSE/avant-garde/issues/1816

Relates to: 

- https://github.com/SUSE/doc-caasp/issues/1020
- https://github.com/SUSE/doc-caasp/pull/896
- https://github.com/SUSE/doc-caasp/pull/920
- https://github.com/SUSE/avant-garde/issues/2022

**Comment by r0ckarong** [comment]
@davidcassany Please let me know when you decide this should be added.

**Comment by davidcassany** [comment]
@r0ckarong sure I'll try to figure that out during tomorrow after discussing with QA.

**Comment by davidcassany** [comment]
@r0ckarong I just included the changes to make helm3 the default into staging area. So we are definitely targeting it to v4.5.2.

**Comment by r0ckarong** [comment]
> @r0ckarong I just included the changes to make helm3 the default into staging area. So we are definitely targeting it to v4.5.2.

Then I will integrate this on Monday. Thanks for letting me know.
