### ISSUE TITLE
[doc] 6.9.8.1  Renewing Control Plane Certificates -> how to create the kubelet certificate for worker nodes??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1048]
6.9.8.1  Renewing Control Plane Certificates:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_renewing_control_plane_certificates

--------------------

When reading through this guide I can not find the details on how to re-create the kubelet certificates for the worker nodes. 
It is only mentioned that they have to be created with the correct IP and DNS name but it is not explained how to create them.. or at least I could not find it here..

So what do I miss or can this be added?

**Comment by r0ckarong** [comment]
@jenting

**Comment by jenting** [comment]
@Martin-Weiss,
You mean the kubelet server certificate, right? Not client certificate.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss,
> You mean the kubelet server certificate, right? Not client certificate.

I mean the kubelet certificates that are stored on the workers.

**Comment by jenting** [comment]
I think it's included already.
![image](https://user-images.githubusercontent.com/49380831/100037831-e2547280-2e3d-11eb-8df0-2bf8e5fa4439.png)

**Comment by Martin-Weiss** [comment]
> I think it's included already.
> ![image](https://user-images.githubusercontent.com/49380831/100037831-e2547280-2e3d-11eb-8df0-2bf8e5fa4439.png)

How exactly do I have to create the server certificate for a worker node on the control plane? I can not find the exact commands required and the name of the file I have to copy...
