### ISSUE TITLE
[doc] 3.3  Note about - ESXi in KVM with nested virtualization - network problems after upgrading to SLES 15 SP2

### ISSUE THREAD

**Issue by adianas** [SUSE/doc-caasp#1050]
3.3  Deployment on VMware:
https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-deployment/#_deployment_on_vmware

ESX in KVM with nested virtualization - network problems after upgrading to  SLES 15 SP2

With SLES 15 SP1, this worked fine, but since upgrading to SLES 15 SP2 there have been issues with unstable network communication, especially between ESX guests and the host or the external network.

Martin Weiss  found a solution to this problem by adjusting the KVM guest for ESXi with this CPU configuration:

```
  <cpu mode='host-passthrough' check='none'>
    <cache mode='passthrough'/>
  </cpu>
```

The default settings (that  caused problems):

`  <cpu mode='host-model' check='partial'/>`

The bug report: https://bugzilla.suse.com/show_bug.cgi?id=1176872

Is it possible to add a note that covers this situation?

Thanks

**Comment by Martin-Weiss** [comment]
I believe this needs to go into the "nested virtualization documentation" for KVM documentation that is part of SLES - but not into CaaSP..

**Comment by adianas** [comment]
Thanks,  I've re-created under the SLES docs
