### ISSUE TITLE
Assigning Roles to the Cluster Nodes with CaaSP v4

### ISSUE THREAD

**Issue by thkukuk** [SUSE/doc-caasp#114]
5.2.5.11  Assigning Roles to the Cluster Nodes

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.cloud-init.user-data.caasp-roles

With CaaSP v4, the cluster role does no longer configure a NTP client. Instead the admin has to configure one (either chrony or systemd-timesyncd) with cloud-init himself. NTP syncronisaton across the cluster is required.

The following text needs to be adjusted:
"...and configure a timesync service with administration node as a reference. You do not have to install any NTP server, but if you need to use one, you need to disable the systemd-timesyncd first."

**Comment by r0ckarong** [comment]
This also relates to:

https://bugzilla.suse.com/show_bug.cgi?id=1098743
and some what https://bugzilla.suse.com/show_bug.cgi?id=1071204
