### ISSUE TITLE
Automatic Installation Using AutoYaST

### ISSUE THREAD

**Issue by alexarnoldy** [SUSE/doc-caasp#117]
4.4.3  Automatic Installation Using AutoYaST

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.nodes.worker_install.manual.autoyast

The network setup in this section is confusing because it calls for netsetup for DHCP, but then points to the Advanced Network Setup section of Autoyast, which only references ifcfg.

ifcfg has more functionality and is preferred in the Autoyast documentation, so all references to netsetup should be replaced with ifcfg.

In addition, an example of the entire boot option line, based on using a static IP, should be given. For instance:
"For a static IP assignment, the Boot Option line will accept this syntax: 
autoyast=http://<FQDN or IP of the Administration Node>/autoyast   ifcfg=eth0=<IP>/<CIDR netmask>,<gateway>,<local dns server>,<search domain>   hostname=<FQDN of this node>
For example: 
autoyast=http://admin.my-caasp.com/autoyast   ifcfg=eth0=192.168.100.11/24,192.168.100.1,192.168.100.2,my-caasp.com   hostname=master1.my-caasp.com"

**Comment by r0ckarong** [comment]
Closed with bc91624
