### ISSUE TITLE
Automatic Installation Using AutoYaST

### ISSUE THREAD

**Issue by alexarnoldy** [SUSE/doc-caasp#118]
4.4.3  Automatic Installation Using AutoYaST

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.nodes.worker_install.manual.autoyast

In this section it says "However, each node will have ssh keys for root on the master node pre-installed."

This is not true. The keys are on the Administration node, not on any of the K8s master nodes.

**Comment by r0ckarong** [comment]
Fixed with ebb2801
