### ISSUE TITLE
[doc] 3.1.4  Recovering From Failed Updates

### ISSUE THREAD

**Issue by asemen** [SUSE/doc-caasp#123]
3.1.4  Recovering From Failed Updates

http://docserv.suse.de/documents/CaaS_Platform_3/caasp-admin/single-html/#sec.admin.software.transactional-updates.recovering

On run of documented 2nd step:

docker exec -it $(docker ps -q -f name="salt-master") \
 salt "*" cmd.run "transactional-update cleanup reboot dup

I do get on my CaaSP 3.0 set up:
"docker: command not found"

**Comment by asemen** [comment]
Or I do get this;
docker exec -it $(docker ps -q -f name="salt-master") \
> salt "*" cmd.run "transactional-update cleanup reboot dup"
ca:
    /bin/sh: transactional-update: command not found
admin:
    ERROR: Zypper failed with the following message(s):
    You are about to do a distribution upgrade with all enabled repositories. Make sure these repositories are compatible before you continue. See 'man zypper' for more information about this command.
    Refreshing service 'SUSE_CaaS_Platform_3.0_x86_64'.
    Loading repository data...
    Reading installed packages...
    Computing distribution upgrade...
    12 Problems:
    Problem: problem with installed package sles12-dnsmasq-nanny-image-3.0.0-2.196.x86_64
    Problem: problem with installed package sles12-flannel-image-3.0.0-4.204.x86_64
    Problem: problem with installed package sles12-haproxy-image-3.0.0-2.205.x86_64
    Problem: problem with installed package sles12-kubedns-image-3.0.0-2.193.x86_64
    Problem: problem with installed package sles12-mariadb-image-3.0.0-3.188.x86_64
    Problem: problem with installed package sles12-pause-image-3.0.0-2.201.x86_64
    Problem: problem with installed package sles12-pv-recycler-node-image-3.0.0-2.192.x86_64
    Problem: problem with installed package sles12-salt-api-image-3.1.1-1.7.x86_64
    Problem: problem with installed package sles12-salt-master-image-3.1.1-1.3.x86_64
    Problem: problem with installed package sles12-salt-minion-image-3.1.1-1.7.x86_64
    Problem: problem with installed package sles12-sidecar-image-3.0.0-2.184.x86_64
    Problem: problem with installed package sles12-tiller-image-3.0.0-2.202.x86_64
    Problem: problem with installed package sles12-dnsmasq-nanny-image-3.0.0-2.196.x86_64
     Solution 1: install sles12-dnsmasq-nanny-image-3.0.0-1.101.x86_64 (with vendor change)
      obs://build.suse.de/Devel:CASP:3.0:ControllerNode  -->  SUSE LLC <https://www.suse.com/>
     Solution 2: keep obsolete sles12-dnsmasq-nanny-image-3.0.0-2.196.x86_64
2b51293b2a8b4b889b63b0bd96f023d1:
ae8bb4677a4e4c5f8c2535422d8989ce:
b106fe185f354deb98a323d15f9eb89f:
ERROR: Minions returned with non-zero exit code

**Comment by jordimassaguerpla** [comment]
Hi,
you are trying to apply the updates onto a devel image. By default transactional-update won't let you do that. Please apply updates on a CaaSPv3 official/supported image.
