### ISSUE TITLE
[doc] Procedure&nbsp;7.2:  Creating a Pod with RBD in Persistent Volume 

### ISSUE THREAD

**Issue by m0rbo** [SUSE/doc-caasp#129]
Procedure&nbsp;7.2:  Creating a Pod with RBD in Persistent Volume 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#id-1.5.9.5.3

I was just walking through this section and setting up Persistent Volumes in CaaSP in my lab and as written with the yaml that includes:
monitors:
    - [MONITOR1_IP:MONITOR1_PORT]
    - [MONITOR2_IP:MONITOR2_PORT]
    - [MONITOR3_IP:MONITOR3_PORT]

I removed 2 of the MONITOR entries and used this:
monitors:
    - [MONITOR1_IP:MONITOR1_PORT]

And when I tried to apply that yaml I got this error:
kubectl apply -f ceph-create-persistent-vol.yaml 
error: error converting YAML to JSON: yaml: line 12: found unexpected ':'

I changed the brackets to single quotes and it worked:
monitors:
    - '192.168.0.184:6789'

kubectl apply -f ceph-create-persistent-vol.yaml 
persistentvolume "bradpv" created

I assume something has changed in kubernetes that the brackets no longer work?

**Comment by r0ckarong** [comment]
I think the person who wrote this just meant to indicate with the brackets that you had to replace the entire string.
All examples I can find for this are either

```
monitors:
- IP:Port
```
or
```
monitors:
- 'IP:PORT'
```
or 
```
monitors: IP:PORT,IP:PORT,IP:PORT
```

I will change the example to the second format to be on the safe side.

**Comment by r0ckarong** [comment]
Added with 38e55bf

Thanks for the input!
