### ISSUE TITLE
[doc] Procedure&nbsp;3.6:  Installation of Kubernetes Dashboard 

### ISSUE THREAD

**Issue by alexarnoldy** [SUSE/doc-caasp#130]
Procedure&nbsp;3.6:  Installation of Kubernetes Dashboard 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#id-1.5.5.6.4

Since section 3.4.3 covers installing heapster, step one in procedure 3.6 should have a note that this step can be skipped if heapster is already installed.

**Comment by r0ckarong** [comment]
I have slightly modified the instructions so the first step of this instruction will point to the previous section detailing heapster installation. Thanks for the heads up!
