### ISSUE TITLE
Please add a note that we should not saturate nodes

### ISSUE THREAD

**Issue by hwoarang** [SUSE/doc-caasp#131]
We should have a suggestion note that nodes should not be overloaded (or even committed) so workloads can have more chances from moving from one node to another during an update or maintenance window.

**Comment by r0ckarong** [comment]
Is there a good rule of thumb how `oversized` a cluster should be planned then?

**Comment by hwoarang** [comment]
I would say 70-80% utilized but that's just me. @ereslibre any other ideas?

**Comment by ereslibre** [comment]
We could encourage 70% and set 80% as the maximum reasonable limit.

However, assuming a cluster with two worker nodes of the same size if both are at 51% Kubernetes will run into troubles moving those workloads from one to another. Same applies if worker nodes are of different size and at different occupation rate, but only in the case of two workers. With more workers it's harder to hit this problem unless they vary a lot in the specs and one is fairly bigger than a big subset of the rest.

**Comment by r0ckarong** [comment]
The immediate question that comes to my mind is then: How do I limit resources to 80% max?
I have an open task to describe RBAC resource limits but I need more input to know if this will cover this sufficiently.

**Comment by hwoarang** [comment]
I am not sure if we want to go into such a depth with resource limits. I would leave it as an exercise to the cluster administrator or just point them to upstream docs https://kubernetes.io/docs/concepts/policy/resource-quotas/

**Comment by ereslibre** [comment]
I agree with @hwoarang, every cluster is different in size and what workloads they run. We should just point to the upstream docs, just wanted to state the previous though.

**Comment by r0ckarong** [comment]
https://github.com/SUSE/doc-caasp/pull/132
