### ISSUE TITLE
[doc] 2.2.7.2  Client Configuration

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#136]
2.2.7.2  Client Configuration

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.scenarios.airgap.helm-charts.client

--> the name of the helm-mirror is case-sensitive and it seems that only "lower case" works.

Please change "SUSE-MIRROR" to "suse-mirror" as otherwise the fetch will not work.

**Comment by r0ckarong** [comment]
Corrected example, added link to helm chart naming conventions.

0b24861db9de957347505f68591f89c4a1f0c1f2
