### ISSUE TITLE
It's "openSUSE Leap 42.x|15.x", not "openSUSE 42.x|15.x"

### ISSUE THREAD

**Issue by Vogtinator** [SUSE/doc-caasp#140]
There is no such thing as "openSUSE 15", but it's still mentioned in various places.

**Comment by r0ckarong** [comment]
Please detail "various places" I can find exactly two references for openSUSE 15 or 42. I've just fixed those with f86a46d2751d356341f6c75845239f8eaa91daad

**Comment by Vogtinator** [comment]
Yup, looks good to me.
