### ISSUE TITLE
Add info about flexvolume drivers

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#145]
https://github.com/kubic-project/salt/pull/724#issuecomment-463628747

**Comment by r0ckarong** [comment]
Ask @lcavajani if this is part of v4 development and implemented yet. Otherwise this just goes into v3 maintenance.

**Comment by lcavajani** [comment]
@r0ckarong @nkoranova this is only valid for `v3`

in `v4`, we are using the default directory in `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`

**Comment by nkoranova** [comment]
#211

**Comment by r0ckarong** [comment]
Merged #211
