### ISSUE TITLE
[doc] Procedure&nbsp;9.1:  Installation of Kubernetes Dashboard 

### ISSUE THREAD

**Issue by rssfed23** [SUSE/doc-caasp#150]
Procedure&nbsp;9.1:  Installation of Kubernetes Dashboard 

https://susedoc.github.io/doc-caasp/develop/caasp-user/single-html/#id-1.6.10.2.4

Gives a 404 when trying to run kubectl apply -f 
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by r0ckarong** [comment]
Looks like they changed the structure of the project. The closest thing I can find is: https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard.yaml but I am not sure if this is the right one. I'll look into it.

**Comment by r0ckarong** [comment]
Find out if we can just swap the old link for the new one.
Probably ask @stefsuse

**Comment by rssfed23** [comment]
I think we should use the helm chart, with some documentation on the common values opposed to applying the updated yaml (I don't know if the new yaml applies all the RBAC stuff like the helm chart does). Plus; the chart is recognised upstream as best practice to install (we can still include the standalone yaml for customers deciding not to use helm)

**Comment by stefsuse** [comment]
sorry I missed your at-mention @r0ckarong 

These instructions are still valid for helm based deployment in v3. https://github.com/SUSE/doc-caasp/blob/dc36ace1e3a692f75bf468332288a02f66dc6091/xml/user_deploy_app.xml

**Comment by jordimassaguerpla** [comment]
@nkoranova do we have this docs in v4?

**Comment by r0ckarong** [comment]
Will be tackled for v4 in #568
