### ISSUE TITLE
Add step for manual node removal

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#159]
> You can try to run this command by replacing the target with the minion-id.

```
docker exec -ti $(docker ps -q --filter name=salt-master) salt-run
--force-color state.orchestrate orch.removal
pillar='{"target":"87019cb873604c21b94b0f3d91d96369"}'
```

**Comment by r0ckarong** [comment]
> Ok... now velum displays the node as "removal failed" and the "force remove" does nothing... Is there any other command similar to the previous one which would trigger a "force removal"?

**Comment by nkoranova** [comment]
Is this something that would go here? https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#sec.admin.nodes.remove

**Comment by r0ckarong** [comment]
Yes, exactly.
