### ISSUE TITLE
wrong ldap ports in documentation

### ISSUE THREAD

**Issue by sinicis** [SUSE/doc-caasp#162]
**topic:** wrong LDAP TLS port

**source:** https://github.com/SUSE/doc-caasp/blob/develop/xml/admin_security.xml#L1407

**correction:** should be 636 instead of 646

**Comment by r0ckarong** [comment]
Fixed with: b0710ddc74704f70883d186794627a1493eaffdc

**Comment by danielorf** [comment]
636 is the correct TLS port
