### ISSUE TITLE
[doc] 2.5  Scaling the Cluster

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#163]
2.5  Scaling the Cluster

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#sec.admin.scale_cluster

Incorrect:
> The default maximum number of nodes in a cluster is 40. The Salt Master configuration needs to be adjusted to handle installation and updating a of larger cluster:

Correct
> The default maximum number of nodes in a cluster is 150. The Salt Master configuration needs to be adjusted to handle installation and updating a of larger cluster:

**Comment by pgonin** [comment]
well...
It depends on Admin node RAM
8GB => up to 40 workers
32GB => up to 150 workers

Also it has been tested at time of CaaSP3 release. 
It might be possible that since then improvements (on salt automation, velum...) might have side effect of allowing more workers to be added to cluster.

**Comment by tgeek77** [comment]
My comment was based on input from AJ. Thanks Paul, the fuller explanation would be best for this bug.

**Comment by r0ckarong** [comment]
Added with af135ab6691fee9ac2b703a9615d2ba530ddfbac and 263dc4a3bee0141c662b768843454624a16c4861
