### ISSUE TITLE
Configuring External OIDC Provider

### ISSUE THREAD

**Issue by martinhonore** [SUSE/doc-caasp#173]
1  Security
https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#cha.admin.security

The configuration of the OIDC Provider is missing from the documentation.

**Comment by r0ckarong** [comment]
Find out if OIDC is supported in v3. If so, how can it be configured.

**Comment by martinhonore** [comment]
The OIDC connector is supported since February 22, 2019

See the following public patch for CaaSP v3:
https://download.suse.com/Download?buildid=SsTSUzb8BY4~
- Complete OIDC connector support

**Comment by nkoranova** [comment]
> https://download.suse.com/Download?buildid=SsTSUzb8BY4~

That link leads me to an error page. "We're sorry, we are unable to complete the download at this time." Is it just me/temporary or wrong link?

**Comment by martinhonore** [comment]
It seems there is a format error on the URL.
It should be better with this link -> [https://download.suse.com/Download?buildid=SsTSUzb8BY4~](https://download.suse.com/Download?buildid=SsTSUzb8BY4~)

**Comment by r0ckarong** [comment]
Waiting for Danny Sauer to provide input PR.

**Comment by dannysauer** [comment]
I got formatting mostly figured out yesterday, and hope to actually get the content together today (pending other priority tasks popping up).  I'll hopefully remember to reference this issue when the PR is opened. :)

**Comment by r0ckarong** [comment]
@dannysauer Any updates here?

**Comment by dannysauer** [comment]
https://github.com/SUSE/doc-caasp/pull/299

**Comment by nkoranova** [comment]
Merged and published. :)
