### ISSUE TITLE
Add VMWare Deployment to quickstart guide

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#178]
Describe VMWare deployment

https://github.com/SUSE/avant-garde/issues/131

**Comment by thehejik** [comment]
@r0ckarong I just created https://confluence.suse.de/display/SUSECaaSPlatform4/Quickstart+guide+for+vNext+on+VMWare

**Comment by r0ckarong** [comment]
Releases and reviewed.
Fixes added from #196
