### ISSUE TITLE
Describe LDAP usage in vNext

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#183]
Needs to clarify if internal or external LDAP is supported and how to configure/use

- [x] https://github.com/SUSE/avant-garde/issues/164
- [x] https://github.com/SUSE/avant-garde/issues/19
- [x] https://github.com/SUSE/avant-garde/issues/17

Output reviews with:

- [x] #298 
- [x] #292 
- [x] #293

**Comment by r0ckarong** [comment]
Relates to: https://github.com/SUSE/avant-garde/issues/19

**Comment by r0ckarong** [comment]
https://github.com/danielorf/doc-caasp/blob/ag17_ldap/ldap/ldap_instructions.md

**Comment by NunoFilipeSantos** [comment]
@r0ckarong Please provide some context to why you are blocked, so we can help you.

**Comment by r0ckarong** [comment]
According to @danielorf the instructions he provided should not be published. I don't understand what I should do with the instructions.

**Comment by r0ckarong** [comment]
@kkaempf What should we do about this? I can not get any information about how the LDAP container is going to be used and if this is being shipped.

**Comment by kkaempf** [comment]
@ereslibre @flavio this needs input from you. Probably for Sprint 6 or 7.

**Comment by flavio** [comment]
To clarify:

  * No LDAP server is part of the CaaSP offering starting from v4
  * Having an external LDAP is a prerequisite of v4 installation
  * Our installation guidelines will provide instructions about how to point the kubernetes cluster to this external LDAP server. I expect the v3 documentation about external LDAP server to be a still valid.
  * Customers can rely on an external LDAP server that is already part of their corporate infrastructure
  * We will provide instructions on how to deploy an external LDAP server that can be used **only** for testing purposes
  * The external LDAP server is going to be deployed on a simple SLES node using a container image. We can use the instructions linked above as a starting point
  * The LDAP container image is the same one used by CaaSP v3. This is already on the SUSE registry.

**Comment by r0ckarong** [comment]
Relates to new: https://github.com/SUSE/avant-garde/issues/164

Review the output of this task

**Comment by r0ckarong** [comment]
#292 #293 #298

**Comment by r0ckarong** [comment]
https://confluence.suse.com/display/SUSECaaSPlatform4/External+LDAP+Server+Document

**Comment by r0ckarong** [comment]
The provided documentation from the Taiwan team does not include any deployment instructions for the testing LDAP.

**Comment by innobead** [comment]
> The provided documentation from the Taiwan team does not include any deployment instructions for the testing LDAP.

This is the current decision, the deployment instruction will be come out until 389-ds container image ready, it is under SLES MR flow.

References:
https://github.com/SUSE/avant-garde/issues/474
https://github.com/SUSE/avant-garde/issues/164

**Comment by r0ckarong** [comment]
@flavio @innobead When was the prerequisite for LDAP added? This wasn't communicated to the docs people.

This needs to be mentioned in the release notes and the first question will be: How to I set up an LDAP for testing, where are the instructions? What can we provide to users?

**Comment by innobead** [comment]
@r0ckarong 

LDAP server setup is optional for v4, because most of customers have their own directory server mentioned in https://github.com/SUSE/avant-garde/issues/474. Also, 389-ds image needs to go through SLES MR first before documentation.

1. So the first priority is to provide the admin guide *how to guide user provides correct LDAP connector settings for Dex* and some existing LDAP operation from v3.
2. The second priority is to provide an optional deployment guide for user to setup LDAP server as a reference.

**Comment by hwoarang** [comment]
It's true that we can copy most of these stuff from v3 although it's important to have some sort of basic instructions on how to deploy LDAP for people (ie sales, support, $someone) who are testing v4 with rbac. I would like to see that once 389-ds MR is accepted.

**Comment by jordimassaguerpla** [comment]
All items in the checklist are done.
