### ISSUE TITLE
Describe cluster management / bootstrap

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#193]
Document how adding/removing nodes works. This is related to: 

https://github.com/SUSE/avant-garde/issues/21
https://github.com/SUSE/caaspctl/pull/115/

**Comment by Klaven** [comment]
To reset a failed bootstrap or join, you can call
`caaspctl node reset --user <user> --sudo --target <ip-or-fqdn> <node-name>`

**Comment by r0ckarong** [comment]
- Bootstrap the cluster (deployment-bootstrap.adoc)
 - What does the bootstrap do?
- Add nodes
- Remove nodes
- ? Reconfigure from worker to master
- ? Reconfigure from master to worker
- Restart nodes if stuck
- Fix failed nodes

**Comment by jordimassaguerpla** [comment]
As a result of the planning, we are moving this to sprint 8.

**Comment by nkoranova** [comment]
https://github.com/SUSE/doc-caasp/pull/247

**Comment by r0ckarong** [comment]
Work continues in the PR
