### ISSUE TITLE
[doc] Procedure 3.5:  Installation of heapster 

### ISSUE THREAD

**Issue by escrevebastante** [SUSE/doc-caasp#200]
Procedure&nbsp;3.5:  Installation of heapster 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#id-1.5.5.5.5.3

In this session, we have the command: 

> helm install --name heapster-default --namespace=kube-system stable/heapster \
> --version=0.2.7 --set rbac.create=true

This will install helm version 0.2.7. However, on "3.5 Installing Kubernetes Dashboard" we have:

> Requirements: Heapster version 1.3.0 or later needs to be installed on the cluster

if version 1.3.0 is necessary to get the Kubernetes Dashboard running, shouldn't we recommend customers to install heapster version 1.3.0 instead of 0.2.7?

**Comment by r0ckarong** [comment]
@escrevebastante The version 0.2.7 refers to the helm chart version not the installed software version. The 0.2.7 version of the chart installs heapster 1.3.0. This is deliberate to get these particular verified versions.

See here:
https://github.com/helm/charts/blob/master/stable/heapster/Chart.yaml#L4

Notice how `version` and `appversion` are different.
