### ISSUE TITLE
Publish CaaSP 4.0 release notes from AsciiDoc as packages

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#214]
Talk to @sknorr about

- Packaging in OBS
- Document process and steps needed for publishing on suse.com

**Comment by r0ckarong** [comment]
> * die release notes müssen im OBS paketiert sein
> * jemand muss /mounts/work/cd/releasenotes anpassen, sodass die release notes veröfffentlicht werden (üblicherweise ro, aber vielleicht hat klaus auch zugriff)

**Comment by sknorr** [comment]
Fwiw, http://docserv.nue.suse.com/documents/Team_Hitchhikers_Guide/hitchhiker-guide/html/cha.doc.rn.html (internal) is mostly up-to-date.

**Comment by jordimassaguerpla** [comment]
This is done.
