### ISSUE TITLE
Figure out how to improve doc workflow with the other projects

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#216]
The challenge is to have doc work visible as part of the other squad planning. 

One suggestion by Klaus: put all the doc backlog in the avant-garde project
Other suggestion that we somehow show issues in multiple projects.

**Comment by r0ckarong** [comment]
@kkaempf https://help.github.com/en/articles/linking-a-repository-to-a-project-board

We should enable linking of other projects to project boards. This could be useful for other constellations as well.

**Comment by r0ckarong** [comment]
Once we figure out if this is actually possible and enable this, the docs repo needs to be linked to the new "Release Coordination Squad" board (not sure this exists yet).

**Comment by kkaempf** [comment]
> @kkaempf https://help.github.com/en/articles/linking-a-repository-to-a-project-board
> 
This doesn't work as described. The [Release Coordination v4](https://github.com/SUSE/avant-garde/projects/9) project does not show `Settings` in its menu. I only see `Edit` and `Copy` :disappointed:

**Comment by r0ckarong** [comment]
@kkaempf I appears this option is only available for user boards and organization boards. Since we set up this entire avant garde thing as a separate repository and work in repository boards this isn't available. I've asked GitHub support to clarify this for me but if I'm right this is very unfortunate.

From my perspective we should set up a organization level project board for this and then link all respective projects there. The workflow would shift the current projects onto the new project boards but the repositories for tracking would stay the same.

I don't see another reasonable way (without duplicating) to display doc issues in the other project board. I also don't see how creating issues in a repo away from the code would make sense.

**Comment by kkaempf** [comment]
> From my perspective we should set up a organization level project board for this

Ugh, sounds like a restart from scratch - which I'd like to avoid. Does [transferring a repo](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-organization) help here ?
