### ISSUE TITLE
remove github/SUSE/caaspctl references in docs for public beta2

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#219]
I see in the deployment guide we refer to github.com/SUSE/ at least in 2 places. We should remove that because this is not public.

thanks.

**Comment by r0ckarong** [comment]
@jordimassaguerpla So multiple questions:

- How can you retrieve the terraform files if you can not access the caaspctl repo?
- Prerequisites for caaspctl are only documented in the code repo, how to deal with this if it's private?
- PodSecurityPolicy is embedded in the caaspctl cluster bootstrap manifest. How to deal with this if it's private?

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla So multiple questions:
> 
>     * How can you retrieve the terraform files if you can not access the caaspctl repo?

They are now installed by the package

> 
>     * Prerequisites for caaspctl are only documented in the code repo, how to deal with this if it's private?

Can you copy that into the deployment guide?

> 
>     * PodSecurityPolicy is embedded in the caaspctl cluster bootstrap manifest. How to deal with this if it's private?

isn't that installed by the rpm?

**Comment by r0ckarong** [comment]
> > @jordimassaguerpla So multiple questions:
> > ```
> > * How can you retrieve the terraform files if you can not access the caaspctl repo?
> > ```
> 
> They are now installed by the package

And what is the location they are installed in? The instructions require the user to modify these files.

> 
> > ```
> > * Prerequisites for caaspctl are only documented in the code repo, how to deal with this if it's private?
> > ```
> 
> Can you copy that into the deployment guide?

I don't think that makes sense. The documentation for caaspctl is maintained and written in the GitHub repo. We are aiming to make this tool publicly available. So then the documentation must be publicly available also. The SSH requirement is already mentioned in the deployment guide and the rest will be described in more detail for the cluster management in admin guide. We need to have a discussion about how we will handle this documentation for caaspctl once that is released to non-CaaSP users. From what I understand that is the goal.

> 
> > ```
> > * PodSecurityPolicy is embedded in the caaspctl cluster bootstrap manifest. How to deal with this if it's private?
> > ```
> 
> isn't that installed by the rpm?

Possibly, if so where?

**Comment by jordimassaguerpla** [comment]
download caaspctl from http://download.suse.de/ibs/SUSE:/SLE-15-SP1:/Update:/Products:/CASP40/standard/x86_64/

do "rpm -qlp caaspctl*rpm" and you will get the list of files. IIRC they are under /usr/share/

**Comment by r0ckarong** [comment]
`/usr/share/caasp/terraform/openstack/terraform.tfvars.example` 

The cluster init manifests files are not installed with this package.

**Comment by r0ckarong** [comment]
Obsolete
