### ISSUE TITLE
Description below the book title

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#221]
This text should appear below the title of the book: "This guide describes general and specialized administrative tasks for {productname} {productversion}." Now it is part of the preface along with the copyright and the warnings.

**Comment by r0ckarong** [comment]
I think this is an issue with the stylesheet. I noticed too that the subtitle isn't rendered correctly.

**Comment by r0ckarong** [comment]
Can you create screenshots from the output document where you can see how it's rendered incorrectly so we can file a new bug in https://github.com/openSUSE/suse-xsl/issues?q=is%3Aopen+is%3Aissue

**Comment by nkoranova** [comment]
Sure, but maybe I will ask @tomschr first to make sure that I got the syntax right before filing the bug. :)

**Comment by r0ckarong** [comment]
The syntax is:

```
= MyTitle: This guide describes general and specialized administrative tasks for {productname} {productversion}.
```

But this isn't really how this subtitle should be used I think. The sentence you're using is an introduction to the purpose of the document and not really a subtitle.
Better would be for example:

```
= Admin Guide: General and specialized tasks for {productname} {productversion}
```

**Comment by tomschr** [comment]
As far as I can see, it's not a stylesheet issue, but a conversion issue. You can't do this directly. However, there is a solution: whenever you want to include additional information into the header (more authors, additional text, other metainformation etc), use so called "docinfo" files.

For more information, see here: https://asciidoctor.org/docs/user-manual/#docinfo-file

**Comment by r0ckarong** [comment]
```
= {productname} {productversion} Administration Guide: This guide describes general and specialized administrative tasks for {productname} {productversion}.
```

![Screenshot_20190520_145254](https://user-images.githubusercontent.com/4920542/58023067-324ace80-7b0f-11e9-8d80-d917b0d59358.png)
![Screenshot_20190520_145238](https://user-images.githubusercontent.com/4920542/58023069-324ace80-7b0f-11e9-932e-a1123459bdec.png)

**Comment by r0ckarong** [comment]
> As far as I can see, it's not a stylesheet issue, but a conversion issue. You can't do this directly.
> 
> However, there is a solution: whenever you want to include additional information into the header (more authors, additional text, other metainformation etc), use so called "docinfo" files.
> 
> For more information, see here: https://asciidoctor.org/docs/user-manual/#docinfo-file

We're talking about different things here. What we're trying to do is to display additional information on the title page of the PDF and underneath the main document title. For this we use the `subtitle` in Asciidoctor.

Then there is another error that when there is a `preface` attribute in the asciidoc DAPS will generate a section with an empty title that leads to an empty clickable link in the HTML menu.

![subtitle](https://user-images.githubusercontent.com/4920542/58023854-27913900-7b11-11e9-9c6a-a962a9024f77.png)
![notitle_page](https://user-images.githubusercontent.com/4920542/58023855-27913900-7b11-11e9-9118-e1d7ec151832.png)
![notitle_clickable](https://user-images.githubusercontent.com/4920542/58023856-27913900-7b11-11e9-8b37-1b1b95aa5677.png)

What needs to be done is to display the `subtitle` on the PDF title page.

The docinfo file only allows injecting additional data into the header or footer that can't be specified inside of the AsciiDoc source (which isn't the case here).

**Comment by r0ckarong** [comment]
![subtitle_page](https://user-images.githubusercontent.com/4920542/58024137-cddd3e80-7b11-11e9-9b44-1c53b8d65f5b.png)
![preface](https://user-images.githubusercontent.com/4920542/58024139-cddd3e80-7b11-11e9-896f-eb6428de0897.png)

**Comment by tomschr** [comment]
Thanks for the screenshots, @r0ckarong 

> [...]
> @tomschr
> I think we're talking about different things here. What we're trying to do is to display additional information on the title page of the PDF and underneath the main document title. For this we use the `subtitle` in Asciidoctor.

Actually, I think we aren't that far away. :wink: However, there are different aspects which leads to your problems. Let me explain my ideas.

Subtitle is... well.. for subtitles, not for a complete paragraph. :wink: As such, you can't abuse subtitle if you want to add a whole paragraph. For that, I've suggested to use a docinfo file. In this file, you can add, for example, an `<abstract>` which can contain your paragraph. The daps toolchain can use this information.
 
> Then there is another error that when there is a `preface` attribute in the asciidoc DAPS will generate a section with an empty title that leads to an empty clickable link in the HTML menu.

Right. When I look into the generated XML file `build/.adoc/caasp-admin.xml`, you can see there is an empty `preface/title`. That's why the document starts with a sentence ("This guide describes..."), but no title is set. For AsciiDoc, this starts a new preface with an empty title.

The first "real" preface is with the title "About This Guide".

> What needs to be done is to display the `subtitle` on the PDF title page.

See here: https://asciidoctor.org/docs/user-manual/#subtitle-partitioning
(it works for me)

> The docinfo file only allows injecting additional data into the header or footer that can't be specified inside of the AsciiDoc source (which isn't the case here).

The information is true, but not the conclusion. :wink:  I would suggest:

* Move the whole copyright text should into a `<legalnotice>`. As there is no equivalent syntax in AD, you need to include the text into the docinfo file.
* Move the paragraph "This guide describes..." into the docinfo file, probably as `abstract`.
* Move the misplaced `disclaimer.adoc` under the "About This Guide" preface.

So you end up with a main file (`book_admin.adoc`) like this:

```asciidoc
include::entities.adoc[]

= Admin Guide: General and specialized tasks for {productname} {productversion}
Markus Napp; Nora Kořánová
:sectnums:
:doctype: book
:toc: left
:toclevels: 3
:toc-title: Contents
:icons: font
:revdate: {docdate}
:imagesdir: images/
:experimental:

// no common_copyright_quick.adoc or disclaimer.adoc

[preface]
== About This Guide
include::common_intro_target_audience_i.adoc[Required Background,leveloffset=+2]
include::common_intro_available_doc_i.adoc[Available Documentation,leveloffset=+2]
include::common_intro_feedback_i.adoc[Feedback,leveloffset=+2]
include::common_intro_typografie_i.adoc[leveloffset=+2]
include::disclaimer.adoc[Disclaimer]

// ...
```

I haven't tested it yet, but I'm pretty sure with my above suggestions you get a correct DocBook XML file.

Does that make sense? :wink:

**Comment by tomschr** [comment]
Actually, I forgot to mention how subtitles are really created. Sorry.
From the XML side, the part that is relevant for the cover page looks like this (SLE HA Guide):

```xml
<info>
    <title>&haguide;</title>
    <productname>&productname;</productname>
    <productname role="abbrev">&sleha;</productname>
    <productnumber>&productnumber;</productnumber>
    <!-- ... -->
</info>
```

The subtitle is created by using the `info/title` as the main title. The subtitle is created by `info/productname` and `info/productnumber`. The abbreviation (`info/productname[@role='abbrev]`) is used in the footer.

You need to inject this information into the AD process chain somehow. As far as I can see, this is only possible with a docinfo file.

**Comment by r0ckarong** [comment]
From what I can tell this is not really possible with the way AsciiDoctor is handling docinfo files. It will append information but not overwrite it from the contents of the docinfo. This, at the time of writing, just isn't possible to do what we wanted.
