### ISSUE TITLE
Review centralized logging docs

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#223]
Relates to: https://github.com/SUSE/avant-garde/issues/325

**Comment by innobead** [comment]
@r0ckarong 

centralized logging document is ready for review at https://confluence.suse.com/display/SUSECaaSPlatform4/Centralized+Logging+Document, please work with @cclhsu to add documents in doc-caasp. Thanks.

P.S. @cclhsu is my member from Taiwan team.

Ref: https://github.com/SUSE/avant-garde/issues/325

**Comment by r0ckarong** [comment]
Relates to: 
https://github.com/SUSE/doc-caasp/issues/176
https://github.com/SUSE/doc-caasp/issues/240

**Comment by nkoranova** [comment]
#260
