### ISSUE TITLE
Define list of questions QA needs to answer about bugs for the patchinfo

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#228]
- What does the user have to do after installing this patch?
- What is the impact of not applying this patch?

**Comment by r0ckarong** [comment]
Add a format example/suggestion for the patchinfo content.

**Comment by r0ckarong** [comment]
From Klaus:

- a severity (critical ... enhancement)
- how to install the patch
  a short - standardized - description about what an admin
  needs to know. How to install it ? How to verify that installation
  was successful ?
- any dependencies ?
- what happens if I do *not* install the patch ?

**Comment by jordimassaguerpla** [comment]
As a result of the planning, we are moving this to sprint 8.
