### ISSUE TITLE
We need SLES-beta, not CaaSP-beta to get JeOS image

### ISSUE THREAD

**Issue by kravciak** [SUSE/doc-caasp#233]
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_deployment_on_suse_openstack_cloud

Instruction says `Download the latest SUSE SLES15-SP1 for SUSE OpenStack Cloud from https://www.suse.com/betaprogram/caasp-beta/#download`.

It should say to download JeOS-OpenStack image (currently SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-GMC.qcow2) from https://www.suse.com/betaprogram/sle-beta/#download

**Comment by r0ckarong** [comment]
> The same in the quick start https://susedoc.github.io/doc-caasp/master/caasp-quickstart/single-html/#_deployment_on_suse_openstack_cloud

Quickstart is literally the same content included in a different meta file.

**Comment by jordimassaguerpla** [comment]
All images (and isos) are in the sle15sp1 beta page.

**Comment by r0ckarong** [comment]
ok then I can change my link variable

**Comment by r0ckarong** [comment]
Fixed with 5788618
