### ISSUE TITLE
Registration code for beta 

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#234]
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#registration_code

These instructions are for the alpha codes which are only internal.

We should change this for instructions on how to get the beta codes. From the announcement email:

Customers who wish to beta test SUSE CaaS Platform 4 should send an e-mail to beta-programs@lists.suse.com to request a SUSE Customer Center subscription and a Registration code.

**Comment by r0ckarong** [comment]
Added internal logic that displays the correct method for registration codes depending on release type.
