### ISSUE TITLE
Document review for kured service

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#236]
This relates to the [Epic: upgrade of base OS](https://github.com/SUSE/avant-garde/issues/331)

Review the documentation contributed from the devs:

* [x] Explain how to completely disable automatic reboots
* [x] Explain how to prevent nodes running special workloads from being rebooted
* [ ] Explain how to prevent nodes with specific prometheus alerts from being rebooted

**Comment by jordimassaguerpla** [comment]
Hi! Just a heads up on something that came up during today standup. Are we considering documenting how to update the management node?

**Comment by MaximilianMeister** [comment]
this is one PR to review https://github.com/SUSE/doc-caasp/pull/246

another one will follow about how to disable automatic updates

**Comment by r0ckarong** [comment]
> Hi! Just a heads up on something that came up during today standup. Are we considering documenting how to update the management node?

@jordimassaguerpla  What exactly is meant with "update the management node"? Updating the OS packages? Updating the runtime? I don't think we specifically considered this for the admin guide so far but this is because I wasn't aware of any requirements for updating. Who can provide this information?

**Comment by jordimassaguerpla** [comment]
> > Hi! Just a heads up on something that came up during today standup. Are we considering documenting how to update the management node?
> 
> @jordimassaguerpla What exactly is meant with "update the management node"? Updating the OS packages? Updating the runtime? I don't think we specifically considered this for the admin guide so far but this is because I wasn't aware of any requirements for updating. Who can provide this information?

Packages (skuba, terraform) are installed by a pattern. I assume our customers will see updates to the packages installed using the SLE tools, be that zypper, SUSE Manager, ... So we were wondering if we should say something about that or point to the SLE guides. @kravciak Is this what you mean at the standup? Did I get it right or am I missing anything?

**Comment by MaximilianMeister** [comment]
> this is one PR to review #246
> 
> another one will follow about how to disable automatic updates

it's now part of the same PR, separate commit

**Comment by kravciak** [comment]
@jordimassaguerpla I meant this scenario:
 - user installs skuba, run bootstrap & add 1 worker
 - user goes for 2 months vacation
 - user comes back, runs wants to add 1 more worker

While he was gone, cluster was self-updating (SUSE-CaaSP-Node), but skuba (SUSE-CaaSP-Management) did not.

Is it possible that at this point skuba (outdated) will not be compatible with cluster (up-to-date)?

**Comment by jordimassaguerpla** [comment]
@MaximilianMeister This is possible. Imagine that kubelet gets updated in the node but the kubernetes containers are not. Which containers to use is managed by skuba.

**Comment by r0ckarong** [comment]
@MaximilianMeister Regarding the last bullet point in the original description. Is it enough that we have the "block reboot for specific nodeID" and let the user figure out how to implement reaction to prometheus events to perform this step on the flagged node? If so we can close this Issue.

**Comment by MaximilianMeister** [comment]
> Regarding the last bullet point in the original description. Is it enough that we have the "block reboot for specific nodeID" and let the user figure out how to implement reaction to prometheus events to perform this step on the flagged node? If so we can close this Issue.

not sure i fully understand the question, the docs regarding configuring prometheus to interact with kured are already in https://github.com/SUSE/doc-caasp/blob/master/adoc/deployment-bootstrap.adoc#prevent-nodes-with-any-prometheus-alerts-from-being-rebooted

so i guess this behaviour (last bullet point) can be configured already, but maybe you can clarify again what you mean

**Comment by r0ckarong** [comment]
@MaximilianMeister Ah, I wasn't part of that pull request that added this stuff. I didn't know it was in the deployment guide. Ok so this can be closed.
