### ISSUE TITLE
Create supportconfig docs

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#238]
Relates to: https://github.com/SUSE/avant-garde/issues/287

Should go into "troubleshooting / debugging" in admin guide

**Comment by jordimassaguerpla** [comment]
As a result of the planning, we are moving this to sprint 8.

**Comment by r0ckarong** [comment]
Please ask @flavio and @ereslibre what needs to be done and what info they can provide.

**Comment by r0ckarong** [comment]
Based on the v3 version, describe what `supportconfig` does and what the options are.

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#cha.admin.troubleshooting

**Comment by nkoranova** [comment]
This will probably require a separate troubleshooting section in the admin guide. We also need to consult the process with CaaSP support.

**Comment by jordimassaguerpla** [comment]
@r0ckarong Can we move this to the Release Coordination project so we have a better overview? Makes sense to you?

**Comment by jordimassaguerpla** [comment]
see https://github.com/SUSE/avant-garde/issues/287#issuecomment-507728278

**Comment by flavio** [comment]
I don't think we have to document anything special, `supportconfig` works in the same way as on SLES. Hence we can point to the official sles documentation, that already has a [section](https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_admsupport_supportconfig.html) about it (forgive the SLES12 link, that's the first hit I got).

Question for @jordimassaguerpla: are we installing our supportconfig plugin as part of the caasp pattern?

**Comment by jordimassaguerpla** [comment]
Not by default but it is available in the repos.

**Comment by jordimassaguerpla** [comment]
kudos to @mjura , I only accepted it ;)

**Comment by r0ckarong** [comment]
Work is being done in the PR #304, closing.

**Comment by r0ckarong** [comment]
Work is being done in the PR #304, closing.
