### ISSUE TITLE
Document central logging container

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#240]
https://github.com/SUSE/avant-garde/issues/324

**Comment by innobead** [comment]
@r0ckarong what info you want to know? For centralized logging architecture, you can check below document. For any help and info, feel free to reach out to @cclhsu, thanks!

https://confluence.suse.com/display/SUSECaaSPlatform4/Centralized+Logging+Document

**Comment by cclhsu** [comment]
@nkoranova I just notice that @r0ckarong is not available till next week. Do you know if this ticket would be pickup by other members of technical writing team?

**Comment by nkoranova** [comment]
@cclhsu no, it's just me and Markus, I will try to draft the article today and we will wait for next week for @rockalong to review and merge it into the docs.

**Comment by r0ckarong** [comment]
Related to: https://github.com/SUSE/doc-caasp/issues/176

**Comment by nkoranova** [comment]
pull request here: #260
