### ISSUE TITLE
Review automatic registration to SMT/SCC to docs

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#242]
https://github.com/SUSE/avant-garde/issues/289

**Comment by inercia** [comment]
I'm taking this issue. @nkoranova @r0ckarong or @jordimassaguerpla assign this to me.

**Comment by jordimassaguerpla** [comment]
This was already done https://github.com/SUSE/doc-caasp/commit/c12d1543d0c65e003ac3f279959602531e689bbe#diff-080a8c5ea31c1a66ad301eac1c5178a4

For vmware, I can't find the commit but I see a similar text about how to use registration.auto.tfvars is there.
