### ISSUE TITLE
Improve Adding Nodes section

### ISSUE THREAD

**Issue by emilianolangella** [SUSE/doc-caasp#244]
2.3.1 Adding Nodes

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#sec.admin.nodes.add

I do believe we need a clear statement on our documentation saying that before adding a new worker, you need to update that worker to the same patch level as other cluster nodes to avoid issues.

**Comment by r0ckarong** [comment]
This should be closed with #269
