### ISSUE TITLE
install terraform package from SUSE CaaSP extension

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#248]
In the deployment guide for ECP I see we are installing terraform from download.opensuse.org/repositories/systemsmanagement:/terraform

while we should install it from the SUSE CaaSP extension. Actually, if the user has installed the CaaSP Management pattern, terraform should be installed.

**Comment by r0ckarong** [comment]
Check if we are still mentioning manual installation of this from OBS.

**Comment by MaximilianMeister** [comment]
I'm going to grab this one

**Comment by MaximilianMeister** [comment]
this should be fine already, i can't find any occurrence of this obs repo anymore:

we are mentioning the correct way of installing terraform through the management pattern in all deployment guides for the different platforms

**Comment by jordimassaguerpla** [comment]
Thanks @MaximilianMeister
