### ISSUE TITLE
add "edit source | report bug"

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#251]
In SLE docs, you can see a link to the right of the chapters about editing or reporting a bug:

https://susedoc.github.io/doc-sle/develop/SLES-dockerquick/single-html/#Docker_Architecture

This is very useful.

Can we have this as well?

**Comment by jordimassaguerpla** [comment]
Thanks @vmoutoussamy for the feedback.

**Comment by vmoutoussamy** [comment]
The "EDIT SOURCE" is optional but could point to github and the "REPORT BUG" could either point to "https://bugzilla.suse.com/enter_bug.cgi?&product=Beta%20SUSE%20CaaS%20Platform%204&component=Documentation" or github's issues. 
You can decide what's best for you : ).

**Comment by r0ckarong** [comment]
I will talk to the Doc team how we can enable this.

**Comment by r0ckarong** [comment]
Created a shared `docinfo.xml` file for the books. 
Added the `:docinfo: shared-head` attribute to the book files.

Modified docmanager settings the docinfo file from https://github.com/SUSE/doc-sle/blob/develop/xml/MAIN.SLEDS.xml#L43 to be used with CaaSP / GitHub.

**Comment by r0ckarong** [comment]
Configuring according to: http://docserv.nue.suse.com/documents/Team_Hitchhikers_Guide/hitchhiker-guide/html/cha.doc.docserv.html#sec.doc.out.docserv.bug

**Comment by r0ckarong** [comment]
Still trying to find out why the "Edit" link won't show up but this should be ok for now.
