### ISSUE TITLE
Update minimal hardware requirements info

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#255]
Relates to:
https://github.com/SUSE/avant-garde/issues/395 

Depends on Cilium 1.5:
https://docs.cilium.io/en/v1.5/install/system_requirements/

**Comment by r0ckarong** [comment]
@jordimassaguerpla How important is this for the next release. We didn't manage to do this in Sprint 7. 
@lcavajani Did the underlying testing for this happen or can it happen this sprint?

**Comment by lcavajani** [comment]
@r0ckarong I'm currently working on it
