### ISSUE TITLE
[doc] 3.4.2  AutoYaST preparation

### ISSUE THREAD

**Issue by dwainsims** [SUSE/doc-caasp#274]
3.4.2  AutoYaST preparation

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_autoyast_preparation

This file does not exist....
Obtain example AutoYaST file from /usr/share/caasp/autoyast/bare-metal/autoyast.xml

**Comment by r0ckarong** [comment]
You did install the CaaSP pattern beforehand right?

**Comment by dwainsims** [comment]
Markus:

We figured this out eventually.  It turns out you need the
SUSE-CaaSP-Management pattern,  and that needs to get applied to your Admin
node.  That is where the autoyast file will be found.  This is in the doc
someplace, but was not in the thread I thought I was following.

Thanks for asking.

Dwain
dsims@suse.com

**Comment by jordimassaguerpla** [comment]
Can we close this issue?

**Comment by nkoranova** [comment]
> Can we close this issue?
No, I think this bug shows that the procedure isn't described well enough - I need to add a note about when and how this 'caasp/autoyast/bare-metal/autoyast.xml' is created (link to the Deployment guide section where this happens).
