### ISSUE TITLE
[doc] 2.2.6.1  Mirror Configuration

### ISSUE THREAD

**Issue by lnyiri63** [SUSE/doc-caasp#277]
2.2.6.1  Mirror Configuration

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.scenarios.airgap.container-registry.mirror

Unfortunately the external registry mirror is RO too. Something is wrong in this guide at basic level

**Comment by r0ckarong** [comment]
Have you verified that the configuration for the external registry mirror does not contain the readonly attribute enabled?

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#id-1.4.4.3.10.3.6

**Comment by r0ckarong** [comment]
v3 is EOL and this hasn't gotten any response. Closing.
