### ISSUE TITLE
[doc] 2.2.6.1  Mirror Configuration

### ISSUE THREAD

**Issue by msvec** [SUSE/doc-caasp#279]
2.2.6.1  Mirror Configuration

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.scenarios.airgap.container-registry.mirror

The text is rather complex, it would be great to have a picture outlining the setup with internal/external registries and how they are interconnected together and with CaaSP.

**Comment by r0ckarong** [comment]
This might be good to add to v4. Moving.
