### ISSUE TITLE
[doc] 3.4.2  AutoYaST preparation

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#281]
3.4.2  AutoYaST preparation

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_autoyast_preparation
the provided
/usr/share/caasp/autoyast/bare-metal/autoyast.xml
doesn't work, when used on a 30GB  system disk
You get an error with the /var/lib partition

the terraform.tfvars file includes sizes for master and worker nodes(50 and 30 GB respectively)
but for the autoyast installation(where no terraform is used), there is no mentioning of minimal disk size

**Comment by r0ckarong** [comment]
@thehejik @kravciak Can you guys provide a minimum disk size for AutoYaST installation or tell me who would know this?

**Comment by thehejik** [comment]
According to AutoYaST and its `partitioning` section:
* 200MB for /boot/efi
* 30GB for /
* the rest of HDD capacity for /var/lib (mainly for container images)

So the minimal disk size would be about 40GB - that means 10GB for containers. Of course it depends on the desired workload and if user plans to use cluster node as "local-storage" for data . Anyway it will be pretty hard to buy such a small drive nowadays.

Currently used space for containers on my bm cluster without any workload for containers on master and worker node is about 3GB each.

**Comment by jordimassaguerpla** [comment]
This looks done. Can we close this issue?

**Comment by nkoranova** [comment]
If nobody wants to review it, then yeah :)
