### ISSUE TITLE
Improve "deployment on existing SLES docs"

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#286]
According to this:

https://chat.suse.de/channel/caasp?msg=o94NJbzsJ4GXQa9Mt

We need to improve the instructions for the existing SLES scenario. The steps install the wrong software pattern which is missing skuba. The entire "management node" concept is not clear enough.

**Comment by jordimassaguerpla** [comment]
featuresquad: please figure out which should be the instructions.

**Comment by stefsuse** [comment]
I believe the wrong pattern issue has been addressed in last beta. 

We have an open ticket for the "management node" wording.  https://github.com/SUSE/doc-caasp/issues/341

Can this issue be closed?

**Comment by inercia** [comment]
I think we can close this issue. #341 has been merged.
