### ISSUE TITLE
Add mention of Layer 7 for Cilium

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#287]
https://chat.suse.de/channel/caasp-devel?msg=hjtXhknjYgTK5KPai

**Comment by r0ckarong** [comment]
https://www.techopedia.com/definition/20338/layer-7

**Comment by jordimassaguerpla** [comment]
L7 is not in our product yet but it is plan for post-FCS. Please let's make sure what we document is aligned with the product.

L7 filtering is already in our Devel projects, so this may confuse some people.

**Comment by r0ckarong** [comment]
OK I misread/missed the original line about this from roger. I will add to the release notes saying that L7 policies will not work.

**Comment by r0ckarong** [comment]
Fixed with https://github.com/SUSE/caasp-release-notes/commit/9229c4ba8f46d1900a9b35810520c577f2811109
