### ISSUE TITLE
Update docs for k8s 1.15

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#294]
- Change the version numbers in attributes.doc
- Check if all references are changed
- Add "new kubernetes features" to release notes where appropriate

Get input from @ereslibre about new k8s features.

**Comment by r0ckarong** [comment]
https://github.com/SUSE/avant-garde/issues/466

**Comment by NunoFilipeSantos** [comment]
@r0ckarong The Feature Squad will be bumping several packages versions, you might want to check out before moving to done.

**Comment by nkoranova** [comment]
https://github.com/SUSE/caasp-release-notes/pull/6

**Comment by r0ckarong** [comment]
@nkoranova I updated the attributes file in the main repo as well. Closing this.
