### ISSUE TITLE
Document "upgrade apply" feature for skuba

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#296]
https://github.com/SUSE/avant-garde/issues/446

**Comment by r0ckarong** [comment]
@ereslibre Is there a separate "skuba cluster upgrade apply"?

**Comment by ereslibre** [comment]
> @ereslibre Is there a separate "skuba cluster upgrade apply"?

No, what will be implemented is what's described in https://github.com/SUSE/caasp-rfc/blob/master/accepted/0040-platform-upgrade.md. This is:

* `skuba cluster upgrade plan`
* `skuba node upgrade plan`
* `skuba node upgrade apply`

We are trying to be 1:1 with the RFC, but ideally after a major command is finished we should write the initial documentation in the place that helps you the most and evolve from there.
