### ISSUE TITLE
Managing User and service accounts and groups

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#312]
Define which concepts apply to CaaSP, describe the full lifecycle for all types
Describe how accounts can be added, removed, modified.

- [ ] Adding Users
- [ ] Removing Users
- [ ] Password / key / credential Management
- [ ] Adding Groups
- [ ] Editing Groups
- [ ] Removing groups
- [ ] Service accounts

**Comment by innobead** [comment]
Documentation already in https://github.com/SUSE/doc-caasp/blob/master/adoc/admin-security-ldap.adoc#managing-users-and-groups which is also based on v3 documentation https://www.suse.com/documentation/suse-caasp-3/book_caasp_admin/data/sec_admin_security_users.html.

**Comment by innobead** [comment]
@nkoranova please confirm if this is still needed, thanks.
