### ISSUE TITLE
Role Management (RBAC)

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#313]
Will at least partially be covered by: #298 

- [x] Defining roles
- [x] Managing access using roles
- [x] Configuration examples for various scenarios

**Comment by nkoranova** [comment]
Done in: 
https://github.com/SUSE/doc-caasp/pull/415 
https://github.com/SUSE/doc-caasp/pull/355 
https://github.com/SUSE/doc-caasp/pull/419
