### ISSUE TITLE
Describe certificate handling

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#315]
- [ ] Usage of certificates within product
- [ ] Which certificates are generated
- [ ] Which certificates can be swapped in from existing CA
- [ ] How to generate certificates
- [ ] How to use certificates from existing CA instead of auto generated certificates
- [ ] Renewal / replacement
- [ ] Lifecycle management
- [ ] Certificate specifications (encryption algorithms used, strength of encryption etc.)

**Comment by nkoranova** [comment]
This is covered by https://github.com/fujexo/doc-caasp/pull/107/files
