### ISSUE TITLE
Describe Cilium networking policies

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#317]
- [ ] Concepts and usage
- [ ] Designing pod security policies
- [ ] Deployment
- [ ] Undeployment
- [ ] Modification

**Comment by nkoranova** [comment]
currently described by https://github.com/SUSE/doc-caasp/blob/master/adoc/deployment-cilium.adoc
and https://github.com/SUSE/doc-caasp/pull/547
