### ISSUE TITLE
Describe Security Audit Log

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#318]
Kubernetes provides a security audit log. Describe how it can be configured, what it is used for, how it can be accessed and how the contents can be interpreted.

**Comment by nkoranova** [comment]
Audits can be done with [centralized logging](https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_centralized_logging), right? @innobead is anyone up to writing a section on how to interpret logs from centralized logging for the purpose of security audits? https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by innobead** [comment]
Audit logging should is about event auditing by API server. But centralized logging deserves enhancing to support to collect logs from a configured audit log path to forward to external (it should be planned later).

cc @jenting @c3y1huang @cclhsu

**Comment by r0ckarong** [comment]
Relates to: https://bugzilla.suse.com/show_bug.cgi?id=1168491

**Comment by r0ckarong** [comment]
Relates: https://github.com/SUSE/avant-garde/issues/1520
