### ISSUE TITLE
Describe software installation procedures

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#320]
How to install software on a CaaSP cluster (for workloads)
How to install additional software / drivers for enabling cluster functionality

- [ ] From package repositories / modules
- [ ] From containers
- [ ] From other sources (helm etc.)
- [ ] How to install patches and temporary fixes
- [ ] How to update, when to update, expected maintenance windows

**Comment by Klaven** [comment]
I will work on this!

**Comment by r0ckarong** [comment]
Covered in #503 for the most part.
