### ISSUE TITLE
Describe CaaSP Upgrade procedure

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#322]
How to upgrade from one CaaSP version to the next, what to expect, which precautions to take

- [x] Describe minor -> minor upgrade
- [ ] Describe minor -> major upgrade
- [ ] Describe major -> major upgrade
- [x] Describe point release upgrade/updates

**Comment by jordimassaguerpla** [comment]
work for updatesquad

**Comment by r0ckarong** [comment]
These are pretty much covered in the release notes for individual releases were needed, update instructions continuously updated. Closing.
