### ISSUE TITLE
Describe migration path from CaaSP v3 -> v4

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#323]
Migration of workloads and all related settings. This is a MAJOR effort that will involve a lot of conversation with stakeholders and customer experienced staff.

We must describe basic migration from a regular supported scenario to the new version.

Scope of this must be defined by PM/PO.

**Comment by r0ckarong** [comment]
@kkaempf @qnetter @NunoFilipeSantos Could you please define the scope of the migration scenarios we support, the versions that can be migrated to which new version of CaaSP and who is responsible for performing migration tests and is the owner on the development side for this topic.

**Comment by kkaempf** [comment]
That's a post-FCS deliverable

**Comment by qnetter** [comment]
The docs need a guidance message about our recommendation (back up workloads, rebuild cluster, restore workloads), as well as our plans to provide a SUSE service offering to support cases where this is not possible. I'll draft it.

**Comment by NunoFilipeSantos** [comment]
Thank you @qnetter ! 👍

**Comment by r0ckarong** [comment]
As per this comment right now migration is not needed and will not be developed as of now.

https://github.com/SUSE/avant-garde/issues/72#issuecomment-543714594
