### ISSUE TITLE
Describe Graceful Shutdown and Startup

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#329]
Describe how to shut down a cluster properly
How to start a cluster back up with all intended workloads

For example for moving machines to a different datacenter, migrating to other machines, in preparation for a maintenance window or emergency, startup after an emergency and so on

**Comment by Klaven** [comment]
@r0ckarong to me, I will describe shutdown, but to be honest, if they are dealing with a power outage they should be able to bring their cluster back online just fine. Really shutdown only maters for what is running on their cluster.

shutting down:
0. take a backup
1. Scale all applications down to zero.
2. Drain/cordon all nodes except for control plane.
3. Shut down worker nodes nodes.
4. Shut down control plane @flavio and @ereslibre I have seen people that do more elaborate control plane shutdown, have you ever found it needed? aka, shutdown control plane service x first. then....?

Starting:
0. start all control plane nodes first and wait for them to come online
1. Once control plane nodes online and healthy, start all other nodes
2. enjoy

Do you need me to make a PR with these or is this enough?

**Comment by r0ckarong** [comment]
> @r0ckarong to me, I will describe shutdown, but to be honest, if they are dealing with a power outage they should be able to bring their cluster back online just fine. Really shutdown only maters for what is running on their cluster.
> 
> shutting down:
> 
>     1. take a backup
> 
>     2. Scale all applications down to zero.
> 
>     3. Drain/cordon all nodes except for control plane.
> 
>     4. Shut down worker nodes nodes.
> 
>     5. Shut down control plane @flavio and @ereslibre I have seen people that do more elaborate control plane shutdown, have you ever found it needed? aka, shutdown control plane service x first. then....?
> 
> 
> Starting:
> 
>     1. start all control plane nodes first and wait for them to come online
> 
>     2. Once control plane nodes online and healthy, start all other nodes
> 
>     3. enjoy
> 
> 
> Do you need me to make a PR with these or is this enough?

@Klaven I only got around to answering during backlog refinement. From what I understand drain/cordon is now done automatically by skuba. Could you open a PR that describes what you started here taking this new feature into account?

**Comment by Martin-Weiss** [comment]
During "Starting" don´t we have to uncordon the workers as step 3 and "enjoy" in step 4?

**Comment by evrardjp** [comment]
nope, I think they will come back online uncordoned. TBC.
