### ISSUE TITLE
Describe Monitoring

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#336]
- [ ] Monitoring recommendations
- [ ] Monitoring the cluster
- [ ] Health Checking

**Comment by NunoFilipeSantos** [comment]
@lcavajani and @fgerling do you have any information you can share on this topic?

**Comment by fgerling** [comment]
Is this from the "Point Of View" of the customer or devs/QA?

I have done some work of monitoring based on prometheus, node_exporter and grafana here: http://techno.qa.prv.suse.net:3000

Please ask me on Rocket.chat or mail for credentials. 

It is monitoring system resources on kernel level. I integrated an auto-discovery feature so we can easily add a new cluster to it. Regardless of OpenStack, bare metal or vmware.

To create customer level documentation, I would need a hand from someone more proficient on writing k8s deployments. We could then also create a cgroups based monitoring to monitor at "container" level. AFAIK k8s is already providing a good amount of data that we could use.

**Comment by lcavajani** [comment]
I wrote the doc for v3 https://www.suse.com/documentation/suse-caasp-3/book_caasp_admin/data/sec_admin_monitoring_stack.html

and a couple of dashboards https://github.com/kubic-project/monitoring

@NunoFilipeSantos AFAIU this will be tackled by the Taiwan team since they worked on Logs, cc to get more info ;) @innobead

**Comment by jordimassaguerpla** [comment]
Thanks for the info @lcavajani and @fgerling . Adding the Taiwan Squad label so they can work on that based on your docs.

**Comment by innobead** [comment]
@lcavajani thanks for the info.

Let's just use v3 admin guide as base for v4 documentation. 

Because we don't have monitoring feature integration in v4 yet that means no sustainable container images/packages provided, so we will focus on configuration & usage instead of deployment.
