### ISSUE TITLE
Describe Logging

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#337]
- [ ] Formats
- [ ] Logging recommendations
- [ ] Central log collection

**Comment by NunoFilipeSantos** [comment]
@innobead Do you have this content, or does it still need to be developed?

**Comment by innobead** [comment]
For now, we have centralized logging documentation, good enough.

**Comment by NunoFilipeSantos** [comment]
@nkoranova Can we close this issue then?

**Comment by nkoranova** [comment]
.... I guess, I mean what we probably have is good enough. I am guessing Markus created this issue based on the RFC, he was creating issues for some of the sections we still need to document. We can always open a new one, if we find that section insufficient at some point.
