### ISSUE TITLE
Create Troubleshooting section

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#338]

**Comment by jordimassaguerpla** [comment]
Work for update squad.

**Comment by NunoFilipeSantos** [comment]
https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_troubleshooting I think there is a typo in the beginning of the section.

**Comment by jordimassaguerpla** [comment]
We already have a section in admin guide: https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_troubleshooting

Only the typo should be fixed.

**Comment by nkoranova** [comment]
Typo fixed with https://github.com/SUSE/doc-caasp/commit/f33ca6f3ea26670c42f1e1326ac726d6d6642ac8
We should continue to add advice on how to troubleshoot, but we will probably have to collect that information once we have a little more feedback and know what frequent issues are.
