### ISSUE TITLE
Reword "Management node" in the CaaSP description

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#341]
Suggestion by @qnetter via email:

```Please let’s not call it the CaaSP management node. That sounds like a dedicated machine like the admin node. Let’s say you need to install the CaaSP deployment or bootstrap tools or something on a (SLES 15 SP1?) system. ```

Find mentions of this in the guides and reword accordingly. Internally this will probably be referred to as the "management node" in future but we want to explain that this is any workstation that can install the tools not an additional machine in the cluster.

**Comment by NunoFilipeSantos** [comment]
@qnetter what should we name it too?

**Comment by qnetter** [comment]
Management host. "Node" implies that it is a member of the cluster.

**Comment by jordimassaguerpla** [comment]
@NunoFilipeSantos given we have the info and it is an easy fix, should I make it P2?

**Comment by NunoFilipeSantos** [comment]
We can, looks like a find and replace to me.

**Comment by jordimassaguerpla** [comment]
@nkoranova Alvaro will work on this.
