### ISSUE TITLE
[doc] 4.1.1  Cluster initialization

### ISSUE THREAD

**Issue by viccuad** [SUSE/doc-caasp#345]
4.1.1  Cluster initialization

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_cluster_initialization

"cluster init generates the folder named my-cluster and initializes the directory that will hold the configuration for the cluster."

We should also say that the kubeconfig for accessing the cluster with kubectl is there.

**Comment by viccuad** [comment]
Fair enough, it's also at https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_using_kubectl

**Comment by r0ckarong** [comment]
Fixed with 739dbb9
