### ISSUE TITLE
Test Docserv2

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#360]
http://docserv.nue.suse.com/documents/Team_Hitchhikers_Guide/hitchhiker-guide/html/cha.doc.docserv2.html

**Comment by nkoranova** [comment]
https://trello.com/b/kSN57LFa/doc-docserv2-team-tasks 
http://docserv.nue.suse.com/docserv-build-test-eli/#caasp

**Comment by jordimassaguerpla** [comment]
Done.
