### ISSUE TITLE
Clarify kubernetes-dashboard v4 status

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#362]
Is it supported? Do we suggest installing it? 

@kkaempf @qnetter

**Comment by kkaempf** [comment]
No. Not interlocked.

**Comment by r0ckarong** [comment]
@nkoranova If Jason needs this for training purposes it needs to go through the PO/feature pipeline and be discussed otherwise it's unsupported and can only be communicated as such.
