### ISSUE TITLE
[doc] 2  Cluster management

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#371]
This is empty.

2  Cluster management

https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_cluster_management

**Comment by jordimassaguerpla** [comment]
It is not empty now but I see this text

/= Cluster Management

looks like a typo in asciidoc

**Comment by bergmannf** [comment]
https://github.com/SUSE/doc-caasp/pull/407

**Comment by nkoranova** [comment]
That heading was supposed to be commented out (it's a long story, but essentially the only way I found out for the document structure to look ok and build - don't ask). What is actually missing is the other slash to have it properly commented out and it's already in the code, https://github.com/SUSE/doc-caasp/blob/beta/adoc/admin-cluster-management.adoc 
I just have to find out why the build docs haven't changed - that should happen automatically.
