### ISSUE TITLE
Add howto for flannel security fix to the v3 release notes

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#373]
The fix makes sure that flannel (layer 3 networking fabric) runs in unprivileged mode. This fix comes in the next release and Ludo's howto describes how to apply those changes here: https://github.com/SUSE/kubic-salt-security-fixes/pull/5#issuecomment-509173363

* put the steps in xml 
* update v3 release notes

**Comment by nkoranova** [comment]
https://gitlab.suse.de/documentation/release-notes-caasp/merge_requests/7

**Comment by jordimassaguerpla** [comment]
Blocked because the fix for v3 is not merged.

**Comment by r0ckarong** [comment]
@jordimassaguerpla Is this merged now?
@nkoranova would you take care of this if it is please?

**Comment by jordimassaguerpla** [comment]
This has not been released yet, sadly.

**Comment by r0ckarong** [comment]
Referenced in https://bugzilla.suse.com/show_bug.cgi?id=1153230

**Comment by sknorr** [comment]
Oh well, can't say I haven't tried. Nora said it was finally released now.

I have revoked the MR I made as well.

**Comment by nkoranova** [comment]
I said it was merged. :) which it was. I foolishly expected it to be released soon thereafter. Sorry. :confused: btw. @sknorr when you merge something into the release notes repo, does that simultaneously mean it  gets published? Or what is the process?

**Comment by sknorr** [comment]
No, it's not automatically published (with your current process anyway). I need to package and submit it after merging and the team needs to accept the submission. But I'd done my part already before I saw Markus's message here. :)

**Comment by sknorr** [comment]
fixed via https://build.suse.de/request/show/204890
