### ISSUE TITLE
[doc] 4.1.1  Install <code class="literal">skuba</code>

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#376]
On the following part, it's not very clear what needs to be installed before cluster bootstrap. My setup failed when I tried, it was only able to continue after I installed necessary components like below:

Master node:
zypper in -t pattern SUSE-CaaSP-Management
zypper in kubernetes-kubeadm kubernetes-kubelet kubernetes-client cri-o cni-plugins

Worker node:
zypper in kubernetes-kubeadm kubernetes-kubelet kubernetes-client cri-o cni-plugins
zypper in -t pattern SUSE-CaaSP-Node

--------
4.1.1  Install <code class="literal">skuba</code>

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_install_skuba

**Comment by jordimassaguerpla** [comment]
I don't think you need to install the patterns in the master and worker, skuba should do it.
@ereslibre can you confirm?

**Comment by ereslibre** [comment]
Correct, skuba will install the correct node pattern on all nodes when bootstrapping and joining.

**Comment by jordimassaguerpla** [comment]
Then nothing to do in the docs.
