### ISSUE TITLE
[v3] [doc] Example 1.7:  Binding a Group to a Role 

### ISSUE THREAD

**Issue by nyoung02** [SUSE/doc-caasp#378]
Example&nbsp;1.7:  Binding a Group to a Role 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#ex.admin.security.groups.role

There should not be a - in the "- kind: Role" line

**Comment by jordimassaguerpla** [comment]
This looks related to RBAC. @innobead can you confirm we need to fix it as proposed?

**Comment by innobead** [comment]
This is already included in https://github.com/SUSE/doc-caasp/blob/master/adoc/admin-security-rbac.adoc#kube-role-binding.

**Comment by innobead** [comment]
@jordimassaguerpla  **I think this ticket is a bug for v3 documentation instead of v4.** 

v4 related ticket should be https://github.com/SUSE/doc-caasp/issues/313 we will work on.

**Comment by jordimassaguerpla** [comment]
@innobead Can you provide a fix for v3 as well?

**Comment by innobead** [comment]
Sure if this is priorities, we can put in the queue.

**Comment by jordimassaguerpla** [comment]
https://github.com/SUSE/avant-garde/projects/13

@NunoFilipeSantos: given v3 is at the bottom of the priorities. Should we not fix this one?

**Comment by NunoFilipeSantos** [comment]
V3 is always there, it is the current product in the hands of our customers. 
If this is generating bugs reports from customers, fix it now.

**Comment by cclhsu** [comment]
Fix PR[441](https://github.com/SUSE/doc-caasp/pull/441)

**Comment by jordimassaguerpla** [comment]
Removing it from sprint12 and postponing this for later according to the team priorities for sprint13

**Comment by nkoranova** [comment]
https://documentation.suse.com/suse-caasp/3/single-html/caasp-admin/#ex-admin-security-groups-role 
@innobead this is a fix for v3 https://github.com/SUSE/doc-caasp/pull/556 
Is that what the original Issue was about?

**Comment by cclhsu** [comment]
@nkoranova #556 and #441 are fixing same issue of extra "-" in admin security document.

**Comment by nkoranova** [comment]
> @nkoranova #556 and #441 are fixing same issue of extra "-" in admin security document.

Ok. In that case the issue is probably solved.
