### ISSUE TITLE
[doc] 3.1.3.1.1  Configuring The Load Balancer

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#379]
What is $MY_REG_CODE below?

SUSEConnect -r $MY_REG_CODE

-------
3.1.3.1.1  Configuring The Load Balancer

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_configuring_the_load_balancer

**Comment by jordimassaguerpla** [comment]
MY_REG_CODE can be the SUSE CaaSP Registration Code or the SUSE Linux Enterprise Registration Code.

**Comment by jordimassaguerpla** [comment]
duplicated of https://github.com/SUSE/doc-caasp/issues/250
