### ISSUE TITLE
[doc] 4.2.3  Cluster bootstrap

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#387]
4.2.3  Cluster bootstrap

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#cluster.bootstrap

skuba node bootstrap --user sles --sudo --target <IP/FQDN> <NODE NAME>
doesn't work with user sles

in bootstrap.go
the following command will fail even with sudo as user sles, because modprobe is not in the PATH of user sles

"sudo sh -c 'modprobe br_netfilter'"

**Comment by jordimassaguerpla** [comment]
@lcavajani @kravciak which should be the instructions here?

**Comment by jordimassaguerpla** [comment]
Work for feature squad to figure this out.

**Comment by kravciak** [comment]
We use this and it works fine.
```bash
skuba node bootstrap --user sles --sudo --target <IP/FQDN> caasp-master-0
```

There is not enough information here (platform, skuba version, JeOS image).

Wild guess is that you use outdated skuba. Do you have this section in terraform.tfvars?
```yaml
# Minimum required packages. Do not remove them.
# Feel free to add more packages
packages = [
  "kernel-default",
  "-kernel-default-base"
]
```

**Comment by Klaven** [comment]
I checked with the original issuer, this issues has not been seen again. can be closed.

**Comment by jordimassaguerpla** [comment]
Thanks.
