### ISSUE TITLE
[doc] 3.1.1  Registration Code

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#388]
3.1.1  Registration Code

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#registration_code

it should be pointed out, that the user requesting the Beta registration code should use an email address, that has a corresponding SCC account, otherwise it will not be possible to activate the Beta subscription

**Comment by jordimassaguerpla** [comment]
Beta reg codes will be removed https://github.com/SUSE/avant-garde/issues/713
