### ISSUE TITLE
[doc] 3.1  Deployment Preparations

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#389]
3.1  Deployment Preparations

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#deployment.preparations

ssh-add <path to key>
is ambiguous

ssh-add ~/.ssh/id_rsa
is not valid and will give problems later on

you have to use i.e.: 
ssh-add /home/sles/.ssh/id_rsa

**Comment by jordimassaguerpla** [comment]
Related to (if not duplicated) https://github.com/SUSE/doc-caasp/issues/245

**Comment by bergmannf** [comment]
I don't see any mention of `ssh-add ~/.ssh/id_rsa` - all references in the linked documentation are with pseudo path-variables.

There was an error of using `ssh-add -i <some_path>` though - which I opened a PR for to fix it: https://github.com/SUSE/doc-caasp/pull/406
