### ISSUE TITLE
[doc] 3.1.3.1.1  Configuring The Load Balancer

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#390]
3.1.3.1.1  Configuring The Load Balancer

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_configuring_the_load_balancer

the example nginx.conf used doesn't include configuration options for gangway and dex
as mentioned in the paragraph preceding this one

"It also needs access to Gangway port 32001 and Dex port 32000 on all master and worker nodes in the cluster for RBAC authentication."

these options should be included in the nginx.conf example:

        server {
              listen 32000;
              proxy_pass $upstream;
        }
        server {
              listen 32001;
              proxy_pass $upstream;
        }

**Comment by jordimassaguerpla** [comment]
@kravciak @lcavajani can you confirm we need this configuration?

**Comment by suseclee** [comment]
Working from feature squad: https://github.com/SUSE/avant-garde/issues/762

**Comment by jordimassaguerpla** [comment]
@suseclee Can you provide a PR to doc-caasp?

**Comment by jordimassaguerpla** [comment]
> Working from feature squad: [SUSE/avant-garde#762](https://github.com/SUSE/avant-garde/issues/762)

thanks for picking this one.
