### ISSUE TITLE
[doc] 4.2  Cluster Deployment

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/doc-caasp#394]
4.2  Cluster Deployment

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_cluster_deployment

This section should add that one can simply run

eval `ssh-agent` and note that it will only run temporarily

**Comment by abonillasuse** [comment]
Additionally, we should mention that if ssh keys have already been copied across nodes, they can simply run ssh-add to include known identities

"If all nodes taking part of the cluster already share ssh keys, a quick-start would be to:
"# eval `ssh-agent`"
"# ssh-add""

**Comment by jordimassaguerpla** [comment]
Related to (if not duplicated) https://github.com/SUSE/doc-caasp/issues/245

**Comment by drpaneas** [comment]
Please /close this issue and keep the information in one place (e.g. at 245)
