### ISSUE TITLE
[doc] 4.2.1.4  Prevent Nodes Running Special Workloads From Being Rebooted

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/doc-caasp#395]
4.2.1.4  Prevent Nodes Running Special Workloads From Being Rebooted

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_prevent_nodes_running_special_workloads_from_being_rebooted

Needs to be a bit less vague - what kind of nodes should be added here? If we think these are external services or we have an example in mind, we should mention it to clarify the intention on when to use this

**Comment by jordimassaguerpla** [comment]
@MaximilianMeister I think you wrote the initial contents of this. Can you tell us "what kind of nodes"?

**Comment by MaximilianMeister** [comment]
@jordimassaguerpla e.g. if `Node A` runs `ImportantPod` you can flag the **pod** as important, and therefore the node where it runs on will not be rebooted. So it's not so much about the node here, it's more about flagging the workload

**Comment by MaximilianMeister** [comment]
https://github.com/SUSE/doc-caasp/pull/439
