### ISSUE TITLE
Improve Release Notes contents for public releases 

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#396]
The current CaaSP 4 release notes only list feature changes and include none of our usual boilerplate content. We should add the following to formalize the content:

- [x] Product introduction -- people should know what they bought and what the headline new features are.
- [x] Support statement & time frame -- customers need to know how they are supported; our website is sadly completely useless in this regard. 
- [ ] How to get documentation -- being able to access documentation is usually important.
- [x]  Definition of a Technology Preview -- important to make sure we communicate support status of the product correctly.
- [x]  Obtaining source -- legal requirement
- [x]  Legal notices -- legal requirement

Inspiration here: https://www.suse.com/releasenotes/x86_64/SUSE-CAP/1/

**Comment by NunoFilipeSantos** [comment]
@qnetter Can you please provide more insight on the added value of this information, while also contributing to it? Otherwise we will stick with what we currently have.

**Comment by qnetter** [comment]
- Product introduction: Chris Lentricchia, Abhinav, and I will supply.
- Support policy: I have a graphical representation of it, and will work on getting the written version of it ready for both the release notes and the website.
- How to get documentation - I will steal/modify content from SLES.
- Technology Preview: is anything in 4.0 at this stage? Again, I can lift from SLES. Ditto for obtaining source and legal notices.

**Comment by nkoranova** [comment]
@qnetter, thanks! About the Legal notices - I suspect they are the same for all products and adding them will be very easy for me. I can do that. 
https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/3.0/#Legal

**Comment by nkoranova** [comment]
https://github.com/SUSE/caasp-release-notes/pull/10

**Comment by jordimassaguerpla** [comment]
>     * Product introduction: Chris Lentricchia, Abhinav, and I will supply.
> 
>     * Support policy: I have a graphical representation of it, and will work on getting the written version of it ready for both the release notes and the website.
> 
>     * How to get documentation - I will steal/modify content from SLES.
> 
>     * Technology Preview: is anything in 4.0 at this stage? Again, I can lift from SLES. Ditto for obtaining source and legal notices.

Hi @qnetter ! Could you provide us with this info or an ETA for us to plan? Thanks.

**Comment by jordimassaguerpla** [comment]
@qnetter Also please, what should we say about "Obtaining source -- legal requirement" ?

**Comment by nkoranova** [comment]
Work is being done in:  https://github.com/SUSE/caasp-release-notes/pull/13

**Comment by jordimassaguerpla** [comment]
We are blocked on getting a review of the https://susedoc.github.io/caasp-release-notes/master/release-notes/single-html/#_support_and_life_cycle by @qnetter
