### ISSUE TITLE
Spellchecking and proofreading the docs before the GC

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#408]
DAPS has a spellcheck and a stylecheck, which we should run before the release and also a urlcheck. All three of these steps can be done either by me or @r0ckarong. 
Apart from that, the docs should be proofread at least once from a professional proofreader. @taroth21 should be able to tell us who we need to contact and how early ahead of our potential deadline. 

- [x] spellcheck
- [ ] stylecheck
- [x] urlcheck
- [x] proofreading

**Comment by jordimassaguerpla** [comment]
Waiting for Microfocus proof reading.

**Comment by nkoranova** [comment]
The proofread pdfs are in and I will start manually integrating the suggestions today. After this is done, I will create a Tag to mark the changes: http://docserv.nue.suse.com/documents/Team_Hitchhikers_Guide/hitchhiker-guide/single-html/#sec-doc-proof-tag

**Comment by nkoranova** [comment]
https://github.com/SUSE/doc-caasp/pull/465

**Comment by nkoranova** [comment]
https://github.com/SUSE/doc-caasp/releases/tag/CaaSP_4_proofreading_1
