### ISSUE TITLE
[doc] 3.2.1  Deploying the cluster nodes

### ISSUE THREAD

**Issue by BriggsyUK1970** [SUSE/doc-caasp#416]
3.2.1  Deploying the cluster nodes

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_deploying_the_cluster_nodes

I have been trying to follow this as the document explains and find it extremely confused if not plain incorrect.

in 3.2.1.3 it states that the file structure for editing vars in terraform is "~/my-cluster/cloud-init" but the example explains this is to be at "~/caasp/deployment/openstack/cloud-init"
(AFAICS my-cluster is actually a skuba example later in the deployment process on OpenStack) 

Then at 3.2.1.6 it explains CPI integration being set through the "~/my-cluster/cpi.auto.tfvars" file.  Again assuming this should be the "~/caasp/deployment/openstack/cpi.auto.tfvars" file, it does not exist in my beta version (maybe this is a bug in the beta as well...).

**Comment by jenting** [comment]
@BriggsyUK1970 Thanks for reporting. We file a PR to fix this.
