### ISSUE TITLE
[doc] Example&nbsp;3.2:  Cluster Role for Creation of Pods 

### ISSUE THREAD

**Issue by bergmannf** [SUSE/doc-caasp#426]
Example&nbsp;3.2:  Cluster Role for Creation of Pods 

https://susedoc.github.io/doc-caasp/master/caasp-admin/html/_security.html#id-1.5.2.5.4

The listing is incorrectly numbered in the text following it:

the listig itself has `1, 2, 3, ...` numbers, but the descriptions refer to `6, 7, 8, ...`

The same issue appears in the following listings as well.

**Comment by jordimassaguerpla** [comment]
I just checked and this is fixed.
