### ISSUE TITLE
[doc] 4.1.1.3  Upgrades of the Kubernetes platform

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-caasp#442]
4.1.1.3  Upgrades of the Kubernetes platform

https://susedoc.github.io/doc-caasp/beta/caasp-architecture/single-html/#_upgrades_of_the_kubernetes_platform

There is no option "check".
Correct option is "plan".

skuba cluster upgrade --help
** This is a BETA release and NOT intended for production usage. **
Manages cluster-wide upgrade operations

Usage:
  skuba cluster upgrade [command]

Available Commands:
  plan        Plan cluster upgrade

**Comment by jordimassaguerpla** [comment]
@ereslibre Can you confirm it should be

skuba cluster upgrade plan

instead of

skuba cluster upgrade check

?

**Comment by ereslibre** [comment]
Yes, it's `skuba cluster upgrade plan`.
