### ISSUE TITLE
[doc] 3.2  Deployment on SUSE OpenStack Cloud

### ISSUE THREAD

**Issue by scmschmidt** [SUSE/doc-caasp#456]
3.2  Deployment on SUSE OpenStack Cloud

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_deployment_on_suse_openstack_cloud

>>>
Get the SLES15-SP1 image.

    Download the pre-built image of SUSE SLES15-SP1 for SUSE OpenStack Cloud from https://www.suse.com/products/server/jeos/.
<<<

When following the link above and continuing to the download section, only SUSE Linux Enterprise Server 12 SP1 JeOS images are vailable, but none for 15.

Not sure, if this is a bug in the documentation or of the download page.

**Comment by jordimassaguerpla** [comment]
I am asking Vincent Moutoussamy (JeOS PM)

**Comment by jordimassaguerpla** [comment]
Waiting on Vincent answer...

**Comment by jordimassaguerpla** [comment]
The download page is not updated. Vincent is taking care. Blocked for now.

**Comment by jordimassaguerpla** [comment]
From Vincent: better use https://download.suse.com/Download?buildid=OE-3enq3uys~

**Comment by scmschmidt** [comment]
https://download.suse.com/Download?buildid=OE-3enq3uys~ works.
I can forward the link to my SAP colleague for now. Thanks. The download page is going to be updated soon I guess?
