### ISSUE TITLE
Quick start guide has only openstack instructions

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#468]
https://susedoc.github.io/doc-caasp/beta/caasp-quickstart/html/index.html has only openstack instructions.

I would expect to have also vmware, bare metal and deploying on existing SLE installations (chapters already in the deployment guide).

Can we include those?

**Comment by nkoranova** [comment]
Hmm, I am not sure what the point of having the same information in two places should be. The Quickstart guide is already largely just a subset of the Deployment guide and in my opinion we could just get rid of the Quickstart guide without much loss. I would have to check what the content overlap is first of course.

**Comment by jordimassaguerpla** [comment]
The only diff between quick start guide and deployment guide would be:

4 Bootstrapping the Cluster

    4.1 Preparation

    4.2 Cluster Deployment

    4.3 Using kubectl

5 Network security

    5.1 Cilium

**Comment by jordimassaguerpla** [comment]
As far as I know, we never released quick start guide in the beta program

https://www.suse.com/betaprogram/caasp-beta/#themes

But we had a quick start guide for CaaSPv3.

**Comment by jordimassaguerpla** [comment]
However, I am not deciding this. I will check

**Comment by NunoFilipeSantos** [comment]
Dropping this in favour of the deployment guide.

**Comment by nkoranova** [comment]
Just a note: I had a look and most SUSE products don't have a Quick installation guide. CaaSP v3 did, but v2 didn't. There is no need to force it, if we don't have anything special to put in it.

**Comment by NunoFilipeSantos** [comment]
Exactly @nkoranova .
