### ISSUE TITLE
[doc] 3.1.3  Installation tools

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#476]
3.1.3  Installation tools

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_installation_tools

Could we get the list of SLES 15 SP1 channels required also added, here? Which SLES 15 SP1 channels are required to be available (base, product, server-applications,...?)

**Comment by Martin-Weiss** [comment]
I assume the list should look like this:

#  | Alias                                        | Name                                         | Enabled | GPG Check | Refresh
---+----------------------------------------------+----------------------------------------------+---------+-----------+--------
 1 | SLE-Module-Basesystem15-SP1-Pool             | SLE-Module-Basesystem15-SP1-Pool             | Yes     | (r ) Yes  | Yes
 2 | SLE-Module-Basesystem15-SP1-Updates          | SLE-Module-Basesystem15-SP1-Updates          | Yes     | (r ) Yes  | Yes
 3 | SLE-Module-Containers15-SP1-Pool             | SLE-Module-Containers15-SP1-Pool             | Yes     | (r ) Yes  | Yes
 4 | SLE-Module-Containers15-SP1-Updates          | SLE-Module-Containers15-SP1-Updates          | Yes     | (r ) Yes  | Yes
 5 | SLE-Module-Server-Applications15-SP1-Pool    | SLE-Module-Server-Applications15-SP1-Pool    | Yes     | (r ) Yes  | Yes
 6 | SLE-Module-Server-Applications15-SP1-Updates | SLE-Module-Server-Applications15-SP1-Updates | Yes     | (r ) Yes  | Yes
 7 | SLE-Product-SLES15-SP1-Pool                  | SLE-Product-SLES15-SP1-Pool                  | Yes     | (r ) Yes  | Yes
 8 | SLE-Product-SLES15-SP1-Updates               | SLE-Product-SLES15-SP1-Updates               | Yes     | (r ) Yes  | Yes
 9 | SLES15-SP1-15.1-0                            | SLES15-SP1-15.1-0                            | Yes     | (r ) Yes  | Yes
10 | SUSE-CAASP-4.0-Pool                          | SUSE-CAASP-4.0-Pool                          | Yes     | (r ) Yes  | Yes
11 | SUSE-CAASP-4.0-Updates                       | SUSE-CAASP-4.0-Updates                       | Yes     | (r ) Yes  | Yes

**Comment by nkoranova** [comment]
We already have this in a couple of places in the individual installation scenarios. For example: 
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_suse_linux_enterprise_server_installation 
As well as the autoyast.xml file: https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_deploying_with_local_repository_mirroring_tool_rmt_server 
We could potentially include the *Basesystem Module* and *Public Cloud Module*, but these might be VMware specific plus it would just be duplicate content. I would say it's better to keep it deployment specific rather than general and possibly not applicable to all.

**Comment by r0ckarong** [comment]
> We already have this in a couple of places in the individual installation scenarios. For example:
> https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_suse_linux_enterprise_server_installation
> As well as the autoyast.xml file: https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_deploying_with_local_repository_mirroring_tool_rmt_server
> We could potentially include the **Basesystem Module** and **Public Cloud Module**, but these might be VMware specific plus it would just be duplicate content. I would say it's better to keep it deployment specific rather than general and possibly not applicable to all.

I agree, the deployment specifics are covered by the instructions and a "catch all" list currently makes no sense for general documentation. If this is needed for some purpose in consulting this should be easy to compile from the separate guides. We do not have that many scenarios to cover at the moment.
