### ISSUE TITLE
[doc] 3.1.4.1.1  Configuring the Load Balancer

### ISSUE THREAD

**Issue by Hui-Zhi** [SUSE/doc-caasp#478]
3.1.4.1.1  Configuring the Load Balancer

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_configuring_the_load_balancer

Should we change "Register SLES:" to "Register Server Applications Module" and change "SUSEConnect -r $MY_REG_CODE" to "SUSEConnect --product sle-module-server-applications/15.1/x86_64"?

**Comment by r0ckarong** [comment]
@jordimassaguerpla Can you confirm that just registering is not enough? I thought server-applications will be added automatically.

**Comment by r0ckarong** [comment]
@jordimassaguerpla bump

**Comment by jordimassaguerpla** [comment]
Hi @r0ckarong ! Sorry for not answering you before. Actually you need to do both, register the SLES15SP1 system and then enabling the Server Application module.
