### ISSUE TITLE
[doc] 3.1.4.1.1  Configuring the Load Balancer

### ISSUE THREAD

**Issue by pablochacin** [SUSE/doc-caasp#479]
3.1.4.1.1  Configuring the Load Balancer

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_configuring_the_load_balancer

Rendering of notes in the nginx.conf file seems broken. Not all callouts are described. Notes appears in random order. 

![Screenshot from 2019-09-16 10-36-58](https://user-images.githubusercontent.com/720259/64944180-0f86b780-d86e-11e9-8733-f0373286ed92.png)

**Comment by r0ckarong** [comment]
This is a weird output quirk of our document processor. I've filed a bug for it. Nothing I can fix right now.

https://github.com/openSUSE/daps/issues/528
