### ISSUE TITLE
[doc] 2.1.3  Worker nodes

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#480]
2.1.3  Worker nodes

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_worker_nodes

--------------------
We should add something like the following:

The worker nodes should also have sufficient memory, CPU and disk space for the PODs/containers/applications that are planned to be hosted on these workers.

**Comment by Martin-Weiss** [comment]
(be more clear about what "workload" means)

**Comment by r0ckarong** [comment]
I can add this note but how would one determine which values to consider here?

**Comment by Martin-Weiss** [comment]
The values that need to be considered need to be delivered by the application vendor / developer / are hopefully specified on the PODs restrictions.

**Comment by r0ckarong** [comment]
OK then I will add this note that they have to have sufficient resources. That you need to plan to size your machines for the workload should be basic implicit knowledge about how to user Kubernetes. Do we really need to go into such detail? We're not a "beginner" product and I haven't heard that our documentation should be aimed at people who've never used Kubernetes.

**Comment by Martin-Weiss** [comment]
>Do we really need to go into such detail? We're not a "beginner" product and I haven't heard that our documentation should be aimed at people who've never used Kubernetes.

I am fine with setting such limitations in the scope of the documentation (not a beginner product, need pre-existing k8s knowlege) - but then they need to be clarified in the beginning to set proper expectations.

**Comment by r0ckarong** [comment]
Added worker node clarification with https://github.com/SUSE/doc-caasp/commit/9a2129f9f16e9011fd62d2d546f59013240b2f42

I will clarify the wording we can use to define the target audience more clearly.
