### ISSUE TITLE
[doc] 2.2.1  Ports

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#481]
2.2.1  Ports

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_ports

---
For centralized logging do we have to add the rsyslog details?

Should we mention ingress/prometheus/grafana, too? (based on the recommended way to deploy them)?

**Comment by r0ckarong** [comment]
@innobead @cclhsu Could you please contribute the ports required for centralized logging to this list: 

https://github.com/SUSE/doc-caasp/blob/master/adoc/deployment-sysreqs.adoc#ports

**Comment by r0ckarong** [comment]
> Should we mention ingress/prometheus/grafana, too? (based on the recommended way to deploy them)?

This is a question for @kkaempf @qnetter @ereslibre. Are we officially describing/supporting these things in some capacity and need to add this to the official list of ports?

**Comment by kkaempf** [comment]
prometheus/grafana - not yet. That will be added later.

**Comment by cclhsu** [comment]
For centralized logging, we only provide Rsyslog Log Agent configuration to deploy and collect different control plane and user space log.  We do not provide centralized logging server and user deploy their centralized log server solution inside or outside the k8s cluster with port of their choice.

**Comment by r0ckarong** [comment]
> For centralized logging, we only provide Rsyslog Log Agent configuration to deploy and collect different control plane and user space log. We do not provide centralized logging server and user deploy their centralized log server solution inside or outside the k8s cluster with port of their choice.

rsyslog agent works without configuring a port in the cluster network?

**Comment by Martin-Weiss** [comment]
I thought rsynclog is 514 - but not sure. 

Do we want to have a complete list for firewall admins?
In this case also DNS (UDP 53, NTP UDP 123 might be required)?
And HTTP/HTTPS for access to SMT/RMT?

**Comment by cclhsu** [comment]
For RSyslog Server, port 514 is usually the default listening port.  However, it is configurable by logging rules and listening to multiple ports. RSyslog log agent is configured with targeted logging server FQDN/IP and port and doesn't need to expose any port locally.
