### ISSUE TITLE
[doc] 2.2.2  IP Addresses

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#482]
2.2.2  IP Addresses

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_ip_addresses

----
we should clearly state IPv4 only, here.

(until we add IPv6 support..)

**Comment by r0ckarong** [comment]
Added with: https://github.com/SUSE/doc-caasp/commit/9a2129f9f16e9011fd62d2d546f59013240b2f42
