### ISSUE TITLE
[doc] 5.1.4  Prometheus

### ISSUE THREAD

**Issue by m0rbo** [SUSE/doc-caasp#484]
5.1.4  Prometheus

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book-caasp-admin/book-caasp-admin.html#prometheus

Due to upstream changes in the Prometheus Helm Chart, the current steps to deploy Prometheus no longer work and need a slight update.

I was told "This seems to be due to Update psps to support all pods (#15055) · helm/charts@af1e617"
Related: https://github.com/helm/charts/commit/af1e617edb58566f859c8c3aabb509c3edafc85b#r34888663

Per a conversation on the CaaSP mailing list one change could be to add "--set podSecurityPolicy.enabled=true" to the end of the "helm install" line for Prometheus, like this:
helm install --name prometheus stable/prometheus --namespace monitoring --values prometheus-config-values.yaml --set podSecurityPolicy.enabled=true

The better/recommended option would be to add a top level PSP as well:
But for the latest chart version is should add the new top level setting as well:

podSecurityPolicy:
  enabled: true

**Comment by r0ckarong** [comment]
Closed with: https://github.com/SUSE/doc-caasp/commit/5a66e65469834863b51e0b83b67b37832f1e8b49
