### ISSUE TITLE
[doc] 3.1.1  Basic SSH Key Configuration

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#485]
3.1.1  Basic SSH Key Configuration

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#ssh.configuration

------

It seems that the ssh-agent process keeps on running even if the ssh session is closed
(create new ssh session and check with "ps aux")

Maybe we should add a note that keeping ssh-agent running is a security risk and before closing the ssh session the ssh-agent needs to be killed?

**Comment by r0ckarong** [comment]
Added with: https://github.com/SUSE/doc-caasp/commit/e18e4b760fc62a0075fef521fed25b36934e7208
