### ISSUE TITLE
[doc] 3.1.4  Load Balancer

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#486]
3.1.4  Load Balancer

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_load_balancer

-------------------------
could we get an example added for using haproxy as load balancer, here?
(the free nginx must not be used in production - so we also have to give an example for production..)

**Comment by r0ckarong** [comment]
@Martin-Weiss Can you provide such an example? 

@ereslibre Who can provide me with an example for haproxy configuration? So far I was told to assume that people understand how to set up "their" load balancer solution.

**Comment by Martin-Weiss** [comment]
Here is what I have so far - secondary IP added on caasp4-01, 02..04 masters, 05..08 workers.
-> but this is just a simple example as a first start and I am not sure if this is correct what I did:

/etc/haproxy/haproxy.cfg

global
  log /dev/log daemon
  maxconn 32768
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  daemon
  stats socket /var/lib/haproxy/stats user haproxy group haproxy mode 0640 level operator
  tune.bufsize 32768
  tune.ssl.default-dh-param 2048
  ssl-default-bind-ciphers ALL:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH

defaults
  log     global
  mode    http
  option  log-health-checks
  option  log-separate-errors
  option  dontlog-normal
  option  dontlognull
  option  httplog
  option  socket-stats
  retries 3
  option  redispatch
  maxconn 10000
  timeout connect     5s
  timeout client     50s
  timeout server    450s

listen stats
  bind 0.0.0.0:80
  bind :::80 v6only
  stats enable
  stats uri     /
  stats refresh 5s
  rspadd Server:\ haproxy/1.6

frontend caasp4-api
  bind 10.1.1.150:6443
  mode tcp
  option tcplog
  default_backend caasp4-api

frontend caasp4-dex
  bind 10.1.1.150:32000
  mode tcp
  option tcplog
  default_backend caasp4-dex

frontend caasp4-gangway
  bind 10.1.1.150:32001
  mode tcp
  option tcplog
  default_backend caasp4-gangway

backend caasp4-api
  mode tcp
  option tcp-check
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server caasp4-02.suse caasp4-02.suse:6443 check
  server caasp4-03.suse caasp4-03.suse:6443 check
  server caasp4-04.suse caasp4-04.suse:6443 check

backend caasp4-dex
  mode tcp
  option tcp-check
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server caasp4-05.suse caasp4-05.suse:32000 check
  server caasp4-06.suse caasp4-06.suse:32000 check
  server caasp4-07.suse caasp4-07.suse:32000 check
  server caasp4-08.suse caasp4-08.suse:32000 check

backend caasp4-gangway
  mode tcp
  option tcp-check
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server caasp4-05.suse caasp4-05.suse:32001 check
  server caasp4-06.suse caasp4-06.suse:32001 check
  server caasp4-07.suse caasp4-07.suse:32001 check
  server caasp4-08.suse caasp4-08.suse:32001 check

**Comment by ereslibre** [comment]
> @ereslibre Who can provide me with an example for haproxy configuration? So far I was told to assume that people understand how to set up "their" load balancer solution.

I think we have been avoiding to document an explicit haproxy configuration, since this is another SUSE product and companies should have already knowledge on how to configure their load balancers.

cc/ @flavio @kkaempf

**Comment by Martin-Weiss** [comment]
For pysical load balancers I agree that we do not have to give examples - and in case the SLE-HA product has a good example that matches to what we need for CaaSP v4 we can also link that - but IMO we have to give customers a good and complete start that can be used in production also in case they do not have physical load balancers...

**Comment by ereslibre** [comment]
> but IMO we have to give customers a good and complete start that can be used in production also in case they do not have physical load balancers...

The problem that I see with this approach is that we are giving a wrong advice. Setting up one load balancer is only part of the HA story. If we say how to configure one load balancer and the customer goes this way just copying & pasting our configuration they still have a single point of failure (the LB). As said, we SUSE provides an HA product and I'm reluctant to provide this much detail here, mainly because ideally they should set up two load balancers (at least), with keepalived or some similar solution, otherwise the setup won't be real HA.

**Comment by Martin-Weiss** [comment]
In most environments we deploy on VMware where VMware does the "physical" fault tolerance. And here a single VM with haproxy would still be better than no load balancer at all.
At the moment we give an nginx example which  has the same problem but is not even giving prechecks.. so adding a second example would still help.. (even through the customer needs SLE-HA subscription for that)

**Comment by ereslibre** [comment]
I'd prefer @flavio, @kkaempf or @qnetter to provide feedback regarding this before we go ahead and document how to configure a single LB.

**Comment by kkaempf** [comment]
It's hard to give clear advise here at this point. I'd rather wait for actual SE/consultant feedback and a concrete use case.

Would SLE-HA be a concrete use case, @Martin-Weiss ?
Which other LB solutions are in use at customers ? Which is the most used one ?

**Comment by Martin-Weiss** [comment]
K8S requires a load balancer - without it does not make much sense.

Many customers have physical load balancer i.e. F5 (the most common one).
But - there are customers that do not / not yet have a Load Balancer and then the best offer we can make is to use SLE-HA with HAPROXY as we can fully support that. AFAIK we do not have any other "production ready load balancer in the SUSE eco system".

**Comment by ereslibre** [comment]
> K8S requires a load balancer - without it does not make much sense.

Not claiming otherwise. What I am claiming is whether we should include an explicit configuration for the LB on the documentation.

I'd propose for the time being to just document that they have to provide a set of load balancers properly configured (with active health checks) in order for their setup to be really HA (of course, at least 3 master nodes).

**Comment by Martin-Weiss** [comment]
The problem her is "properly configured (with active health checks)" -> what is this and how can we give the right advice on this? How can someone get a supported SUSE solution?

As said - either remove the nginx example, too or add the haproxy example (or point to the sle-ha documentation with giving the right advice for  "properly configured (with active health checks)".

-> Did I configure haproxy above correct for k8s/CaaSP or not? What could have been better and how does this compare to what QA is testing with?

**Comment by r0ckarong** [comment]
@Martin-Weiss @kkaempf So this is "blocked" for me now. Who can provide the things Martin is asking for? What is a "supported SUSE" load balancer solution and who can describe it in detail for documentation?

Can I simply add the haproxy example (also relates to #508) and where can I find this "right advice" about configuration?

**Comment by lcavajani** [comment]
@kkaempf @Martin-Weiss @r0ckarong   I've recently deployed SUSE HA for this purpose:
* 2 nodes with one VIP + HAproxy

I could write the procedure for the documentation.

**Comment by Martin-Weiss** [comment]
> 
> 
> @kkaempf @Martin-Weiss @r0ckarong I've recently deployed SUSE HA for this purpose:
> 
>     * 2 nodes with one VIP + HAproxy
> 
> 
> I could write the procedure for the documentation.

It would be great if we could have this! 

I believe in the CaaSP documentation we just need the specifics required for the haproxy.conf for CaaSP (API, DEX, Gateway, Nginx-Ingress, ssl?, active checks?). 

I believe the VIP and SLE-HA setup should be linked to the SLE-HA documentation for setting this up (in case it can be found there already) as long as this does not have CaaSP specific requirements.
