### ISSUE TITLE
[doc] 4.2.5  Cluster Bootstrap - adjustment of kubeadm-init.conf?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#488]
4.2.5  Cluster Bootstrap

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#cluster.bootstrap
------------------------------------

It seems I can not find any details about the required adjustments of kubeadm-init.conf
-> i.e. network settings for pods and services..

Customers have to adjust this:
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12

To ensure they do not have conflicting addresses.

And it is strange that the podSubnet is bigger than the serviceSubnet per default - I have never seen a situation where more services than pods were required.. Maybe the default is wrong?

**Comment by r0ckarong** [comment]
@kkaempf @ereslibre Who can help me with this?

**Comment by ereslibre** [comment]
I can help with this.
