### ISSUE TITLE
[doc] 3.1.4.1.1  Configuring the Load Balancer -> dex and gangway via master??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#490]
3.1.4.1.1  Configuring the Load Balancer

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_configuring_the_load_balancer

-----------------------------
I would expect PODs that are not running on the masters to be reached via nodeports on the workers.. and I see dex and gangway not starting on the masters ... we might need to change this in the nginx config example!

**Comment by innobead** [comment]
NodePort service should be allowed to access from any node in the cluster, the traffic would be routed to the node running the pod.

To configure the rule to access user facing services like dex n gangway will make sense to users without impacting by any workers change.

**Comment by Martin-Weiss** [comment]
> 
> 
> NodePort service should be allowed to access from any node in the cluster, the traffic would be routed to the node running the pod.
> 

True - but what is the sense of routing the traffic through the masters for PODs running only on the workers?

> To configure the rule to access user facing services like dex n gangway will make sense to users without impacting by any workers change.

A worker change (patch / reboot / load) will have impact on PODs running on the workers. And to solve this problem we setup a load balancer "in front" of that and ensure that all PODs have replica >1.

So I still believe it makes sense to change 32000/32001 to point to the workers and not the masters.
(or let gangway / dex run on the masters?)
AND - even more important - why is dex and gangway deployed with replica=1? Is this a bug?

**Comment by jenting** [comment]
What's the scenario dex and gangway need to deploy with replica > 1?

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss What's the scenario dex and gangway need to deploy with replica > 1?

Fault tolerance. No service in a cluster should be provided by a single pod instance only. In case there is a failure on the host hosting this pod it takes a "long" time until the pod is restarted on a second node - this can be several minutes and this failure scenario can be avoided by running every POD with replica >1 and running them on different workers per default.

(in CaaSP v3 we also ran dex with replica 3 AFAIK)

**Comment by jenting** [comment]
A [bug](https://bugzilla.suse.com/show_bug.cgi?id=1143232) already filed, thanks for reporting this.

**Comment by nkoranova** [comment]
@jenting it looks like this bug was fixed with https://github.com/SUSE/skuba/pull/717 
Is there anything to change in https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_configuring_the_load_balancer ?

**Comment by jenting** [comment]
> @jenting it looks like this bug was fixed with [SUSE/skuba#717](https://github.com/SUSE/skuba/pull/717)
> Is there anything to change in https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_configuring_the_load_balancer ?

The bug fixed dex/gangway with replicas=3. Not the one mentioned in the issue topic Load Balancer -> dex/gangway via the masters.

Service type NodePort is [accessible](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) on all master/worker port, so in my opinion, I vote to keep Load balancer -> dex/gangway via the masters.

**Comment by nkoranova** [comment]
If this remains the recommended configuration, it doesn't look like there is actually a bug in the docs. @Martin-Weiss @jenting can I close this or is there anything specific in need of fixing?

**Comment by jenting** [comment]
I'd prefer close it.

**Comment by Martin-Weiss** [comment]
> 
> 
> If this remains the recommended configuration, it doesn't look like there is actually a bug in the docs. @Martin-Weiss @jenting can I close this or is there anything specific in need of fixing?

Just to be sure to be sure - what is the exact result of the "recommended configuration"?
- passing all application network I/O to services through the masters or
- passing all the application network I/O to services through the workers?
