### ISSUE TITLE
[doc] 6.1.3  Installing Helm and Tiller

### ISSUE THREAD

**Issue by cduch** [SUSE/doc-caasp#495]
6.1.3  Installing Helm and Tiller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#helm_tiller_install

The example refers to a helm version variable which does not exists.

```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --tiller-image registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version} --service-account tiller
```

I assume that {helm_tiller_version} is a placeholder for "2.14.2"? That's the current helm client version in SLES 15 SP1.

**Comment by zoopster** [comment]
There is no need to use --tiller-image. The init *should* pull the latest available.
For RBAC installs we have to use --service-account when installing tiller.

**Comment by Martin-Weiss** [comment]
> 
> 
> There is no need to use --tiller-image. The init _should_ pull the latest available.
> For RBAC installs we have to use --service-account when installing tiller.

How do we ensure that the SUSE image for tiller is used in case we do not specify --tiller-image?

**Comment by r0ckarong** [comment]
Somehow the entity specifying the version got skipped during a merge. I've re-added this.

With regards to Martins' question @flavio @hwoarang any ideas?

**Comment by r0ckarong** [comment]
Main issue resolved with: https://github.com/SUSE/doc-caasp/commit/e9c64c1ceff73ee59ba9ae5ff166668333e8c87b
