### ISSUE TITLE
[doc] 3.5  Configuring an External LDAP Server - persistence of data not working

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#496]
3.5  Configuring an External LDAP Server

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_configuring_an_external_ldap_server

------
Either the documentation or the image does not work the way it is documented.
Please see also bug https://bugzilla.suse.com/show_bug.cgi?id=1151343

**Comment by r0ckarong** [comment]
@innobead Are you guys familiar with this and can have a look?

**Comment by cclhsu** [comment]
for bsc#1151340, bsc#1151343, bsc#1151414, create PR's in both [caasp-container-images](https://github.com/SUSE/caasp-container-images/pull/29) and [doc-caasp](https://github.com/SUSE/doc-caasp/pull/513).  Solution under reviews.
