### ISSUE TITLE
[doc] 3.5.3.1.1  Example 1: 389-ds Content LDIF - password management?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#497]
3.5.3.1.1  Example 1: 389-ds Content LDIF

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_example_1_389_ds_content_ldif

-----
I can not find the information on how to set / reset the password for the users created via ldif. (LDIF files do not have password??)

**Comment by r0ckarong** [comment]
@innobead

**Comment by r0ckarong** [comment]
If I understand it correctly you just "overwrite" the user with the same LDIF but with a new password.
Like descibed here in the general LDAP stuff: 

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_adding_a_new_user

@innobead Please confirm this is the correct procedure.

**Comment by Martin-Weiss** [comment]
No - this is not the same with 389-ds. There you have to have the password in clear text in the ldif and then overwrite or hash the password with an other tool (pwdhash).

I am also not sure what the process is for a user to change his own password, now - but we really need that for security reasons.

**Comment by r0ckarong** [comment]
@innobead So given this above comment would you please provide

a) Procedure to set/change password for 389-ds user
b) Procedure for user to self-change password

**Comment by cclhsu** [comment]
We have a section in "https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_modifying_a_user" to instruct user to change password or attribute.

**Comment by Martin-Weiss** [comment]
> 
> 
> We have a section in "https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_modifying_a_user" to instruct user to change password or attribute.

But this requires the "Bind DN and Bind password" of the LDAP admin user - so the user (not the admin) can not change the password himself with this procedure.

Also the hashing for the password to ensure it is not in clear text in the LDIF file is missing.

**Comment by r0ckarong** [comment]
@innobead Is there a password self service process?

Can you provide a method to hash the password for the LDIF please?

**Comment by cclhsu** [comment]
[slappasswd](https://linux.die.net/man/8/slappasswd)

 Use following to generate hash password
```
slappasswd -h {SSHA} -s password
```
and replace NEW_PASSWORD
```
userPassword: NEW_PASSWORD
```

**Comment by r0ckarong** [comment]
@cclhsu OK so this is the one part.

Is there a procedure that a regular user can perform to change their own password or can passwords only be changed by LDAP admin?

**Comment by innobead** [comment]
@cclhsu we already have a document for admin to change user password. Please try below similar command to verify user own password change to check if user is able to change password from outside. 

`ldappasswd -p 389 -h server.example.com -x -D "uid=user1,ou=People,dc=example,dc=com" -W -a old_password -s new_password`

**Comment by Martin-Weiss** [comment]
> 
> 
> [slappasswd](https://linux.die.net/man/8/slappasswd)
> 
> Use following to generate hash password
> 
> ```
> slappasswd -h {SSHA} -s password
> ```
> 
> and replace NEW_PASSWORD
> 
> ```
> userPassword: NEW_PASSWORD
> ```

Are you sure we have to / can use slappasswd for LDIFs against 389ds? 
I thought I had to use the tool "pwdhash" instead.

**Comment by cclhsu** [comment]
@Martin-Weiss 

There are a number of ways to generate ssha hash password.  `slappasswd` and `pwdhash` are two have them.  Simple bash command as following will also work.

```
PASSWORD=<YOUR_PASSWORD>
SALT="$(openssl rand 3)"
SHA1="$(printf "%s%s" "${PASSWORD}" "${SALT}" | openssl dgst -binary -sha1)"
printf "{SSHA}%s\n" "$(printf "%s%s" "${SHA1}" "${SALT}" | base64)"
```

**Comment by Martin-Weiss** [comment]
I can not remember the details anymore - but I had some problems with the LDIF files for users with passwords created for openLDAP using slappasswd when using them with 389ds. The users just could not login with the password against 389ds.

Then I had to realize that 389ds brings pwdhash instead of slappasswd. So I am not sure if all the documented slappasswd hashes and the way to specify them in LDIF work as passwords in 389ds and if there is full supported compatibility.

**Comment by cclhsu** [comment]
@Martin-Weiss I just done some testing with latest 389ds with `slappasswd`, `pwdhash`, and script previous provided. All SSHA hash from three sources worked.  The  `slappasswd` is from registry.suse.com/sles12/openldap:10.0.  My guess is that 389ds have fixed some issue since sinc then.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss I just done some testing with latest 389ds with `slappasswd`, `pwdhash`, and script previous provided. All SSHA hash from three sources worked. The `slappasswd` is from registry.suse.com/sles12/openldap:10.0. My guess is that 389ds have fixed some issue since sinc then.

Just to be sure to be sure - did you also test with {sha} and {crypt} (AFAIK crypt was used in V3 later on) - and did you try to login with the newly created users when using the old hashing with the new 389ds server? (maybe it was just my human error that it did not work for me ;-))

**Comment by cclhsu** [comment]
Yes, they work.  Not sure why we are using {CRYPT}.  Since from my understanding, `slappasswd`, `pwdhash`, and `openssl` using {CRYPT} only hash first 8 letters of a long password.

**Comment by Martin-Weiss** [comment]
Great - thanks!

Unfortunately I do not / can not find a reference anymore where and why {CRYPT} was used - but if it is true that just the first 8 letters would be hashed - we should even recommend not to use this at all.

Then we should just document that either slappasswd or pwdhash can be used for hashing with valid examples.
