### ISSUE TITLE
[doc] 3.5.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/dex.yaml</code>) -> example for root ca data should be added before ldap example

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#498]
3.5.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/dex.yaml</code>)

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_example_2_dex_ldap_tls_connector_configuration_addonsdexdex_yaml
--------------------------
For AD we have this hint at the end:
base64 encoded PEM file can be generated by running:

cat <root-ca-pem-file> | base64 | awk '{print}' ORS='' && echo

--> could we get this added before the examples for ldap or ad? (customers to not read the AD chapter in case they configure ldap via 389-ds.

**Comment by r0ckarong** [comment]
Moved as a TIP to the beginning of the examples.

https://github.com/SUSE/doc-caasp/commit/4ebdfd293104c6e28beebbe3e1f86cdd9846da34
