### ISSUE TITLE
[doc] 3.5.3  Examples of Usage -> kubectl apply / patch example should be added for dex adjustments

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#499]
3.5.3  Examples of Usage

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_examples_of_usage

-----
when following the docs here - customer modifies the dex.yaml and then reaches pod security without the info how to apply the config change and how to verify if it is working.

Could we get the info added how the change is applied and how customers can verify if the ldap connection works via dex and how they can see the right logs if it does not work?

**Comment by r0ckarong** [comment]
@drpaneas Can you give me some info how to do this or whom I can ask?

**Comment by drpaneas** [comment]
Ask Martin or Tomas from QA. I think they have a test case for Dex which we can use in the docs as an example of usage. If not, ping Nuno to create a card for it asap.

PS: I will come back at the office on Wednesday.

**Comment by innobead** [comment]
@jenting @cclhsu please also take a look. Thanks.

**Comment by cclhsu** [comment]
The document already have "https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_update_the_authentication_connector" and "https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_user_access" for apply and access through web/cli  Will just added a reference to the sections.

**Comment by r0ckarong** [comment]
Waiting for https://github.com/SUSE/doc-caasp/pull/513 to be resolved to close.
