### ISSUE TITLE
[doc] 3.5.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/dex.yaml</code>) - example should match to 389-ds ldap server configuration

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#500]
3.5.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/dex.yaml</code>)

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_example_2_dex_ldap_tls_connector_configuration_addonsdexdex_yaml

-------
In my example I had to use this:

    connectors:
    - type: ldap
      id: weiss-2-389-ds
      name: weiss-2-389-ds
      config:
        host: weiss-2.weiss.ddnss.de:389
        #insecureNoSSL: false
        #insecureSkipVerify: true
        startTLS: true
        rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdBakNDQStxZ0F3SUJBZ0lKQUtDUFd4TDlVOExkTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdWTVFzd0NRWUQKVlFRR0V3SkVSVEVkTUJzR0ExVUVDQXdVUW1Ga1pXNHRWOE9Ed3J4eWRIUmxiV0psY21jeEVqQVFCZ05WQkFjTQpDVk4wZFhSMFoyRnlkREVPTUF3R0ExVUVDZ3dGVjJWcGMzTXhIekFkQmdOVkJBTU1GbmRsYVhOekxUSXVkMlZwCmMzTXVaR1J1YzNNdVpHVXhJakFnQmdrcWhraUc5dzBCQ1FFV0UzZGxhWE56TG0xaGNuUnBia0IzWldJdVpHVXcKSGhjTk1Ua3dPVEU0TURnek5EUTNXaGNOTWprd056STNNRGd6TkRRM1dqQ0JsVEVMTUFrR0ExVUVCaE1DUkVVeApIVEFiQmdOVkJBZ01GRUpoWkdWdUxWZkRnOEs4Y25SMFpXMWlaWEpuTVJJd0VBWURWUVFIREFsVGRIVjBkR2RoCmNuUXhEakFNQmdOVkJBb01CVmRsYVhOek1SOHdIUVlEVlFRRERCWjNaV2x6Y3kweUxuZGxhWE56TG1Sa2JuTnoKTG1SbE1TSXdJQVlKS29aSWh2Y05BUWtCRmhOM1pXbHpjeTV0WVhKMGFXNUFkMlZpTG1SbE1JSUNJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXpvTElEWUlsMTgrZGZsSFlMQ0d1VWJlTVVWcm1aK3ZHClcwM1RjUDloTERkSk9pMWRqS1NuVjZBRjcvQ0IxQ0NYTjVtM2NsNXMxV3pkb2FhZGJpSEhBTXhhYmlQQ1lOK2wKQ2ZsaHp4bnZrcnRWN3R0dWVLVllsSUM5QWpqSVZ4ekNVOTZjS3MvWjgxaXRBQkV1MFcxKzhNSkd4S2dpQkJrVAo4Z2E3VFIzMERWcHNnc3hVWHQyZ0JjclB0RkdRV1dwVlVZMEt1UWJOdFZoZmhJY1d2T1VmOFZrakxxQUtKdWF0CllSRExTM1BOYkszMlB5c3IwcTc4Tm8zUVZ0QThuUHFGTVlVaGdTdzlxcGU0VE5nbm10Z1JCNVdCc01rVFlpTWEKbDhUY3dFZDZaQVFlYU5jdS9qVDJEZTFMZUFBMDJoTVM3S0ZSbTdyS3FzbnQrV0ZkUEFXNUd0YUxISW8wQkpzSgpidlFPTW02eU1Odk94aFI0cGpIS1Q4L0FmU2ljNFIxM2h0Sjg2bG9vY0dNZ0lpZko2QzhsZ3NXRmVPV2FKQnE5CjVyREMydFRtdjY2Q2xKVTRVWVlFMHlVVFpwbFdYUzlJVDZ6NDB1RUZaakxUZEZ4d3YvSTlya2ViVTczYXB0clMKWXRUM0U4cG5NQkRIWDVpYlZ0TERhZXUrYlRnRktldGhmVUMvcEhrVXhOa3NCOUIyQmYwTEZwZ3VXNi9lbE9jUgpKUnVyMHF0NEV5UWhuNVJRd2pNdDAwZHVWd1FRT2xpcWk1V0YxZTJkRHV2M2tOZG5LNUxTZnJDZGN3UUZ0eCtYCkd1UTJIYnl3ckdRcmV3NmdKVERxWmtlcExuaElyczZVNUZRL2grVkh5QjdtMHBoUzhwK0M2OTR0RW5rcWxPQnMKR1UzK2xCSHZ0eHNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRktUQS9rNnJZa0Z1enl4STJPU3UreVl3MlpWMQpNQjhHQTFVZEl3UVlNQmFBRktUQS9rNnJZa0Z1enl4STJPU3UreVl3MlpWMU1BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBRkdGSFZEL2NlWUltRllKdXdNeWYrcW5EOWpLd0t3VGc4cEYKOWI5c25Jd1ArOW5KcVRxUmdZUmNsTktPTnIvdUR4OTJXZjFhUTFCSEt1SUhLVDlUaFRodmptS0NUbkpYL3hLLwp4elFwdm9UWEtqNmgxRzRQejIzNUNydmoveWYxVzlzcDBidmVuTE00U0VaYUQrbTVNOGpZU00zNHdLRmRlM2hpCjMwRCtHVkxxblBpTDVTbG81SU4wTm4zMm9CanZ5TjJDSEZydHQwVWQyeEpDcDBKRFd4ZnBjWVl1UmQwVnEzY3YKMFNXNzdaTEdkR3o4eVFpV3VBQ0FkMjNWekJlR2J6VWZnU0ltZ3ZHMFdYSEovaXZRK2E5NWFzY2pPcytCRU1QQwp4THFpSHJYMGZjQVNoZXNvMVZGelZYTmVMdjBtajNmNnBmZlZUbGhtQVpjMDlDaEhUNUVCMjFJMzdmNmVqSWlYCkRUZFlQbk1ldWFDUzYrN3A3UFNlRG1ld25PWS9RR0ttbTFNajQvRDhOSXdkeG9nMVJpQ2RXbVJIRHVPT01hamoKT0NqV1U1eC85NTdPc29XV1JhQXVzS0YvZVFvTnFiYWNEWDhRdFl1cUxLRFRoS05iZmFXVVpkYmhtei9Zd0JIaApBOUwzdkdsTGdKVWpjYjhxVjIrSk1RcjRqQk9xOUNLOERneEhuY2RmSkozSm9COVJEK004WDM4N2x0UjJDYVI5CkwxRzRRU0lKRVhiVDRqUmZzenpRVFQwdlFWbVl2WXAydXV2dEZWYSt0Z2dRM2N4bS9TR1R1U0hIR2xkdFRwU3UKbnc1TEhORm0rWC83ZWh6a0FZRjhsNEdNdHFyZHZKRm5aYmpSSkE2bXJPV09LWUR1alpuU2tRYWtXV1gzT20zdQpCR0x6ZlhTRAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        bindDN: cn=binduser,dc=weiss,dc=ddnss,dc=de
        bindPW: suse1234
        usernamePrompt: Email Address
        userSearch:
          baseDN: ou=users,dc=weiss,dc=ddnss,dc=de
          filter: "(objectClass=person)"
          username: mail
          idAttr: DN
          emailAttr: mail
          nameAttr: cn
        groupSearch:
          baseDN: ou=groups,dc=weiss,dc=ddnss,dc=de
          filter: "(objectClass=groupOfUniqueNames)"
          userAttr: DN
          groupAttr: uniqueMember
          nameAttr: cn

--> especially the filters should match to the schema we used in 389-ds

**Comment by r0ckarong** [comment]
@innobead Could you please provide an updated example. Thanks.

**Comment by innobead** [comment]
@cclhsu please help on this. Thanks.

**Comment by cclhsu** [comment]
change have made in fork branch [389ds](https://github.com/cclhsu/doc-caasp/tree/Remove_INSTANCE_NAME).  Will check in once reviewed.
