### ISSUE TITLE
[doc] 3.6.1  Default Policies -> unclear default PSP role

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#501]
3.6.1  Default Policies

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_default_policies

-------
I believe this is not complete or clear enough:
"All authenticated users and service accounts have a RoleBinding to run pods using the privileged policy in the kube-system namespace."

I believe this should read:
"All authenticated system users (group system:authenticated) and service accounts in kube-system (system:serviceaccounts:kube-system)  have a RoleBinding (suse:caasp:psp:privileged) to run pods using the privileged policy in the kube-system namespace."

**Comment by r0ckarong** [comment]
Added with: https://github.com/SUSE/doc-caasp/commit/0200a374e681dbf20dc64748f059337d645ae777
