### ISSUE TITLE
[doc] 6.1.3  Installing Helm and Tiller - section should be moved to a place before helm is used the first time

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#503]
6.1.3  Installing Helm and Tiller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#helm_tiller_install

--------
in 6.1.3 we learn how to deploy helm and tiller - but it gets used in the monitoring section already - so could we move the helm and tiller "before this"?
Maybe it should be at a place where also kubectl installation on a client is mentioned?
Maybe a chapter on "how to prepare the admin machine to manage the CaaSP 4 and K8S cluster?" Maybe this is also required to be documented in the deployment guide instead of the admin guide?

**Comment by r0ckarong** [comment]
I had the same idea when working on this earlier. We currently don't have a "software management" chapter like we did with v3 so I'm still working out what the best place to move this to is. But I agree this should be moved out of the logging section.

**Comment by r0ckarong** [comment]
Fixed with: 88ff4229e0c21d0465b9206019df5be42eedf377
