### ISSUE TITLE
[doc] 6.1.3  Installing Helm and Tiller - one tiller per cluster and / or per namespace?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#504]
6.1.3  Installing Helm and Tiller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#helm_tiller_install
-----------------
Should we also document how a customer can use multiple tiller installations in a cluster i.e. one per namespace?
(required for shared clusters or clusters with staging areas)

**Comment by r0ckarong** [comment]
@ereslibre Is using multiple tiller installations recommended or desireable?

**Comment by ereslibre** [comment]
> @ereslibre Is using multiple tiller installations recommended or desireable?

I think this is part of the regular operation of the cluster, we could mention it, but it's really Kubernetes user knowledge; they can deploy whatever they want, including different tiller servers on different namespaces with different permissions.

**Comment by r0ckarong** [comment]
Not going to document this. As Rafa said, this is k8s user knowledge.
