### ISSUE TITLE
[doc] 6.1.3  Installing Helm and Tiller - deployment insecure??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#505]
6.1.3  Installing Helm and Tiller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#helm_tiller_install
-----
when I follow the docs and deploy tiller with the command specified I get this output:

------
Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
------

--> Maybe we should add a hint to the documentation that the customers should checkout the secure helm / tiller installation for production environments and follow the best practice documented there?

**Comment by r0ckarong** [comment]
@ereslibre Is there a reason we deploy in this unsecure mode by default or did we just never bother to follow those best practices?

**Comment by ereslibre** [comment]
> @ereslibre Is there a reason we deploy in this unsecure mode by default or did we just never bother to follow those best practices?

I'd say the latter. We have to follow up on this.

**Comment by r0ckarong** [comment]
I've assigned you the issue. Anything else I need to do? Duplicate this to avant-garde or are you taking care of that?

**Comment by MaximilianMeister** [comment]
Default helm 2 is known to be insecure. We can use https://github.com/helm/helm/blob/master/docs/securing_installation.md#best-practices-for-securing-helm-and-tiller as a general guideline
