### ISSUE TITLE
[doc] 5.1.3.3  Prometheus - need storage before deploying Prometheus

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#506]
5.1.3.3  Prometheus

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_prometheus

-----
we describe that we should use an existing storage class for prometheus deployment but we do not explain how to configure storage before..
-> could we get the storage provisioning added, first?

Here is what I have done:
helm fetch stable/nfs-client-provisioner
helm inspect values nfs-client-provisioner-1.2.6.tgz

adjust values.yaml:
```
caaspadm@caasp4-01:~/caasp4/nfs> diff values.yaml values.yaml.org
14,17c14,16
<   server: 10.1.1.1
<   path: /srv/backup/caasp4-cluster
<   mountOptions:
<     - soft
---
>   server:
>   path: /ifs/kubernetes
>   mountOptions:
24c23
<   provisionerName: nfs-client-provisioner
---
>   # provisionerName:
28c27
<   defaultClass: true
---
>   defaultClass: false
32c31
<   name: nfs-storage-class
---
>   name: nfs-client
51c50
<   enabled: true
---
>   enabled: false
62c61
<   name: nfs-client-provisioner-serviceaccount
---
>   name:

```
helm install -f values.yaml nfs-client-provisioner-1.2.6.tgz --namespace kube-system -n nfs-client-provisioner

--> now we have the storage class that we can use for prometheus persistent storage

**Comment by r0ckarong** [comment]
@lcavajani Can you verify this example and confirm that this is what I can add to make it work please?

**Comment by lcavajani** [comment]
I don't think defining a storage belongs to the Prometheus section. However we should have a chapter for this and point to it when we document how to deploy something required persistent storage.

@r0ckarong @Martin-Weiss I have no opinion with the `nfs-client-provisioner` but can we add this to the doc ?

**Comment by r0ckarong** [comment]
@kkaempf @qnetter  Is `nfs-client-provisioner` officially supported and should we describe it in the docs?

**Comment by kkaempf** [comment]
I would vote against it, since NFS is not a recommended storage option for CaaSP.

@Martin-Weiss usually has an opinion on topics like these :wink:

**Comment by Martin-Weiss** [comment]
At the moment we deliver upstream prometheus, grafana and nginx-ingress with our deployment/admin guides. So where exactly is the difference to the nfs-client-provisioner regarding the support questions?

Regarding the nfs-client-provisioner - this is what "everyone" is using per default already. (even internally - see caasp mailing list). And as long as we have no other storage solution we can use at customers I do not see much of an other chance. 
At our CaaSP customers we do not have SES - so what is the storage solution they can use instead of the nfs-client-provisioner?

**Comment by Hui-Zhi** [comment]
Maybe we can use ```stable/prometheus-operator``` instead of ```stable/prometheus```? 

Because ```prometheus-operator``` doesn't need a storage for it, it can make it much easier.

command:
```shell
helm install stable/prometheus-operator --name prometheus-operator --namespace monitoring
```
If customer want to view it remotely, just can change the network type from ```type: clusterIP``` to ```type: NodePort``` without load balance deployment by below command: 
```shell
kubectl edit svc prometheus-operator-alertmanager -n monitoring
kubectl edit svc prometheus-operator-grafana -n monitoring
kubectl edit svc prometheus-operator-prometheus -n monitoring
```
Of cause we need a professional deployment guide for production environment. But a simply way to  use it is also needed.
