### ISSUE TITLE
[doc] 5.1.3.1  NGINX Ingress Controller -  need to switch to SUSE helm chart and need to do this outside of Monitoring

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#507]
5.1.3.1  NGINX Ingress Controller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_nginx_ingress_controller
-----
similar to storage - this is a pre-requisite for many applications we deploy to k8s.
Due to that the nginx-ingress controller chapter should be outside and before monitoring.
In addition to that we have a "suse/nginx-ingress                      0.28.4" on https://kubernetes-charts.suse.com - so I assume we should use this supported one instead of the upstream one?

**Comment by r0ckarong** [comment]
@lcavajani Any reason we are using upstream nginx-ingress instead of the one on the suse repo? Support question maybe? I vaguely recall hearing something about nginx-ingress and a package support problem at the time but I don't know the details anymore.

Also we so far only describe nginx-ingress as part of the monitoring. I am not aware of any other of the "many applications we deploy" to use this. Maybe I'm ignorant here.

I'm happy to move this to a different place in the docs but I have to understand first how it's used.

**Comment by Martin-Weiss** [comment]
Just created https://bugzilla.suse.com/show_bug.cgi?id=1151493 - seems we have to use upstream because the SUSE provided version does not work on v4 / with PSPs (or I am doing something wrong..)

**Comment by lcavajani** [comment]
@r0ckarong when I first created this for v3, the SUSE nginx ingress controller was not ready/working yet. Now that we have a SUSE working version, I think this should be in it's own chapter now.

Need to check @Martin-Weiss bsc now ;)

**Comment by r0ckarong** [comment]
@lcavajani What is the correct command in helm to install the latest version of the chart? Or are we limited to installing this specific 0.28.4?

What I currently have is
```
helm install --name nginx-ingress suse/nginx-ingress 0.28.4 \
--namespace monitoring \
--values nginx-ingress-config-values.yaml
```

**Comment by jenting** [comment]
The reason why we did not use suse/nginx-ingress is that we do not have grafana helm chart in https://kubernetes-charts.suse.com. So, we wanna make the monitoring document used helm charts all aligned. 

Also, I tested `suse/nginx-ingress:0.28.4` have an issue on PSP, we need to change the example `nginx-ingress-config-values.yaml`.

And yes, we could move the NGINX ingress controller part to new chapter now. I saw @r0ckarong move this :+1:

**Comment by jenting** [comment]
@r0ckarong There is an [issue](https://bugzilla.suse.com/show_bug.cgi?id=1151493) with `suse/nginx-ingress:0.28.4` and I saw you changed the doc already. Recommends to reverts it until we found the solution for this.

**Comment by Martin-Weiss** [comment]
IMO Ingress is not a "monitoring" component anyway - this is like storage a component that is required globally and should be outside...

In case we use "upstream" - we might have to lock down on the helm chart versions and image versions that should be used with CaaSP v4 as it might happen that there are newer versions "upstream" that will not work with CaaSP v4 anymore..

**Comment by r0ckarong** [comment]
> @r0ckarong There is an [issue](https://bugzilla.suse.com/show_bug.cgi?id=1151493) with `suse/nginx-ingress:0.28.4` and I saw you changed the doc already. Recommends to reverts it until we found the solution for this.

So revert this to upstream again?

**Comment by r0ckarong** [comment]
> IMO Ingress is not a "monitoring" component anyway - this is like storage a component that is required globally and should be outside...
> 
> In case we use "upstream" - we might have to lock down on the helm chart versions and image versions that should be used with CaaSP v4 as it might happen that there are newer versions "upstream" that will not work with CaaSP v4 anymore..

@Martin-Weiss @lcavajani So which namespace should nginx-ingress be installed to if it's not `monitoring` any more?

**Comment by jenting** [comment]
> > @r0ckarong There is an [issue](https://bugzilla.suse.com/show_bug.cgi?id=1151493) with `suse/nginx-ingress:0.28.4` and I saw you changed the doc already. Recommends to reverts it until we found the solution for this.
> 
> So revert this to upstream again?

Yes, until the issue got fixed.

**Comment by r0ckarong** [comment]
> > > @r0ckarong There is an [issue](https://bugzilla.suse.com/show_bug.cgi?id=1151493) with `suse/nginx-ingress:0.28.4` and I saw you changed the doc already. Recommends to reverts it until we found the solution for this.
> > 
> > 
> > So revert this to upstream again?
> 
> Yes, until the issue got fixed.

https://github.com/SUSE/doc-caasp/commit/bbb749a39b7a22f4e603607c5531693bb6f87dc8

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss @lcavajani So which namespace should nginx-ingress be installed to if it's not `monitoring` any more?

I assume a namespace like "nginx-ingress" or "kube-system" might be the one...

**Comment by lcavajani** [comment]
I'd plead for `nginx-ingress` ;)

**Comment by jenting** [comment]
Missing a step to create namespace `nginx-ingress`

**Comment by r0ckarong** [comment]
> Missing a step to create namespace `nginx-ingress`

https://github.com/SUSE/doc-caasp/commit/f521d2c14d5f5a34588987d56214ed6230958c2a

**Comment by lcavajani** [comment]
Just a quick info, previously create the namespace is not required with Helm `v2` but it is with `v3`.
