### ISSUE TITLE
[doc] 5.1.3.1  NGINX Ingress Controller - node port and load balancer instead of external IP

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#508]
5.1.3.1  NGINX Ingress Controller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_nginx_ingress_controller
----------------------
I believe we should change this:
    externalIPs:
      - 10.86.4.158

--> instead of using external IPs we have to use nodeport and export 30080/30443 and then put a load balancer in front of it (similar to kube-api).

**Comment by r0ckarong** [comment]
@lcavajani Can you please provide the info on how to do this.

**Comment by Martin-Weiss** [comment]
Here is what I have done:

haproxy.conf:
Adjust
```
listen stats
  bind 0.0.0.0:81
  bind :::81 v6only
```

and add the following in /etc/haproxy/haproxy.cfg:

```
frontend nginx-ingress-http
  bind 10.1.1.150:80
  mode tcp
  option tcplog
  default_backend nginx-ingress-http

frontend nginx-ingress-https
  bind 10.1.1.150:443
  mode tcp
  option tcplog
  default_backend nginx-ingress-https

backend nginx-ingress-http
  mode tcp
  option tcp-check
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server caasp4-05.suse caasp4-05.suse:32080 check
  server caasp4-06.suse caasp4-06.suse:32080 check
  server caasp4-07.suse caasp4-07.suse:32080 check
  server caasp4-08.suse caasp4-08.suse:32080 check

backend nginx-ingress-https
  mode tcp
  option tcp-check
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server caasp4-05.suse caasp4-05.suse:32443 check
  server caasp4-06.suse caasp4-06.suse:32443 check
  server caasp4-07.suse caasp4-07.suse:32443 check
  server caasp4-08.suse caasp4-08.suse:32443 check

```

And this in values.yaml:

```
diff values.yaml values.yaml.org
259c259
<       #    type: LoadBalancer
---
>     type: LoadBalancer
261c261,266
<     type: NodePort
---
>     # type: NodePort
>     # nodePorts:
>     #   http: 32080
>     #   https: 32443
>     #   tcp:
>     #     8080: 32808
263,271c268,271
<       http: 32080
<       https: 32443
<       tcp:
<         8080: 32808
<         #    nodePorts:
<         #      http: ""
<         #      https: ""
<         #      tcp: {}
<         #      udp: {}
---
>       http: ""
>       https: ""
>       tcp: {}
>       udp: {}
314c314
<     enabled: true
---
>     enabled: false
317,319c317,319
<       annotations:
<       prometheus.io/scrape: "true"
<       prometheus.io/port: "10254"
---
>       annotations: {}
>       # prometheus.io/scrape: "true"
>       # prometheus.io/port: "10254"
392c392
<     name:
---
>     name:
480c480
<   enabled: true
---
>   enabled: false
```

Now I need to point my DNS entries to 10.1.1.150 (haproxy load balancer IP) and configure the ingress to forward <DNS>/<URL> to the right service/pod.

**Comment by lcavajani** [comment]
Both can be done, either use `NodePort` which will expose the port on ALL the nodes including the masters which is something I always prefer to avoid.

Using `NodePort` is like doing this on port `80` and `443` (it is still possible to change the ports)

Considering:

* caasp4-05.suse = 10.0.0.5
* caasp4-06.suse = 10.0.0.6
* caasp4-07.suse = 10.0.0.7
* caasp4-08.suse = 10.0.0.8

We can use:

```
externalIPs:
- 10.0.0.5
- 10.0.0.6
- 10.0.0.7
- 10.0.0.8
```

But again it's just a personal preference. Both will work well.

**Comment by Martin-Weiss** [comment]
Yes - sure - both will work but I would recommend using nodePort with high ports (pre-defined nodePort range) as using the host network might also cause conflicts one day.

**Comment by r0ckarong** [comment]
Can't move forward with this until I get some more info on #486 and which load balancers we are actually supposed to describe.

**Comment by jenting** [comment]
`NodePort` is a best practice in production due to node might auto-scaling and with load-balancer in front of it, growing/shrinking nodes can provide service to outside.
`externalIPs` is good for node auto-scaling not supported or enabled. 

I preferred to keep both but recommended the user to use `NodePort`.

**Comment by lcavajani** [comment]
I'm not pleading in favor of `externalIPs` but the same thing can be achieved in the situation you describe, there is just one more step and it's a matter of adding the new node IP in the service definition.

But in general if I was going to production I would not use `NodePort`.

**Comment by Martin-Weiss** [comment]
> But in general if I was going to production I would not use `NodePort`.

I am not sure if I understand the background of this message. Could you explain why?

**Comment by lcavajani** [comment]
This mostly for security reasons and to "reduce" the domain of failure:

* I'd just avoid as much as I can exposing services on the masters
* Even if these `NodePort` on the masters are not exposed to the public, `kube-proxy` is adding iptables rules, so less rules is always a way to avoid issues (there are enough).
* If we have 400 nodes, we probably don't need to expose the services to all these nodes.
* AFAIK there are no pools of ports reserved for `NodePort` so these ports are shared for every "type/service" provided by a NodePort. I just find it a bit messy as an administrator having a "production" port available in a range used for dev.

So nothing really tragic here, just a personal taste :wink:

**Comment by lcavajani** [comment]
For me this a bit the equivalent of `*:80` vs `192.168.1.1:80`, I always prefer to explicitly declare where I want to listen.

**Comment by Martin-Weiss** [comment]
The problem I see with :80 / :443 is that these are "low" ports and we might have potential conflicts depending on what is running in the cluster.. For node-ports the system takes care (if we do not hard-code them). Accessing them via masters is a different thing - I believe the load balancer need to be configured to go to a list of workers for nginx-ingress, anyway. Also maintaining a direct 1:N relationship between load balancer and worker config might be challenging.

To solve this issue I believe we should just document both options with the pro and contra and then the customer can decide what makes more sense for them.

**Comment by lcavajani** [comment]
@Martin-Weiss (I didn't mention it but I would also change the ports when using `externalIPs`. )

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss (I didn't mention it but I would also change the ports when using `externalIPs`. )

Great - and if we would use secondary IPs (VIP) for that we could even move them between workers and without the need to adjust them on the load balancer.. is there a way to manage secondary IPs via K8S?

**Comment by lcavajani** [comment]
@Martin-Weiss I did try and you can use VIP in `externalIPs` without issues since it's just adding NAT rules on all the nodes.

Let's say we use `10.0.1.1` in the `externalIPs`, the following rules will be added on all the nodes so wherever the VIP is attached, it should work (I just did the test by manually adding an ip with `ip addr add`)

```
    0     0 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            10.0.1.1          /* default/nginx: external IP */ tcp dpt:31222
    0     0 KUBE-SVC-4N57TFCL4MD7ZTDA  tcp  --  *      *       0.0.0.0/0            10.0.1.1         /* default/nginx: external IP */ tcp dpt:31222 PHYSDEV match ! --physdev-is-in ADDRTYPE match src-type !LOCAL
    0     0 KUBE-SVC-4N57TFCL4MD7ZTDA  tcp  --  *      *       0.0.0.0/0            10.0.1.1          /* default/nginx: external IP */ tcp dpt:31222 ADDRTYPE match dst-type LOCAL
```

So this also means one of my point about reducing the number of iptables rules on the master does not stand since the rules are added anyway.
