### ISSUE TITLE
[doc] 3.3  Installation Tools

### ISSUE THREAD

**Issue by lnyiri63** [SUSE/doc-caasp#511]
3.3  Installation Tools

https://documentation.suse.com/suse-caasp/4/single-html/caasp-quickstart/#_installation_tools

![image](https://user-images.githubusercontent.com/52237953/65394931-df6e7580-dd93-11e9-804a-53f32d69696a.png)
As anyone can see, there is no "Product".

**Comment by r0ckarong** [comment]
https://github.com/SUSE/doc-caasp/commit/e67d6eac2b1d665845968288c7d212b1577e254c
