### ISSUE TITLE
[doc] 3.3.3.1  Terraform

### ISSUE THREAD

**Issue by lnyiri63** [SUSE/doc-caasp#512]
3.3.3.1  Terraform

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_terraform

How is setup procedure communicating with SuSE OpenStack Cloud - isolated, firewalled environment, installed from RMT server (RMT server is communicating with internet by proxy, no other server is allowed to communicate with internet)? What data are transfered to SuSE OpenStack Cloud? What is purpose of those data in vSphere environment? Who has control over those data?

**Comment by r0ckarong** [comment]
This deployment has nothing to do with SOC. The deployment instructions for SOC and VMWare were originally created from the same template and we didn't replace one of the product entities that fills in product names. I've corrected the file.

https://github.com/SUSE/doc-caasp/commit/369308d96ad54f73fed343adb14a27296374adee
