### ISSUE TITLE
[doc] 4.3  Using kubectl

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#518]
4.3  Using kubectl

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_using_kubectl

The bold line below is incorrect:
Then you can perform all cluster operations as usual. For example, checking cluster status with either:
**skuba cluster status**
or
kubectl get nodes -o wide
or

Below command fails after linking admin.conf to kubeconfig, I believe it should be removed from documentation as skuba requires the admin.conf file, so we should enter to the skuba init directory to be able to use skuba commands.

caas4master:~/caas4-demo # ln -s /root/caas4-demo/admin.conf /root/.kube/config

caas4master:~ # skuba cluster status
E0923 16:27:50.067140   24421 status.go:34] unable to get cluster status: unable to get admin client set: could not load admin kubeconfig file: failed to load admin kubeconfig: open admin.conf: no such file or directory

**Comment by savasirez** [comment]
> That sounds like a bug to me not a documentation issue. I'll find out what needs to be done.

I think it should be a documentation issue, because below item, mentions about removing swap partition from the nodes during SLES installation:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_deployment_on_vmware
3.3.2.1
"Remove the swap partition."

**Comment by r0ckarong** [comment]
Just to verify, you are running "skuba cluster status" as root?

**Comment by savasirez** [comment]
> Just to verify, you are running "skuba cluster status" as root?

Yes, I also installed as root.

**Comment by r0ckarong** [comment]
Filed a bugzilla for this: https://bugzilla.suse.com/show_bug.cgi?id=1151797

**Comment by savasirez** [comment]
> Even if you link it to `~/.kube/config` we are never looking at that location right now, but on the current directory, that there's an `admin.conf`. This should work:
> 
> ```
> caas4master:~/caas4-demo # ln -s /root/caas4-demo/admin.conf /root/.kube/config
> caas4master:~/caas4-demo # skuba cluster status
> ```
> 
> (Running `skuba cluster status` from within the `~/caas4-demo` directory). In the future we might think about changing this behavior when we [get rid of the cluster definition folder](https://github.com/SUSE/avant-garde/issues/566).


Yes, thats why below line should be removed from there, because it may be understood that, after the link, it will work in any way... 

------------
To talk to your cluster, simply symlink the generated configuration file to ~/.kube/config.
ln -s ~/clusters/my-cluster/admin.conf ~/.kube/config
Then you can perform all cluster operations as usual. For example, checking cluster status with either:
**`skuba cluster status`**
or
kubectl get nodes -o wide
or
kubectl get pods --all-namespaces
