### ISSUE TITLE
[doc] 3.4.1  Environment Description

### ISSUE THREAD

**Issue by cseader** [SUSE/doc-caasp#519]
3.4.1  Environment Description

https://documentation.suse.com/suse-caasp/4/html/caasp-deployment/_deployment_instructions.html#_environment_description_2

It would seem the quickstart has information on the load balancer setup. Can we have a pointer to that documentation or include it here.

**Comment by Martin-Weiss** [comment]
Strange - I would have expected that the quickstart is just a reduced part of the deployment and architecture guide.. I would not have expected to find information in the quickstart that are not in the deployment guide..

**Comment by r0ckarong** [comment]
There is a prerequisites section that applies to all deployment types. This contains the load balancer instructions (3.1.4 Load Balancer). I assume you jumped straight to "bare metal" and 

https://documentation.suse.com/suse-caasp/4/html/caasp-deployment/_deployment_instructions.html#_load_balancer 

The bare metal instructions were missing the box telling you to complete the preparations. I've added that now.
