### ISSUE TITLE
[doc] 3.4.1  Environment Description

### ISSUE THREAD

**Issue by cseader** [SUSE/doc-caasp#520]
3.4.1  Environment Description

https://documentation.suse.com/suse-caasp/4/html/caasp-deployment/_deployment_instructions.html#_environment_description_2

The Autoyast preparation needs to be more obvious in the steps in order to deploy with a local RMT server. If you don't have this information in the docs then someone reading this for the first time is taken on a goose chase to find the right information to put in here. Lets not have everyone going on a wild goose chase to find the right information. This is a time suck of at least an hour to figure it out. Maybe more depending on your skill level. Here is the needed information as an example below.

  

  <suse_register>
    <do_registration config:type="boolean">true</do_registration>
    <install_updates config:type="boolean">true</install_updates>
    <email></email>
    <reg_server>https://rmt.seader.us</reg_server>
    <reg_server_cert>https://rmt.seader.us/rmt.crt</reg_server_cert>
    <reg_server_cert_fingerprint_type>SHA1</reg_server_cert_fingerprint_type>
    <reg_server_cert_fingerprint>7A:33:5A:6F:3F:24:67:AF:1A:D0:57:AF:2A:0C:92:39:46:07:2C:46</reg_server_cert_fingerprint>
    <slp_discovery config:type="boolean">false</slp_discovery>
    <addons config:type="list">
      <addon>
        <name>sle-module-containers</name>
        <version>15.1</version>
        <arch>x86_64</arch>
      </addon>
      <addon>
        <name>caasp</name>
        <version>4.0</version>
        <arch>x86_64</arch>
      </addon>
    </addons>
  </suse_register>

**Comment by Martin-Weiss** [comment]
Maybe we can even add a recommendation / hint to checkout our Consulting Installation Framework at https://github.com/Martin-Weiss/cif ;-?
