### ISSUE TITLE
[doc] 5.1.3.3  Prometheus - persistent storage - NFS needs to be v4

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#521]
5.1.3.3  Prometheus

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_prometheus

----------------
Just had to learn that the NFS server backing the persistent storage behind prometheus and grafana must be providing NFSv4 - otherwise the database locks created are not possible.

So could we add the information "NFSv4 required on the NFS server providing the export" to the section where we document how to deploy the nfs-client-provisioner?

**Comment by r0ckarong** [comment]
Waiting for a definitive answer that we are actually going to officially describe `nfs-client-provisioner`.
