### ISSUE TITLE
[doc]   

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#523]
It looks like some warnings etc are forgotten to be erased from here. I think they should be fixed since CaasP 4.0 is GA now.

https://documentation.suse.com/suse-caasp/4/single-html/caasp-quickstart/#id-1.2

**Comment by r0ckarong** [comment]
This was already fixed with https://github.com/SUSE/doc-caasp/commit/27adecf949017a8c428c657f0db2ceeaf10546c7

We just didn't publish the latest changes yet. I've triggered rebuild and publishing of the current commit state.
