### ISSUE TITLE
[doc] 6.1.3  Installing Helm and Tiller

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#524]
6.1.3  Installing Helm and Tiller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#helm_tiller_install

When I tried to install Tiller, it outputs the following, but it fails:

> caas4master:~ # helm init --tiller-image registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version} --service-account tiller
> Creating /root/.helm
> Creating /root/.helm/repository
> Creating /root/.helm/repository/cache
> Creating /root/.helm/repository/local
> Creating /root/.helm/plugins
> Creating /root/.helm/starters
> Creating /root/.helm/cache/archive
> Creating /root/.helm/repository/repositories.yaml
> Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
> Adding local repo with URL: http://127.0.0.1:8879/charts
> $HELM_HOME has been configured at /root/.helm.
> 
> Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
> 
> Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
> To prevent this, run `helm init` with the --tiller-tls-verify flag.
> For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
> 

When I checked the logs of the pod, the output is below:

> Events:
>   Type     Reason         Age                    From                 Message
>   ----     ------         ----                   ----                 -------
>   Normal   Scheduled      7m16s                  default-scheduler    Successfully assigned kube-system/tiller-deploy-78cb5db596-vl77d to caas4node3
>   Warning  InspectFailed  5m (x12 over 7m13s)    kubelet, caas4node3  Failed to apply default image tag "registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version}": couldn't parse image reference "registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version}": invalid reference format
>   Warning  Failed         119s (x26 over 7m13s)  kubelet, caas4node3  Error: InvalidImageName
> 

I think it's something to do with the **{helm_tiller_version}** part.

**Comment by savasirez** [comment]
OK, not sure if I got the correct way, but, here is what I did to workaround it:
1st a note: I tried couple of time as it was suggested inside the document, but it always failed with the same error (InvalidImageName).

But, when I delete the deployment and retry the "helm init" like below, it successfuly deployed the Tiller pod.

> caas4master:~ # kubectl get pods --all-namespaces
> NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE
> kube-system   cilium-989cz                            1/1     Running            4          26h
> kube-system   cilium-dzwfb                            1/1     Running            1          26h
> kube-system   cilium-k9qm9                            1/1     Running            1          26h
> kube-system   cilium-operator-7d6ddddbf5-5g2pr        1/1     Running            3          47h
> kube-system   cilium-wsbhg                            1/1     Running            1          26h
> kube-system   coredns-69c4947958-5mvqg                1/1     Running            1          26h
> kube-system   coredns-69c4947958-ckfvj                1/1     Running            1          26h
> kube-system   coredns-69c4947958-jnfmv                1/1     Running            1          26h
> kube-system   etcd-caas4master                        1/1     Running            3          47h
> kube-system   kube-apiserver-caas4master              1/1     Running            3          47h
> kube-system   kube-controller-manager-caas4master     1/1     Running            3          47h
> kube-system   kube-proxy-9v4j8                        1/1     Running            1          26h
> kube-system   kube-proxy-hvwp5                        1/1     Running            3          47h
> kube-system   kube-proxy-wnfj4                        1/1     Running            3          47h
> kube-system   kube-proxy-xzk47                        1/1     Running            3          30h
> kube-system   kube-scheduler-caas4master              1/1     Running            3          47h
> kube-system   kubernetes-dashboard-7d75c474bb-vlt5t   1/1     Running            0          23h
> kube-system   kured-hrqsg                             1/1     Running            1          26h
> kube-system   kured-kscsf                             1/1     Running            1          26h
> kube-system   kured-lfc4q                             1/1     Running            1          26h
> kube-system   kured-tsvkt                             1/1     Running            1          26h
> kube-system   oidc-dex-55fc689dc-h7vn9                1/1     Running            4          47h
> kube-system   oidc-gangway-7b7fbbdbdf-sq4tr           1/1     Running            3          47h
> kube-system   tiller-deploy-78cb5db596-v6kwg          0/1     InvalidImageName   0          4m3s
> 

> caas4master:~ # kubectl delete deployment tiller-deploy --namespace kube-system
> deployment.extensions "tiller-deploy" deleted


> caas4master:~ # kubectl get pods --all-namespaces
> NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
> kube-system   cilium-989cz                            1/1     Running   4          26h
> kube-system   cilium-dzwfb                            1/1     Running   1          26h
> kube-system   cilium-k9qm9                            1/1     Running   1          26h
> kube-system   cilium-operator-7d6ddddbf5-5g2pr        1/1     Running   3          47h
> kube-system   cilium-wsbhg                            1/1     Running   1          26h
> kube-system   coredns-69c4947958-5mvqg                1/1     Running   1          26h
> kube-system   coredns-69c4947958-ckfvj                1/1     Running   1          26h
> kube-system   coredns-69c4947958-jnfmv                1/1     Running   1          26h
> kube-system   etcd-caas4master                        1/1     Running   3          47h
> kube-system   kube-apiserver-caas4master              1/1     Running   3          47h
> kube-system   kube-controller-manager-caas4master     1/1     Running   3          47h
> kube-system   kube-proxy-9v4j8                        1/1     Running   1          26h
> kube-system   kube-proxy-hvwp5                        1/1     Running   3          47h
> kube-system   kube-proxy-wnfj4                        1/1     Running   3          47h
> kube-system   kube-proxy-xzk47                        1/1     Running   3          30h
> kube-system   kube-scheduler-caas4master              1/1     Running   3          47h
> kube-system   kubernetes-dashboard-7d75c474bb-vlt5t   1/1     Running   0          23h
> kube-system   kured-hrqsg                             1/1     Running   1          26h
> kube-system   kured-kscsf                             1/1     Running   1          26h
> kube-system   kured-lfc4q                             1/1     Running   1          26h
> kube-system   kured-tsvkt                             1/1     Running   1          26h
> kube-system   oidc-dex-55fc689dc-h7vn9                1/1     Running   4          47h
> kube-system   oidc-gangway-7b7fbbdbdf-sq4tr           1/1     Running   3          47h

> caas4master:~ # helm init --tiller-image registry.suse.com/caasp/v4/**helm-tiller:2.14.2** --service-account tiller
> $HELM_HOME has been configured at /root/.helm.
> Warning: Tiller is already installed in the cluster.
> (Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)

> caas4master:~ # kubectl get pods --all-namespaces
> NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
> kube-system   cilium-989cz                            1/1     Running   4          26h
> kube-system   cilium-dzwfb                            1/1     Running   1          26h
> kube-system   cilium-k9qm9                            1/1     Running   1          26h
> kube-system   cilium-operator-7d6ddddbf5-5g2pr        1/1     Running   3          47h
> kube-system   cilium-wsbhg                            1/1     Running   1          26h
> kube-system   coredns-69c4947958-5mvqg                1/1     Running   1          26h
> kube-system   coredns-69c4947958-ckfvj                1/1     Running   1          26h
> kube-system   coredns-69c4947958-jnfmv                1/1     Running   1          26h
> kube-system   etcd-caas4master                        1/1     Running   3          47h
> kube-system   kube-apiserver-caas4master              1/1     Running   3          47h
> kube-system   kube-controller-manager-caas4master     1/1     Running   3          47h
> kube-system   kube-proxy-9v4j8                        1/1     Running   1          26h
> kube-system   kube-proxy-hvwp5                        1/1     Running   3          47h
> kube-system   kube-proxy-wnfj4                        1/1     Running   3          47h
> kube-system   kube-proxy-xzk47                        1/1     Running   3          30h
> kube-system   kube-scheduler-caas4master              1/1     Running   3          47h
> kube-system   kubernetes-dashboard-7d75c474bb-vlt5t   1/1     Running   0          23h
> kube-system   kured-hrqsg                             1/1     Running   1          26h
> kube-system   kured-kscsf                             1/1     Running   1          26h
> kube-system   kured-lfc4q                             1/1     Running   1          26h
> kube-system   kured-tsvkt                             1/1     Running   1          26h
> kube-system   oidc-dex-55fc689dc-h7vn9                1/1     Running   4          47h
> kube-system   oidc-gangway-7b7fbbdbdf-sq4tr           1/1     Running   3          47h
> kube-system   tiller-deploy-55d564b8c9-lqtfj          1/1     Running   0          12s


Logs of tiller-deploy pod:

> Events:
>   Type    Reason     Age   From                 Message
>   ----    ------     ----  ----                 -------
>   Normal  Scheduled  21s   default-scheduler    Successfully assigned kube-system/tiller-deploy-55d564b8c9-lqtfj to caas4node3
>   Normal  Pulled     19s   kubelet, caas4node3  Container image "registry.suse.com/caasp/v4/helm-tiller:2.14.2" already present on machine
>   Normal  Created    18s   kubelet, caas4node3  Created container tiller
>   Normal  Started    18s   kubelet, caas4node3  Started container tiller

**Comment by r0ckarong** [comment]
As you stated correctly this happens because an entity that should have replaced the container image version was missing and thus not working.

This was fixed with commit https://github.com/SUSE/doc-caasp/commit/e9c64c1ceff73ee59ba9ae5ff166668333e8c87b

Updated instructions should be published soon.
