### ISSUE TITLE
[doc] 2.1.1  Management Workstation

### ISSUE THREAD

**Issue by gusraggio** [SUSE/doc-caasp#531]
2.1.1  Management Workstation

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_management_workstation

The skuba cli is available on the caasp module so you will need a SLES subscription and Caasp subscription.

**Comment by r0ckarong** [comment]
Will add a note clarifying that this is the case. We assumed this is a natural implication if you already need these subscriptions for the rest of the deployment processes.
