### ISSUE TITLE
[doc] 3.4.3.1  SUSE Linux Enterprise Server Installation

### ISSUE THREAD

**Issue by m0rbo** [SUSE/doc-caasp#542]
3.4.3.1  SUSE Linux Enterprise Server Installation

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_suse_linux_enterprise_server_installation_2

The link in the text "bootstrap guide" is invalid, it goes here:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/deployment-bootstrap.adoc

I assume it should go to:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#bootstrap

**Comment by r0ckarong** [comment]
Closed with https://github.com/SUSE/doc-caasp/commit/88de53a9eda21390758f100d5ca6b904b890c965
