### ISSUE TITLE
[doc] 4.3  Using kubectl

### ISSUE THREAD

**Issue by Hui-Zhi** [SUSE/doc-caasp#550]
4.3  Using kubectl

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_using_kubectl

Please change ```mkdir -p ~/.kube``` to ```mkdir ~/.kube```, because there's no sub directory need to be created.

**Comment by Martin-Weiss** [comment]
I thought the „-p“ prevents an error message in case the directory already exists. Did you get an error message with using „-p“?

**Comment by Hui-Zhi** [comment]
No I didn't get an error.

You made the point, it can prevent an error.
