### ISSUE TITLE
[doc] 4.7  NGINX Ingress Controller

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#558]
4.7  NGINX Ingress Controller

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#nginx-ingress

I see 2x issues.

In the example command:

```
helm install --name nginx-ingress stable/nginx-ingress \
--namespace nginx-ingress \
--values nginx-ingress-config-values.yaml
```
You are using the nginx-ingress namespace

When you check the pods, you are using the "monitoring" namespaces. The two should be consistent.
```
kubectl -n monitoring get pod
NAME                                             READY     STATUS    RESTARTS   AGE
nginx-ingress-controller-74cffccfc-p8xbb         1/1       Running   0          4s
nginx-ingress-default-backend-6b9b546dc8-mfkjk   1/1       Running   0          4s
```

The second issue is that you are using the _stable/nginx-ingress_ chart. However, there is a SUSE-created chart  _suse/nginx-ingress_.  Should that one be used instead?

**Comment by r0ckarong** [comment]
Will change [Line 58](https://github.com/SUSE/doc-caasp/blame/master/adoc/admin-security-nginx-ingress.adoc#L58) to reflect the correct namespace.

@lcavajani I'm sorry if this is a duplicate but wasn't there a reason we use the upstream chart than the suse published one? I can't find the discussion about this we had last time.

**Comment by lcavajani** [comment]
@r0ckarong it was just because the SUSE one was not ready at that time ;)
