### ISSUE TITLE
Incorrect attribute references in LDIF example docs - external ldap

### ISSUE THREAD

**Issue by cclhsu** [SUSE/doc-caasp#561]
After triage [bsc#1154404](https://bugzilla.suse.com/show_bug.cgi?id=1154404), following action is required for updating the document:

- Need to modify document to add "OU:Users"
- Need to modify document to update "posix group attributes"
- Need to modify document to add "modify operation type"

Assignee: @cclhsu

**Comment by innobead** [comment]
@r0ckarong @nkoranova please help assign to @cclhsu . Thanks.

**Comment by cclhsu** [comment]
[doc-caasp pr 562](https://github.com/SUSE/doc-caasp/pull/562)

**Comment by innobead** [comment]
@cclhsu please help close the bsc as well. Thanks.

**Comment by cclhsu** [comment]
[bac#1154404](https://bugzilla.suse.com/show_bug.cgi?id=1154404) is set as resolved.
