### ISSUE TITLE
needed steps for adding Kubernetes dashboard are missing in the CaasP v4 docs

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/doc-caasp#568]
Please, add the needed steps to add Kubernetes dashboard into the CaasP v4 docs.

Thx
Andi

**Comment by r0ckarong** [comment]
https://github.com/sigsteve/vagrant-caasp/blob/master/deploy/07.add_dashboard.sh

**Comment by Klaven** [comment]
@kkaempf and @qnetter some questions here.

Installing the dashboard is easy.

How it is configured is complicated and I think can generally depend on how you want to use it.

aka, do you give your dashboard the cluster admin role binding? If you do you would only want a few people to have access to it. Do you want users? and how do you want them to log in?

I guess the question that it comes down to is this, k8s dashboard has good documentation on their own that works, until we support this feature should we have any documentation? Or just point anyone that wants to use it to k8s dashboard documentation as they cover the different scenarios in detail.

An easy way we could document this is just do the very basic install and then give links to the rest, saying they should read the links to understand configuring the dashboard. 

The provided "steps taken" give the kube dashboard cluster admin. if they where to install this and plan for anyone to have access to the dashboard this is dangerous. But if you plan on only 2 or 3 people accessing it this can be ok (although I'm still not sure optimal.)

Thanks

**Comment by r0ckarong** [comment]
@ereslibre What is the intended use of k8s dashboard in a CaaSP environment? Can we give some scenario that we can base docs on?

**Comment by ereslibre** [comment]
> @ereslibre What is the intended use of k8s dashboard in a CaaSP environment? Can we give some scenario that we can base docs on?

The most common use case is to watch your resources inside the cluster and operate them with the UI if you want it that way. Note that this UI allows you to manage resources within the cluster, not the cluster itself: adding, removing or upgrading nodes is not in the scope of this UI.

It gives you eye candy to see all the current resources in the cluster, metadata, events...

**Comment by r0ckarong** [comment]
> The most common use case is to watch your resources inside the cluster and operate them with the UI if you want it that way. Note that this UI allows you to manage resources within the cluster, not the cluster itself: adding, removing or upgrading nodes is not in the scope of this UI.
> 
> It gives you eye candy to see all the current resources in the cluster, metadata, events...

That's not what I meant. With regards to Mareks comment above. What does the user/security setup look like for this common use case? Do we have recommendations? Best practices? Right now I don't have enough information to explain a proper setup of the dashboard in our cluster. You can do a basic "admin does all" installation but is that what we want to tell users?

**Comment by ereslibre** [comment]
Before we get down this path I'd like to know if we want to document how to run the dashboard as opposed for letting users do it their way.

@kkaempf opinion?

**Comment by kkaempf** [comment]
> Before we get down this path I'd like to know if we want to document how to run the dashboard as opposed for letting users do it their way.
> 
> @kkaempf opinion?

k8s dashboard is not on our short-term backlog. It will become relevant as a part of the `Stratos` release later next year.

**Comment by r0ckarong** [comment]
So I'm taking this will come up again during the Stratos release and for now we can't do anything. We can't really add the steps if they are not going to be tested and I can't get enough info to describe what to configure in CaaSP. Closing for now. We will add more info on this once it's in development.
