### ISSUE TITLE
[doc] 1.2  Administrator Accounts

### ISSUE THREAD

**Issue by phs4suse** [SUSE/doc-caasp#569]
1.2  Administrator Accounts

https://documentation.suse.com/suse-caasp/3/html/caasp-admin/cha-admin-security.html#sec-admin-security-admin

The link for Access Control is broken -" https://v1-11.docs.kubernetes.io/docs/reference/access-authn-authz/controlling-access/"

**Comment by r0ckarong** [comment]
This is a tough one to deal with. k8s breaks our legacy docs by only keeping the last 5 releases on their website and releasing often. I will replace this link with the github repo of the old version but expect some artifacts because of unrendered entity replacements.

**Comment by r0ckarong** [comment]
https://github.com/kubernetes/website/blob/release-1.11/content/en/docs/reference/access-authn-authz/controlling-access.md
