### ISSUE TITLE
[doc] 5.2.1  Initializing the Cluster

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/doc-caasp#571]
5.2.1  Initializing the Cluster

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_initializing_the_cluster
---
Can we add a picture from a scenario when you have to add load balancer IP to make it more clear for customers?

**Comment by r0ckarong** [comment]
With `picture` you mean a diagram of a deployment scenario that uses a load balancer?

**Comment by andreas-mach** [comment]
yes, sorry if I was not clear enough. 
Thanks
