### ISSUE TITLE
[doc] 3.1.2.2  Mirrored Resources - change "SUSESUSE" to "SUSE"

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#582]
3.1.2.2  Mirrored Resources

https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_mirrored_resources

---
SUSESUSE Linux Enterprise Server RPM packages

**Comment by r0ckarong** [comment]
This was already done in: https://github.com/SUSE/doc-caasp/commit/81ca9382a16442147c55d445cf9b7233c813b2f9

Will be pushed with the next buid.
