### ISSUE TITLE
[doc] 6.1.3.2  Prometheus

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/doc-caasp#584]
6.1.3.2  Prometheus

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_prometheus

---

After step: "3. Deploy the upstream helm chart and pass our configuration values file."
from my point of view one step is missing here to be able to access the Prometheus Expression browser/API, the missing step is to add the "EXTERNAL-IP" to the "nginx-ingress-controller" service:

example command if you use NGINX "NodePort" network configuration:
kubectl patch svc nginx-ingress-controller -p '{"spec":{"externalIPs":["10.162.193.27"]}}' -n nginx-ingress

Thanks

**Comment by Martin-Weiss** [comment]
Do you need the externalIPs when you use nodeport and a load balancer in front of it?

**Comment by r0ckarong** [comment]
@lcavajani Can you answer this?

**Comment by lcavajani** [comment]
@andreas-mach configuring the ingress controller is out of the scope of the Prometheus/Monitoring documentation, at the step you mention, regardless of your network config, you can access Prometheus at the following URL: https://prometheus.example.com

The doc at the beginning points to https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#nginx-ingress , here you can choose a network configuration.

**Comment by andreas-mach** [comment]
I've setup my env based on the "bare metal" instruction's from the official docs https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#deployment_bare_metal , agreed if you don't want to add this step to "Prometheus/Monitoring" section, but to get this working and make "Prometheus", "Prometheus-Alertmanager" and "Grafana" accessible from outside it was needed for me to add the "EXTERNAL-IP" to the "nginx-ingress-controller" pod, so this step is missing in my opinion and should be added, let me know if I miss something. Thx

**Comment by lcavajani** [comment]
Not sure about what you mean, configuring and external IP is described in the link I pointed you to in the last comment, https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#nginx-ingress

So here are the steps order:

1. Deploy on bare-metal
2. Deploy nginx-ingress controller configured to use external Ips
3. Deploy monitoring stack

**Comment by andreas-mach** [comment]
ok, thanks for clarification, I'll test to use external IPs as descried in the docs and provide feedback

**Comment by r0ckarong** [comment]
@andreas-mach Please open a new issue if you have feedback that requires changes. Thanks. Closing this.
