### ISSUE TITLE
Nutanix Acropolis not listed as supported platform for v4

### ISSUE THREAD

**Issue by karras** [SUSE/doc-caasp#590]
Nutanix is currently not listed as a supported platform in the v4 docs. Is it possible to add this hypervisor as a supported platform as well?

For v3 this was accepted and merged, see #217.

**Comment by r0ckarong** [comment]
@qnetter @kkaempf What's the status of Nutanix support for v4?

**Comment by kkaempf** [comment]
Not on my 3-6 month backlog.

**Comment by karras** [comment]
Maybe I should rephrase my question. Could we add a generic paragraph in the supported platforms section that any kind of deployment on standard SLE **VMs** (VMware, KVM, Hyper-V, Xen, etc.) is supported but a fully automated deployment is currently only possible for VMware + OpenStack?

It might be obvious for technicians who are already more familiar with the CaaSP internals but could shoo away people who just want to give it a try or a looking for a quick requirements overview.

**Comment by r0ckarong** [comment]
> Maybe I should rephrase my question. Could we add a generic paragraph in the supported platforms section that any kind of deployment on standard SLE **VMs** (VMware, KVM, Hyper-V, Xen, etc.) is supported but a fully automated deployment is currently only possible for VMware + OpenStack?

@kkaempf @qnetter

**Comment by kkaempf** [comment]
> Maybe I should rephrase my question. Could we add a generic paragraph in the supported platforms section that any kind of deployment on standard SLE **VMs** (VMware, KVM, Hyper-V, Xen, etc.) is supported but a fully automated deployment is currently only possible for VMware + OpenStack?

No, we don't. Every additional platform needs to be accessible to engineering and customer support in order to test and re-create bugs.

If you want more platforms for CaaSP, please open a Jira ticket and add a business case.

**Comment by lordfolken** [comment]
Just to clarify, we are not suse people, we are a suse partner. We already have a customer that is/was running CaaSP 3 on Nutanix. Given the profility of Nutanix in the local market, it would make sense to add the above statement.
SLE15 inkl. SAP HANA is already supported on nutanix hci, so caasp would just be an extension to that.
