### ISSUE TITLE
[doc] 5.2  Cluster Deployment -> make clear that "USERNAME" is a variable

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#592]
5.2  Cluster Deployment

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_cluster_deployment

-> echo "USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers should be changed to something like

-> echo "\<USERNAME\> ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

Or could we change USERNAME to a different font?

**Comment by r0ckarong** [comment]
What does the second command without "USERNAME" do?

I fail to see how a different font would impact on people that don't read the sentence preceding.

**Comment by Martin-Weiss** [comment]
> 
> 
> What does the second command without "USERNAME" do?
> 
> I fail to see how a different font would impact on people that don't read the sentence preceding.

Git suppressed my "<" and ">"

Basically the question is how we also can "optical" make clear that a example command needs to be adjusted.. maybe we can change "USERNAME" to _"\<USERNAME\>"_  (i.e. use italic font)?

**Comment by r0ckarong** [comment]
This should be possible with the "quotes" parameter. But it might break in some use cases with lots of formatting like characters in the code example.

https://asciidoctor.org/docs/user-manual/#applying-substitutions

@nkoranova This also relates to our open issue about the placeholders (#538).
