### ISSUE TITLE
[doc] 2.1.3  Worker nodes -> minumum CPU should be 2 VCPU

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#594]
2.1.3  Worker nodes

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_worker_nodes

----
We should never setup a system with just 1 VCPU - the minmum should always be 2.
(otherwise one crazy process can/will cause the whole server to get stuck)

**Comment by r0ckarong** [comment]
@ereslibre Should we communicate 2 vCPU as the new minimum? Are there test scenarios that customers can't use if we require more vCPU?

**Comment by ereslibre** [comment]
I think 2vCPU's is the minimum we should ask for. Anyone can fullfil this requirement IMO.
