### ISSUE TITLE
[doc] 4.5.2  Deploying a 389 Directory Server with an External Certificate -> SSL certificate replacement process does not work this way!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#597]
4.5.2  Deploying a 389 Directory Server with an External Certificate

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_deploying_a_389_directory_server_with_an_external_certificate
-----

THis will fail:
docker run --rm -it \
  -p 389:389 \
  -p 636:636 \
  -v <DATA_DIR>:/data \
  --entrypoint /bin/bash \
  --name 389-ds registry.suse.com/caasp/v4/389-ds:1.4.0

--> remove the "-p" and remove the "--name" as otherwise we have conflicts as the 389-ds already exists from the step before.

So this might work:
docker stop 389-ds

docker run --rm -it \
  -v <DATA_DIR>:/data \
  --entrypoint /bin/bash \
  registry.suse.com/caasp/v4/389-ds:1.4.0

**Comment by cclhsu** [comment]
Good catch. It is an issue been fix in #513 , at once point in the document we have "--rm" in all the docker run command.

**Comment by r0ckarong** [comment]
Since this will be fixed with the mentioned PR I'm closing the issue.

**Comment by Martin-Weiss** [comment]
> 
> 
> Since this will be fixed with the mentioned PR I'm closing the issue.

As long I as have the solution next Monday this is fine ;-).

**Comment by r0ckarong** [comment]
> > Since this will be fixed with the mentioned PR I'm closing the issue.
> 
> As long I as have the solution next Monday this is fine ;-).

Given it's Friday and that pull request is work in progress since september I wouldn't count on it.
