### ISSUE TITLE
[doc] 4.5.2  Deploying a 389 Directory Server with an External Certificate - image 1.4.0 does not have the required and fixed entrypoint script!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#598]
4.5.2  Deploying a 389 Directory Server with an External Certificate

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_deploying_a_389_directory_server_with_an_external_certificate

------------------------
It seems the whole thing does not work - did anyone else try to work with this??
(just delete and recreate the container with existing data...)

**Comment by cclhsu** [comment]
The command was tested a while back when we have the document https://confluence.suse.com/display/SUSECaaSPlatform4/Setup+389ds+TLS+for+RBAC-Authenticate+with+Self-signed+Certificate.  The docker with new fixed entrypoint is still verifying by QA and has not been released.

**Comment by Martin-Weiss** [comment]
Ok - then we need fixed documentation forthe old image until we have the new image with the fixed entry point released. 

Docs need to match what is released.

**Comment by r0ckarong** [comment]
@cclhsu @innobead Can we provide information on the old image or is the release of the new one imminent?

**Comment by Martin-Weiss** [comment]
> 
> 
> The command was tested a while back when we have the document https://confluence.suse.com/display/SUSECaaSPlatform4/Setup+389ds+TLS+for+RBAC-Authenticate+with+Self-signed+Certificate. The docker with new fixed entrypoint is still verifying by QA and has not been released.

@cclhsu  - where can I find the new entrypoint.sh that is fixed and the steps I need to use with this? Can I use the 1.4.0 image version and just the new entrypoint.sh or are there more changes required to get the SSL certificate replacement working? (I am onsite and have to get this working ASAP).

**Comment by cclhsu** [comment]
Hi! Martin.  The updated entrypoint can be find at https://github.com/SUSE/caasp-container-images/blob/master/caasp-389-ds-image/root/usr/local/bin/entrypoint.sh.  Cert Replacement code is as following:

```
        echo -e "\n>> Deleting ${SERVER_CERT} database in ${SLAP_DIR}...\n"
        # /usr/bin/certuti -d ${SLAP_DIR} -D -n "${SERVER_CERT}" # Remove certificate
        # /usr/bin/certuti -d ${SLAP_DIR} -F -n "${SERVER_CERT}" # Remove key
        echo > ${SLAP_DIR}/pwdfile.txt
        rm -f ${SLAP_DIR}/*.db
        /usr/bin/certutil -N --empty-password -d ${SLAP_DIR}

        echo -e "\n>> Importing the ${ROOT_CA} to ${SERVER_CERT} database in ${SLAP_DIR}...\n"
        /usr/bin/certutil -A -n ${SELF_SIGNED_CA} -t "CT,," -a -i ${SSCA_DIR}/${ROOT_CA}.crt -d ${SLAP_DIR} -f ${SLAP_DIR}/pwdfile.txt

        echo -e "\n>> Importing the certificate to ${SERVER_CERT} database in ${SLAP_DIR}...\n"
        if [ -e "${SLAP_DIR}/pwdfile-import.txt" ]; then
            /usr/bin/openssl pkcs12 -export -inkey ${SLAP_DIR}/${SERVER_CERT}-Key.pem -in ${SLAP_DIR}/${SERVER_CERT}.crt -out ${SLAP_DIR}/${SERVER_CERT}.p12 -nodes -name "${SERVER_CERT}" -passin file:${SLAP_DIR}/pwdfile-import.txt -passout file:${SLAP_DIR}/pwdfile.txt
            /usr/bin/pk12util -i ${SLAP_DIR}/${SERVER_CERT}.p12 -d ${SLAP_DIR} -w ${SLAP_DIR}/pwdfile.txt
        else
            /usr/bin/openssl pkcs12 -export -inkey ${SLAP_DIR}/${SERVER_CERT}-Key.pem -in ${SLAP_DIR}/${SERVER_CERT}.crt -out ${SLAP_DIR}/${SERVER_CERT}.p12 -nodes -name "${SERVER_CERT}" -passout file:${SLAP_DIR}/pwdfile.txt
            /usr/bin/pk12util -i ${SLAP_DIR}/${SERVER_CERT}.p12 -d ${SLAP_DIR}
        fi
        /bin/rm -f ${SLAP_DIR}/${SERVER_CERT}.p12

        echo "Certificate Database is now Up-to-date."
        /bin/cp /tmp/certsum_new /data/.certsum
```

The new image has added to 4.0.3 plan for release.  We are working on that this week.

**Comment by cclhsu** [comment]
@Martin-Weiss I have created a [doc-caasp PR603]((https://github.com/SUSE/doc-caasp/pull/603)) to update external certificate replacement using current image.  You can also refers to for steps.

**Comment by cclhsu** [comment]
New 389ds image is plan for 4.0.3 release and has been approved by QA [Release caasp-389ds-image #1007](https://github.com/SUSE/avant-garde/issues/1007).  New external certificate replacement method is described in  [389ds changes](https://github.com/SUSE/doc-caasp/pull/513)

**Comment by cclhsu** [comment]
New 389ds image is plan for 4.0.3 release and has been approved by QA [Release caasp-389ds-image #1007](https://github.com/SUSE/avant-garde/issues/1007).  New external certificate replacement method is described in  [389ds changes](https://github.com/SUSE/doc-caasp/pull/513)
