### ISSUE TITLE
[doc] 4.1.3  Installation Tools - proxy server whitelist missing

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#600]
4.1.3  Installation Tools

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_installation_tools

----------------
When deploying CaaSP behind a proxy server we need to have the whitelist of remote URLs that need to be allowed in the proxy.

Can we get the list of URLs / Servers required for SMT/RMT, for HELM and Images that a customer needs to allow in his proxy for CaaSP?

**Comment by r0ckarong** [comment]
Definitely registry.suse.com and scc.suse.com, need to look into the others.

**Comment by Martin-Weiss** [comment]
I assume also kubernetes-charts.suse.com

For SLES registration and updates I am not sure if scc.suse.com is enough or if we need more..

And I have heard that the registry is hosted somewhere where even other URLs might matter?

**Comment by r0ckarong** [comment]
> For SLES registration and updates I am not sure if scc.suse.com is enough or if we need more..
>
> And I have heard that the registry is hosted somewhere where even other URLs might matter?

@jordimassaguerpla @ereslibre Do you know anything more about which URLs we need for scc or registry?

**Comment by jordimassaguerpla** [comment]
@Martin-Weiss IIRC the extra urls are for the CDN. Could you please ask in scc-help channel in rocket chat? They should be able to give you more info.

**Comment by Martin-Weiss** [comment]
Got this so far: updates.suse.com and scc.suse.com

**Comment by r0ckarong** [comment]
- registry.suse.com
- scc.suse.com
- kubernetes-charts.suse.com
- updates.suse.com

**Comment by Martin-Weiss** [comment]
As long as we have upstream components in the documentation I believe we also have to add the sources for upstream helm-charts and images (grafana/nginx-ingress/prometheus/....)

**Comment by r0ckarong** [comment]
> As long as we have upstream components in the documentation I believe we also have to add the sources for upstream helm-charts and images (grafana/nginx-ingress/prometheus/....)

@lcavajani Can you tell me which upstream URLs we need for this?

**Comment by Martin-Weiss** [comment]
FYI - just had to realize that for registry.suse.com the whitelist "registry.suse.com" is NOT sufficient!

We get forbidden due to the URL "https://d20cu4swhmy76u.cloudfront.net/docker/registry/v2/blobs..."
--> why do we get such a DNS entry back when accessing registry.suse.com? Is this going to be fixed on the SUSE registry or do we have to whitelist also *.cloudfront.net ?

**Comment by lagartoflojo** [comment]
That's correct, we serve the images via CloudFront, which is AWS's CDN.
We'd need to see if we can use a SUSE domain, but if it's something you need in the short-term, I suggest opening the rules to `*.cloudfront.net` as well.

**Comment by lagartoflojo** [comment]
Added to our backlog: https://trello.com/c/E5W5V2Bl/862-rsc3-serve-files-using-a-suse-domain

**Comment by lcavajani** [comment]
> > As long as we have upstream components in the documentation I believe we also have to add the sources for upstream helm-charts and images (grafana/nginx-ingress/prometheus/....)
> 
> @lcavajani Can you tell me which upstream URLs we need for this?

So the charts come from the stable repository: `kubernetes-charts.storage.googleapis.com` and the images from `docker.io`.

AFAIK `k8s.gcr.io` is not needed, all the "caasp" images are on `registry.suse.com`

**Comment by Martin-Weiss** [comment]
I had to use k8s.gcr.io for upstream nginx-ingress (while the SUSE one does not support PSP) and for the upstream kubernetes-dashboard.

**Comment by lcavajani** [comment]
@r0ckarong  I thought we switched to the SUSE one in the documentation ?

@Martin-Weiss  IIRC we don't provide installation of the kubernetes-dashboard

**Comment by Martin-Weiss** [comment]
Ok - probably we might need two lists - one list with what SUSE already provides and one list what customers need in addition for the kubernetes-dashboard or istio or other important things that are not (yet) provided by SUSE?

**Comment by lcavajani** [comment]
There is also `quay.io` which is used to get the `kube-state-metrics` image

**Comment by r0ckarong** [comment]
> Ok - probably we might need two lists - one list with what SUSE already provides and one list what customers need in addition for the kubernetes-dashboard or istio or other important things that are not (yet) provided by SUSE?

@kkaempf Is this even something we can possibly provide? The most realistic procedure would be to somehow generate a list like that through some steps. Is this something that we need to describe?

**Comment by kkaempf** [comment]
> @Martin-Weiss IIRC we don't provide installation of the kubernetes-dashboard

Yet. It's on the backlog (as a supplement to Stratos).

**Comment by kkaempf** [comment]
> Ok - probably we might need two lists - one list with what SUSE already provides and one list what customers need in addition for the kubernetes-dashboard or istio or other important things that are not (yet) provided by SUSE?

We can only generate the first list - what SUSE provides and supports.
Any other 'workloads' are customer specific and a respective list would be endless.

**Comment by Martin-Weiss** [comment]
Agree - maybe we should create a wiki page or similar for the addons we have to use from upstream at the moment because our eco system is not yet complete..

**Comment by r0ckarong** [comment]
> Agree - maybe we should create a wiki page or similar for the addons we have to use from upstream at the moment because our eco system is not yet complete..

@ereslibre Can you do this or point me to whoever can create that list?

**Comment by ereslibre** [comment]
> @ereslibre Can you do this or point me to whoever can create that list?

Maybe bring this to #caasp-champions or get it as a new task on our sprint (or future sprints), so someone can take ownership of this. Thank you.

**Comment by dannysauer** [comment]
This should be fairly easy to do by simply setting up a proxy to log what is requested when the addons are installed, then collating the proxy log.  I'll see about scripting that, so maybe it'll be easier to generate / update the whitelist after that addon list is put together.
