### ISSUE TITLE
Check that our documentation includes NTP client deployment 

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#607]
Our documentation has to specify that the bootstrapper node needs to run NTP as well and be synced in terms of time. Bootstrapping skuba using a fully up-to-date system won't be possible unless we have this documented. 

https://bugzilla.suse.com/show_bug.cgi?id=1157063&GoAheadAndLogIn=1

Check that we have this info and include it if we don't.

**Comment by r0ckarong** [comment]
Does this mean, once merged, we have to rebuild the 4.0.2 docs release package?

**Comment by nkoranova** [comment]
@ereslibre how urgent is this? You said it' not critical, but we should have this info public ASAP, right? So rebuilding the 4.0.2 docs package might be a good idea.

**Comment by ereslibre** [comment]
> @ereslibre how urgent is this? You said it's not critical, but we should have this info public ASAP, right? So rebuilding the 4.0.2 docs package might be a good idea.

It's not crit-sit, if that makes sense, but if we have the chance to include this on the 4.0.2 docs I think that would be great. I am struggling with this because I could swear we documented this, but maybe I'm wrong and we never wrote it down on the *public* documentation.

**Comment by nkoranova** [comment]
>  I am struggling with this because I could swear we documented this

Yeah this also has me slightly worried, I really hope it didn't get lost somewhere in our publishing process :-/

**Comment by r0ckarong** [comment]
The terraform examples for both VMWare and SOC mention NTP servers to be used configured in the terraform examples:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_using_terraform
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_deploying_the_cluster_nodes

I would have assumed that the clients using these servers are deployed by terraform.

Bare metal needs to be installed via AutoYast and that mentions NTP client as well:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_autoyast_preparation

I currently do not see where this is missing. We do not explicitly state this as a requirement though as I believe we did in v3 docs.

**Comment by jordimassaguerpla** [comment]
Can we do this for 4.0.3? We already released 4.0.2. Unless you consider this a P1 issue. 4.0.3 is already being reviewed and we expect it to be released in the next 2 weeks.

**Comment by ereslibre** [comment]
> I currently do not see where this is missing. We do not explicitly state this as a requirement though as I believe we did in v3 docs.

Please, check https://bugzilla.suse.com/show_bug.cgi?id=1157063#c2. This is referring to the bootstrapper machine (the machine that is running `skuba`, that might be an external node). This machine needs to be in sync also with NTP, so when bootstrapping you won't get the error mentioned in bsc#1157063.

**Comment by r0ckarong** [comment]
Ah now I understand the problem. That's an easy fix.
