### ISSUE TITLE
[doc] 4.8.2  Configured admission controllers

### ISSUE THREAD

**Issue by thehejik** [SUSE/doc-caasp#610]
4.8.2  Configured admission controllers

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_configured_admission_controllers

At time of release 4.0.3 only enabled plugins are `NodeRestriction` and `PodSecurityPolicy`. We originally enabled all the mentioned plugins but in the end it was reverted by https://github.com/SUSE/skuba/pull/817

On the other hand the plugins will be re-enabled again in later (probably next) release due https://github.com/SUSE/skuba/pull/837

**Comment by r0ckarong** [comment]
So NOT part of 4.0.3 but will be re-enabled with 4.0.4?

**Comment by r0ckarong** [comment]
According to QA this was never shipped, Need to remove from master (revert PR) and then re-add once the feature works.
