### ISSUE TITLE
[doc] 4.9.6  Manual Certificate Renewal -> document what is required to use custom certificates for dex and gangway

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#619]
4.9.6  Manual Certificate Renewal

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal

----
Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?

Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.

But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.

**Comment by r0ckarong** [comment]
@ereslibre @kkaempf @aojea Is this supported and who can tell me how that can be done?

**Comment by ereslibre** [comment]
I think the Taiwan team can help here. cc/ @innobead

**Comment by kkaempf** [comment]
@innobead is on FTO - asking @jenting for help

**Comment by innobead** [comment]
> 4.9.6 Manual Certificate Renewal
> 
> https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal
> 
> Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?
> 
> Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.
> 

Yes, it’s possible to change the cert key pair for these services especially they are user facing but some limitation or fixes needed like there will be no auto cert renew taken care by skuba during `skuba node upgrade apply`, instead user needs to handle cert renew by themselves.

> But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.

Agree, no question for this. The current design is following kubeadm concept to support auto cert renew by skuba self-signed root CA for the created cluster until we have complete cert management story in following 4.x. 

But for this moment, we will take a look to see how to enhance the current doc.

cc @jenting @c3y1huang @cclhsu

**Comment by jenting** [comment]
> 4.9.6 Manual Certificate Renewal
> 
> https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal
> 
> Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?

As for automatically rotate dex+gangway server certificate, the dex+gangway server certificate is signed by Kubernete CA. So the current design is if the customer wants to use their CA (root CA or intermediate CA), replace it before first node bootstrap.

Now, skuba does not support replace customer CA after cluster deployment due to it will have downtime during replacing cilium certificate (this will be fixed after we shipping cilium `1.6.0` and we will re-evaluate replace customer CA after cluster deployment)

If the customer just STILLwant dex+gangway server certificate NOT signed by the Kubernetes CA, yes, we can add a document on it. But the customer has to take the server certificate rotation by themselves.

> 
> Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.

We had already update admin doc (#602) that skuba supports foreign root CA or intermediate CA (but the user has to provide certificate and key for skuba to signed the inter-cluster server and client cert/key by the customer providing root CA or intermediate CA.

> 
> But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.

Agree, also kube-apiserver are end-user visible, that's the reason why we choose dex+gangway signed by Kubernete CA (same CA as kube-apiserver)

**Comment by Martin-Weiss** [comment]
> 
> 
> > 4.9.6 Manual Certificate Renewal
> > https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal
> > Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?
> 
> As for automatically rotate dex+gangway server certificate, the dex+gangway server certificate is signed by Kubernete CA. So the current design is if the customer wants to use their CA (root CA or intermediate CA), replace it before first node bootstrap.

And exactly this is not possible as the customer can not share the private key of his CA.
Or do I miss something here? Do we expect customers to create an intermediate CA of their root CA and put the private key of this intermediate CA in clear text on the host running skuba?

> 
> Now, skuba does not support replace customer CA after cluster deployment due to it will have downtime during replacing cilium certificate (this will be fixed after we shipping cilium `1.6.0` and we will re-evaluate replace customer CA after cluster deployment)
> 
> If the customer just STILLwant dex+gangway server certificate NOT signed by the Kubernetes CA, yes, we can add a document on it. But the customer has to take the server certificate rotation by themselves. Is it okay? @Martin-Weiss
> 

Yes - I think so.


> > Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.
> 
> We had already update admin doc (#602) that skuba supports foreign root CA or intermediate CA (but the customer has to provide certificate and key for skuba to signed the inter-cluster server and client cert/key by the customer providing root CA or intermediate CA.
> 

Do we have any customer who provided the private key of their root CA for this usage?
I believe this would be a major security breach.


> > But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.
> 
> Agree, also kube-apiserver are end-user visible, that's the reason why we choose dex+gangway signed by Kubernete CA (same CA as kube-apiserver)

As far as I understood the kube-api certiciate is part of the ~/.kube/config file - so when using kubectl based tools or when this config file is used on API clients - they can trust the API certificate easily. 
But you are right - also for the kube-api it might be a valid request to replace this key and cert with a customer provided one.

Maybe I missed something - but
1. we can not expect that customers create intermiditate CAs and 
2. we can not expect that customers share the private key of their CA
so how exactly does the usage of "non kubernetes / skuba created CAs" work under these circumstances?

**Comment by jenting** [comment]
> > > 4.9.6 Manual Certificate Renewal
> > > https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal
> > > Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?
> > 
> > 
> > As for automatically rotate dex+gangway server certificate, the dex+gangway server certificate is signed by Kubernete CA. So the current design is if the customer wants to use their CA (root CA or intermediate CA), replace it before first node bootstrap.
> 
> And exactly this is not possible as the customer can not share the private key of his CA.
> Or do I miss something here? Do we expect customers to create an intermediate CA of their root CA and put the private key of this intermediate CA in clear text on the host running skuba?
> 

Well, it depends on how the customer manages their TLS certificate.
Of course, in general, do not share the private key of his CA, but we cannot enforce user NOT doing this.

> > Now, skuba does not support replace customer CA after cluster deployment due to it will have downtime during replacing cilium certificate (this will be fixed after we shipping cilium `1.6.0` and we will re-evaluate replace customer CA after cluster deployment)
> > If the customer just STILLwant dex+gangway server certificate NOT signed by the Kubernetes CA, yes, we can add a document on it. But the customer has to take the server certificate rotation by themselves. Is it okay? @Martin-Weiss
> 
> Yes - I think so.

Okay, I will update the doc about this.

> 
> > > Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.
> > 
> > 
> > We had already update admin doc (#602) that skuba supports foreign root CA or intermediate CA (but the customer has to provide certificate and key for skuba to signed the inter-cluster server and client cert/key by the customer providing root CA or intermediate CA.
> 
> Do we have any customer who provided the private key of their root CA for this usage?
> I believe this would be a major security breach.

To be honestly, I am not sure. You are the expert on this.

> 
> > > But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.
> > 
> > 
> > Agree, also kube-apiserver are end-user visible, that's the reason why we choose dex+gangway signed by Kubernete CA (same CA as kube-apiserver)
> 
> As far as I understood the kube-api certiciate is part of the ~/.kube/config file - so when using kubectl based tools or when this config file is used on API clients - they can trust the API certificate easily.
> But you are right - also for the kube-api it might be a valid request to replace this key and cert with a customer provided one.
> 
> Maybe I missed something - but
> 
> 1. we can not expect that customers create intermiditate CAs and

Yes.

> 2. we can not expect that customers share the private key of their CA

Yes.

>    so how exactly does the usage of "non kubernetes / skuba created CAs" work under these circumstances?

To be honestly, I don't know. Waiting for the customer's feedback.

**Comment by Martin-Weiss** [comment]
I do not have any customers that would allow creation of intermediate CAs for their CA for each K8S cluster they have to run. I also do not have customers that would allow the private key of their CA to be stored on the k8s or skuba hosts.
I have some customers that run their CA with automated certificate enrollment in Active Directory - I am not sure (never have done this myself) but I assume this might be related https://blogs.technet.microsoft.com/jeffbutte/2016/12/16/236/.

**Comment by innobead** [comment]
> I do not have any customers that would allow creation of intermediate CAs for their CA for each K8S cluster they have to run. I also do not have customers that would allow the private key of their CA to be stored on the k8s or skuba hosts.
> I have some customers that run their CA with automated certificate enrollment in Active Directory - I am not sure (never have done this myself) but I assume this might be related https://blogs.technet.microsoft.com/jeffbutte/2016/12/16/236/.

@Martin-Weiss Thanks for the feedback. The current document is based on best practices from kubernetes certs management [1] which includes most cert management cases maybe some customers are not willing to create intermediate CA or provide (single root CA) cert key pairs to delegate kubeadm do auto cert management, but imho we still need to provide the options to user.

But let’s focus on this issue, we really missed a document for external cert management which is we should fix later.

[1] https://kubernetes.io/docs/setup/best-practices/certificates/

**Comment by Martin-Weiss** [comment]
> 
> 
> > I do not have any customers that would allow creation of intermediate CAs for their CA for each K8S cluster they have to run. I also do not have customers that would allow the private key of their CA to be stored on the k8s or skuba hosts.
> > I have some customers that run their CA with automated certificate enrollment in Active Directory - I am not sure (never have done this myself) but I assume this might be related https://blogs.technet.microsoft.com/jeffbutte/2016/12/16/236/.
> 
> @Martin-Weiss Thanks for the feedback. The current document is based on best practices from kubernetes certs management [1] which includes most cert management cases maybe some customers are not willing to create intermediate CA or provide root/intermediate CA key to delegate kubeadm do auto cert management, but imho we still need to provide the feasible options to user.
> 

Yeah - again a "practice" that was called "best practice" without any explanations and background for decisions ;-). If you have one practice you can call that "best practice" ;-).

In general the implementation depends on current situation and requirements. Based on that a concept is required and needs to be implemented. The current "best practice" does not cover this and I can not find the assumed situation nor the assumed requirements that lead to this..

What I can say is that this does not fulfill the integration into existing environment requirements nor does it cover the operational / day 2 requirements (at least not for the customers I had to deal with so far ;-)).

> But let’s focus on this issue, we really missed a document for external cert management of dex/gangway which is we should fix later.

Yes - 100% agree. So IMO the next step should be to document how to replace and maintain the dex+gangway cecrtificates and ensure that skuba does handle the customer replaced ones properly.

- one approach would be to create customer dex/gangway secrets and replace the certificate names in the deployment yamls in the addons?
- an other approach would be to overwrite the secrets with customer ca-cert/key/cert content.

In both cases we should have a look at a way that skuba can take over the job for managing and replacing them in the future including warnings ahead of expiry date. 

We also should explain how to create the key and csr so that the certs can be signed by the customers CA.

> 
> [1] https://kubernetes.io/docs/setup/best-practices/certificates/
