### ISSUE TITLE
Add another output example of when cluster has only a new minor k8s level available

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#622]
Under 5.1.1  [Generating an Overview of Available Platform Updates](
https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_generating_an_overview_of_available_platform_updates) we'll add another output example to differentiate  "a new patch-level and minor" and another section "only a new minor" as discussed in: 
https://github.com/SUSE/doc-caasp/pull/606#discussion_r351854769

**Comment by nkoranova** [comment]
Having finally researched this, I found out that there have actually not been any existing k8s upgrades that this output would reflect. We've had 1.15.2 -> 1.16.x and now 1.16.x na 1.17.y ... so those are examples of minor version upgrades, but we haven't had any patch upgrades. It doesn't make much sense to have unrealistic output and it would IMHO make the upgrades section unnecessarily confusing and complex. Hence, I am closing this issue.

**Comment by evrardjp** [comment]
Agreed on this! Patch can be dealt with skuba-update, making it transparent to end users. If there is something special to deal with (maybe one day!), this can be done in release notes.
