### ISSUE TITLE
Master or worker nodes must not be cloned

### ISSUE THREAD

**Issue by kkaempf** [SUSE/doc-caasp#623]
From `caasp-internal@suse.de`

> Subject: Re: [caasp-internal] skuba-update annotates only the first node from the node list
> 
> > Are these machines cloned somehow?
> >
> > We are reading the `/etc/machine-id` with `skuba-update`. Then we list all
> > the nodes using the API, and retrieve the one matching this `/etc/machine-
> > id`. From your description I would say chances are that these machines have
> > the same `/etc/machine-id` contents. Is this the case?
> 
> Yes, this is. I cloned machines and just confirmed that all /etc/machine-id is the same.

The documentation should explicitly cover this case and ask users to watch for duplicate `/etc/machine-id` values.

**Comment by r0ckarong** [comment]
https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_setup_by_hand

**Comment by ereslibre** [comment]
Or if they are cloning the machines, before they create the template they need to make sure that their `/etc/machine-id` file is deleted.

**Comment by r0ckarong** [comment]
> Or if they are cloning the machines, before they create the template they need to make sure that their `/etc/machine-id` file is deleted.

So what is the scenario this would happen? Which platform? Is this all limited to VMWare?

**Comment by kkaempf** [comment]
> @ereslibre So what is the scenario this would happen? Which platform? Is this all limited to VMWare?

That can happen with every platform. VMware just makes it very easy to shoot yourself in the foot.
