### ISSUE TITLE
[doc] 1.1  Required Background

### ISSUE THREAD

**Issue by andavissuse** [SUSE/doc-caasp#627]
Intro paragraph wording is not correct for bullet points.

**Comment by r0ckarong** [comment]
Could you please provide more details?

- Which guide/on what URL did you encounter this?
- What is the actual nature of the bug that needs to be fixed?
- What is the expected change to the document that you wish to see?

**Comment by andavissuse** [comment]
Hi,

Wow, thank you for the very quick reply.  :)  This isn't a big issue at all, just something that I noticed.  The current text is:

********
To keep the scope of these guidelines manageable, certain technical assumptions have been made. These documents are not aimed at beginners in Kubernetes usage and require extensive knowledge of

	• You have some computer experience and are familiar with common technical terms.

	• You are familiar with the documentation for your system and the network on which it runs.
...
********

The structure would be better if the wording could be changed to:

********
To keep the scope of these guidelines manageable, certain technical assumptions have been made. These documents are not aimed at beginners in Kubernetes usage and require that

	• You have some computer experience and are familiar with common technical terms.

	• You are familiar with the documentation for your system and the network on which it runs.
...
********

Thanks and Regards,

Ann
