### ISSUE TITLE
How to update from "cilium without envoy" to "cilium with envoy"

### ISSUE THREAD

**Issue by kkaempf** [SUSE/doc-caasp#628]
> The migration from Cilium without Envoy to Cilium with Envoy will not require any manual steps.
> 
> Migration from Cilium 1.5 to Cilium 1.6 requires one operation - migrating data from etcd to CRD. This will be done automatically in Skuba. And that operation requires the following steps:
> 
>   *  Update Cilium ConfigMap to contain both new values from 1.6 and etcd config, which is going to be removed in next steps.
>   *  Deploying cilium-preflight DaemonSet which uses that ConfigMap to have an access to etcd.
>   *  Executing cilium preflight migrate-identity in one of cilium-preflight pods.
>   *  After success, remove cilium-preflight DaemonSet.
>   *  Update Cilium ConfigMap to not contain etcd config.
> 
> More details about that migration: https://docs.cilium.io/en/v1.6/install/upgrade/#migrating-from-kvstore-backed-identities-to-kubernetes-crd-backed-identities

Reference https://github.com/SUSE/avant-garde/issues/985

**Comment by kkaempf** [comment]
I used the `4.1.0` tag (lacking a better one). It's actually `4.1.x` since Envoy will not be part of the initial 4.1.0 release.

/cc @mrostecki

**Comment by r0ckarong** [comment]
Still not part of 4.1.1

**Comment by r0ckarong** [comment]
Relates to #587

**Comment by r0ckarong** [comment]
Still blocked by Cilium progress

**Comment by mrostecki** [comment]
Honestly, I don't think there is anything to document. Envoy is just shipped in the container image together with Cilium and Cilium is managing the Envoy process by itself. Feel free to re-open if anyone thinks, that there is something unclear in the current docs and an example of creating a l7 policy.
