### ISSUE TITLE
Advise to use SUSE helm chart instead of upstream

### ISSUE THREAD

**Issue by drpaneas** [SUSE/doc-caasp#630]
At https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#nginx-ingress

At the section 4.7.1.2

It says:

```
Deploy the upstream helm chart and pass along our configuration values file.
```

That's not true. We do not support the upstream ingress helm chart that is https://github.com/helm/charts/tree/master/stable/nginx-ingress

but we support our own https://github.com/SUSE/kubernetes-charts-suse-com

I would suggest to rephrase this sentence a bit different, pointing to SUSE helm charts. The term `upstream` is usually not what I would describe it.

**Comment by r0ckarong** [comment]
Good call. Will change this wording. The rest of the instructions have been changed to suse charts already.
