### ISSUE TITLE
[doc] 5.3  Using kubectl - add an aditional chapter to delete identical pods on same nodes

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#632]
5.3  Using kubectl

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_using_kubectl
------------------
We should add a chapter about "make coredns, dex and gangway" fault tolerant after the initial cluster creation with sufficient masters and workers.

After deployment we have 2 * coredns, 3 * dex and 3 * gangway running on master1. In case master1 failes - we will have a downtime of several minutes for DNS name resolution in the cluster and also for authentication because all replicas of these PODs are scheduled on the same node during initial deployment of master1.

So after we have three masters and the workers deployed / joined - it is required to kill/delete N-1 PODs on Master1 for coredns/dex/gangway to ensure they are distributed in a fault tolerant way among two/three nodes in the cluster.

**Comment by innobead** [comment]
This seems the extension of https://bugzilla.suse.com/show_bug.cgi?id=1157337.

The team is handling automatic distributed workload for dex/gangway in https://github.com/SUSE/skuba/pull/860 (in progress). The idea is during node management (join/remove), skuba will take care workload balanced distribution w/o human involved. 

Let's follow on the implementation first, then look back to see if this request is still needed. 

cc @c3y1huang

**Comment by Martin-Weiss** [comment]
The skuba solution will only address the problem during deployment (adding nodes).
Skuba (AFAIK) does not take care of re-distribution in case of downtime. So in case we have multiple instances of a replica set on the same worker or master after a worker or master failed - an administrator has to re-distribute by killing pods manually anyway and independent of skuba usage.
Or do I miss something?

**Comment by c3y1huang** [comment]
> The skuba solution will only address the problem during deployment (adding nodes).
> Skuba (AFAIK) does not take care of re-distribution in case of downtime. So in case we have multiple instances of a replica set on the same worker or master after a worker or master failed - an administrator has to re-distribute by killing pods manually anyway and independent of skuba usage.
> Or do I miss something?

By the fix we will also address to the case of downtime. The expectation is to not involve manually killing pods for redistribution.

**Comment by Martin-Weiss** [comment]
I am not sure about the fix - but does the planned fix include the case where multiple replicas already exist on one master? I.e. if we had to power of master1 for some hours and then adding the third master some hours later?

**Comment by c3y1huang** [comment]
> I am not sure about the fix - but does the planned fix include the case where multiple replicas already exist on one master? I.e. if we had to power of master1 for some hours and then adding the third master some hours later?

Of a complete cluster that started equal or exceed the replica number (master + worker). There will be no duplicated pods exist on same node. 

Let’s look at example when dex set to replica 3, and in a cluster with 1 master and 2 worker:
1. When bootstrap, 3 dex goes on master node - master(3).
2. Worker-1 joins, 1 of dex redistributed to new worker - master(2) + worker-1(1).
3. Worker-2 joins, dex redistributed again - master(1) + worker-1(1) + worker-2(1).
4. Worker-1 fails, dex on worker-1 goes into Pending state - master(1) + (Pending) + worker-2(1).
5. Worker-1 come back. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-2(1).
6. Worker-2 burned down. dex on worker-2 goes into Pending state - master(1) + worker-1(1) + (Pending).
7. Worker-3 joins. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-3(1).

**Comment by Martin-Weiss** [comment]
> 
> 
> > I am not sure about the fix - but does the planned fix include the case where multiple replicas already exist on one master? I.e. if we had to power of master1 for some hours and then adding the third master some hours later?
> 
> No problem. Let’s figure out If the fix off-drifted from what you are expecting, and how we can narrow the gaps.
> 
> To the first question regards to multiple replica exist on same host:
> Of a complete cluster that started equal or exceed the replica number (master + worker). There will be no duplicated pods exist on same node.
> 
> To the second question where nodes powers down:
> Let’s look at example when dex set to replica 3, and in a cluster with 1 master and 2 worker:
> 
>     1. When bootstrap, 3 dex goes on master node - master(3).
> 
>     2. Worker-1 joins, 1 of dex redistributed to new worker - master(2) + worker-1(1).
> 

Who is doing this re-distribution (killing the POD on master1)? Skuba?

>     3. Worker-2 joins, dex redistributed again - master(1) + worker-1(1) + worker-2(1).
> 

Again redistribution via skuba?

>     4. Worker-1 power down, dex on worker-1 goes into Pending state - master(1) + (Pending) + worker-2(1).
> 
>     5. Worker-1 power up. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-2(1).
> 
>     6. Worker-2 burns down. dex on worker-2 goes into Pending state - master(1) + worker-1(1) + (Pending).
> 
>     7. Worker-3 joins. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-3(1).

**Comment by c3y1huang** [comment]
> > > I am not sure about the fix - but does the planned fix include the case where multiple replicas already exist on one master? I.e. if we had to power of master1 for some hours and then adding the third master some hours later?
> > 
> > 
> > No problem. Let’s figure out If the fix off-drifted from what you are expecting, and how we can narrow the gaps.
> > To the first question regards to multiple replica exist on same host:
> > Of a complete cluster that started equal or exceed the replica number (master + worker). There will be no duplicated pods exist on same node.
> > To the second question where nodes powers down:
> > Let’s look at example when dex set to replica 3, and in a cluster with 1 master and 2 worker:
> > ```
> > 1. When bootstrap, 3 dex goes on master node - master(3).
> > 
> > 2. Worker-1 joins, 1 of dex redistributed to new worker - master(2) + worker-1(1).
> > ```
> 
> Who is doing this re-distribution (killing the POD on master1)? Skuba?
> 
> > ```
> > 3. Worker-2 joins, dex redistributed again - master(1) + worker-1(1) + worker-2(1).
> > ```
> 
> Again redistribution via skuba?
> 
> > ```
> > 4. Worker-1 power down, dex on worker-1 goes into Pending state - master(1) + (Pending) + worker-2(1).
> > 
> > 5. Worker-1 power up. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-2(1).
> > 
> > 6. Worker-2 burns down. dex on worker-2 goes into Pending state - master(1) + worker-1(1) + (Pending).
> > 
> > 7. Worker-3 joins. Scheduler found healthy node for dex - master(1) + worker-1(1) + worker-3(1).
> > ```

skuba will handle distribution during cluster deployment (step 1, 2, 3). Kubernetes will handle the distribution of after deployment (step 4, 5, 6, 7).

**Comment by Martin-Weiss** [comment]
Ok - so then I am more than happy!! Thanks :-).

**Comment by r0ckarong** [comment]
Do we still need a docs update for this after the fix is shipped? Otherwise I will close this once the code is merged.

**Comment by c3y1huang** [comment]
> Do we still need a docs update for this after the fix is shipped? Otherwise I will close this once the code is merged.

Let's keep this open for now. I am agreeing to @innobead said earlier:
> Let's follow on the implementation first, then look back to see if this request is still needed.

**Comment by Martin-Weiss** [comment]
Maybe we can at least add a note to the admin guide that for proper fault tolerance an operator should verify after deployment and also after node failures if "multiple PODs of a replica set that are expected to be running on different nodes for fault tolerance are running on the same nodes - how to detect and how to "fix"".

**Comment by r0ckarong** [comment]
> Maybe we can at least add a note to the admin guide that for proper fault tolerance an operator should verify after deployment and also after node failures if "multiple PODs of a replica set that are expected to be running on different nodes for fault tolerance are running on the same nodes - how to detect and how to "fix"".

This starts as a simple request and turns into "how to detect and how to fix", who can provide me with this how to?

**Comment by c3y1huang** [comment]
> > Maybe we can at least add a note to the admin guide that for proper fault tolerance an operator should verify after deployment and also after node failures if "multiple PODs of a replica set that are expected to be running on different nodes for fault tolerance are running on the same nodes - how to detect and how to "fix"".
> 
> This starts as a simple request and turns into "how to detect and how to fix", who can provide me with this how to?

I will provide with the fix for balancing replica.

**Comment by c3y1huang** [comment]
While fix is waiting for review. I've updated doc [here](https://github.com/SUSE/doc-caasp/pull/617).

**Comment by r0ckarong** [comment]
Closed with #617
