### ISSUE TITLE
[doc] 3.1.6.1  Mirror Configuration - tiller image missing

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#633]
3.1.6.1  Mirror Configuration

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-mirror

-----
In https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt it seems we are missing the helm-tiller image...

**Comment by r0ckarong** [comment]
@jordimassaguerpla Why would this image be missing?

**Comment by Martin-Weiss** [comment]
In case you try to do a helm init ..--tiller-image.. in an air-gapped environment. This will fail in case the image was not replicated to the on-premise registry beforehand...

**Comment by r0ckarong** [comment]
> In case you try to do a helm init ..--tiller-image.. in an air-gapped environment. This will fail in case the image was not replicated to the on-premise registry beforehand...

I understand but the question is why this is not listed in the images list, since it should.

**Comment by Martin-Weiss** [comment]
> 
> 
> > In case you try to do a helm init ..--tiller-image.. in an air-gapped environment. This will fail in case the image was not replicated to the on-premise registry beforehand...
> 
> I understand but the question is why this is not listed in the images list, since it should.

Ok - just guessing - probably because this is "helm" related and does not matter for "skuba images...".

**Comment by r0ckarong** [comment]
Maybe I misunderstand but the problem here is that the "chart" is there but can't find the "image" and that's because the image wasn't on the list you need to mirror.

**Comment by Martin-Weiss** [comment]
> 
> 
> Maybe I misunderstand but the problem here is that the "chart" is there but can't find the "image" and that's because the image wasn't on the list you need to mirror.

Yes - and the list of images that need to be mirrored are in https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt   but probably we might need an other helm-images.txt which also covers the list of images we need for all the helm chart related images..

**Comment by r0ckarong** [comment]
> > Maybe I misunderstand but the problem here is that the "chart" is there but can't find the "image" and that's because the image wasn't on the list you need to mirror.
> 
> Yes - and the list of images that need to be mirrored are in https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt but probably we might need an other helm-images.txt which also covers the list of images we need for all the helm chart related images..

Then I had a misunderstanding. I thought this list would also contain these. @jordimassaguerpla

**Comment by jordimassaguerpla** [comment]
Don't we have already an issue for the helm ones?

**Comment by jordimassaguerpla** [comment]
https://github.com/SUSE/doc-caasp/issues/621 Isn't this a duplicate?

**Comment by r0ckarong** [comment]
> #621 Isn't this a duplicate?

Not a duplicate because that one was about versioning in the file. We could use this one to track the other problem proven here and mentioned in the older one.

Is there any work underway to generate a list like that?

**Comment by Martin-Weiss** [comment]
Basically we need a list of images for skuba images (that is what we have already).
Then we need a list of images for the helm charts we have to deploy with the version dependencies on skuba/k8s.
And we need a place for images that are neither skuba nor helm-charts related - at the moment this is just the helm-tiller image AFAIK and this is why I created this issue #633, here.

**Comment by r0ckarong** [comment]
@jordimassaguerpla Any updates on this?

**Comment by jordimassaguerpla** [comment]
A proposal is being discussed here https://github.com/SUSE/avant-garde/issues/1197

**Comment by jodavis-suse** [comment]
It does seem like we should add some explanation to https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#airgap-container_registry-mirror to call out the Tiller image.  While tiller is in registry.suse.com, it isn't called out in the https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt as it is not used by skuba.  We don't need to create a helm-images.txt file to match that, because helm-mirror will generate the list of images for us and again, that list isn't going to include Tiller because Tiller isn't installed by a chart but from a `helm` command line call which passes the image name.

(It is really tempting to say 'just use Helm 3 in airgapped environments and skip Tiller', but as we don't have that packaged for CaaSP 4 that isn't helpful.)

**Comment by jodavis-suse** [comment]
I attempted to walk all the steps in a local setup, though had some trouble with the docker mirror setup (likely due to some of my shortcuts to avoid having to actually use two different SLES systems).  Result is in PR https://github.com/SUSE/doc-caasp/pull/957
