### ISSUE TITLE
[doc] 6.1.3.4  Grafana - how to serve from sub-path?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#636]
6.1.3.4  Grafana

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_grafana

-----------------------
In the majority of customer deployments customers do not want to create and manage one DNS entry (A record or CNAME) per application in the kubernetes cluster and they want to access the applications like prometheus, grafana, kubernetes-dashboard via different URLs for the same FQDN.

I.e. 
cluster-api.domain.com/prometheus -> prometheus
cluster-api.domain.com/grafana-> grafana
cluster-api.domain.com/dashboard -> dashboard

Could we document how to configure this properly with the applications we deliver and with usage of nginx-ingress?

**Comment by Martin-Weiss** [comment]
FYI  with grafana from upstream helm chart 3.8.14 - the usage of serve_from_sub_path in the grafana.ini was working fine but with grafana helm chart 4.0.0 from SUSE that has an older grafana version than the upstream 3.8.14 the parameter serve_from_sub_path does not exist so we need to find and document an alternative working way.

**Comment by r0ckarong** [comment]
cc/ @kkaempf @ereslibre @lcavajani 

Who can contribute how to do this?

**Comment by kkaempf** [comment]
@mjura has done some work in this area. Otherwise, please reach out via `caasp-champions` on RC.

**Comment by Martin-Weiss** [comment]
Maybe the rewrite function in nginx-ingress can help with this but I could not get it working properly (have a similar problem with the kubernetes-dashboard)

**Comment by ereslibre** [comment]
We might want to ship https://github.com/kubernetes-sigs/external-dns at some point, so this would cover this use case, not in the same approach but in a more generic one.

**Comment by Martin-Weiss** [comment]
> 
> 
> We might want to ship https://github.com/kubernetes-sigs/external-dns at some point, so this would cover this use case, not in the same approach but in a more generic one.

I like the idea of dynamic external DNS management  but for on-premise usecases this topic can be an other Pandoras box ;-). Dynamic DNS entries in existing large enterprise DNS infrastructures can be a big challenge especially from a security point of view.
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md does not seem to have more security than TSIG keys and with that I can only limit security on full DNS zones AFAIK - so we even might need additional DNS zones - one per cluster, one per namespace etc.. and DNS also has some TTL challenges.

So yes - external-dns is nice to have but the request is more about not to have so many DNS entries at all - that is why the sub-path is requested..

**Comment by suseclee** [comment]
My best bet is
Adding Haproxy configuration in LB like this
```
frontend dashboard
  bind *:443
  default_backend dashboard
frontend monitoring
  bind *:80
  default_backend grafana

backend dashboard
  server dashboard 10.17.3.0:30001 check

backend grafana
  server grafana 10.17.2.0:32486 check  no-check-ssl
```
In this case, you can access dashboard with https://LB-IP and grafana with http://LB-IP.
Dashboard's token can get from `kubectl describe secrets -n kube-system $(kubectl -n kube-system get secret | awk '/dashboard-admin/{print $1}')`. Username and password for grafana to login is configured in grafana yaml file.

Another option would be
Adding Haproxy configuration in LB like dex and gangway
```
listen dashboard
  bind    *:30001
  option httpchk GET /
  server clee-master-0.caasp.local 10.17.2.0:30001

listen grafana
  bind    *:32468
  server clee-master-0.caasp.local 10.17.2.0:32001 check no-check-ssl

listen prometheus
  bind    *:31395
  server clee-master-0.caasp.local 10.17.2.0:32001 check no-check-ssl
```
In this case, you can access dashboard with https://LB-IP:30001, grafana with http://LB-IP:32468, and prometheus with http://LB-IP:31395.

There are many different and complicated network configurations to solve this problem. But IMO, this is basic setup aligned with something we offered from Dex and Gangway. Let me know your thoughts.

**Comment by suseclee** [comment]
I also tried to use acl in frontend in haproxy configuration but it did not work because the url extentions does not stick to /grafana and /dashboard.

**Comment by Martin-Weiss** [comment]
I am not sure if you are mixing up things, here.
With the upstream grafana 6.3 or newer version it is simply possible to add the serve_from_sub_path see https://grafana.com/docs/grafana/latest/installation/configuration/ option.

So the idea is to have
Load Balancer with VIP forwarding 80/443 to NGINX-Ingress on nodePorts 32080/32443
Then add a DNS Entry i.e. "caasp-cluster" pointing to the VIP.
Now configure an ingress to forward "https://caasp-cluster:443/grafana" to the Grafana service running on cluster IP.
But for this configuration it is required to configure grafana.ini with the serve_from_sub_path option so that the URLs generated are correct.

With the grafana version we deliver (pre-6.3 version) this option for the grafana.ini is not available so we have to configure nginx-ingress different i.e. with the rewrite option.. But so far I could not find out what the right settings need to be - there are lots of variations when searching via google but so far non of them was working well with the SUSE nginx-ingress and the SUSE grafana.

**Comment by suseclee** [comment]
@Martin-Weiss Thanks for clarification. 
I will work on how ingress and ingress controller works with CaaSP. It seems promising that once ingress works well, NodePort for application will works with ingress in sub_path. 

I will work on 
1. I will check we have ingress controller instruction in CaaSP documentation.
    Found: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/index.html#nginx-ingress
2. If there is no doc, I need to check the instruction works well and is good enough for customer. 
2. I need to check if platforms (libvirt, openstack, vmware) might have different behaviors on ingress controller.
3. I will check with the applications such as k8s Dashboard and Grafana.

**Comment by suseclee** [comment]
I tried first with libvirt platform with metallb and ingress. I believe this is worst platform regarding network. The actual problem was not the ingress in this platform. The problem was the External-IP from loadbalancer does not accessible. Even though I can apply Ingress fanout in this platform, the external-ip would not be accessible. Tomorrow, I will use openstack with service-provider, this will be better because it should have loadbalancer as a default.

**Comment by Martin-Weiss** [comment]
As load balancer we have just used haproxy based on the deployment guide and added 80/443 forward to 32080/32443 to the worker nodes. We "exposed" nginx-ingress as nodePort.
So https://<load-balancer-vip> is automatically forwarded to nginx-ingress which forwards to prometheus/grafana etc.

**Comment by suseclee** [comment]
I found out how to configure nginx ingress controller in openstack cloud-provider. https://confluence.suse.com/pages/viewpage.action?pageId=416874852. But I am not sure about our supports for the ingress controller because we do not ship ingress controller. https://medium.com/flant-com/comparing-ingress-controllers-for-kubernetes-9b397483b46b is a good doc for ingress controller comparison. I will keep working on it. @Martin-Weiss yes, I think, for libvirt we can use NodePort instread of LoadBalancer. @kkaempf Is it ok to add ingress usages to doc even though we do not support the image or chart?

**Comment by Martin-Weiss** [comment]
@suseclee - did you see https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#nginx-ingress ? We deliver a SUSE supported ingress controller..

**Comment by suseclee** [comment]
I deployed ingressed kubernetes dashboard. It needs to be the entire domain name.
If I use `- path: /dashboard` in ingress yaml file, the dashboard would not show. The draft doc is https://confluence.suse.com/display/~clee/NGINX+Igress+with+KubernetesDashbaord+and+Prometheus. I will keep working on after heckweek.

**Comment by jordimassaguerpla** [comment]
I  see this is wip, removing it from 4.1.2

**Comment by suseclee** [comment]
I followed the Prometheus and Grafana deployment from the doc: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_monitoring. It already has ingress configuration with it. 
![Screenshot from 2020-02-18 19-45-08](https://user-images.githubusercontent.com/43277007/74806492-f65db900-529a-11ea-88f1-e18512cae143.png)
![Screenshot from 2020-02-18 19-47-18](https://user-images.githubusercontent.com/43277007/74806497-f9f14000-529a-11ea-8b8c-db75eccb0391.png)
![Screenshot from 2020-02-18 22-02-20](https://user-images.githubusercontent.com/43277007/74806505-fc539a00-529a-11ea-904c-55e58cd21bfa.png)

The accesses were (my ingress service types is NodePort with 32080 and 32443): 
https://prometheus.example.com:32443
https://prometheus-alertmanager.example.com:32443
https://grafana.example.com:32443

Users can follow the doc and Prometheus and Grafana were used ingress and  worked well.
I also documented how I followed caasp doc in https://confluence.suse.com/display/~clee/Prometheus+and+Grafana+on+CaaS

However, If there is some additional explanation, I can add more details in the monitoring Doc. However, I agree that the ingress doc did not have any example, so I will add k8s dashboard example in the ingress doc tomorrow.

**Comment by Martin-Weiss** [comment]
This is not "serve_as_subpath" - this is using ingress with different DNS entries. But for this you have to create multiple DNS entries (one for each application) which is not what customers want to have... they prefer applications to server with subpath (i.e. cluster-dns-name/grafana instead of grafana.cluster-dns-name)

This issue here is the request to document also how to "serve via sub-path".. (the other one is already part of the CaaSP documentation)

**Comment by suseclee** [comment]
This was because doc introduces sub-domain way of ingress for Prometheus and Grafana. If I add Prometheus and Grafana with subpath, where should this doc needs to go in (ingress or monitoring)?

**Comment by suseclee** [comment]
I created sub_path ingress for Prometheus and Grafana. Everything works ok except Prometheus root directory. This is because Prometheus changed the root path to "graph" after users logged in. I am working on it in my confluence page: https://confluence.suse.com/display/~clee/Prometheus+and+Grafana+on+CaaS+with+separate+ingresses

![Screenshot from 2020-02-19 11-33-28](https://user-images.githubusercontent.com/43277007/74869240-77a16400-530c-11ea-849c-f271ac81d7fe.png)
![Screenshot from 2020-02-19 11-33-12](https://user-images.githubusercontent.com/43277007/74869258-7cfeae80-530c-11ea-83c0-e811252b3018.png)
![Screenshot from 2020-02-19 11-32-56](https://user-images.githubusercontent.com/43277007/74869267-7ff99f00-530c-11ea-9de4-7843cb3e7a48.png)

**Comment by suseclee** [comment]
Now the Prometheus subpath works as well. I changed the above confluence page. 
![Screenshot from 2020-02-19 16-50-48](https://user-images.githubusercontent.com/43277007/74890629-6fabe900-5339-11ea-91c6-c50e65b17ceb.png)
  
Now I will add it to doc-caasp.

**Comment by Martin-Weiss** [comment]
> 
> 
> This was because doc introduces sub-domain way of ingress for Prometheus and Grafana. If I add Prometheus and Grafana with subpath, where should this doc needs to go in (ingress or monitoring)?

Great!! I believe we need to do several things:
1. explain for ingress what ingress is and does and what the differences are between different DNS names vs. different sub-paths
2. in grafana and prometheus deployments we should give two examples
   a) with DNS based ingress routing
   b) with sub path ingress routing

Thanks!!

**Comment by suseclee** [comment]
I am not sure if ingress controller is located in 4.Security: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_security. Should I move it somewhere?

**Comment by suseclee** [comment]
The PR is ready for review: https://github.com/SUSE/doc-caasp/pull/713
