### ISSUE TITLE
[doc] 5.1.1.2  Generating an Overview of Available Addon Updates - looks a bit different

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#643]
5.1.1.2  Generating an Overview of Available Addon Updates

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_generating_an_overview_of_available_addon_updates

......

Why does this look different for me?

```
caaspadm@caasp4-01:~/caasp4-cluster> skuba addon upgrade plan
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.15.2

Addon upgrades for 1.15.2:
  - cilium: 1.5.3 (new addon)
  - dex: 2.16.0 (new addon)
  - gangway: 3.1.0-rev4 (new addon)
  - kured: 1.2.0 (new addon)
  - psp:  (new addon)
caaspadm@caasp4-01:~/caasp4-cluster> skuba addon upgrade plan
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.15.2

Addon upgrades for 1.15.2:
  - cilium: 1.5.3 (new addon)
  - dex: 2.16.0 (new addon)
  - gangway: 3.1.0-rev4 (new addon)
  - kured: 1.2.0 (new addon)
  - psp:  (new addon)
caaspadm@caasp4-01:~/caasp4-cluster> skuba addon upgrade apply
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.15.2

[apply] Successfully upgraded addons
caaspadm@caasp4-01:~/caasp4-cluster> skuba addon upgrade plan
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.15.2

Congratulations! Addons for 1.15.2 are already at the latest version available

```

for the updated addons I just see / saw "new addon" but not the previous version...

**Comment by r0ckarong** [comment]
@ereslibre @kkaempf Who can explain this change?

**Comment by r0ckarong** [comment]
Relates to: #626

**Comment by kkaempf** [comment]
> @ereslibre @kkaempf Who can explain this change?

According to `git blame`, @MaximilianMeister touched this code.

Max, the documentation shows
   `<addon>: <old-version> -> <new-version>`
while the current code only shows
  `<addon>: <new-version>`
(it seems).

**Comment by ereslibre** [comment]
They look different because in this specific installation it's the first time that you use the `skuba addon upgrade` command.

Addon versions are saved inside the cluster in the `skuba-config`ConfigMap, in the `kube-system` namespace.

Since the bootstrap happened with a version of `skuba` that didn't create this ConfigMap, the new version of `skuba` detects all addons as `new addon`. This is expected and normal.

Next addon upgrades will show the expected output with the comparison of current version and next version to be upgraded to.

**Comment by Martin-Weiss** [comment]
Thanks - probably we need to inform our customers then about this ;-). 
Either in the release notes or in the documentation..

**Comment by r0ckarong** [comment]
@jordimassaguerpla When was this change shipped? Can we still get this into the 4.1.0 release notes?

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla When was this change shipped? Can we still get this into the 4.1.0 release notes?

This change is in 4.1.0. We are ready to release so it is too late to change the release notes package. Sorry.

**Comment by Martin-Weiss** [comment]
Hm - I see the change in 4.0.3 or with the update to 4.0.3..

**Comment by r0ckarong** [comment]
This will be covered with the rework in #675
