### ISSUE TITLE
[doc] 5  Cluster Updates

### ISSUE THREAD

**Issue by kravciak** [SUSE/doc-caasp#645]
5  Cluster Updates

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_cluster_updates

Before cluster upgrade customers need to upgrade skuba/helm/terraform/... (packages installed by SUSE-CaaSP-Management pattern).

We need `5.0` section since running all `skuba * upgrade` commands without updating skuba first will not show any cluster upgrade. Section should say something like:

---

Before upgrading cluster it's required to upgrade packages installed by SUSE-CaaSP-Management pattern on management node.

Cluster upgrade depends on skuba, but might also require new helm / terraform or other dependencies.

Run `sudo zypper update` on management node.

**Comment by r0ckarong** [comment]
Relates to: #644
