### ISSUE TITLE
[doc]  shell redirection won't work if the user has no permission to write

### ISSUE THREAD

**Issue by bhdn** [SUSE/doc-caasp#646]
In the linked (below) section:
 ```
sudo docker run --entrypoint htpasswd registry.suse.com/sles12/registry:2.6.2 -Bbn USERNAME PASSWORD \
> /etc/docker/registry/auth/htpasswd
```
Won't work, as very likely the user has no permission to write to `/etc/docker/registry/auth/htpasswd`

https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#id-1.6.2.11.3.7

**Comment by r0ckarong** [comment]
@ereslibre What needs to be done if the user has no write permissions?

**Comment by innobead** [comment]
Please help fix by below updated command.

```
sudo docker run --entrypoint htpasswd registry.suse.com/sles12/registry:2.6.2 -Bbn USERNAME PASSWORD  | sudo tee /etc/docker/registry/auth/htpasswd
```
