### ISSUE TITLE
[doc] 5.3.2  Completely Disabling Reboots - how to do the reboot manually?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#653]
5.3.2  Completely Disabling Reboots

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_completely_disabling_reboots

------
In case the automated drain and reboot is not used and turned off following this method - what are the manual steps required to be followed for a manual reboot? I assume this needs to be documented. (drain, reboot, uncordon and first all masters in sequential order and then all workers in sequential order?)

**Comment by r0ckarong** [comment]
@ereslibre @MaximilianMeister

**Comment by ereslibre** [comment]
Yes, the operations should be, first on all control plane nodes, then on worker nodes:

- For control plane nodes
  - Drain
  - Reboot
  - Uncordon

- For worker nodes
  - Drain
  - Reboot
  - Uncordon

In principle, if no user workloads are running on the control plane nodes it's safe to reboot them without having to follow the drain/uncordon cycle, but let's document the safest way.

**Comment by Martin-Weiss** [comment]
It would be nice to document the exact commands required for the drain.. 
(remember error: cannot delete DaemonSet-managed Pods)

I assume we might need to add 
`--ignore-daemonsets=false --delete-local-data=false  --force=true` to `kubectl drain`
?

**Comment by r0ckarong** [comment]
@ereslibre Please provide the detailed steps to properly perform these procedures or let me know who can provide them.
