### ISSUE TITLE
[doc] 5.3.2  Completely Disabling Reboots - need to document how to configure reboot schedules properly

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#654]
5.3.2  Completely Disabling Reboots

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_completely_disabling_reboots

------
Customers need to adjust the kured reboot schedule so that they can have planned and controlled reboots. For this they have to add i.e.

            - --reboot-days="sat,sun"
            - --start-time=8pm
            - --end-time=11pm
            - --time-zone="Europe/Berlin"
            - --period=10m

See also https://github.com/weaveworks/kured

Probably this also needs to add --period 10m as 1h might be too long?

And - I am not sure if the kured version in CaaSP v4 already does support these flags - so far I just got an error when trying to use --reboot-days:

```
kubectl logs -n kube-system kured-md7js
Error: unknown flag: --reboot-days
Usage:
  kured [flags]

Flags:
      --alert-filter-regexp regexp.Regexp   alert names to ignore when checking for active alerts
      --blocking-pod-selector stringArray   label selector identifying pods whose presence should prevent reboots
      --ds-name string                      name of daemonset on which to place lock (default "kured")
      --ds-namespace string                 namespace containing daemonset on which to place lock (default "kube-system")
  -h, --help                                help for kured
      --lock-annotation string              annotation in which to record locking node (default "weave.works/kured-node-lock")
      --period duration                     reboot check period (default 1h0m0s)
      --prometheus-url string               Prometheus instance to probe for active alerts
      --reboot-sentinel string              path to file whose existence signals need to reboot (default "/var/run/reboot-required")
      --slack-hook-url string               slack hook URL for reboot notfications
      --slack-username string               slack username for reboot notfications (default "kured")
      --telemetrics                         Enable telemetrics messages
      --telemetrics-level int               Only telemetrics messages with this or a higher severity level are submitted (default 2)
```

--> do we also need to request a newer version of kured?

**Comment by Martin-Weiss** [comment]
FYI - also created https://jira.suse.com/browse/CTNRFEAT-109

**Comment by r0ckarong** [comment]
@ereslibre @MaximilianMeister

**Comment by ereslibre** [comment]
I see this feature got introduced in https://github.com/weaveworks/kured/commit/170a3a4bac9fcde23b1a0ca03d8d08c60e76227c, but `kured` wasn't tagged since:

```
~/p/g/s/g/w/kured (master) > git tag --contains 170a3a4b
~/p/g/s/g/w/kured (master) >
```

We could include the patch ourselves if it's pressing.

**Comment by Martin-Weiss** [comment]
As the customer really needs to control when the reboots are allowed / scheduled - do you need anything else beside the Jira entry?

**Comment by ereslibre** [comment]
I don't think so, @kkaempf, is anything else needed?

**Comment by kkaempf** [comment]
No, nothing else is needed. Looks like a low hanging fruit we should just pick.

**Comment by r0ckarong** [comment]
> No, nothing else is needed. Looks like a low hanging fruit we should just pick.

Closing this issue.
