### ISSUE TITLE
[doc] 5.1.2  Generating an Overview of Available Addon Updates - how to upgrade all the existing addon yaml files?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#656]
5.1.2  Generating an Overview of Available Addon Updates

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_generating_an_overview_of_available_addon_updates

------------------------------
Just had to realize that skuba addon upgrade apply updates the deployments in the cluster  but does NOT update the existing addon yaml files (i.e. dex.yaml).

When re-applying the existing and adjusted / customized addon yaml files with custom settings - this can and/or will lead to rolling back and removing changes that were done during the addon upgrade apply.

I assume we have to document how to get the local dex.yaml, gangway.yaml, kured.yaml etc. adjusted so that they also have the changes done i.e. in 4.0.3 vs. 4.0.2 or earlier.

One quick workaround was to create a new 4.0.3 cluster with skuba cluster init - but there are also changes like secrets that must not be taken or changed.. so not sure what the right approach is, now.

**Comment by r0ckarong** [comment]
@ereslibre

**Comment by ereslibre** [comment]
There are currently two problems until we have the `kustomize` support merged in regarding addons:

- New addon versions will be forcefully applied, overriding customizations.
- The YAML manifests in the cluster definition folder are not written back with the updated versions.

Until we have `kustomize`, my recommendation here is for users to use `kustomize` nevertheless, so they will change our defaults provided as `kustomize` patches. They can use `kubectl apply -k` to apply their changes on top of our base manifests. When an addon upgrade happens, they can download the updated base manifests (or run `skuba cluster init` as you did), updating the base YAML, and running `kubectl apply -k` with their patches. There is a window in which `skuba addon upgrade apply` will have applied the default updated manifests though, until they run `kubectl apply -k` again.

**Comment by Martin-Weiss** [comment]
We just had to realize that even the secret in dex/gangway (clientSecret) got changed after or during a skuba addon upgrade. So after applying the "old" dex.yaml the "trust" between dex and gangway was broken. So the current "challenge" might als be seen as critical - not sure if I should also create a bugzilla entry on this?

What way we recommend and use - it needs to be tested and also added to the documentation ASAP.. where and how can a customer get kustomize so he can use it with CaaSP/Skuba?

**Comment by ereslibre** [comment]
> What way we recommend and use - it needs to be tested and also added to the documentation ASAP.. where and how can a customer get kustomize so he can use it with CaaSP/Skuba?

I think this should be a task in engineering backlog to properly allot for the time to document this properly. I'll reach out to @kkaempf about this.

**Comment by ereslibre** [comment]
https://github.com/SUSE/caasp-rfc/blob/master/accepted/0046-addon-customizations.md is covering the `kustomize` use case integrated in `skuba`, and I have a PR almost ready for it.

While we get to that I think we can document a similar approach that needs to be added to our backlog.

**Comment by r0ckarong** [comment]
@ereslibre Please set up an engineering task to produce documentation on how to install and use `kustomize` if this is the desired solution.

**Comment by ereslibre** [comment]
The kustomize PR has been merged on master and will be released with the next release.

Documentation for that task will be tackled at https://github.com/SUSE/avant-garde/issues/1370.
