### ISSUE TITLE
[doc] 2.1.3  Storage Performance - how to verify?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#657]
2.1.3  Storage Performance

https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_storage_performance

----
Could we add a command on how to verify if the given disk fulfills the requirements?

**Comment by r0ckarong** [comment]
@ereslibre Do we have some simple methods to determine this? From my experience this involves running at least a series of tests with a benchmarking tool over some time to get an idea of the "real" performance. etcd itself recommends `diskbench` or `fio`. Fio is available from packagehub: https://packagehub.suse.com/packages/fio/

**Comment by r0ckarong** [comment]
@kkaempf This is one good example of "where to draw the line" in our docs. What's your opinion on this? I personally think measuring performance should be knowledge that the admin possesses or acquires and not something we need to provide.

I would add instructions how to install this unsupported package from packagehub and then link to the fio docs (https://fio.readthedocs.io/en/latest/fio_doc.html) but I currently don't know what kind of tests we should describe to run with this.

**Comment by ereslibre** [comment]
There are mainly two major themes:

- https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md
- https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md#disks

Measuring disk I/O throughput is important, but it's also important to ack that network as it is can keep up with the requests. Latency on the network can also impact etcd's operation. For this reason, I think that we can leverage to etcd's check perf command directly: `ETCDCTL_API=3 etcdctl check perf`.

If you want to provide a specific command for `diskbench` or `fio` this will require someone to take a look at the parameters and a recommendation for our users, but as a starting point I think `etcdctl check perf` should be enough.

**Comment by Martin-Weiss** [comment]
Can we use "ETCDCTL_API=3 etcdctl check perf" before we deploy ETCD?

IMO we have to do two things:
1. clearly define what is the minimum hardware and network requirements are
2. verify if 1. is fulfilled before the deployment

**Comment by kkaempf** [comment]
> @kkaempf This is one good example of "where to draw the line" in our docs. What's your opinion on this? I personally think measuring performance should be knowledge that the admin possesses or acquires and not something we need to provide.

Full ack !

> 
> I would add instructions how to install this unsupported package from packagehub and then link to the fio docs (https://fio.readthedocs.io/en/latest/fio_doc.html) but I currently don't know what kind of tests we should describe to run with this.

Reaching out to @l-mb here, asking for recommendations on testing storage i/o performance.

**Comment by r0ckarong** [comment]
> Can we use "ETCDCTL_API=3 etcdctl check perf" before we deploy ETCD?
> 
> IMO we have to do two things:
> 
>     1. clearly define what is the minimum hardware and network requirements are
> 
>     2. verify if 1. is fulfilled before the deployment

@ereslibre Would you please setup an engineering task to determine these hardware and network requirements?
