### ISSUE TITLE
[doc] 3.1.6.1  Mirror Configuration - txt file with SUSE helm charts and corresponding images vs. CaaSP / Skuba versions

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#658]
3.1.6.1  Mirror Configuration

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-mirror

-----------------------
Thought I already created an issue for this but can not find it at the moment. So creating an other one.

For staging, airgap and version management of helm charts and corresponding images we need a similar file like https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt that contains the list of helm charts for a given CaaSP release plus the images required for it so that customers can use this for replication and staging..

Could we get such a file added?

**Comment by r0ckarong** [comment]
The original issue is #633 and still in progress. Closing and continuing in the original issue.
