### ISSUE TITLE
[doc] 3.1.6.1  Mirror Configuration - txt file show skuba 1.2.1 with images for k8s 1.15.2 and 1.16.2

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#662]
3.1.6.1  Mirror Configuration

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-mirror

-----
Here https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt we have this, now:

```
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/etcd:3.3.11
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/coredns:1.3.1
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/pause:3.1
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/skuba-tooling:0.1.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/hyperkube:v1.15.2
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/cilium-init:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/cilium-operator:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/cilium:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/caasp-dex:2.16.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/gangway:3.1.0-rev4
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.15.2 image:registry.suse.com/caasp/v4/kured:1.2.0-rev4
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/hyperkube:v1.16.2
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/etcd:3.3.15
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/coredns:1.6.2
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/pause:3.1
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/skuba-tooling:0.1.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/cilium-init:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/cilium-operator:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/cilium:1.5.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/caasp-dex:2.16.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/gangway:3.1.0-rev4
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/kured:1.2.0-rev4
```

--> is it correct that skuba 1.2.1 for caasp 4.1.0 supports also deployment of k8s 1.15.2? I would have expected just to see 1.16.2 with skuba1.2.1/caasp4.1.0..

**Comment by r0ckarong** [comment]
@jordimassaguerpla

**Comment by jordimassaguerpla** [comment]
This might be a bug in skuba cluster images. skuba 1.2.1 supports migration from 1.15 to 1.16.

**Comment by jordimassaguerpla** [comment]
@ereslibre What should be expected here?

**Comment by jordimassaguerpla** [comment]
In the other hand, we are stating that 1.15.2 is a supported version https://github.com/SUSE/skuba/blob/master/internal/pkg/skuba/kubernetes/versions.go#L101 , which makes me think skuba 1.2.1 should be able to work with 1.15.2 and 1.16.2....

**Comment by ereslibre** [comment]
`skuba` itself won't allow you to choose the Kubernetes version to deploy (this is possible on development `skuba` versions though). However, `skuba` has the old version in the map still because it needs to know if it is expected to infer an upgrade from version X to version Y, and it needs this knowledge on the static versions map.

Also, this static versions map (compiled into skuba) is what `skuba` uses to print the `skuba cluster images` output. I don't think it's a big problem to print all known versions in the map.

It could be possible to only print the images related to the latest version on the map (as it does when you do a `skuba cluster init` forcefully in release mode), however I think it is hiding information that it has nevertheless and I think it would be good to leave it as it is.

**Comment by ereslibre** [comment]
> In the other hand, we are stating that 1.15.2 is a supported version https://github.com/SUSE/skuba/blob/master/internal/pkg/skuba/kubernetes/versions.go#L101 , which makes me think skuba 1.2.1 should be able to work with 1.15.2 and 1.16.2....

`skuba` has a flag `--kubernetes-version` on `skuba cluster init` only visible in development builds. This was done in purpose, partially for smoke testing upgrades with newer versions of skuba, and partially because we might want to support this use case for our customers, however this argument is not exposed in release mode (yet, don't know if we want to do so).

**Comment by jordimassaguerpla** [comment]
IIUC, you could have a cluster running 1.15. Then, update skuba and you are offered the possibility to run "cluster upgrade" commands. However, you could not run them and still have k8s 1.15. Thus, I believe, to be in the safe side, you should keep 1.15 in your mirrors.
@ereslibre makes sense what am I saying?

**Comment by Martin-Weiss** [comment]
If we can deploy a supported cluster with k8s 1.15.2 using skuba 1.2.1 - leaving the status as is is fine.
In case we do NOT support this and we support 1.16.2 with skuba 1.2.1 only - we have to remove the 1.15.2 <-> 1.2.1 from the txt file.

Customers need to know which images to fetch for CaaSP 4.1 - and I thought this is 1.16.2 only?

**Comment by jordimassaguerpla** [comment]
If you want to update a running cluster, in the initial phase, so after updating skuba but before calling the skuba-update commands, you need both, 1.15 and 1.16. To be in the safe side I would leave it as it is.

**Comment by Martin-Weiss** [comment]
> 
> 
> If you want to update a running cluster, in the initial phase, so after updating skuba but before calling the skuba-update commands, you need both, 1.15 and 1.16. To be in the safe side I would leave it as it is.

Could you explain this in a bit more detail?
When and why do we need the list of images for CaaSP 4.1/k8s 1.15.2 with skuba 1.2.1 exactly?

An other question: Do we support adding or removing nodes on a CaaSP 4.0.3 cluster with skuba 1.2.1 before that is upgraded to 1.16.2?

**Comment by jordimassaguerpla** [comment]
1- You have a running cluster with k8s 1.15.
2- You update skuba to 1.2.1.
3- You still have k8s 1.15.
4- You use the "skuba upgrade" subcommands to update the cluster to 1.16.
5- You have k8s 1.16

At 3, you still have k8s 1.15. Just to play safe, I would keep the k8s 1.15 images in your mirror until you are at point 5.

It may not be totally necessary, but to prevent weird support requests, my recommendation is to keep the 1.15 images until you are in point 5.

**Comment by Martin-Weiss** [comment]
It is not about leaving the 1.15 images - we do / will not remove them from the registry for sure (similar like we never remove old RPMs in RPM staging..).
It is more about which 1.15 images do we use between 3- and 4- and if this is then caasp-4.0.3 patch updates or if this is caasp-4.1..
