### ISSUE TITLE
[doc] 5.2  Updating Kubernetes Components -> add info that addons need to be upgraded first!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#664]
5.2  Updating Kubernetes Components

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_updating_kubernetes_components

-----

It seems that we have to do "skuba addon upgrade plan/apply" always BEFORE we do skuba node or cluster upgrade.

I.e. got this via skuba node upgraded plan:

```
caaspadm@caasp4-01:~/caasp4-cluster> skuba node upgrade plan caasp4-02
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

Component versions in caasp4-02
  - apiserver: 1.15.2 -> 1.16.2
  - controller-manager: 1.15.2 -> 1.16.2
  - scheduler: 1.15.2 -> 1.16.2
  - etcd: 3.3.11 -> 3.3.15
  - kubelet: 1.15.2 -> 1.16.2
  - cri-o: 1.15.0 -> 1.16.0

Unable to plan node upgrade: node caasp4-02 cannot be upgraded yet. The following errors were detected:
 - There are addon upgrades available for the current cluster version (1.15.2) that need to be applied first

```

It would be nice if we could add a full update/upgrade process description maybe also including a picture of the workflow.

- zypper up; reboot on admin
- skuba-update on master+worker (systemd timer around midnight)
- reboot of master+worker via kured (checks every hour for reboot needed(
- skuba addon upgrade plan/apply on admin
- skuba node upgrade plan/ apply on admin against master1..masterN
- skuba node upgrade plan/ apply on admin against worker1..workerN

So at least the chapter "skuba addon upgrade apply" before "node upgrade" seems to be missing..

I assume the command "cluster upgrade plan" might not be needed at all?

**Comment by ereslibre** [comment]
> It seems that we have to do "skuba addon upgrade plan/apply" always BEFORE we do skuba node or cluster upgrade.

Not necessarily, only if any addon got upgraded for the current version of your cluster.

https://github.com/SUSE/skuba/pull/911 will improve `skuba cluster upgrade plan` output, telling you whether you have to upgrade addons before upgrading the platform, how the upgrade looks like, and if you have to upgrade addons afterwards as well.

**Comment by Martin-Weiss** [comment]
> 
> 
> > It seems that we have to do "skuba addon upgrade plan/apply" always BEFORE we do skuba node or cluster upgrade.
> 
> Not necessarily, only if any addon got upgraded for the current version of your cluster.
> 

Sure - so the rule will always be "upgrade addons" and then "the nodes / k8s". 
In case there are no addon upgrades - this step can be skipped.

Probably we need an other addon upgrades also after the node upgrade in case the addon upgrade can only be applied after the k8s upgrade?

> [SUSE/skuba#911](https://github.com/SUSE/skuba/pull/911) will improve `skuba cluster upgrade plan` output, telling you whether you have to upgrade addons before upgrading the platform, how the upgrade looks like, and if you have to upgrade addons afterwards as well.

Just realized that after the addon upgrade we need some sort of status check in the node upgrade that verifies if the addon upgrade really went through. I.e. the sequential kured upgrade we do at the moment can take a long time in a cluster.. (I believe it took ~15 minutes in my 6 node cluster) and I assume that the node upgrade should not be started before the addon upgrade is completed?

**Comment by ereslibre** [comment]
> Probably we need an other addon upgrades also after the node upgrade in case the addon upgrade can only be applied after the k8s upgrade?

Exactly. If you are upgrading from 1.15 to 1.16, this is what it looks like:

- Check that 1.15 addons are at their latest release available. This might be necessary, for example, upgrading addons that are known to be incompatible with 1.16 in their older version, so they can interoperate both with 1.15 and 1.16.
- Upgrade your nodes to 1.16
- Check that addons are up to date for 1.16: e.g. if an addon can be upgraded here is because it wasn't compatible with 1.15 but now it can be applied.

This is why the addon check needs to be performed twice.

**Comment by r0ckarong** [comment]
@ereslibre @Martin-Weiss 

> * skuba-update on master+worker (systemd timer around midnight)
> * reboot of master+worker via kured (checks every hour for reboot needed(

As I understand this happens automatically. Is there a recommended manual procedure to achieve this? @Martin-Weiss What did you mean when you wrote this as part of the process? Wait for it to happen?

**Comment by Martin-Weiss** [comment]
> 
> 
> @ereslibre @Martin-Weiss
> 
> > * skuba-update on master+worker (systemd timer around midnight)
> > * reboot of master+worker via kured (checks every hour for reboot needed(
> 
> As I understand this happens automatically. Is there a recommended manual procedure to achieve this? 

1. So far customers asked to configure --annotate-only in /etc/sysconfig/skuba-update to allow this to be executed manually or via other scheduler.

2. For kured - we hope to get a newer version that allows specification of date and time for reboot window. At the moment the only change that we see useful is to change the check interval to i.e 5 / 10 or 15 Minutes to speed up the rolling reboot. (instead of kured a manual drain / reboot / uncordon could be done - but this is far to complicated and too much effort in a cluster with 6 or more nodes..)

For  1. + 2. there are already issues against the documentation.

@Martin-Weiss What did you mean when you wrote this as part of the process? Wait for it to happen?
> 

See above - I believe we need more control instead of just "wait for it to happen". also we need an overview of the current patch status from the RPMs per node / cluster and also including addons, k8s version and helm chart versions...

> I've added a PR to address the issues. Please check if I got the procedure explanations correct. Thanks.

Will have a look at that and provide feedback, there.
