### ISSUE TITLE
[doc] 3.1.2.2.1  Unsecured Tiller Deployment

### ISSUE THREAD

**Issue by rssfed23** [SUSE/doc-caasp#665]
3.1.2.2.1  Unsecured Tiller Deployment

This section is using version 2.15.1

For v4.1 it should be 2.16.1.

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_unsecured_tiller_deployment

**Comment by r0ckarong** [comment]
@ereslibre @jordimassaguerpla Could you please verify the versions listed in the attributes file are correct for 4.1.0? 

https://github.com/SUSE/doc-caasp/blob/master/adoc/attributes.adoc

I will include this into our docs release procedure to have this updated more towards the end of a release. Apparently there are still too many version changes slipping through.

**Comment by jordimassaguerpla** [comment]
:cilium_version: 1.5.3
:crio_version: 1.16.0
:dex_version: 2.16.0
:etcd_version: 3.3.15
:gangway_version: 3.1.0-rev4
:kube_version: 1.16.2
:kured_version: 1.2.0-rev4
:vmware_version: 6.7.0.20000
:helm_tiller_version: 2.16.1

**Comment by jordimassaguerpla** [comment]
Tiller is the one that needs to be updated in https://github.com/SUSE/doc-caasp/blob/master/adoc/attributes.adoc

**Comment by r0ckarong** [comment]
Fixed in 32ec549
