### ISSUE TITLE
[doc] 1.2  Available Documentation

### ISSUE THREAD

**Issue by rssfed23** [SUSE/doc-caasp#666]
1.2  Available Documentation

In the available documentation section it has the line "he SUSE CaaS Platform Admin Guide discusses authorization, updating clusters and individual nodes, monitoring, use of Helm and Tiller, the **Kubernetes dashboard**, and integration with SUSE Enterprise Storage.

But the Kubernetes dashboard isn't mentioned once during the documentation (I assume because we're now shipping stratos in tech preview). 

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_available_documentation

**Comment by r0ckarong** [comment]
I think this is due to the text being a verbatim copy of what we used to have for v3. I will remove this sentence.

**Comment by r0ckarong** [comment]
Removed some obsolete text and updated wording for admin guide with 0a78445ff3e4a6ea2268da07610fa40c62221bbe
