### ISSUE TITLE
[doc] 3.1.6.2  Client Configuration - registries.conf needs some tuning

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#668]
3.1.6.2  Client Configuration

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-client

------
For airgap setup we use such a setup these days in /etc/containers/registries.conf:

1. Required for unqualified registry (i.e. in case the helm chart has "image: busybox:1.30":

`unqualified-search-registries = ["docker.io"]`

2. For the registry replicas something similar to this (caasp-prod is the stage we use - without staging just remove "/caasp-prod":

```
[[registry]]
prefix = "registry.suse.com"
location = "registry01.mydomain.local:5000/caasp-prod/registry.suse.com"
[[registry]]
prefix = "docker.io"
location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
[[registry]]
prefix = "docker.io/library"
location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
[[registry]]
prefix = "quay.io"
location = "registry01.mydomain.local:5000/caasp-prod/quay.io"
[[registry]]
prefix = "k8s.gcr.io"
location = "registry01.mydomain.local:5000/caasp-prod/k8s.gcr.io"
[[registry]]
prefix = "gcr.io"
location = "registry01.mydomain.local:5000/caasp-prod/gcr.io"

```

**Comment by kraml** [comment]
Also the current doc is a little bit unclear. The original registry.conf is in version 1 format. The example in our doc is in version 2 format. They cannot co-exist. If the user just append the example in our doc in registry.conf without removing original content he actually will not pull from the local mirror.

So could you improve the doc to make this clear, something for example: "the original registry.conf should be backup and a new one should be created to include only the content from here"?

**Comment by r0ckarong** [comment]
@Martin-Weiss Could you show me an example what your `/etc/nginx/vhosts.d/registry-server-https.conf` looks like for all these mirrors?

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss Could you show me an example what your `/etc/nginx/vhosts.d/registry-server-https.conf` looks like for all these mirrors?

I just copy the helm data to a sub-directory on the web-server root.
With apache i.e. to /srv/www/htdocs/kube-prod

mkdir /srv/www/htdocs/kube-prod
cd /srv/www/htdocs/kube-prod
helm fetch <app1>
helm fetch <app2>
then I do a "helm repo index" in that directory with --url https://<helm-repo-server>/kube-prod

So nothing special required - just check the root directory of your web-server.

**Comment by r0ckarong** [comment]
> > @Martin-Weiss Could you show me an example what your `/etc/nginx/vhosts.d/registry-server-https.conf` looks like for all these mirrors?
> 
> I just copy the helm data to a sub-directory on the web-server root.
> With apache i.e. to /srv/www/htdocs/kube-prod
> 
> mkdir /srv/www/htdocs/kube-prod
> cd /srv/www/htdocs/kube-prod
> helm fetch
> helm fetch
> then I do a "helm repo index" in that directory with --url https:///kube-prod
> 
> So nothing special required - just check the root directory of your web-server.

What I meant was how do the entries in the registries.conf correspond to the naming of the subdirectories of your web-server root? I'm assuming you create a directory `docker.io` when you use an entry like `location = "registry01.mydomain.local:5000/docker.io"`

**Comment by Martin-Weiss** [comment]
Oh - then we are not talking about nginx/apache - we are talking about registries.conf.

So first of all - I create the on premise registry with portus for authentication and authorization, where portus uses :3000 and registry uses :5000. 
Then I create different namespaces, teams and users via portus.
After this I replicate the images from external registries to these namespaces and stage images from "daily" to "test" / "reference" / "prod".

Then the /etc/containers/registries.conf looks like this (this is the caasp-prod namespace as example):

```
unqualified-search-registries = ["docker.io"]
[[registry]]
prefix = "registry.suse.com"
location = "registry01.mydomain.local:5000/caasp-prod/registry.suse.com"
[[registry]]
prefix = "docker.io"
location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
[[registry]]
prefix = "docker.io/library"
location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
[[registry]]
prefix = "quay.io"
location = "registry01.mydomain.local:5000/caasp-prod/quay.io"
[[registry]]
prefix = "k8s.gcr.io"
location = "registry01.mydomain.local:5000/caasp-prod/k8s.gcr.io"
[[registry]]
prefix = "gcr.io"
location = "registry01.mydomain.local:5000/caasp-prod/gcr.io"

```

Does this answer your question?

**Comment by r0ckarong** [comment]
> Oh - then we are not talking about nginx/apache - we are talking about registries.conf.
> 
> So first of all - I create the on premise registry with portus for authentication and authorization, where portus uses :3000 and registry uses :5000.
> Then I create different namespaces, teams and users via portus.
> After this I replicate the images from external registries to these namespaces and stage images from "daily" to "test" / "reference" / "prod".
> 
> Then the /etc/containers/registries.conf looks like this (this is the caasp-prod namespace as example):
> 
> ```
> unqualified-search-registries = ["docker.io"]
> [[registry]]
> prefix = "registry.suse.com"
> location = "registry01.mydomain.local:5000/caasp-prod/registry.suse.com"
> [[registry]]
> prefix = "docker.io"
> location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
> [[registry]]
> prefix = "docker.io/library"
> location = "registry01.mydomain.local:5000/caasp-prod/docker.io"
> [[registry]]
> prefix = "quay.io"
> location = "registry01.mydomain.local:5000/caasp-prod/quay.io"
> [[registry]]
> prefix = "k8s.gcr.io"
> location = "registry01.mydomain.local:5000/caasp-prod/k8s.gcr.io"
> [[registry]]
> prefix = "gcr.io"
> location = "registry01.mydomain.local:5000/caasp-prod/gcr.io"
> ```
> 
> Does this answer your question?

Not quite, I'm still wondering where the directories in `caasp-prod` come from. Are those names that skopeo creates?

**Comment by Martin-Weiss** [comment]
caasp-prod is the namespace I created in portus / on the registry.

first I copy the images from https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt to registry01.mydomain.local:5000/registry.suse.com (this is the "daily" namespace)

then I copy the images from the daily namespace to caasp-test so
registry01.mydomain.local:5000/registry.suse.com to registry01.mydomain.local:5000/caasp-test/registry.suse.com
then from test to reference
registry01.mydomain.local:5000/caasp-test/registry.suse.com to registry01.mydomain.local:5000/caasp-reference/registry.suse.com
and finally from reference to prod
registry01.mydomain.local:5000/caasp-reference/registry.suse.com to registry01.mydomain.local:5000/caasp-prod/registry.suse.com

A cluster in prod gets the "prod" registries.conf and a cluster in "test" gets the registries.conf with the mapping to the caasp-test namespace.

Each cluster gets its own registry user/bot/credentials and with this cluster specific credentials the cluster can only access images in the namespace he is meant to use.
