### ISSUE TITLE
[doc] 6.1.3.3  Alertmanager Configuration Example - upgrade related - could we add an example for failed pods?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#669]
6.1.3.3  Alertmanager Configuration Example

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_alertmanager_configuration_example

-------
Just had a problem that during kured based reboots some PODs did NOT start anymore on other nodes. This can happen i.e. due to some incompatibilities showing up with new patches or config changes.

In such a situation we want to stop the kured rolling reboot and that gets stop when prometheus has alerts. So we need to add and configure alerts for pods that have a increasing number of failures or that do not start properly anymore at all (i.e. due to image pull error).

Could we add an example for such a prometheus alert that can / will block the kured based reboot process?

**Comment by r0ckarong** [comment]
What would the criteria be to detect that this has happened?

@lcavajani Can you define such a Prometheus alert example?

**Comment by Martin-Weiss** [comment]
At the moment I do these manual checks:

1. watch kubectl get daemonsets. --all-namespaces

--> see if all daemonsets are up and running with latest versions
DESIRED =  CURRENT =  READY = UP-TO-DATE =  AVAILABLE

2. watch kubectl get deployments --all-namespaces
--> see if all deployments are up and running with latest versions
READY =  UP-TO-DATE  = AVAILABLE

3. watch kubectl get pods --all-namespaces
--> see if all containers of all PODs are running
STATUS = Running and Ready: X/Y - where X=Y

Not sure we we have to check further things?

**Comment by jodavis-suse** [comment]
I think the link has moved to https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#alertmanager_configuration_example

**Comment by r0ckarong** [comment]
@evrardjp

**Comment by evrardjp** [comment]
I have serious doubts about adding workload dependent recommendations.

If we add recommendations, I guess we could technically list all the minimum deployment expectations (=what's installed in caasp by default).

I would remove the daemonsets/static pods from this, as a kured operation on a sane cluster would naturally drop the value of the CURRENT/READY. This recommendation would therefore mark the system as "in alert" and prevent a run, delaying the system of at least an hour by default.
IMO, we should trust kured to do the right thing, and to rotate the nodes to reboot as soon as possible in a relatively non-disruptive way.

What were the incompatible changes you are talking about?
You are mentioning image pull problems, maybe that should be a problem on the container runtime, which should give that information back to k8s to determine if that node is schedulable.

**Comment by evrardjp** [comment]
If we wanted to continue, I suggest to add that to the APJ squad's backlog. What do you think @innobead ?

**Comment by Martin-Weiss** [comment]
> 
> 
> I have serious doubts about adding workload dependent recommendations.
> 

IMO we should at least add the minimum based on the default workloads we document (grafana, nginx-ingress, rsyslog-daemon sets, nfs-client-provisioner,...).

Basically for the standard checks you would do manually anyway (get nodes, get pods see if all are running with 1/1 or 2/2 etc.).

> If we add recommendations, I guess we could technically list all the minimum deployment expectations (=what's installed in caasp by default).
> 

Agreed

> I would remove the daemonsets/static pods from this, as a kured operation on a sane cluster would naturally drop the value of the CURRENT/READY. This recommendation would therefore mark the system as "in alert" and prevent a run, delaying the system of at least an hour by default.
> IMO, we should trust kured to do the right thing, and to rotate the nodes to reboot as soon as possible in a relatively non-disruptive way.
> 

I see that we also need to verify the kured and rsyslog daemon sets as i.e. setting a wrong image or wrong parameter will cause kured to do endless restarts or not work at all.

> What were the incompatible changes you are talking about?

Specify a parameter for kured 1.3 in kured 1.2 

> You are mentioning image pull problems, maybe that should be a problem detected by the container runtime, which should give that information back to k8s (kubelet) by setting the node to an unschedulable state (through a condition).


Image pull problems might be related to just one image, one registry or one deployment etc. so setting the whole node on "unschedulable" would not be "fair" ;-).

> 
> @Martin-Weiss

**Comment by evrardjp** [comment]
> 
> > I would remove the daemonsets/static pods from this, as a kured operation on a sane cluster would naturally drop the value of the CURRENT/READY. This recommendation would therefore mark the system as "in alert" and prevent a run, delaying the system of at least an hour by default.
> > IMO, we should trust kured to do the right thing, and to rotate the nodes to reboot as soon as possible in a relatively non-disruptive way.
> 
> I see that we also need to verify the kured and rsyslog daemon sets as i.e. setting a wrong image or wrong parameter will cause kured to do endless restarts or not work at all.

Kured is shipped as an addon, while rsyslog daemonset isn't. Probably worth separating the cases here.

For kured, the addon upgrade is handled just fine in our processes. So that shouldn't be a problem.
For rsyslog, I think we shouldn't assume everyone would be using rsyslog, so I am not sure it matters for this alertmanager config. However, it could make sense to write best practices if necessary.

> 
> > What were the incompatible changes you are talking about?
> 
> Specify a parameter for kured 1.3 in kured 1.2

That sound be handled in the upgrades process, so there is nothing to worry about.

 
> Image pull problems might be related to just one image, one registry or one deployment etc. so setting the whole node on "unschedulable" would not be "fair" ;-).

I see what you mean there. I am not sure whether this should be automatically defined in alertmanager, but I see your point of us lacking either the appropriate documentation or a tool to validate/verify some of those non-addons cases.

> 
> > @Martin-Weiss

**Comment by Martin-Weiss** [comment]
> 
> 
> > > I would remove the daemonsets/static pods from this, as a kured operation on a sane cluster would naturally drop the value of the CURRENT/READY. This recommendation would therefore mark the system as "in alert" and prevent a run, delaying the system of at least an hour by default.
> > > IMO, we should trust kured to do the right thing, and to rotate the nodes to reboot as soon as possible in a relatively non-disruptive way.
> > 
> > 
> > I see that we also need to verify the kured and rsyslog daemon sets as i.e. setting a wrong image or wrong parameter will cause kured to do endless restarts or not work at all.
> 
> Kured is shipped as an addon, while rsyslog daemonset isn't. Probably worth separating the cases here.
> 
> For kured, the addon upgrade is handled just fine in our processes. So that shouldn't be a problem.

How do you want to know how a customer adjusted / customized the kured parameters?
How do you want to realize as a customer that with the new parameter - kured pods die every 10 Minutes?

> For rsyslog, I think we shouldn't assume everyone would be using rsyslog, so I am not sure it matters for this alertmanager config. However, it could make sense to write best practices/examples for it. I agree.
> 

All the customers following the admin guide will setup a remote syslog server as this is a standard and basic requirement and also best practice ;-).

However - I do not think that we do want application specific alerts.. I would like to have a "all PODs are running with all containers" or "3 out of 35 PODs are not running as expected".

So if you check "kubectl get pods --all-namespaces" - we see for each pod it it is running as expected or not:

```
NAMESPACE              NAME                                                READY   STATUS        RESTARTS   AGE
backuptest             nfs-sles12sp3-2-864b68cd54-ffb4f                    1/1     Running       0          56d
console                stratos-0                                           3/3     Running       0          56d
console                stratos-db-7d78f7fbb9-5t9tr                         1/1     Terminating   0          54d
console                stratos-db-7d78f7fbb9-bsdm2                         1/1     Running       0          42d
default                nfs-sles12sp3-6c9b764f77-4srx4                      1/1     Terminating   0          54d
default                nfs-sles12sp3-6c9b764f77-59l9b                      1/1     Running       0          42d
kube-system            cilium-2rvxr                                        0/1     Init:Error    1          59d
kube-system            cilium-7889b                                        0/1     Running       12         152d
kube-system            cilium-8vl6m                                        0/1     Init:Error    0          56d
kube-system            cilium-gfh8s                                        0/1     Running       45         152d
kube-system            cilium-m4j8g                                        1/1     Running       8          110d
kube-system            cilium-operator-77885968c8-g255s                    0/1     Error         0          56d
kube-system            cilium-plxd4                                        0/1     Running       46         152d
kube-system            cilium-zlg65                                        0/1     Init:Error    12         109d
kube-system            coredns-6d85b94965-d75w6                            0/1     Error         0          56d
kube-system            coredns-6d85b94965-f2s4r                            0/1     Error         0          55d
kube-system            etcd-caasp4-02                                      1/1     Running       11         123d
kube-system            etcd-caasp4-03                                      1/1     Running       9          123d
kube-system            etcd-caasp4-04                                      1/1     Running       9          123d
kube-system            kube-apiserver-caasp4-02                            1/1     Running       15         123d
kube-system            kube-apiserver-caasp4-03                            1/1     Running       14         123d
kube-system            kube-apiserver-caasp4-04                            1/1     Running       14         123d
kube-system            kube-controller-manager-caasp4-02                   1/1     Running       13         123d

```

and we should have an alert if we have PODs not on READY X=Y or not in Running or Completed.

So this is ok:
rook-ceph              csi-cephfsplugin-hxs6r                              3/3     Running            15         58d

This is error:
rook-ceph              csi-cephfsplugin-hxs6r                              1/3     Running            15         58d
or
rook-ceph              csi-cephfsplugin-hxs6r                              3/3     Error                  15         58d
rook-ceph              csi-cephfsplugin-hxs6r                              3/3     Terminating       15         58d

> > > What were the incompatible changes you are talking about?
> > 
> > 
> > Specify a parameter for kured 1.3 in kured 1.2
> 
> That sound be handled in the upgrades process, so there is nothing to worry about.

Similar to dex - also kured can and will have customer adjustments and this is not related to upgrades.

> 
> > Image pull problems might be related to just one image, one registry or one deployment etc. so setting the whole node on "unschedulable" would not be "fair" ;-).
> 
> I see what you mean there. I am not sure if this should be automatically defined in alertmanager, but I see your point of us lacking either the appropriate documentation or a tool to validate/verify some of those non-addons cases.

--> Basically an alert should be generated similar to a human being checking the clusters status with "kubectl get pods --all-namespaces"

**Comment by evrardjp** [comment]
> How do you want to know how a customer adjusted / customized the kured parameters?

I am interested, but I should not: In this case, it doesn't matter. There is no way we can QA every single _non standard_ configuration of a software correctly or incorrectly defined.

For me, if the customer moves away from a standard configuration, he is responsible for it. In this case, I would test my upgrade before doing it in prod. If it fails, it should be detected in my upgrade test cases.

> How do you want to realize as a customer that with the new parameter - kured pods die every 10 Minutes?

Customer test cases, as expressed above. We can't test _every single kubernetes parameter_ to see how it would fail in the customer environment. IMO, we can only support to help in the case of something is wrong.

> 
> > For rsyslog, I think we shouldn't assume everyone would be using rsyslog, so I am not sure it matters for this alertmanager config. However, it could make sense to write best practices/examples for it. I agree.
> 
> All the customers following the admin guide will setup a remote syslog server as this is a standard and basic requirement and also best practice ;-).

A remove logging server doesn't mean rsyslog. But I disgress here :) 

> However - I do not think that we do want application specific alerts.. I would like to have a "all PODs are running with all containers" or "3 out of 35 PODs are not running as expected".
> 
> So if you check "kubectl get pods --all-namespaces" - we see for each pod it it is running as expected or not:
> 
> ```
> NAMESPACE              NAME                                                READY   STATUS        RESTARTS   AGE
> backuptest             nfs-sles12sp3-2-864b68cd54-ffb4f                    1/1     Running       0          56d
> console                stratos-0                                           3/3     Running       0          56d
> console                stratos-db-7d78f7fbb9-5t9tr                         1/1     Terminating   0          54d
> console                stratos-db-7d78f7fbb9-bsdm2                         1/1     Running       0          42d
> default                nfs-sles12sp3-6c9b764f77-4srx4                      1/1     Terminating   0          54d
> default                nfs-sles12sp3-6c9b764f77-59l9b                      1/1     Running       0          42d
> kube-system            cilium-2rvxr                                        0/1     Init:Error    1          59d
> kube-system            cilium-7889b                                        0/1     Running       12         152d
> kube-system            cilium-8vl6m                                        0/1     Init:Error    0          56d
> kube-system            cilium-gfh8s                                        0/1     Running       45         152d
> kube-system            cilium-m4j8g                                        1/1     Running       8          110d
> kube-system            cilium-operator-77885968c8-g255s                    0/1     Error         0          56d
> kube-system            cilium-plxd4                                        0/1     Running       46         152d
> kube-system            cilium-zlg65                                        0/1     Init:Error    12         109d
> kube-system            coredns-6d85b94965-d75w6                            0/1     Error         0          56d
> kube-system            coredns-6d85b94965-f2s4r                            0/1     Error         0          55d
> kube-system            etcd-caasp4-02                                      1/1     Running       11         123d
> kube-system            etcd-caasp4-03                                      1/1     Running       9          123d
> kube-system            etcd-caasp4-04                                      1/1     Running       9          123d
> kube-system            kube-apiserver-caasp4-02                            1/1     Running       15         123d
> kube-system            kube-apiserver-caasp4-03                            1/1     Running       14         123d
> kube-system            kube-apiserver-caasp4-04                            1/1     Running       14         123d
> kube-system            kube-controller-manager-caasp4-02                   1/1     Running       13         123d
> ```
> 
> and we should have an alert if we have PODs not on READY X=Y or not in Running or Completed.

I am not disagreeing on the fact that people should monitor events to know what's wrong or not.
What I am saying is that our customers _know best_ what's relevant for them. PODs is probably the wrong abstraction. Deployments sound already better. Pods Terminating events could be a natural response of something happening on the node, which doesn't mean that it will impact the deployment. Humans or robots shouldn't micro-manage pods, kubernetes handles that.

What we could do, is clarify what the baseline is. For example: "All your nodes should run a kured daemonset, which must not be in error state" (it means they could be terminated, the expected could be lower than the desired, but this is not an error state). That could translate into a _recommendation_ of configuration of alertmanager, but I would not encourage to automatically have a policy, mapping on pods directly.

I will leave others to step in there, to give their opinion :)
