### ISSUE TITLE
[doc] 4.1.2  Product Key

### ISSUE THREAD

**Issue by mattikbk** [SUSE/doc-caasp#670]
4.1.2  Product Key

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#registration_code

The documentation tells me to "Navigate to Products › ]" but there is no "Products" navigation available. Do you mean "Additional Products"? Plus, there could be some info what to do if "SUSE CaaS Platform" is not found there. Additionally the URL says I'm reading "/suse-caasp/4.1/" but the doc says "Select SUSE CaaS Platform › 4.0 › x86_64"

**Comment by r0ckarong** [comment]
@jordimassaguerpla This is another side effect of "reusing" the 4.0 channel. SCC will show the wrong version. It only lists 4.0 but the actual contents will be 4.1.

**Comment by r0ckarong** [comment]
Rewrote this to avoid the version name. 

Closed with de8c78d, ddce8e0
