### ISSUE TITLE
[doc]  external mirror - which registry image to be used? 

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#674]
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#id-1.6.2.11.3.7

It seems that there are two registry:2.6.2 images on registry.suse.com:
registry.suse.com/sles12/registry:2.6.2 and
registry.suse.com/caasp/v4/registry:2.6.2

From the image metadata it seems that the one in caasp/v4 is newer 
("Created": "2019-03-01T10:17:54Z")
as the one in sles12/
"Created": "2019-08-12T15:42:59Z",

--> what is the difference between these two images and which one should CaaSP v4.1 customers use?

**Comment by r0ckarong** [comment]
@jordimassaguerpla

**Comment by jordimassaguerpla** [comment]
The one in https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-mirror is correct.

registry.suse.com/caasp/v4/registry:2.6.2 was part of CaaSPv4 beta1. See the beta tag:

caasp/v4/registry                        2.6.2, 2.6.2-rev1, 2.6.2-rev1-build1.2, 2.6.2-rev1-build2.1, beta1

**Comment by Martin-Weiss** [comment]
> 
> 
> The one in https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#airgap-container_registry-mirror is correct.
> 
> registry.suse.com/caasp/v4/registry:2.6.2 was part of CaaSPv4 beta1. See the beta tag:
> 
> caasp/v4/registry 2.6.2, 2.6.2-rev1, 2.6.2-rev1-build1.2, 2.6.2-rev1-build2.1, beta1

I see multiple images with different tags, here - and "2.6.2" is NOT beta.
"Beta tags also exist for other caasp images - see caasp/v4/cilium                          1.2.1, 1.2.1-rev1, 1.2.1-rev1-build1.1, 1.2.1-rev1-build1.2, 1.2.1-rev1-build1.3, 1.2.1-rev1-build2.1, 1.2.1-rev1-build2.2, 1.2.1-rev1-build2.3, 1.4.2, 1.4.2-rev1, 1.4.2-rev1-build1.11, 1.4.2-rev1-build2.2.1, 1.4.2-rev1-build2.2.2, 1.4.2-rev2, 1.4.2-rev2-build1.13, 1.5.1, 1.5.1-rev1, 1.5.1-rev1-build2.2.5, 1.5.1-rev1-build2.2.6, 1.5.3, 1.5.3-rev1, 1.5.3-rev1-build2.2.19, 1.5.3-rev1-build2.2.7, 1.5.3-rev2, 1.5.3-rev2-build2.2.11, 1.5.3-rev2-build2.2.6, 1.5.3-rev2-build3.2.8, 1.5.3-rev3, 1.5.3-rev3-build1.1, beta, beta1

Also the patchlevel and the meta-information are newer in caasp/v4/registry 2.6.2.

Maybe we should delete the "not supported stuff"?

**Comment by jordimassaguerpla** [comment]
Hi,
I agree the way the information is presented is misleading.
Please open a bug for removing the registry not supported and we will work on that.
thanks.

**Comment by Martin-Weiss** [comment]
No problem - https://bugzilla.suse.com/show_bug.cgi?id=1161566 created ;-)
