### ISSUE TITLE
[doc] 4.8  NGINX Ingress Controller - add: suse nginx-ingress does not support PSP

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#676]
4.8  NGINX Ingress Controller

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#nginx-ingress
----

Just tried to deploy on 4.1 with 

```
podSecurityPolicy:
  enabled: true
```

And get this error:

`Error: validation failed: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions"`

So the required changed in the helm chart for k8s 1.16.2 seems to be missing and I believe we do not support the PSP with our version, anyway.

Due to that we should add a note that we do not support PSP with this helm chart and deployment.

**Comment by r0ckarong** [comment]
@ereslibre @jordimassaguerpla Can you please verify if this is intentional or a bug?

**Comment by thehejik** [comment]
I can confirm this issue. But I don't know if it is intentional or a bug.

**Comment by Martin-Weiss** [comment]
> 
> 
> I can confirm this issue. But I don't know if it is intentional or a bug.

Upstream version does not have this problem but that is a newer version of nginx and I remember that we had some discussions that we can not provide the newer nginx version for some reason..

**Comment by thehejik** [comment]
Ok, there is a bug in our nginx-ingress helm chart, we forgot to migrate the deprecated API fro `apiVersion: extensions` to `apiVersion: policy/v1beta1` according to https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ in https://github.com/SUSE/kubernetes-charts-suse-com/blob/master/stable/nginx-ingress/templates/podsecuritypolicy.yaml

After the change it works as expected. I'll prepare PR...

**Comment by jordimassaguerpla** [comment]
Thanks @thehejik

**Comment by thehejik** [comment]
The PR above was merged but unfortunately it wasn't enough, one more issue with enabled PSP found and reported https://github.com/SUSE/avant-garde/issues/1259

**Comment by r0ckarong** [comment]
@jordimassaguerpla @thehejik Is this resolved now?

**Comment by thehejik** [comment]
@r0ckarong yes this was fixed and our tests are passing now. This is related fix for PSP on nginx-ingress helm chart  https://github.com/SUSE/kubernetes-charts-suse-com/pull/122

No note about PSP support is needed (now it works in both cases - with enable and disabled PSP as well). I'd say this can be closed.
