### ISSUE TITLE
[doc] 4.6.2  Deploying a 389 Directory Server with an External Certificate - rootCA.crt?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#677]
4.6.2  Deploying a 389 Directory Server with an External Certificate

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_deploying_a_389_directory_server_with_an_external_certificate

-----

as part of this shouldn´t we also replace the Self-Signed-CA.pem so that we do not get this warning in the logs:

`[17/Jan/2020:14:08:22.430464647 +0000] - WARN - Security Initialization - SSL alert: CERT_VerifyCertificateNow: verify certificate failed for cert Server-Cert of family cn=RSA,cn=encryption,cn=config (Netscape Portable Runtime error -8179 - Peer's Certificate issuer is not recognized.)`

**Comment by jenting** [comment]
cc @cclhsu

**Comment by r0ckarong** [comment]
Closed with #710
