### ISSUE TITLE
Broken links in v3 and v4 (not 4.1)

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#680]
Check links this file: 
https://w3.nue.suse.com/~sknorr/scd-links-filter

Each link has to be manually checked, because some might be false positives. Remove/fix broken links.

**Comment by nkoranova** [comment]
PR for v4: https://github.com/SUSE/doc-caasp/pull/681

**Comment by nkoranova** [comment]
PR for v3: https://github.com/SUSE/doc-caasp/pull/683

**Comment by nkoranova** [comment]
All done. I'll ask for a rebuild of the v3 docs.

**Comment by r0ckarong** [comment]
Since the PRs are merged do you want to close this issue?

**Comment by nkoranova** [comment]
yes, merged and rebuilt. closing.
