### ISSUE TITLE
[doc] 6.1.3.3  Alertmanager Configuration Example - no alert when node "NotReady"

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#684]
6.1.3.3  Alertmanager Configuration Example

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_alertmanager_configuration_example

---------------------------------------
I am not sure if the documentation is wrong - but I configured the alertmanager following this example and it does NOT create any alert in case a node is in the status "NotReady".

Is it just me or is this a general problem?

```
kubectl get nodes
NAME        STATUS     ROLES    AGE    VERSION
caasp4-02   NotReady   master   127d   v1.16.2
caasp4-03   Ready      master   127d   v1.16.2
caasp4-04   Ready      master   127d   v1.16.2
caasp4-05   Ready      <none>   127d   v1.16.2
caasp4-06   Ready      <none>   127d   v1.16.2
caasp4-07   Ready      <none>   127d   v1.16.2
caasp4-08   Ready      <none>   127d   v1.16.2

```

But `kube_node_status_condition{condition="Ready",status="false"} == 1` in prometheus gives back nothing.
And `kube_node_status_condition{condition="Ready",status="false"} == 0` in prometheus gives back my 7 nodes

In describe node I can see this:

```
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----                 ------    -----------------                 ------------------                ------              -------
  NetworkUnavailable   False     Thu, 16 Jan 2020 16:52:45 +0100   Thu, 16 Jan 2020 16:52:45 +0100   CiliumIsUp          Cilium is running on this node
  MemoryPressure       Unknown   Wed, 22 Jan 2020 16:23:57 +0100   Wed, 22 Jan 2020 16:24:41 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure         Unknown   Wed, 22 Jan 2020 16:23:57 +0100   Wed, 22 Jan 2020 16:24:41 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure          Unknown   Wed, 22 Jan 2020 16:23:57 +0100   Wed, 22 Jan 2020 16:24:41 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready                Unknown   Wed, 22 Jan 2020 16:23:57 +0100   Wed, 22 Jan 2020 16:24:41 +0100   NodeStatusUnknown   Kubelet stopped posting node status.

```

And if I filter in prometheus on "condition="unknown" I get the "NotReady" node listed.

So this works if the node is down:
`kube_node_status_condition{condition="Ready",status="unknown"} == 1`

So should we change the alert to something like the following?

`kube_node_status_condition{condition="Ready",status="unknown"} == 1 or kube_node_status_condition{condition="Ready",status="false"} == 1`

**Comment by r0ckarong** [comment]
@lcavajani Could you verify this please?

**Comment by lcavajani** [comment]
I will try to have a look this week
