### ISSUE TITLE
[doc] Update example 'cluster status' output with STATUS and ROLE columns

### ISSUE THREAD

**Issue by jodavis-suse** [SUSE/doc-caasp#696]
The Administration guide does not mention 'skuba cluster status' or 'kubectl caasp cluster status' anywhere.  

The Deployment guide at https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#cluster.bootstrap and the Quickstart https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-quickstart/#cluster.bootstrap do have an example `cluster status` output
This needs to be updated with both STATUS and ROLE, as those columns have been recently added.

Note the README.md in skuba repo has already been updated with these columns.

This issue was created after completion of https://github.com/SUSE/skuba/pull/935 .

**Comment by r0ckarong** [comment]
@jodavis-suse Would you please add a PR showing this `STATUS` and/or `ROLE` output and ideally how to interpret the new output params?

**Comment by jodavis-suse** [comment]
Chang's PR https://github.com/SUSE/skuba/pull/935 has some example output in the description showing some possible values for ROLE and STATUS.  Additionally the README.md at https://github.com/SUSE/skuba/pull/938/files has been updated, though that doesn't have any additional information over the description in 935.

I can give a quick description and @suseclee can correct me or fill in more detail.
ROLE
values are either "master" for the control nodes or "<none>" for worker nodes
STATUS
values are "NotReady" for a node that is still starting up, "Ready" for a node that is working correctly, or "Ready,SchedulingDisabled" for a worker node that has been marked to not accept new workloads

These role and status values should correlate to the 'kubectl get nodes' values.
