### ISSUE TITLE
Docs and kubernetes.spec file show different config values

### ISSUE THREAD

**Issue by jvanz** [SUSE/doc-caasp#702]
The FlexVolume [documentation](https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_flexvolume_configuration) says the users should configure their vendor driver at `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`. However, the [kubernetes.spec](https://build.suse.de/package/view_file/SUSE:SLE-15-SP1:Update:Products:CASP40:Update/kubernetes.SUSE_SLE-15-SP1_Update_Products_CASP40_Update/kubernetes.spec?expand=1) file uses a different value for this configuration. It set the directory to `%{_localstatedir}/lib/kubelet/volume-plugin`. 

I would like to know which one is the right directory. I've tried to check in the OBS revision some hints about why it's different. But I could not find anything.  This problem come from  a [customer](https://bugzilla.suse.com/show_bug.cgi?id=1162093).

**Comment by r0ckarong** [comment]
@nkoranova Do you remember who contributed the flexvolume config? I think it was @lcavajani if I am not mistaken.

**Comment by lcavajani** [comment]
@jvanz the doc was created for `v3` which was based on MicroOS so the default directory for flexvolumes could not be used. With `v4` this problematic is gone and we can use the default.

Let me check the BSC.

**Comment by jvanz** [comment]
This is not a docs issue. It's a packing problem which already being handle. So, I'm closing this. Thanks
