### ISSUE TITLE
[doc] 1.2  Available Documentation

### ISSUE THREAD

**Issue by dwainsims** [SUSE/doc-caasp#703]
1.2  Available Documentation

https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_about_this_guide.html#_available_documentation

**Admin Guide
The SUSE CaaS Platform Admin Guide discusses authorization, updating clusters and individual nodes, monitoring, use of Helm and Tiller, the Kubernetes dashboard, and integration with SUSE Enterprise Storage.**

This is the only reference that I can find to "the Kubernetes dashboard" in this doc.  

And it really does need to be addressed.  Since we have moved to Kubernetes V1.16, the v1 release of the dashboard will not work with this Kubernetes.  (you get 404 errors when you login.)
If you install the dashboard via helm, you will get v1 (and it will fail.)

You have to use Kubernetes dashboard v2 to make this work.  Documentation around the web seems spotty on getting this installed, as it is not fully released yet.(RC3 as of this writing.)  

A note here might save someone a lot of time and frustration.

**Comment by r0ckarong** [comment]
This was already removed and will be gone with the next update. 

https://github.com/SUSE/doc-caasp/commit/0a78445ff3e4a6ea2268da07610fa40c62221bbe
