### ISSUE TITLE
[doc] 4.2.1  Deploying the Cluster Nodes

### ISSUE THREAD

**Issue by mmeiste** [SUSE/doc-caasp#704]
4.2.1  Deploying the Cluster Nodes

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_deploying_the_cluster_nodes

The image below "7.Now you can deploy the nodes by running:" shows "haproxy".
Does that mean it will only work with haproxy, so e.g. SOC8 Crowbar and it will fail within CLM?

**Comment by r0ckarong** [comment]
@kkaempf

**Comment by r0ckarong** [comment]
bump
@kkaempf @evrardjp

**Comment by kkaempf** [comment]
Uhm, I can't answer that. @ereslibre maybe ?

**Comment by ereslibre** [comment]
@mmeiste I don't know a lot about OpenStack. As far as I know `haproxy` is one of the two LB implementations OpenStack has, right? Are you asking if other backend will work? Can you please clarify the question?

**Comment by ereslibre** [comment]
As a side note, I see that the openstack terraform provider supports a `loadbalancer_provider` setting. We haven't tried to override this value and at this time we are defaulting to whatever the openstack terraform provider is doing.

**Comment by evrardjp** [comment]
CPI doesn't necessary need to be enabled.
If enabled, Octavia or LBaaS needs to be enabled in the cloud, for having load balancing services, While the terraform files might need adapting to set the `provider` or `loadbalancer_provider`, both should work (TM).

IIRC, CLM8 supported Neutron LBaaS v2, and 9 supports octavia. I can't remember if those were defaults or not. To be confirmed by @dirkmueller or @rktidwell . If that's the case, it should work with SOC and CLM.

**Comment by mmeiste** [comment]
seems for clm based cloud following change adding 'loadbalancer_provider = "haproxy"' worked. load-balancer.tf:
---snip---
   resource "openstack_lb_loadbalancer_v2" "lb" {
     name          = "${var.stack_name}-lb"
     loadbalancer_provider = "haproxy"
---snap---

**Comment by dirkmueller** [comment]
@mmeiste the screenshot is taken from a SOCC8 installation, which only supported haproxy. in general as long as the terraform scripts do not configure an explicit _provider, any should work. 

there was an issue that CLM did not deploy the lbaasv2 compat layer (which is used by terraform), but that has been fixed.

**Comment by evrardjp** [comment]
AFAIK, we don't explicitly give a provider in those loadbalancer tf files. This should be good to go without extra changes then.
