### ISSUE TITLE
[doc] 4.1.2  Registration Code

### ISSUE THREAD

**Issue by genet022** [SUSE/doc-caasp#708]
4.1.2  Registration Code

https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_deployment_instructions.html#registration_code

This feels like a good spot to mention that a trial Registration Code can be obtained. Perhaps add a pointer to [here](https://www.suse.com/products/caas-platform/download/) in this section?

I could see the argument that this is out of scope for this section as well, so feel free to disregard if that is your stance.

**Comment by r0ckarong** [comment]
@kkaempf Does it make sense to mention trials here? I think we could do it unless there are many restrictions to the trial version (I don't know how they work).

**Comment by r0ckarong** [comment]
Since I can't get a response how they work I won't be able to add anything regarding trials.
