### ISSUE TITLE
[doc] 4.3.3.2  SUSE Linux Enterprise Server Installation

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#709]
4.3.3.2  SUSE Linux Enterprise Server Installation

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_suse_linux_enterprise_server_installation

The screenshot still says "Alpha" and the text says "Beta". Neither are correct.

**Comment by r0ckarong** [comment]
Need to adjust the text to automatically contain the correct version number (https://github.com/SUSE/doc-caasp/blame/master/adoc/deployment-vmware.adoc#L91) and find some way to update the screenshot automatically (maybe from QA).

**Comment by r0ckarong** [comment]
There was a poor choice made when the release channel was set up in the beginning. All 4.x versions will go into the `4.0` channel and thus the text for the module will not change. I have removed the Alpha/Beta mentions from the text and screenshots.
