### ISSUE TITLE
[doc] 3.1.2.2.1  Unsecured Tiller Deployment-> version variable not filled?

### ISSUE THREAD

**Issue by dominikmathern** [SUSE/doc-caasp#711]
3.1.2.2.1  Unsecured Tiller Deployment

https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_unsecured_tiller_deployment

------------------------
We can see this:

`helm init --tiller-image registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version} \`

but would expect to see the correct tiller version instead of {helm_tiller_version}

**Comment by r0ckarong** [comment]
This was fixed in a later release of the documentation. The correct version to be placed there is: `2.14.2`.

**Comment by r0ckarong** [comment]
Duplicate of #495
