### ISSUE TITLE
[doc] 5.6  Control plane nodes certificates

### ISSUE THREAD

**Issue by flavio** [SUSE/doc-caasp#714]
About this section:

>5.6  Control plane nodes certificates
>
> https://susedoc.github.io/doc-caasp/master/html/caasp-architecture/_deployment_scenarios.html#_control_plane_nodes_certificates

I think we should specify how certificates are automatically rotated.

@ereslibre can you provide some information, I fear I might write something wrong here.

**Comment by evrardjp** [comment]
@ereslibre @flavio I am curious, certificate renewals are listed in the Admin guide (https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_automatic_certificate_renewal). That page also mentions the manual renewals. This page is also the complete reference for certificates installation (or referred as such in the quickstart and installation guides). Should we point in the architecture guide to this page? Or do you want extra information? Which extra information would it be?

**Comment by evrardjp** [comment]
As discussed in the meeting this morning, we think it's okay to document things in the caasp admin guide (maybe write in a little less terse manner), and reference to it from the Architectural guide.

Workers should follow the same path.
