### ISSUE TITLE
[doc] 5.7  Worker nodes certificates

### ISSUE THREAD

**Issue by flavio** [SUSE/doc-caasp#715]
About this section:

> 5.7  Worker nodes certificates
>
> https://susedoc.github.io/doc-caasp/master/html/caasp-architecture/_deployment_scenarios.html#_worker_nodes_certificates

I think we should specify how certificates are automatically rotated.

@ereslibre can you provide some information, I fear I might write something wrong here.

**Comment by evrardjp** [comment]
This needs further investigation.

**Comment by evrardjp** [comment]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L181 is set to `True` in our /var/lib/kubelet/config.yaml , which means the configuration is appropriate. I didn't check if certificates appropriately rotated, but at least the kubelet is configured as it should. Which means the documentation I have provided is most likely good enough.
