### ISSUE TITLE
[doc] 1  Product Description - feedback about chart

### ISSUE THREAD

**Issue by flavio** [SUSE/doc-caasp#716]
Some feedback about the https://susedoc.github.io/doc-caasp/master/html/caasp-architecture/images/architecture-caasp-components.jpg diagram:

* Maybe we can replace "CoreOS dex Server" with "Dex identity service"
* There's no mention of "gangway (https://github.com/heptiolabs/gangway) - authentication component". It should stay next to dex
* The graphic is a little "sad", we could ask for external help to make it look more "SUSE" (company color scheme and icons). But we can do that later

**Comment by r0ckarong** [comment]
@flavio 
This graphic was created by Randia Mohamed for some research she did previously. I don't have the source files for this. We have at least one other open task for creating diagrams like this. Who would suggest as "external help" to produce better diagrams? The basis needs to be a technical diagram verified by engineering and then somebody could rebuild this looking a bit better.

I've done this before for airgap in a very limited capacity and it's incredibly time consuming.

**Comment by r0ckarong** [comment]
Also worth noting that the wording on this diagram is very outdated.

**Comment by nvin-krja** [comment]
I am good with network diagrams. If you need any help then let me know. I can show you different styles/themes and redo this diagram.

**Comment by r0ckarong** [comment]
> I am good with network diagrams. If you need any help then let me know. I can show you different styles/themes and redo this diagram.

That would be cool. I need to learn some new tricks with diagramming I can do it but it takes way too long. Can I reach you on Rocket Chat?
