### ISSUE TITLE
[doc] 3.2.1  Deploying the Cluster Nodes

### ISSUE THREAD

**Issue by adianas** [SUSE/doc-caasp#726]
3.2.1  Deploying the Cluster Nodes

https://susedoc.github.io/doc-caasp/master/html/caasp-deployment/_deployment_instructions.html#_deploying_the_cluster_nodes

The EC2 type instance proposed here ("m1.medium") have been discontinued.
for a master node, a better option might be the "m5.large"

**Comment by r0ckarong** [comment]
@flavio

**Comment by r0ckarong** [comment]
@ereslibre Is m5.large the right sizing? Should I change the docs to this?

**Comment by pgonin** [comment]
I did all my tests with t2.large (default I had in terraform template)

**Comment by r0ckarong** [comment]
> I did all my tests with t2.large (default I had in terraform template)
> That would be 2 vCPUS, 8GB RAM
> https://aws.amazon.com/ec2/instance-types/t2/ low cost / general purpose instances

Thanks Paul!
