### ISSUE TITLE
Rework architecture diagram for v4

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#734]
Relates to:

#571 
https://github.com/SUSE/doc-caasp/issues/716
#717 

Replace the old diagram:
![architecture-caasp-components](https://user-images.githubusercontent.com/4920542/76628820-a1316200-653d-11ea-8b9f-43159a67f7d8.jpg)

**Comment by r0ckarong** [comment]
Collecting some info here: https://confluence.suse.com/display/~mnapp/Architecture+Diagram+overhaul

**Comment by r0ckarong** [comment]
@flavio @ereslibre @kkaempf This is the current state. Is this any better? Are we missing something?

![caasp_cluster_components](https://user-images.githubusercontent.com/4920542/76628622-4ef04100-653d-11ea-9478-1f13ebab0cd9.png)
![caasp_cluster_software](https://user-images.githubusercontent.com/4920542/76628625-4f88d780-653d-11ea-8a46-03354d8b2e83.png)

**Comment by ereslibre** [comment]
Some comments:

- I would put `etcd` out of `System workloads`. It could be inside the `Control Plane` group. The `apiserver` connects to it.

- `kube-proxy` is a DaemonSet in reality, so I would place it into `System workloads` in all nodes.

- `kubelet` talks to `CRI-O`.

- The `load-balancer` is not very clear from my perspective. It should connect to every `apiserver` on every control plane node. It should not connect to `kubelet`, or `SSH`. I would completely remove a layer in front of any `SSH` connection, we are targeting nodes directly, except for very specific customer setups where they could be using bastion nodes (I wouldn't draw this case).

- I don't fully understand what "Invoke Kubernetes" means, where it is coming from, and what is its purpose, going through "Internet".

- `kubectl` does not talk to the `kubelet`, but to the `API server`.

**Comment by r0ckarong** [comment]
>     * I don't fully understand what "Invoke Kubernetes" means, where it is coming from, and what is its purpose, going through "Internet".

This was some orphaned line from a previous user item. I've changed it now.

>     * `kubectl` does not talk to the `kubelet`, but to the `loadbalancer`, that in turn, talks to the `apiserver` on every control plane node.

Changed

**Comment by r0ckarong** [comment]
@Martin-Weiss Any thoughts on this ...

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss Any thoughts on this ...

Looks great - but yes - there is something missing that is mandatory for all enterprise customers with on-premise deployments.. -> airgap and staging is missing.

SUSE provides RPMs via SCC -> SMT/RMT/SUSE Manager
SUSE provides Images -> skopeo to on premise registry (docker-distribution-registry+portus - connected to LDAP/AD)
SUSE provides Helm Charts -> helm fetch / copy file to web-server -> helm index

For all there things we have to have staging and different namespaces for test/reference/production.

And then all internal components fetch their things from the internal sources based on the environment..

Some other thoughts:
- The LDAP server should not be hosted on the admin machine - this is external / fault tolerant and probably Active-Directory
- The load balancer should also be separated from the admin machine - this is external / fault tolerant and probably HAPROXY or F5 or similar
- The storage should not be "within the master / worker" as this is an external connected service - most often NFS to NetApp or SLES, or external Ceph or VSphere provisioner

**Comment by r0ckarong** [comment]
> > @Martin-Weiss Any thoughts on this ...
> 
> Looks great - but yes - there is something missing that is mandatory for all enterprise customers with on-premise deployments.. -> airgap and staging is missing.
> 
> SUSE provides RPMs via SCC -> SMT/RMT/SUSE Manager
> SUSE provides Images -> skopeo to on premise registry (docker-distribution-registry+portus - connected to LDAP/AD)
> SUSE provides Helm Charts -> helm fetch / copy file to web-server -> helm index
> 
> For all there things we have to have staging and different namespaces for test/reference/production.
> 
> And then all internal components fetch their things from the internal sources based on the environment..
> 
> Some other thoughts:
> 
>     * The LDAP server should not be hosted on the admin machine - this is external / fault tolerant and probably Active-Directory
> 
>     * The load balancer should also be separated from the admin machine - this is external / fault tolerant and probably HAPROXY or F5 or similar
> 
>     * The storage should not be "within the master / worker" as this is an external connected service - most often NFS to NetApp or SLES, or external Ceph or VSphere provisioner

The airgap diagram is still not finished, as you said it's quite a bit more complex and I haven't untangled all the spaghetti on the picture yet.
