### ISSUE TITLE
Add documentaton about user sessions in kubeconfig files

### ISSUE THREAD

**Issue by jvanz** [SUSE/doc-caasp#735]
Recently, one customer faced some difficulties to use the kubeconfig file on multiples machines. Turn out that was the expected behavior and it would be nice to have a docs about how it works to avoid confusion in the future. 

The bug is [bsc#1165701](https://bugzilla.suse.com/show_bug.cgi?id=1165701)

**Comment by jvanz** [comment]
I'm willing to add these docs. But I would like to know where is the best section to add those.

**Comment by r0ckarong** [comment]
@jvanz Since you asked, I think this should go into the Admin Guide as an addition to the security section explaining how these tokens are used and what to consider.

I'm sure Nora will help you with this.

**Comment by nkoranova** [comment]
Yep, we're on it. :)
