### ISSUE TITLE
[doc] Example&nbsp;4.3:  Binding a Group to a Role 

### ISSUE THREAD

**Issue by AvengerMoJo** [SUSE/doc-caasp#741]
Example&nbsp;4.3:  Binding a Group to a Role 

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#q

roleRef:
- kind: Role
  name: <ROLE_NAME> 
  apiGroup: rbac.authorization.k8s.io

Should be 

roleRef:
  kind: Role
  name: <ROLE_NAME> 
  apiGroup: rbac.authorization.k8s.io

Instead.  Or else got "array", expected "map" error.

**Comment by innobead** [comment]
@cclhsu please help fix this. thanks.
