### ISSUE TITLE
[doc] 4.4.3  Adding a New Group to an Organizational Unit

### ISSUE THREAD

**Issue by AvengerMoJo** [SUSE/doc-caasp#742]
4.4.3  Adding a New Group to an Organizational Unit

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_adding_a_new_group_to_an_organizational_unit

dn: cn=GROUP,ou=OU_NAME,dc=example,dc=org
changetype: add
objectClass: top
objectClass: groupOfNames
gidNumber: GROUPID
cn: GROUP

seem to need to add : objectclass: posixGroup  as following to avoid 
ldap_add: Object class violation (65)
        additional info: attribute "gidNumber" not allowed

dn: cn=GROUP,ou=OU_NAME,dc=example,dc=org
changetype: add
objectclass: top
objectclass: groupOfNames
objectclass: posixGroup
gidNumber: GROUPID
cn: GROUP

**Comment by innobead** [comment]
@cclhsu please help check.
