### ISSUE TITLE
[doc] 3.6.1.2  Disabling Swap

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-caasp#747]
3.6.1.2  Disabling Swap

https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_deployment_instructions.html#_disabling_swap

The current doc does not disable swap permanently. Swap will be used again after reboot.... While it can still go through caasp installation, the kubelet service won't be able to start after the worker node is rebooted as the swap will be in use again. 

To permanently disable swap, I'd suggest the following procedure before deploying caasp on that node:

1. Run `cat /proc/swaps` to see which partition has been used as swap
1. Run `sudo swapoff -a` to disable swap 
1. Delete the swap entry in `/etc/fstab`
1. Run `fdisk` to delete the swap partition
1. Reboot the node and check `cat /proc/swaps` again which should return nothing from there.

This is how I work around it when deploying CaaSP on an existing default SLES15SP1 installation. 

Thank you!

**Comment by r0ckarong** [comment]
>  Swap will be used again after reboot...
Are you referring to an automatic reboot or manual reboot after following the steps that are currently in the documentation? I need to figure out the wording on how to prevent this from happening. Thank you.

**Comment by zoopster** [comment]
Your instruction here does disable swap immediately "swapoff -a" and it will prevent it from starting at reboot if removed from /etc/fstab. In an ideal world, removing the swap partition will completely prevent it from coming back.

Ideally we need to have specifics on setting up the node...disable swap during install (among other things).

**Comment by r0ckarong** [comment]
Which platform did you deploy on? I know we have dedicated instructions on how to disable/remove swap for existing SLES and VMWare.

**Comment by dsohk** [comment]
It's deployed by our partner on a hypervisor. He just spinned up a standard SLES15SP1 VM by accepting all the default settings and then handed over to someone to install CaaSP on it. I guess the default installatio of SLES15SP1 will have swap enabled.

**Comment by r0ckarong** [comment]
> It's deployed by our partner on a hypervisor. He just spinned up a standard SLES15SP1 VM by accepting all the default settings and then handed over to someone to install CaaSP on it. I guess the default installatio of SLES15SP1 will have swap enabled.

Yes, this would be considered a "baremetal"/KVM installation and that specifically has instructions to disable swap. 

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_disabling_swap

**Comment by dsohk** [comment]
Yes, I am referring to installing CaaSP on existing SLES15SP1. I just found "swapoff -a" and removing swap entry in /etc/fstab alone won't clean enough to make swap disabled after reboot. That's why I outlined the "ideal steps" to ensure it's disabled. Otherwise, even if you can install CaaSP on these nodes by following today's doc, the kubelet service won't be able to start after CaaSP deployed on the node and reboot.

**Comment by r0ckarong** [comment]
@ereslibre How would the nodes "re-enable" swap if you turn swap off specifically AND remove the swap partition from the fstab? The only thing I see here that's not like our instructions is to remove the actual swap partition. Is there some effect where this would be "detected" as swap on boot and just re-added?

I'm happy to add the extra step to the instructions but it doesn't quite make sense to me, yet.

**Comment by zoopster** [comment]
It's not a corner case...accepting all defaults on a SLE15 install will enable swap.

**Comment by r0ckarong** [comment]
> It's not a corner case...accepting all defaults on a SLE15 install will enable swap.

I changed my previous comment with the wording for that. If you follow the docs it clearly tells you to disable SWAP in this scenario and the described method should work.

I am not aware of any mechanism that would re-enable swap. if you do please let me know what it is and I'll add the step for removing the partition volume, too.
