### ISSUE TITLE
[doc] 3.4.2  Setup with AutoYaST

### ISSUE THREAD

**Issue by alexarnoldy** [SUSE/doc-caasp#748]
3.4.2  Setup with AutoYaST

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_setup_with_autoyast

I feel like this section and the next one, 3.4.3 Setup using VMWare Template, are mutually exclusive; as in either deploy your nodes with AutoYaST or by way of a VMware Template. If this is true, that should be called out just above this section. 

As it's written, someone who is not familiar with CaaSP and/or AutoYaST and/or Terraform could read this as two, successive steps.

**Comment by r0ckarong** [comment]
Yeah, good call. I'm going to change the wording that this must be done in only one way.
