### ISSUE TITLE
[doc] 3.1  Deployment Preparations

### ISSUE THREAD

**Issue by qnetter** [SUSE/doc-caasp#749]
3.1  Deployment Preparations

https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_deployment_instructions.html#deployment.preparations

Shouldn't this say "not part of the SUSE CaaS Platform cluster" or "not part of the Kubernetes cluster" rather than "not part of the skuba cluster"?

**Comment by r0ckarong** [comment]
I do not know why this wording was chosen at the time. I will change it.
