### ISSUE TITLE
[doc] 3.1  Deploying the Cluster Nodes

### ISSUE THREAD

**Issue by qnetter** [SUSE/doc-caasp#750]
3.1  Deploying the Cluster Nodes

https://documentation.suse.com/suse-caasp/4.1/html/caasp-quickstart/_deployment_on_suse_openstack_cloud.html#_deploying_the_cluster_nodes

We need to rework the Quickstart Guide to use VMware and Bare Metal/KVM. No new customers can get SOC.

**Comment by r0ckarong** [comment]
> 3.1 Deploying the Cluster Nodes
> 
> https://documentation.suse.com/suse-caasp/4.1/html/caasp-quickstart/_deployment_on_suse_openstack_cloud.html#_deploying_the_cluster_nodes
> 
> We need to rework the Quickstart Guide to use VMware and Bare Metal/KVM. No new customers can get SOC.

Having more than one deployment in this document is against the purpose that was communicated to me. VMWare is also not a "quick" process. Should we switch this to KVM? This is what we typically tell people to use for a start anyway.

cc / @kkaempf

**Comment by kkaempf** [comment]
Yeah, that's what one gets with changing deployment priorities in the middle of a product :-(

I agree with Markus that the 'Quick'start guide should focus on one platform.

In the [core team meeting](https://confluence.suse.com/display/CaaSP/Core+Team) of January 28th we agreed on this priority order for CaaSP deployment platforms
1) VMware
2) KVM
3) Public Cloud
4) Bare Metal
5) SOC

@qnetter: we either document vmware in the quickstart guide or change the deployment platform priorities. What do you recommend ?

**Comment by r0ckarong** [comment]
As discussed in the PM sync 2020-04-09, switch Quickstart to KVM/Baremetal, unpublish for SUSE internal use, get in touch with VMWare marketing team for customized VMWare quickstart.

**Comment by r0ckarong** [comment]
Internal discussion continued in https://github.com/SUSE/avant-garde/issues/1485
