### ISSUE TITLE
[doc] 6.1  Monitoring Stack

### ISSUE THREAD

**Issue by cseader** [SUSE/doc-caasp#752]
6.1  Monitoring Stack

https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_monitoring.html#_monitoring_stack

Nooo. this is supported. Now an RFI is going to have trouble.

**Comment by r0ckarong** [comment]
@kkaempf @qnetter Please confirm that the described monitoring stack is fully supported then I will remove this wording.

**Comment by kkaempf** [comment]
Yes, Prometheus & Grafana are fully supported for CaaSP.
