### ISSUE TITLE
Requirements sections of Deployment Guide and Quick Start lack indication of base SLES version

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-caasp#755]
Both the Deployment Guide and the Quick Start have Requirements sections and neither makes any real indication which version of SLES is under your CaaSP install, which is a bit weird imo. Afaict, CaaS Platform is only(?) shipped as VM images which already include an OS but mentioning the base OS would still be good so people know what behavior to expect etc.

(Maybe I am wrong of course and this is a non-issue for some reason or this is mentioned elsewhere and I did not find it.)

Sections I checked:
* https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_requirements.html#_nodes
* https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-quickstart/#_requirements

**Comment by r0ckarong** [comment]
> Afaict, CaaS Platform is only(?) shipped as VM images which already include an OS but mentioning the base OS would still be good so people know what behavior to expect

That's not true. CaaS is installed as packages (and later containers and charts) from a SLE extension module. We do not ship specific VMs with CaaSP pre-deployed.

The type of OS you need to download is detailed in the actual deployment steps. I will add some wording clarifying this.
