### ISSUE TITLE
[doc] 8.2.2  Procedures

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-caasp#757]
8.2.2  Procedures

https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_integration.html#_procedures

At the very least, the domain `omg.howdoi.website` should be removed since that's an internal DNS. It should be make more generic.

However, a bigger question is that having CAP docs in CaaS Platform is going to be a constant effort in ensuring it's not out-of-date. CAP has its own struggles with this (see https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#sec-cap-changes-kube-reqs) so maybe we need pointers to other SUSE product docs or a different tack.

**Comment by troytop** [comment]
8.2  SUSE Cloud Application Platform Integration

https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_integration.html#_suse_cloud_application_platform_integration

There should be no documentation in the CaaS Platform guide for installing SUSE CAP, just links to the relevant sections of the CAP docs: 

https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#cha-cap-depl-caasp

**Comment by r0ckarong** [comment]
@kkaempf I'm happy to remove this and replace with the link provided by Troy. Any objections?

**Comment by kkaempf** [comment]
not at all ;-)
