### ISSUE TITLE
[doc] 9.6.2.2  Procedure

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#763]
9.6.2.2  Procedure
https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_procedure_2

In 9.6.2.1 it states the recover procedure only needs to be done on one master as others will sync. Yet at step 10 in 9.6.2.2 it says to repeat step 7, 8, & 9 to recover all remaining masters?
Contradicting perhaps?

**Comment by r0ckarong** [comment]
AFAIU the etcd database will sync automatically to all configured masters but you still have to manually join these masters to the etcd cluster (which is what 9.6.2.2 / 7-9 describe).

I think this just needs some clarification on what these procedures actually do to make that clear.

@innobead Could you please confirm that my assumption is correct?

**Comment by innobead** [comment]
> 9.6.2.2 Procedure
> https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_procedure_2
> 
> In 9.6.2.1 it states the recover procedure only needs to be done on one master as others will sync. Yet at step 10 in 9.6.2.2 it says to repeat step 7, 8, & 9 to recover all remaining masters?
> Contradicting perhaps?

You just need to restore the database on the first master node, but you still need to form the etcd cluster back by adding the following members into the first master.  Please help check the documentation again and I think the description is correct.

```
You will only need to **restore database on one of the master node (master-0)**  to regain control-plane access. The remaining master nodes will sync to the restored database after joining the cluster.
```

cc @c3y1huang
