### ISSUE TITLE
[doc] 7.1  Centralized Logging

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#766]
7.1  Centralized Logging

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_centralized_logging

The SLE documentation doesn't contain any information for setting up a log server, which is a bug in itself, but here are the lines that should be added to a SLE server's /etc/rsyslog.conf for a minimal log server configuration:

```
# Configure Log Server
$ModLoad imtcp
$InputTCPServerRun 514
$template RemoteLogs,"/var/log/caasp/%HOSTNAME%/caasp.log"
*.* ?RemoteLogs
```

This will listen for incoming logs on TCP port 514. UDP does not work for this. It will create a new directory called, /var/log/caasp and subdirectories with the hostnames of each CaaSP node. Each subdirectory will contain a log file, caasp.log, with all of the logs from that node. This is a basic minimal configuration. More detail can be added or removed by consulting the man page for rsyslog.

**Comment by Martin-Weiss** [comment]
I would recommend to add the config to /etc/rsyslog.d/remote.conf

in my config I have this:
```

$ModLoad imudp.so         # provides UDP syslog reception
$UDPServerRun 514         # start a UDP syslog server at standard port 514
$template RemoteLogs,"/var/log/%HOSTNAME%/%PROGRAMNAME%.log"
*.* ?RemoteLogs
& stop

```

--> I also use UDP as with TCP the remote syslog host could be a single point of failure for the cluster.

**Comment by Martin-Weiss** [comment]
Oh - and forgot the most important point!! Do not forget about log rotation!!!

/etc/logrotate.d/remote

Hint: my hosts are called "caasp*":

```
/var/log/caasp*/*.log
{
    compress
    dateext
    maxage 365
    rotate 99
    missingok
    notifempty
    size +4096k
    create 640 root root
    sharedscripts
    postrotate
        /usr/bin/systemctl reload syslog.service > /dev/null
    endscript
}

```

**Comment by tgeek77** [comment]
I think all in all, there does need to be logserver section in the SLE Docs and at least some mention of how to set it up in the CaaSP Docs or at least a link.

**Comment by Martin-Weiss** [comment]
> 
> 
> I think all in all, there does need to be logserver section in the SLE Docs and at least some mention of how to set it up in the CaaSP Docs or at least a link.

+1

**Comment by r0ckarong** [comment]
I'm going to get in touch with the SLE folks and see what we can do here.

**Comment by taroth21** [comment]
Hi all - in the SLE docs, the main chapters with regards to logging are:
- journalctl: Query the systemd Journal, Admin Guide:
https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-journalctl.html 
- Analyzing and Managing System Log Files, Tuning Guide: https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-tuning-logfiles.html

I will add a card to our backlog that information about how to set up a logserver is missing, but a bug report would be helpful for tracking.

**Comment by Martin-Weiss** [comment]
Ok - this does not cover the rsyslog details and logrotate details a customer needs to setup the central logging for CaaSP. I really believe we have to add the right examples..

**Comment by r0ckarong** [comment]
> I really believe we have to add the right examples.. 

As usual with this kind of statement, my retort: Can you provide such examples or tell me who can?

**Comment by Martin-Weiss** [comment]
> 
> 
> > I really believe we have to add the right examples..
> 
> As usual with this kind of statement, my retort: Can you provide such examples or tell me who can?

See the comments above with the /etc/logrotate.d/remote and /etc/rsyslog.d/remote.conf - I believe these can be good starting points - we just need someone else that double-checks what I have done..

**Comment by evrardjp** [comment]
After a discussion with @innobead , we agreed that most of the setup information of a new central logging solution is out of scope of the CaaSP documentation.

At best, we could point to SLE documentation on how to set up log servers. It's not necessary, but I can agree it's nice for customers. The rest of the logging details (the kubernetes specifics) is already in our documentation, and shouldn't need more work.

**Comment by r0ckarong** [comment]
This should be covered with the work that went into #952
