### ISSUE TITLE
[doc] 6.1.3.2.4  Ingress - for grafana and prometheus needs to stay in helm chart and values!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#769]
6.1.3.2.4  Ingress

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_ingress
-----------------------

It seems that the documented example for "serve from subpath" is based on turning of "ingress" in the prometheus and grafana helm charts values.yaml and then add a separate ingress yaml manually.

This is not the best approach and should only be seen as workaround.

Could this be changed for proper helm chart values.yaml adjustments instead?

**Comment by r0ckarong** [comment]
@suseclee
