### ISSUE TITLE
[doc] 3.3.1.4  IAM Profiles

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#771]
The section below states IAM profiles, but describes AWS credentials. These are two distinctly different subjects. Because of how we're using the AWS CPI the IAM profile probably needs to be expanded with a bit more detail on exactly what is needed (the README.md in /usr/share/caasp/terraform/aws has a bit more content, but not enough).

3.3.1.4  IAM Profiles

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_iam_profiles

**Comment by r0ckarong** [comment]
This relates to: http://bugzilla.suse.com/show_bug.cgi?id=1169506

**Comment by r0ckarong** [comment]
@flavio @ereslibre Who can help me expand this info or amend the README for terraform? I don't remember seeing anything specific about setting up IAM in the AWS deployment. If only using one main admin for everything this might work (sort of) but for proper usage of IAM we need to explain this more.

**Comment by innobead** [comment]
cc @cclhsu @maximenoel8

**Comment by cclhsu** [comment]
[Add documents for creation of AWS role instance policy and profile (Closes #772) #782](https://github.com/SUSE/doc-caasp/pull/782) has addressed this issue and merged.
