### ISSUE TITLE
[doc] 3.3.2  Deploying the Infrastructure

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#772]
In this section if you leave the iam_profile_master and iam_profile_worker empty, TF does not create the proper IAM Profile even with explicit IAM_Passthru rights or the use of root credentials.
The deployment will fail with a "cannot attach profile" error.
If you add/uncomment these lines, the deployment will finish however the skuba node bootstrap will fail with a error listing instances error.

3.3.2  Deploying the Infrastructure

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_deploying_the_infrastructure

**Comment by r0ckarong** [comment]
@flavio @ereslibre What is going wrong here? What is the correct procedure to do this?

**Comment by innobead** [comment]
cc @cclhsu @maximenoel8

**Comment by cclhsu** [comment]
[fix issue for aws iam profile [bsc#1169506] (1517) #1058](https://github.com/SUSE/skuba/pull/1058) shoudl fixes this issue.

**Comment by r0ckarong** [comment]
Does this need any additional docs updates?

**Comment by cclhsu** [comment]
@r0ckarong No document update required, we only need to update terraform file to properly create iam and instance profile.

**Comment by r0ckarong** [comment]
@jordimassaguerpla We should add this to the known issues until it's merged.

**Comment by jordimassaguerpla** [comment]
@r0ckarong Does it need to have some content or just the bug mentioned?

**Comment by r0ckarong** [comment]
@jordimassaguerpla To do it right we would have to explain the entire workaround with doing the steps terraform is missing by hand but I'm not sure if you can salvage an already failed deployment that way.
If we just mention the issue then AWS is basically non functional until we ship the patch.

Not sure what to do with the right amount of effort.

@kkaempf What do you think?

**Comment by kkaempf** [comment]
That's one of the problems with "tech previews". :-/

> If we just mention the issue then AWS is basically non functional until we ship the patch.

Well, if it's really _non functional_, that's embarrassing :facepalm: 

Workaround for now:
- document it in the release notes
- make a fixed package available _internally_ (+ announce it on caasp-internal)
- wait for bug reports

Not perfect, but (imho) a minimal effort approach.

**Comment by zoopster** [comment]
If you simply document the workaround (setup the instance profile prior) then the fix to the tf files can come later and it's functional until then.

**Comment by r0ckarong** [comment]
@cclhsu Could you provide the steps required to set up the IAM profile to work around this? I think linking to this specification (https://github.com/kubernetes/cloud-provider-aws#readme) and some steps on how to achieve this on AWS would suffice?

**Comment by zoopster** [comment]
Through the aws console...it's just a matter of creating a role with the documented policy (in iam_policies.tf) and the instance profile will be created automatically with the same name of the role. That role/instance profile name needs to be added to the terraform.tfvars (where  the commented caasp-k8s-master-vm-profile is noted). If you need specific docs...happy to create them...
