### ISSUE TITLE
[doc] 1.1  Platform - need overview for CaaSP release vs. supported Helm Chart addons in the release notes or documentation

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#775]
1.1  Platform

https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_platform

---------------------------------------
Customer is running CaaSP 4.0.3 and we can not find out which Helm Chart versions are tested and supported in combination with this CaaSP release. Running a newer version than tested might cause issues and support discussions - so could we add a spread-sheet with that overview to the documentation?

**Comment by r0ckarong** [comment]
This isn't covered by this file? 

https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt

cc/ @jordimassaguerpla

**Comment by Martin-Weiss** [comment]
> 
> 
> This isn't covered by this file?
> 
> https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
> 
> cc/ @jordimassaguerpla

In this file I can only find the skuba images - all the helm charts and addon images / tiller images are missing, there.

At the moment I am trying to maintain an "other-images.txt" file myself manually just to take care about all the other stuff.. (nginx-ingress,...prometheus, grafana, tiller,...... vs. helm chart versions etc.)

A few lines out of that file:

```
#
# 389-ds (documentation caasp 4.1)
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/389-ds:1.4.0
#
# upstream nfs client provisioner nfs-client-provisioner-1.2.6.tgz and nfs-client-provisioner-1.2.8.tgz 3.1.0
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
#
# upstream nginx ingress controller nginx-ingress-1.20.0.tgz 0.25.1
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.1
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/nginx:latest
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/lemonldapng/lemonldap-ng-controller:0.2.0
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/busybox:latest
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:k8s.gcr.io/defaultbackend-amd64:1.5
#
# suse nginx ingress controller nginx-ingress-0.28.4 0.15.0
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:registry.suse.com/sles12/nginx-ingress-controller:0.15.0
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/nginx:latest
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/lemonldapng/lemonldap-ng-controller:0.2.0
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:docker.io/busybox:latest
skuba:1.1.1 caasp-release:4.0.2 kubernetes:1.15.2 image:registry.suse.com/sles12/default-http-backend:0.15.0
#
# suse prometheus prometheus-9.3.2.tgz 2.13.1 (push gateway image missing)
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-alertmanager:0.16.2
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/configmap-reload:0.3.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/kube-state-metrics:1.6.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-node-exporter:0.17.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-server:2.7.1
#skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/pushgateway:v0.8.0
#
# suse prometheus prometheus-9.3.3.tgz 2.13.1
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-alertmanager:0.16.2
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/configmap-reload:0.3.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/kube-state-metrics:1.9.3
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-node-exporter:0.17.0
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-server:2.7.1
skuba:1.2.1 caasp-release:4.1.0 kubernetes:1.16.2 image:registry.suse.com/caasp/v4/prometheus-pushgateway:0.6.0

```

**Comment by r0ckarong** [comment]
We've recently added a little information about this but nothing regarding versions per release.

@jordimassaguerpla This request sounds something like what we discussed this morning with the build config but can we somehow generate this for previous versions? This relates directly to a previous unsolved Issue: https://github.com/SUSE/doc-caasp/issues/621

**Comment by jordimassaguerpla** [comment]
It is in our backlog and I would love to tackle this asap, but unfortunately it is not our top priority right now, so we should tackle this eventually but can't tell when. I am happy to see Martin found out a solution for his customers so this is at least not causing more issues.

**Comment by Martin-Weiss** [comment]
The real problem I see is i.e. in case a system runs the oldest Prometheus or nginx-ingress etc. for k8s 1.15 we released but we do not support this on the latest k8s version i.e. 1.17 anymore. So a customer and support really needs an overview "what do I have i.e. via helm list" and has to compare this with what we support "release notes / helm charts vs images".

**Comment by r0ckarong** [comment]
cc/ @kkaempf

**Comment by kkaempf** [comment]
This is more than just documentation and needs QA and probably other squads involved. To be discussed in next grooming.

**Comment by SheilaghM** [comment]
@r0ckarong @kkaempf - is this still blocked or is it finished?  Can it be closed?

**Comment by r0ckarong** [comment]
> @r0ckarong @kkaempf - is this still blocked or is it finished? Can it be closed?

From what I can tell, nothing has happened. Still blocked.

**Comment by kkaempf** [comment]
:disappointed: all the `EngineeringInput` labeled issues should be referenced in `avant-garde`, otherwise they're not exposed to the team.
Tracked as https://github.com/SUSE/avant-garde/issues/2007 now.

**Comment by r0ckarong** [comment]
> disappointed all the `EngineeringInput` labeled issues should be referenced in `avant-garde`, otherwise they're not exposed to the team.
> Tracked as [SUSE/avant-garde#2007](https://github.com/SUSE/avant-garde/issues/2007) now.

Then I will duplicate all the issues to avant-garde?

**Comment by kkaempf** [comment]
Well, we escalated via champions / teamleads but this didn't work out apparently.
