### ISSUE TITLE
[WIP] Update Cilium documentation for 1.6 update

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#778]
We are finally nearing shipping a new Cilium. This needs an overhaul of various aspects of the networking related docs.

Existing issues and PRs are:

https://github.com/SUSE/doc-caasp/pull/587
https://github.com/SUSE/doc-caasp/issues/628

Criteria:

- [x] Update deployment-cilium.adoc with instructions on how to deploy on fresh cluster
- [x] Update admin-updates.adoc with instructions how to deploy to existing cluster + #628 (@mrostecki)
- [x] Update architecture-description.adoc with cilium details (@soumynathan)
- [x] Create new admin-security-cilium.adoc (or appropriate name) document that details how to configure and use cilium features for CaaSP with examples. (@mrostecki)
- [x] Update release notes with mention of cilium and relevant feature information (caasp-release-notes repository) https://github.com/SUSE/caasp-release-notes/pull/54

**Comment by r0ckarong** [comment]
@mdarnell-suse Which other criteria would you see for the docs of this?

@mrostecki @mmnelemane

**Comment by soumynathan** [comment]
ok I can pick up Update architecture-description.adoc with cilium details

**Comment by mrostecki** [comment]
I'm picking admin-upgrade and admin-security.

**Comment by mmnelemane** [comment]
I can help with updating the release notes

**Comment by soumynathan** [comment]
Added this PR with the details.
https://github.com/SUSE/doc-caasp/pull/781

**Comment by r0ckarong** [comment]
> I can help with updating the release notes

Waiting for the PR against https://github.com/SUSE/caasp-release-notes/pulls

> Added this PR with the details.
> #781

As detailed in the PR I can not use this.

**Comment by r0ckarong** [comment]
@manuelbuil @mmnelemane I'm still waiting for the Release notes contribution.

**Comment by nkoranova** [comment]
> > #781
> 
> As detailed in the PR I can not use this.

looks like the copy paste issue was fixed: https://github.com/SUSE/doc-caasp/pull/781#issuecomment-626604670

**Comment by nkoranova** [comment]
Release notes were updated with https://github.com/SUSE/caasp-release-notes/pull/54

**Comment by nkoranova** [comment]
As far as I can tell, this can be closed.
