### ISSUE TITLE
[doc] 9.1.1.2.2.2  Minio

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#789]
9.1.1.2.2.2  Minio

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_minio

You must also define a region name or else velero can't connect to minio
export MINIO_REGION_NAME=<region_name>

**Comment by r0ckarong** [comment]
@innobead Could you give me the correct example how to do this and verify please? Thanks

**Comment by innobead** [comment]
@jenting please help with this. Thanks.

**Comment by jenting** [comment]
@tgeek77 
Sorry, I can't reproduce it.

What's the _region-name_ setting `--set configuration.backupStorageLocation.config.region` when helm install?
Is your minio server in _or_ out k8s cluster?

**Comment by tgeek77** [comment]
I can't reproduce it again either.

**Comment by jenting** [comment]
Never mind~
Closing the issue, feel free to re-open if you find the way to reproduce it, thanks :bow:
