### ISSUE TITLE
[doc] 3.3.5.1  Using Terraform - resource pool definition needs to have better explanation / example

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#794]
3.3.5.1  Using Terraform

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_using_terraform

-----------------------

Customers tend to not have a resource pool definition in their VSphere environment.
And in case the "default" NO manually created resource pool - it is unclear what to specify in the terraform.tfvars.

In my case this works perfect:

vsphere_resource_pool = "Name of the vsphere cluster/Resources"

So I use
vsphere_resource_pool = “Cluster1/Resources” for my environment.

Could we add this to the docs and also to the terraform.tfvars.example file?
vsphere_resource_pool = "Name of the vsphere cluster/Resources"

**Comment by r0ckarong** [comment]
@innobead

**Comment by innobead** [comment]
@c3y1huang please help on this. Thanks.

**Comment by c3y1huang** [comment]
Sync vsphere_resource_pool example with with terraform site and add ref link to doc, xref: https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html.

**Comment by c3y1huang** [comment]
@Martin-Weiss I think `Name of the vsphere cluster` is more of a description than an example. I've update so its sync with the example in terraform site.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss I think `Name of the vsphere cluster` is more of a description than an example. I've update so its sync with the example in terraform site.

Thanks - please ensure that we also add a sentence in the documentation what to configure here in case the customer did not create manually created resource pools ;-).
