### ISSUE TITLE
[doc] 3.3.4  Setup using VMWare Template - network configuration details missing

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#795]
3.3.4  Setup using VMWare Template

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_setup_using_vmware_template

-----------------------------

It seems that it is assumed that a customer does NOT configure a static IP for the VM during creation and that DHCP is available in the servers network.

Unfortunately this assumption is wrong and customers have to give servers static names and addresses during installation as otherwise not even the installation server is reachable.

I just did this during the template creation and now I have to realize that the terraform process does NOT change the setup of the clones for IP or server name and all the machines get the name and IP the template has.

--> Could this be changed to allow static names and IP addresses for the servers?

**Comment by r0ckarong** [comment]
> It seems that it is assumed that a customer does NOT configure a static IP for the VM during creation and that DHCP is available in the servers network. 
>
> Unfortunately this assumption is wrong and customers have to give servers static names and addresses during installation as otherwise not even the installation server is reachable.

@kkaempf @ereslibre

This doesn't seem to have been a criteria during the testing. What is the correct thing here? Can we use terraform to actually configure this properly? If not, what are the correct steps and where in the procedure must they be taken to configure the deployed machines?

Is this going to be simplified with the vApp approach that is in the works? @thehejik provided me with the VMWare steps originally. Do we have anyone else on the team I can ask about this?

**Comment by kkaempf** [comment]
> Do we have anyone else on the team I can ask about this?

I already reached out to @qnetter before, asking for a contact within the 'vmware team'.

**Comment by jordimassaguerpla** [comment]
ping @qnetter
