### ISSUE TITLE
Add Intro to etcd Cluster Backup

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#801]
We are missing and introduction to etcd as mentioned in: 
https://github.com/SUSE/doc-caasp/pull/791#issuecomment-625195309 

What is cluster backup good for? 
What is etcd? 
How does it differ from Velero and what role does it play in disaster recovery?

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by innobead** [comment]
@nkoranova closing. Please reopen if you think something missing.

**Comment by nkoranova** [comment]
> @nkoranova closing. Please reopen if you think something missing.

I think it's all done, just forgot to close the issue. Thanks!
