### ISSUE TITLE
[doc] 4.6.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/patches/custom.yaml</code>) -> need correct kustomization and filename

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#808]
4.6.3.1.2  Example 2: Dex LDAP TLS Connector Configuration (<code class="literal">addons/dex/patches/custom.yaml</code>)

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_example_2_dex_ldap_tls_connector_configuration_addonsdexpatchescustom_yaml

----------------------------------------------

1. the filename addons/dex/patches/custom.yaml is different than ~/clusters/<CLUSTER_NAME>/addons/dex/patches/dex-patch.yaml a  few chapters further down.

2. the documented example is not a valid dex-patch.yaml as far as I understand and the kubectl apply -k will fail.

--> could we standardize the patch file names and give valid examples how the files should look like "exactly"?

**Comment by r0ckarong** [comment]
@mjura

**Comment by innobead** [comment]
@jenting please help with this. 

cc @cclhsu

**Comment by r0ckarong** [comment]
@innobead I haven't seen anything regarding this since your comment. Is this still in your backlog?

**Comment by jenting** [comment]
yes, it's still on my radar.

**Comment by jenting** [comment]
PR in flight.

**Comment by jenting** [comment]
The doc PR merged already, close this issue.
