### ISSUE TITLE
[doc] 6.3  Stratos Web Console - link should be changed to 1.5.2 I assume

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#813]
6.3  Stratos Web Console

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_stratos_web_console
----

pointing to outdated 1.5.1 might not be good as helm chart is not 2.6.1 anymore - it is 3.1.0, now

**Comment by r0ckarong** [comment]
Will be fixed with next build and properly in 4.2.1 release.

https://github.com/SUSE/doc-caasp/commit/1367940458b641a746324250d4c43675d1d18a7a
