### ISSUE TITLE
[doc]  

### ISSUE THREAD

**Issue by bodi4a** [SUSE/doc-caasp#815]
`skopeo sync --source-yaml sync.yaml dir:/tmp/skopeodata `  not working

`skopeo sync --src yaml --dest dir sync.yaml /tmp/skopeodata `  correct format

https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_deployment_scenarios.html#id-1.5.3.13.4

**Comment by r0ckarong** [comment]
This is going to be fixed in 4.2.1 and onward.
