### ISSUE TITLE
[doc] 3.1.4  Installation Tools - references in the whole 5.0 guide need to change to caasp/5.0/? and sles15sp2?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#821]
3.1.4  Installation Tools

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_installation_tools

.....

seems also here we have caasp/4.0/ -> will this change to 5.0?

and we have sles15sp1 but might need to change all to sles15sp2?

**Comment by r0ckarong** [comment]
You're again too hasty :) Development of 5 literally just began a week ago and the site you are referencing are rolling builds of the current state. We haven't gotten around to changing it all. 

From what I am told the new package repo will be `caasp/5/` or something of that nature that avoid the current confusing situation.

References to SLE 15 SP1 will be updated as we work on the respective sections.

**Comment by Martin-Weiss** [comment]
> 
> 
> You're again too hasty :) Development of 5 literally just began a week ago and the site you are referencing are rolling builds of the current state. We haven't gotten around to changing it all.

:-) Sorry - just went to the documentation the headline was about CaaSP v5 - so I was assuming someone already did the search/replace ;-).

> 
> From what I am told the new package repo will be `caasp/5/` or something of that nature that avoid the current confusing situation.
> 
> References to SLE 15 SP1 will be updated as we work on the respective sections.
