### ISSUE TITLE
[doc] 3.2  Deployment on SUSE OpenStack Cloud - download link broken

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#822]
3.2  Deployment on SUSE OpenStack Cloud

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_deployment_on_suse_openstack_cloud
----

Download the pre-built image of SUSE SLES15-SP1 for SUSE OpenStack Cloud... -> the specified link does not lead to the download anymore after the changes in SUSE download page..

**Comment by r0ckarong** [comment]
I wasn't aware that the downloads page changed and also not about the fact we apparently do not offer any SOC images anymore.

@kkaempf Should we remove SOC deployment from 5 altogether? And is there a new location where we can point to the SOC image for v 4.x?

**Comment by kkaempf** [comment]
> 
> @kkaempf Should we remove SOC deployment from 5 altogether?

That's for @qnetter to decide.

> And is there a new location where we can point to the SOC image for v 4.x?

@dirkmueller do you know ?

**Comment by cmurphy** [comment]
I think this can be closed. Currently it seems the download link goes to https://www.suse.com/download/sles/ , if from there you click `AMD64/Intel 64` under Architecture you can download the `SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud-GM.qcow2` image which is what you should upload to OpenStack.

**Comment by r0ckarong** [comment]
> I think this can be closed. Currently it seems the download link goes to https://www.suse.com/download/sles/ , if from there you click `AMD64/Intel 64` under Architecture you can download the `SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud-GM.qcow2` image which is what you should upload to OpenStack.

Agreed, closing.
