### ISSUE TITLE
[doc] 3.2.1  Deploying the Cluster Nodes - novell NTP servers?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#823]
3.2.1  Deploying the Cluster Nodes

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_deploying_the_cluster_nodes

---
Should we really promote these NTP servers?

0.novell.pool.ntp.org....

**Comment by r0ckarong** [comment]
@kkaempf Do we have SUSE NTP servers or should I just change this to the general ntp pool servers?

This was written when still part of MF and thus Novell was not a voldeword yet.

**Comment by kkaempf** [comment]
> @kkaempf Do we have SUSE NTP servers

I do not know. I only know about `opensuse.org` ntp servers.

> or should I just change this to the general ntp pool servers?

I would leave specifics out and refer to `https://www.ntppool.org/en/use.html` instead. Customers usually have their local ntp servers or respective usage guides/procedures.

You must not refer to "general ntp pool servers", this is [explicitly discouraged](https://www.ntppool.org/en/vendors.html#vendor-zone)

**Comment by r0ckarong** [comment]
I guess that was the reason we used the novell. distinction these are generalized examples after all that make little sense without probable values. I will change those to 0.example.ntp.org in the config file examples.

**Comment by kkaempf** [comment]
I just checked the SLES documentation, which keeps things pretty generic:

> If a network is already configured, you can configure time synchronization with an NTP server. Click Other Settings to either alter the NTP settings or to Manually set the time. See Chapter 31, Time Synchronization with NTP for more information on configuring the NTP service. When finished, click Accept to continue the installation.

(from https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-install.html#sec-yast-install-welcome)

**Comment by r0ckarong** [comment]
Yeah but we have full terraform files as examples.
