### ISSUE TITLE
[doc] 3.3.5  Deploying VMs from the Template - second disk for /var/lib/containers missing!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#825]
3.3.5  Deploying VMs from the Template

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_deploying_vms_from_the_template

--------------------------

We recommend to have >50GB for /var/lib/containers and it seems that the vmware (and openstack?) process does not cover this.

Could we get this extended to add the second disk to both processes?

**Comment by r0ckarong** [comment]
@ereslibre @kkaempf I would think the admin can tack on additional storage as they like. Should we really go into SOC here again? Who can give me the steps on VMware to create a volume and adding it? Is this just an additional step during the template phase or does this have to be done afterwards?

**Comment by kkaempf** [comment]
If @lcavajani doesn't know, Alex Arnoldy and Christophe LeDorze from the VMware team should.

**Comment by r0ckarong** [comment]
According to Alex Arnodly: 

```
4:24 PM
I'm sure you already know or suspect that there will likely be just two answers. One is incredibly easy, and the other fairly complex.
The easy answer is to set your boot drive with the total capacity needed.
The complex answer will very likely be: 1) Create and provide another virtual disk via TF, 2) Configure cloud-init to mkfs the second disk, put it into the /etc/fstab, and then mount it.
```

@qnetter @kkaempf What is the intended method we want to focus on? Creating a 100GB boot volume sounds weird to me especially for a template that is also going to be used for master nodes. Both make the setup on VMWare more complex in any case.

**Comment by Martin-Weiss** [comment]
In my scenarios we have de-dup on the storage and we also can use thin-provisioned sometimes. So as a best practice we use 100G for all /var/lib/containers.. From the experience with CaaSP 4 plus CAP and some other deployments I already went out of disk space in /var/lib/containers with having 50G only - so now even my LAB has 75G.. 
But yes - on Masters we can "theoretically" use less for /var/lib/containers.

For the OS (not boot volume :-)) we use 50GB as best practice for BTRFS.. (otherwise snapshots get useless pretty quickly ;-))
