### ISSUE TITLE
[doc] 3.4.3  Provisioning the Cluster Nodes - number of nodes??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#826]
3.4.3  Provisioning the Cluster Nodes

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_provisioning_the_cluster_nodes

-----

    2 load balancers

    3 masters

    3 workers

--> why 2 load balancers and 3 workers where in the messages earlier in the document we have 1 load balancer and 2 workers?

**Comment by ereslibre** [comment]
A single load balancer would mean a SPOF, on an ideal setup at least two load balancers should exist. We assume that customers know how to set up this already though (e.g. using keepalived for example).

**Comment by Martin-Weiss** [comment]
I believe we discussed this already - we need 1 load balancer and that must be fault tolerant. (i.e. 1 load balancer appliance from F5 or 1 load balancer provided via a SLE-HA cluster or 1 load balancer provided as a VM made highly available by the virtualization infrastructure).

And this needs to be sync for all the deployment methods we have in the document. (number of load balancers and number of workers...)

**Comment by ereslibre** [comment]
> How do you want to control the clients traffic if you have two load balancers? How should a client do a failover from load balancer 1 to load balancer 2?

Not sure what you mean, with a VIP + keepalived?

> I believe we discussed this already

I think we did yeah... I found something here https://github.com/SUSE/doc-caasp/issues/486, maybe there's more...

**Comment by Martin-Weiss** [comment]
Yes - and we have the haproxy configs in the deployment guide with a hint to SLE-HA - so here we should just replace "2 load balancers" with "1 fault tolerant load balancer" ;-).

(I am not sure if we already support keepalived - so far we have SLE-HA with pacemaker..)

**Comment by ereslibre** [comment]
I have some doubts about the wording, I just cannot understand how 1 load balancer can be fault tolerant. I would instead say that it needs a fault tolerant load balancer system?

**Comment by Martin-Weiss** [comment]
This would also mean "1 caasp cluster is not fault tolerant" and we have to deploy "2 caasp clusters".

If you order "1 load balancer appliance" - or "1 NetApp storage system" - these systems are fault tolerant per default. 

1 load balancer service provided in a HA setup is fault tolerant.

And if you discuss this to the end - even two might not be the right solution for a three or four data-center setup :-). It always depends..

And if you setup two physical machines, install load balancer on both, put SLE-HA and pacemaker on top - you still end up with one single "virtual load balancer" - the VIP running in that cluster.. and only one IP is also a single point of failure ;-).

**Comment by ereslibre** [comment]
> This would also mean "1 caasp cluster is not fault tolerant" and we have to deploy "2 caasp clusters".

Not sure... You can certainly have a single caasp cluster with a certain failure tolerance level (depending on the etcd instances).

> If you order "1 load balancer appliance" - or "1 NetApp storage system" - these systems are fault tolerant per default.

Cannot argue there, I don't know anything about them. However this documentation was for a generic use case of setting VM's for load balancing.

> 1 load balancer service provided in a HA setup is fault tolerant.

Hm, I'm not so sure, but I also dont' want to discuss small details ad infinitum. An HA setup doesn't have to be fault tolerant...

> And if you discuss this to the end - even two might not be the right solution for a three or four data-center setup :-). It always depends..

Yes, but you need to draw the line somewhere. More advanced use cases can always rely on their knowledge, not everything can be documented.

> And if you setup two physical machines, install load balancer on both, put SLE-HA and pacemaker on top - you still end up with one single "virtual load balancer" - the VIP running in that cluster.. and only one IP is also a single point of failure ;-).

I don't understand this. I don't see how a VIP is a single point of failure if it moves across different machines when doing the failover.

**Comment by ereslibre** [comment]
In any case, we can reword the documentation so we don't state those extra nodes, just the need for a fault tolerant load balancer, would that work @Martin-Weiss?

**Comment by Martin-Weiss** [comment]
General rule of fault tolerance: one of anything is not fault tolerant ;-).
So 1 cluster, 1 data-center, 1 storage, 1 admin, 1 IP.
A single command can kill the whole CaaSP cluster - so regardless how big it is - having only one is not fault tolerant..
1 IP also can be down i.e. with ARP problems.

The question is always what RTO / RPO do you need and how to you achieve and guarantee that..

Basically the rule should be "ensure your load balancer has a higher availability than the availability you expect from your cluster". The same is true for persistent storage, virtualization infrastructure etc.
(basically do not build your house on sand)

We need one load balancer "service" that has the availability the customer requires (i.e. clustered with VIP failover or what ever technology the customer wants to have). We do NOT need "two load balancer services".

Most customers have only one load balancer and that load balancer is provided  in a high available way (what ever that means for the technology they have chosen). Also network core switches are often only "1" and the core switch itself is build in a fault tolerant way - often even in a single chassis ;-).

IMO we just should write "have a load balancer that fulfills your RTO and fault tolerance requirements"..
