### ISSUE TITLE
[doc] 4.2.5  Cluster Bootstrap - add logging examples to skuba node join etc.

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#827]
4.2.5  Cluster Bootstrap

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#cluster.bootstrap

---------------------------
In the examples we should add `-v5 |tee <nodename>-skuba-join.log` or similar so that customers have a log of what ever happens in skuba and it is easier to help our customers in case they have issues..

**Comment by r0ckarong** [comment]
@ereslibre Isn't skuba doing any logging b default during this? That doesn't sound right to me.

**Comment by cmurphy** [comment]
skuba only logs to stdout/stderr, there's no built-in way to log to disk to my knowledge. So suggesting to `| tee` or `|& tee` may be useful.

`-v5` creates debug-level logs so I wouldn't instruct customers to use it by default, but it could be mentioned in a note as an option for debugging.
