### ISSUE TITLE
[doc]    - add a disclaimer about the update / upgrade lifecycle requirements for CaaSP

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#829]
https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#id-1.2

----------------------

Customers tend to be slow in patch and upgrade of servers and systems and they must realize from the first day that in the container / k8s world it is a basic requirement to upgrade the whole stack on a regular basis and often. The recommended update/upgrade schedule IMO should be every 3 Months..

If customers do not follow this recommendation - i.e. the update only every 6 to 9 months they have to understand that after 6 or 9 months they have a support problem as their version and patchlevel might not be supported anymore and that they still have to go through all the upgrade steps in a sequential way and still will have the same effort - but do three upgrades on one day when they wait for 9 Months..

**Comment by r0ckarong** [comment]
@kkaempf @qnetter This is too hot an iron for me to try and come up with wording. Officially I am told our version support ends as soon as 2 months after the next one comes out. How can this reflect on these 3/6/9 month mentions here?

What is the actual support window that we should describe here?

What is the expectation of the docs? Backporting all fixes for docs across maybe 3-4 versions at the same time is a massive task and overhead. If customers stay with old versions of the software they will use the old version of docs.

**Comment by r0ckarong** [comment]
@kkaempf @qnetter What is the current status of the product support lifecylce? What should we describe here? We currently already basically force sequential upgrades because 4.2 -> 4.5 doesn't work in any other way.

**Comment by kkaempf** [comment]
https://www.suse.com/lifecycle/ currently says

4.2 EOL: 07 Dec 2020* (with footnote: * Users of SAP Data Intelligence: for extended support information, contact your account team.)
4.5 EOL: 31 May 2021

The [4.5 interlock slide deck](https://confluence.suse.com/pages/viewpage.action?pageId=535626270) says "Six months overlap between version 4.2 and 4.5."

**Comment by kkaempf** [comment]
I've added this topic to the agenda of the next pm/eng sync meeting

**Comment by jordimassaguerpla** [comment]
@qnetter will supply with the text https://confluence.suse.com/pages/viewpage.action?pageId=380698630

**Comment by r0ckarong** [comment]
Since there is no PM to answer this anymore: Closing.
