### ISSUE TITLE
[doc] 2  Available Documentation - architecture guide not mentioned

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#830]
2  Available Documentation

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_available_documentation

-----

It seems in this list of documentation available we miss the architecture guide.. https://susedoc.github.io/doc-caasp/master/single-html/caasp-architecture/

**Comment by r0ckarong** [comment]
Architecture guide was outdated and the rewrite is blocked by lack of engineering cycles. Unfortunately nothing I can change. Once the revamp is done this will officially be added back. Right now, it's not available publicly.

See: https://github.com/SUSE/avant-garde/issues/1344
