### ISSUE TITLE
[doc] 4.6.3.2.2  Example 2: Dex Active Directory TLS Connector Configuration -> change login for AD to samaccountname

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#832]
4.6.3.2.2  Example 2: Dex Active Directory TLS Connector Configuration

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_example_2_dex_active_directory_tls_connector_configuration

-----------------------

Email address is not a standard attribute in active directory and might be different (UPN) vs. real users email address. So in AD worlds we most often use samAccountName for logging in.

Can we give a second example or change the current example to use samAccountName instead of "usernamePrompt: Email Address" ? (also change username: mail to username: samAccountName )

**Comment by jenting** [comment]
cc @cclhsu
