### ISSUE TITLE
[doc] 4.7  Pod Security Policies - wording needs to be adjusted

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#833]
4.7  Pod Security Policies

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_pod_security_policies

-----
This is something we should adjust:

The default policies shipped with SUSE CaaS Platform are not suitable for production environments.

Customers expect that what we deliver is "production ready".

Maybe to something like this:

The default policies shipped with SUSE CaaS Platform are a good start but depending on security requirements adjustments should be made or additional policies should be created.

**Comment by r0ckarong** [comment]
Closed with #850
