### ISSUE TITLE
[doc] 4.8.1.3  Create DNS entries - add info about wildcard DNS entry

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#835]
4.8.1.3  Create DNS entries

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_create_dns_entries

...........

Most often we use wildcard DNS entries these days:

*.clustername.customerdomain. CNAME <load-balancer-FQDN>.

This way all DNS names i.e.

dashboard.clustername.customerdomain.
prometheus.clustername.customerdomain.
grafana.clustername.customerdomain.

are resolved to the load-balancer-VIP and we just specify with the ingress rules to which service the request should be forwarded.

Big value: no more future DNS entries required as all can be controlled within the cluster using ingress...

**Comment by r0ckarong** [comment]
@ereslibre Is usind DNS wildcards our recommended way to do it? If so I will change the respective places in the docs to use these wildcards instead of single purpose DNS entries.

**Comment by jenting** [comment]
> Is using DNS wildcards our recommended way to do it? 

I believe the answer is _yes_.
