### ISSUE TITLE
[doc] 4.8.2  Deploy Kubernetes Dashboard as an example - why access token?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#837]
4.8.2  Deploy Kubernetes Dashboard as an example

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_deploy_kubernetes_dashboard_as_an_example

-------
Note: Access Token -> we should not login to the dashboard with this access token.. it would be better to explain how to get the personal ID token from ~/.kube/config and use this to login to the dashboard.

**Comment by r0ckarong** [comment]
@kkaempf Who can tell me how to get this personal ID token? Is there even a permissions difference between those? I think the example was written so people can actually admin the dashboard once it's installed. Would that be possible with this personal token? If not we need to describe even more stuff about dashboard permissions and such.

**Comment by kkaempf** [comment]
apj squad (@innobead) has most knowledge around authentication. Otherwise @ereslibre might know.

**Comment by innobead** [comment]
I think the documentation is `ok` from my view and actually follow up the one way suggested by Kubernetes documentation. 

ref: https://kubernetes.github.io/dashboard/docs/user/access-control/creating-sample-user.html

But it deserves some enhancement by using user id-token from their kubeconf on hand. Let's put into the backlog to revisit later. 

cc @jenting @cclhsu @c3y1huang

**Comment by r0ckarong** [comment]
@innobead Is this still on your radar?

**Comment by innobead** [comment]
@jenting please help with this by using user `kubeconfig` instead of SA token? and have a reference to the upstream doc to let people know some alternatives they can use as well (upstream doc: https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#authentication).

ref: https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#kubeconfig

**Comment by jenting** [comment]
After research, the user's token by default does not exist in the user's ~/.kube/config, so we have to find an easy way to create the token by the user or by the admin.

**Comment by jenting** [comment]
From https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#kubeconfig

> External identity providers or certificate-based authentication are not supported at this time.

From my testing, the `admin.conf` _or_ downloaded `kubeconf` thru dex&gangway both does not exist the `token` inside, therefore, we could not log in to the Kubernetes dashboard by providing the _kubeconf_. Ref: https://stackoverflow.com/questions/48228534/kubernetes-dashboard-access-using-config-file-not-enough-data-to-create-auth-inf

So, the way I could find from now is to log in by _token_. The token is cluster-wide _or_ namespace-wide. There might be a case that a user belongs to multiple namespaces, but I could not find a way to have a single token that is cross multiple namespaces.

I could think the solution is using token and the token is either cluster-wide _or_ per-namespace, so I'd prefer not to fix the issue.

**Comment by jenting** [comment]
Instead, I've tried to deploy https://github.com/vmware-tanzu/octant and it uses _kubeconf_ to do authentication/authorization and more simple to deploy.

**Comment by innobead** [comment]
As per @jenting described, there is no way to get `token` from the kubeconfig generated from gangway/dex, because it does not exist when doing `oidc` authentication. (this is the limitation of K8s dashboard)

The only way to improve the doc is by guiding users on how to create a namespace token via service account to access the dashboard, but remember that **the generated token is totally not related to the user's kubeconfig, and it's `namespaced` only**.

**Comment by jenting** [comment]
As explained above, it's a limitation on Kubernetes dashboard but the other dashboard like octant does not have this design and constraint. I'd recommend closing this issue. What are other people thinking?

**Comment by r0ckarong** [comment]
> As explained above, it's a limitation on Kubernetes dashboard but the other dashboard like octant does not have this design and constraint. I'd recommend closing this issue. What are other people thinking?

This is a technical limitation from upstream. When this will become possible we can reconsider. Closing.
