### ISSUE TITLE
[doc] 4.10.5  Replace Server Certificate signed by a Trusted CA Certificate - kustomize changed the addon handling

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#839]
4.10.5  Replace Server Certificate signed by a Trusted CA Certificate

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_replace_server_certificate_signed_by_a_trusted_ca_certificate

--------------------
I believe this sentence is not true anymore since 4.2.0 and kustomize:

The oidc-dex and oidc-gangway server certificate and key would be replaced when skuba addon upgrade apply contains dex or gangway addon upgrade. Make sure to reapply your changes after running skuba addon upgrade apply, had you modified the default settings of oidc-dex and oidc-gangway addons.

-----

In case the modifications are in dex-patch.yaml and gangway-patch.yaml - this problem should not exist. Or do I miss something?

**Comment by Martin-Weiss** [comment]
IMO we have to adjust this via the dex-patch.yaml

      - name: dex-cert-path
        secret:
          secretName: oidc-dex-cert


--> use oidc-dex-cert-custom

and create oidc-dex-cert-custom with the customers certificate content.

And for gangway change gangway-patch.yaml

        - name: gangway-cert-path
          secret:
            secretName: oidc-gangway-cert

to
        - name: gangway-cert-path
          secret:
            secretName: oidc-gangway-cert-custom

and create oidc-gangway-cert-custom with the customers certificate content..

This way we should not have the problem with skuba addon upgrade apply anymore..

**Comment by jenting** [comment]
Thanks for your idea.

According to this limitation https://github.com/kubernetes-sigs/kustomize/issues/170 and current skuba code, the oidc-dex-cert Secret is generated in skuba code https://github.com/SUSE/skuba/blob/release-caasp-4.2.0/internal/pkg/skuba/dex/dex.go#L55-L65, not from the base manifest, and skuba allows only one base manifest for now https://github.com/SUSE/skuba/blob/release-caasp-4.2.0/internal/pkg/skuba/addons/addons.go#L329-L341.

Therefore, the above suggestion won't work _unless_ we enhance skuba code to allowing multiple manifests in base folder _or_ prepare a Secret in the base manifest.

**Comment by jenting** [comment]
The v5 will have a solution for addon certificate rotation (includes custom CA) which leverages `cert-manager`.

Personally, I'd like to use the cert-manager to cover the addon custom CA certificate scenario that the custom CA certificate won't be refresh after `skuba addon upgrade apply` instead to enhance skuba code.
