### ISSUE TITLE
[doc] 4.10.7.2  Renewing Certificates Created -> why /etc/kubernetes/pki.bak ?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#840]
4.10.7.2  Renewing Certificates Created by <code class="literal">skuba</code>:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_renewing_certificates_created_by_skuba

------

For this process I would recommend to use the skuba cluster directory on the admin node and not /etc/kubernetes/pki.bak

--> /etc/kubernetes/pki.bak does not exist on the admin node and would also not be writeable as non-root user.

So can we change the paths, here?

**Comment by jenting** [comment]
Because we based on the assumption that the admin login into one of the control plane nodes, so we suggest backup the certificate in `/etc/kubernetes/pki.bak`.

And yes, we could change to back up the certificates in the admin node.
