### ISSUE TITLE
[doc] 4.10.8.2  Self-signed Server Certificate - wording needs to be changed for self signed

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#841]
4.10.8.2  Self-signed Server Certificate

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#self_signed_certificate
---------------------
This should be changed:

Do not use self-signed certificates in production environments. There is severe risk of Man-in-the-middle attacks. Use proper trusted 3rd-party signed certificates.

To:

Make sure that in case you use self-signed certificates that the Certificate Authority used for signing is configured in a secure way as trusted Certificate Authority on the clients.

Background:

Several customers have their own CA i.e. Active Directory integrated and use this to sign certificates themselves. As they use a secure way (active directory domain join) to trust this CA and the signed certificates - the risk of Man-In-The-Middle attacks is not worth the big red warning.

**Comment by innobead** [comment]
@jenting please help with this. Thanks.
