### ISSUE TITLE
[doc] 6.1.4.2  ETCD Cluster - see issue https://github.com/SUSE/caasp-monitoring/issues/9

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#843]
6.1.4.2  ETCD Cluster

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_etcd_cluster

-----

For ETCD scraping we should use our own SSL certificate instead of one from the masters.

So we should have all we need on the skuba node and would not need to steal anything from a master.

**Comment by innobead** [comment]
@jenting please help with this, thanks. 

ref: https://github.com/SUSE/caasp-monitoring/issues/9

**Comment by jenting** [comment]
> For ETCD scraping we should use our own SSL certificate instead of one from the masters.
> 
> So we should have all we need on the skuba node and would not need to steal anything from a master.

Agree, but we still need to login to the control plane node in order to sign an ETCD client cert by ETCD CA.

**Comment by Martin-Weiss** [comment]
> 
> 
> > For ETCD scraping we should use our own SSL certificate instead of one from the masters.
> > So we should have all we need on the skuba node and would not need to steal anything from a master.
> 
> Agree, but we still need to login to the control plane node in order to sign an ETCD client cert by ETCD CA.

We have the ETCD CA key and crt in the clusters skuba pki directory on the admin node.. so we can create our own cert for ETCD health check monitoring instead of "stealing one of the masters.."

**Comment by jenting** [comment]
ok, we'll update the doc :wink:
