### ISSUE TITLE
[doc] 6.1.4.1  Prometheus Jobs - not 100% correct?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#851]
6.1.4.1  Prometheus Jobs

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_prometheus_jobs

------

I assume this is not correct: prometheus.io/port=true
-> I would expect a port number and not "true"

I am also not sure if prometheus.io/scrape=true really needs to be set as annotation on all ports as I understood that it is the default to scrape all pods per default and we just need to set "false" in case we do not want to scrape a pod. -> could this be verified?

**Comment by r0ckarong** [comment]
Closed with #854
