### ISSUE TITLE
[doc] 6.2  Health Checks - cAdvisor???

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#858]
6.2  Health Checks:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_health_checks

----
I believe this sentence needs to be removed as we do not have cAdvisor reachable anymore and we also do not have this on the admin node:

<SNIP>
A very basic (visual) health check can be achieved by accessing cAdvisor on the admin node at port 4194. This will display a basic statistics UI about the cluster resources.
</SNIP>

**Comment by r0ckarong** [comment]
@lcavajani Is this fully deprecated now? Can I remove this sentence? We still have prometheus checks against cAdvisor.

**Comment by lcavajani** [comment]
@r0ckarong yes `cAdvisor` is fully deprecated, Prometheus is using kubelet api to fetch metrics
