### ISSUE TITLE
[doc] 7.1.3  Enable Auditing On Running Cluster - how to ensure this is also forwarded via log-agent-rsyslog ?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#859]
7.1.3  Enable Auditing On Running Cluster:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_enable_auditing_on_running_cluster

--------
When enabling audit logging I assume we should configure it in a way that also allow forwarding this log to the configured central syslog server via log-agent-rsyslog.

--> what else do we have to configure to allow this?

**Comment by r0ckarong** [comment]
@c3y1huang Can you help here?

**Comment by c3y1huang** [comment]
Currently log-agent-rsyslog doesn't monitor and parse the audit log path. Yes I could help later if no one picks this up.

cc @innobead

**Comment by innobead** [comment]
This is more like a feature request, we will create a ticket on engineering backlog to proceed first.

**Comment by c3y1huang** [comment]
@Martin-Weiss the engineer team discussed in sprint review to have K8s audit log forwarding `enabled` by default. Please let me know if you disagree.
