### ISSUE TITLE
[doc] 9.1.3  Scheduling etcd Cluster Backup - example of backing up every three minutes?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#864]
9.1.3  Scheduling etcd Cluster Backup:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_scheduling_etcd_cluster_backup

------
SCHEDULE="*/3 * * * *"

--> this means to backup etcd every three minutes - does this make sense?

Maybe we should change this to once per day in the examples?

**Comment by jenting** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
Updated Kubernetes etcd cronjob example to backup daily at 1am.
