### ISSUE TITLE
Backup/Restore section wording

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#865]
Not sure if this has been addressed...apologies if it has. I didn't look at all the pull requests.

Both 9.4 and 9.5 are quite confusing. Shouldn't the installation be the same no matter where CaaSP is running?
For starters..."on on-premise" probably is not a proper statement.
It seems the titles are misleading a bit. No need to state "Kubernetes cluster". It would be the CaaSP Cluster, right?
The titles on all of the sections are misleading...
9.4.1 should read something like Backup Kubernetes objects only
9.4.1.1 should read Backup to a Cloud Provider
9.4.2 shoud read something like Backup Kubernetes objects and Volumes to Cloud Provider. Velero will backup using the provider snapshot capability to backup the volumes (aws ebs snapshots or use restic for snapshots)
The diff in these are simply the volume snapshot.
9.5 seems redundant because it won't matter where CaaSP is run. The backup process will be the same

9.4  Deployment On On-Premise:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_deployment_on_on_premise

**Comment by r0ckarong** [comment]
@innobead @jenting Could you clarify if there are any reasons (other than legibility) why we have multiple instructions for cloud and on-premise? 

Can you find more appropriate wording for the points mentioned above?

**Comment by jenting** [comment]
> @innobead @jenting Could you clarify if there are any reasons (other than legibility) why we have multiple instructions for cloud and on-premise?
> 
> Can you find more appropriate wording for the points mentioned above?

okay, the suggestion looks good at first glance, we'll discuss next week.
