### ISSUE TITLE
[doc] 4.2.3.2.2  vSphere In-tree CPI (VCP) - how to enable vsphere CPI on an existing cluster?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#869]
4.2.3.2.2  vSphere In-tree CPI (VCP):

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#cluster.bootstrap.vcp

-----

I can not find how to enable the vsphere CPI on an existing cluster.. is that documentation available, somewhere?

**Comment by r0ckarong** [comment]
@innobead

**Comment by innobead** [comment]
We don't support for enabling vSphere CPI in the existing cluster due to some changes introduced to terraform script operation. 

Do we still have this request for now? 

cc @c3y1huang

**Comment by Martin-Weiss** [comment]
> 
> 
> We don't support for enabling vSphere CPI in the existing cluster due to some changes introduced to terraform script operation.
> 
> Do we still have this request for now?
> 

Yes - all customers that are currently on VMware and that are using NFS because they do not have SES will have the need and motivation to move from NFS to VSPhere storage.

So at least we have to describe the manual steps required to enable VSphere Storage on existing CaaSP clusters in the documentation.
We also have to make sure that the VSphere CPI/CSI works well in case NO terraform is used to create the VMs.

**Comment by innobead** [comment]
I have created an issue in the engineering backlog, and let's follow up there.
