### ISSUE TITLE
[doc] 4.2.3.2.2  vSphere In-tree CPI (VCP) - in-tree vs. out-of-tree and disk.EnableUUID

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#870]
4.2.3.2.2  vSphere In-tree CPI (VCP):

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#cluster.bootstrap.vcp

------------------------------

I can see a few problems, here!

1. disk.EnableUUID seems to be required but is not mentioned anywhere. So we have to adjust the image template / terraform and also the documentation on how to create your own template

2. Based on https://cloud-provider-vsphere.sigs.k8s.io/concepts/in_tree_vs_out_of_tree.html - "in-tree" seems to be deprecated and we should / must? use out-of-tree... so is there any good reason why we document "in-tree" instead of "out-of-tree"? (maybe I misunderstand something...)

**Comment by Martin-Weiss** [comment]
Oh - and I see that VSphere 6.7 U3 seems to be required - we might have to add this requirement also to the documentation..

**Comment by r0ckarong** [comment]
@innobead

**Comment by innobead** [comment]
> 4.2.3.2.2 vSphere In-tree CPI (VCP):
> 
> https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#cluster.bootstrap.vcp
> 
> I can see a few problems, here!
> 
> 1. disk.EnableUUID seems to be required but is not mentioned anywhere. So we have to adjust the image template / terraform and also the documentation on how to create your own template

@c3y1huang I did remember you have it documented, but not sure in the official or confluence page. Please help check to see if we need to fix it. Thanks.

> 2. Based on https://cloud-provider-vsphere.sigs.k8s.io/concepts/in_tree_vs_out_of_tree.html - "in-tree" seems to be deprecated and we should / must? use out-of-tree... so is there any good reason why we document "in-tree" instead of "out-of-tree"? (maybe I misunderstand something...)

The goal is to release vSphere storage support soon, so this is why we release in-tree first then out-of-tree later. Actually the evaluation work of out-of-tree has been done, and it will be planned to release in v5.

**Comment by c3y1huang** [comment]
> Oh - and I see that VSphere 6.7 U3 seems to be required - we might have to add this requirement also to the documentation..

 VSphere 6.7 U3 is not required for in-tree vcp, but its required for out-of-tree.

**Comment by c3y1huang** [comment]
> 1. disk.EnableUUID seems to be required but is not mentioned anywhere. So we have to adjust the image template / terraform and also the documentation on how to create your own template

Provision with terraform script will automatically enable `disk.EnableUUID`. But sure we could add this to doc.

**Comment by innobead** [comment]
> > Oh - and I see that VSphere 6.7 U3 seems to be required - we might have to add this requirement also to the documentation..
> 
> VSphere 6.7 U3 is not required for in-tree vcp, required only for out-of-tree.

@c3y1huang to confirm for smooth upgrading to out-of-tree, should we require vSphere 6.7 U3 at the beginning even when using in-tree?

**Comment by c3y1huang** [comment]
> > > Oh - and I see that VSphere 6.7 U3 seems to be required - we might have to add this requirement also to the documentation..
> > 
> > 
> > VSphere 6.7 U3 is not required for in-tree vcp, required only for out-of-tree.
> 
> @c3y1huang to confirm for smooth upgrading to out-of-tree, should we require vSphere 6.7 U3 at the beginning even when using in-tree?

IMO is not necessary as we've already included `hardware_version` to terraform vars. This allows user to upgrade their vsphere tmx to the required version using  `terraform apply`.

**Comment by Martin-Weiss** [comment]
Please keep in mind that VMware deployments are NOT guaranteed to be done using terraform. Many customers have their own frameworks to install their servers.

And in my case - terraform did NOT enable the disk.enableUUID - maybe this was added later?

Is the in-tree fully supported also by VMware and against 7.0 and newer?
(it would be bad if i.e. VCenter or ESXi would crash when using the in-tree version)

**Comment by c3y1huang** [comment]
> And in my case - terraform did NOT enable the disk.enableUUID - maybe this was added later?
Please set `cpi_enable = true` in your tfvar. Ref: https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_using_terraform
> 
> Is the in-tree fully supported also by VMware and against 7.0 and newer?
> (it would be bad if i.e. VCenter or ESXi would crash when using the in-tree version)
iirc its been tested on 6.7 and 6.7 U3. cc @maximenoel8

**Comment by Martin-Weiss** [comment]
> > And in my case - terraform did NOT enable the disk.enableUUID - maybe this was added later?
> 
> Please set `cpi_enable = true` in your tfvar. Ref: https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_using_terraform
> 

My terraform copy does not include this - seems we need to document how to upgrade and adjust terraform after updating the skuba rpm..

--> how to update terraform and all deployment systems with it from CaaSP 4.1.x to terraform CaaSP 4.2.x.?

> > Is the in-tree fully supported also by VMware and against 7.0 and newer?
> > (it would be bad if i.e. VCenter or ESXi would crash when using the in-tree version)
> 
> AFAK its been tested on `6.7` and `6.7 U3`. And I am not sure how in-tree would crash the VCenter or ESXi, could you share more info on that so our QA could be better prepared? /cc @maximenoel8

I really believe we have to add a chapter in the requirements section or in the CPI/CSI section for VMware that describes what is supported by SUSE and by the feature similar to this:

https://vsphere-csi-driver.sigs.k8s.io/compatiblity_matrix.html
https://vsphere-csi-driver.sigs.k8s.io/supported_features_matrix.html
https://vsphere-csi-driver.sigs.k8s.io/limits.html

And we also have to clarify what is supported by VMware.. - so what should a customer do i.e. in case ESXi and/or VSPhere crash when using our in-tree version..

**Comment by innobead** [comment]
> > > And in my case - terraform did NOT enable the disk.enableUUID - maybe this was added later?
> > 
> > 
> > Please set `cpi_enable = true` in your tfvar. Ref: https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_using_terraform
> 
> My terraform copy does not include this - seems we need to document how to upgrade and adjust terraform after updating the skuba rpm..
> 
> --> how to update terraform and all deployment systems with it from CaaSP 4.1.x to terraform CaaSP 4.2.x.?
> 
> > > Is the in-tree fully supported also by VMware and against 7.0 and newer?
> > > (it would be bad if i.e. VCenter or ESXi would crash when using the in-tree version)
> > 
> > 
> > AFAK its been tested on `6.7` and `6.7 U3`. And I am not sure how in-tree would crash the VCenter or ESXi, could you share more info on that so our QA could be better prepared? /cc @maximenoel8
> 
> I really believe we have to add a chapter in the requirements section or in the CPI/CSI section for VMware that describes what is supported by SUSE and by the feature similar to this:
> 
> https://vsphere-csi-driver.sigs.k8s.io/compatiblity_matrix.html
> https://vsphere-csi-driver.sigs.k8s.io/supported_features_matrix.html
> https://vsphere-csi-driver.sigs.k8s.io/limits.html
> 
> And we also have to clarify what is supported by VMware.. - so what should a customer do i.e. in case ESXi and/or VSPhere crash when using our in-tree version..

vSphere cloud provider integration is more about client operation with vSphere server-side ( ESXi/cluster), so it's common as other clients do. If anything goes wrong, it definitely relates to the operation failure between both sides. 

Basically, we should focus on the scope of CaaSP cluster itself.  For example, if PVC for vSphere block storage is not bound to a PV, the way to troubleshoot should be the same as general as other volume provisions. Other than that, all things just relate to vSphere.
