### ISSUE TITLE
[doc] 4.10.5  Replace Server Certificate signed by a Trusted CA Certificate

### ISSUE THREAD

**Issue by adianas** [SUSE/doc-caasp#871]
4.10.5  Replace Server Certificate signed by a Trusted CA Certificate:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_replace_server_certificate_signed_by_a_trusted_ca_certificate

Is it still necessary to reapply the changes made (custom server certs) to  oidc-dex and oidc-gangway after each cluster upgrade or is not longer needed if you use kustomize to re-apply the changes.

**Comment by r0ckarong** [comment]
@innobead @jenting Can you help with this please?

**Comment by r0ckarong** [comment]
This is actually a duplicate of #839 
Closing, please follow the other issue.
