### ISSUE TITLE
[doc] 2.2  Bootstrap and Initial Configuration

### ISSUE THREAD

**Issue by Johngoutbeck** [SUSE/doc-caasp#876]
2.2  Bootstrap and Initial Configuration:

https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_cluster_management.html#_bootstrap_and_initial_configuration

Please add example 'skuba cluster init' syntax/line
and
Please add example 'skuba node bootstrap ' syntax/line

just like in section 2.3

**Comment by r0ckarong** [comment]
@Klaven Is this something you could look at?

**Comment by r0ckarong** [comment]
CaaSP is in maintenance mode and only hi-prio security fixes will be added. Closing.
