### ISSUE TITLE
[doc] 3.1.3  Unique Machine IDs

### ISSUE THREAD

**Issue by Johngoutbeck** [SUSE/doc-caasp#880]
3.1.3  Unique Machine IDs:

https://documentation.suse.com/suse-caasp/4.1/html/caasp-deployment/_deployment_instructions.html#machine-id

The 3 run commands do NOT change the machine-id
need to delete or rename the machine-id file, then the 3 run commands

so add the command
rm /etc/machine-id before the 3 run commands

**Comment by r0ckarong** [comment]
I will update the wording for future versions but I wonder how you missed both places in the same section that tell you to remove (or have removed) the file beforehand.

**Comment by Johngoutbeck** [comment]
Sometimes I'm blind in 1 eye and cant see out the other
