### ISSUE TITLE
[doc] 4.2.3.3  Example vSphere Cloud Provider Configuration - folder must be specified!

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#884]
4.2.3.3  Example vSphere Cloud Provider Configuration:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#_example_vsphere_cloud_provider_configuration

------------
I have not created and folder nor put VMs into a folder. So I assumed I can leave "folder" empty or even remove this parameter. But unfortunately with the in-tree vsphere CSI the kubelet does not start if folder="" is specified in vsphere.conf!

(with the out-of-tree - not specifying the folder is NO problem!)

I am not sure if this is a bug or if we should specify "folder = "Default"" instead. At least with "folder="Default"" - the kubelet starts.

So could we clarify what the right setting is for folder and add this to the documentation?
(just in case someone else also does not create special folders for the VMs)

**Comment by r0ckarong** [comment]
@kkaempf @lcavajani  Who can check if this is a bug?

**Comment by kkaempf** [comment]
Vsphere cloud provider is owned by @innobead and @c3y1huang ;-)

**Comment by innobead** [comment]
@c3y1huang please help with this. Thanks.

**Comment by c3y1huang** [comment]
The folder in the cloud-config is used by the VCP storage class persistent volume claim only. You can input any value to the `folder` if only intend to use for in-line and persistent volume. 

Out-of-tree does not require this kind of folder structure as the driver was completely re-written with another library to call for the vCenter entity.

**Comment by Martin-Weiss** [comment]
What do I have to enter for "folder" if I have NO folder created and the machines are in the "root"?

**Comment by c3y1huang** [comment]
> What do I have to enter for "folder" if I have NO folder created and the machines are in the "root"?

The VMs created by default should have a path look like: 
```
/PROVO/vm/caasp-master-1
```

You need to manually create a folder in vCenter and move the cluster node VMs inside.

The new path should looks like:
```
/PROVO/vm/caasp-cluster/caasp-master-1
```
`.

**Comment by Martin-Weiss** [comment]
I do not want to have a folder - so the machines should be in the default place where VMs get created.
So what do I need to specify for the "folder" variable to create all VMs in the default root?
(where also new VMs are created with an undefined folder using the out-of-tree CSI)

**Comment by innobead** [comment]
As per @c3y1huang explained, the folder is necessary for in-tree VCP, so there is nothing we can do for the non-folder case, except migrating to out-of-tree in the future.
