### ISSUE TITLE
[doc] 6.1.3.1.5  Adding Grafana Dashboards - adding custom / own certificates

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#886]
6.1.3.1.5  Adding Grafana Dashboards:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#adding_grafana_dashboards

-----

We explain how to monitor custom certificates / add them to the exporter - but we do not explain how to add these to the dashboard..

In the prometheus and grafana explanations we describe how to create and add ingress ssl certificates - maybe we should add these per default, too?

**Comment by jenting** [comment]
> We explain how to monitor custom certificates / add them to the exporter - but we do not explain how to add these to the dashboard..
It would be shown in "Secret PKI Certs Expiry".
 
> In the prometheus and grafana explanations we describe how to create and add ingress ssl certificates - maybe we should add these per default, too?
Good suggestion. It needs to add label/annotation to the ingress SSL and configures the cert-exporter to monitors the SSL certificates.

**Comment by innobead** [comment]
> > We explain how to monitor custom certificates / add them to the exporter - but we do not explain how to add these to the dashboard..
> 
> It would be shown in "Secret PKI Certs Expiry".
> 

So as per @jenting comment, I think there is no problem for now for this issue.

> > In the prometheus and grafana explanations we describe how to create and add ingress ssl certificates - maybe we should add these per default, too?
> 
> Good suggestion. It needs to add label/annotation to the ingress SSL and configures the cert-exporter to monitors the SSL certificates.

There is no operator for now for helping this kind of logic, so we should tackle this in another ticket on avant-garde in the future.

Closing, if still have any question, feel free to reopen.
