### ISSUE TITLE
[doc] 6.1.1  Introduction

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#889]
6.1.1  Introduction:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_introduction_3

This section can be a bit confusing because we now have a Kubernetes metrics-server in addition to Prometheus/Grafana where Prometheus is defined as a "metrics server". May wish to delineate in some form? For instance the k8s metrics server is utilized only for HPA/VPA where Prometheus is what *should* be used for gathering widescale metrics.

**Comment by r0ckarong** [comment]
Note to self: Add HPA VPA abbreviations to glossary.

**Comment by r0ckarong** [comment]
@kkaempf Who can give me more insights into how the different metrics servers are used?

**Comment by kkaempf** [comment]
https://github.com/SUSE/avant-garde/issues/915 shows @ereslibre and @lcavajani should have knowledge.

**Comment by lcavajani** [comment]
`metrics-server` does not have the same purpose as Prometheus. `metrics-server` collects metrics in-memory so it's not possible to forward them somewhere else and use them like Prometheus does. Unlike Prometheus, `metrics-server` is not a monitoring solution.

From the `metrics-server` official doc, it says:

```
Use cases:

You can use Metrics Server for:

    CPU/Memory based horizontal autoscaling (learn more about Horizontal Pod Autoscaler)
    Automatically adjusting/suggesting resources needed by containers (learn more about Vertical Pod Autoscaler)

Don't use Metrics Server when you need:

    Non-Kubernetes clusters
    An accurate source of resource usage metrics
    Horizontal autoscaling based on other resources then CPU/Memory
```

It is also used to provide metrics when using `kubect trop node|nodes` and `kubectl top pods|pod`.

Official Prometheus doc:

```
Prometheus however is a full monitoring and trending system that includes built-in and active scraping, storing, querying, graphing, and alerting based on time series data.
```

**Comment by r0ckarong** [comment]
@innobead While working on this i noticed that we provide steps to change the metric-server cert but not list it in addon certs list. Could you please review the certificates section and amend what is missing?

https://github.com/SUSE/doc-caasp/blame/master/adoc/admin-security-certificates.adoc#L116

**Comment by jenting** [comment]
> @innobead While working on this i noticed that we provide steps to change the metric-server cert but not list it in addon certs list. Could you please review the certificates section and amend what is missing?
> 
> https://github.com/SUSE/doc-caasp/blame/master/adoc/admin-security-certificates.adoc#L116

I remember I had added the metrics-server certificate in the add-on certificates list.

* master branch
![image](https://user-images.githubusercontent.com/49380831/89482256-0c6d2080-d7cc-11ea-92f2-4bad40f0e351.png)
* maintenance/CaaS4 branch
![image](https://user-images.githubusercontent.com/49380831/89482343-3fafaf80-d7cc-11ea-825e-3ac102ff3be9.png)

**Comment by r0ckarong** [comment]
> > @innobead While working on this i noticed that we provide steps to change the metric-server cert but not list it in addon certs list. Could you please review the certificates section and amend what is missing?
> > https://github.com/SUSE/doc-caasp/blame/master/adoc/admin-security-certificates.adoc#L116
> 
> I remember I had added the metrics-server certificate in the add-on certificates list.
> 
>     * master branch
>       ![image](https://user-images.githubusercontent.com/49380831/89482256-0c6d2080-d7cc-11ea-92f2-4bad40f0e351.png)
> 
>     * maintenance/CaaS4 branch
>       ![image](https://user-images.githubusercontent.com/49380831/89482343-3fafaf80-d7cc-11ea-825e-3ac102ff3be9.png)

My bad, sorry. Must've missed this :/
