### ISSUE TITLE
[doc] 4 Bootstrapping the Cluster - skuba addons directory is currently not document

### ISSUE THREAD

**Issue by JanZerebecki** [SUSE/doc-caasp#910]
The existing skuba addons directory is currently not document: https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#bootstrap https://github.com/SUSE/doc-caasp/blob/master/adoc/deployment-bootstrap.adoc

https://github.com/SUSE/skuba/pull/1127 added support for the addons/containers directory.

This documentation about the addons direcotory could be linked as a mention that it is possible to deploy /etc/containers/registries.conf via skuba in: https://github.com/SUSE/doc-caasp/blob/master/adoc/admin-crio-registries.adoc https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_configuring_container_registries_for_cri_o

**Comment by r0ckarong** [comment]
@JanZerebecki Some questions: 

1. How would a user "use" the addons directory during deployment? Will they put addons/configs there and then be able to do something in skuba to deploy these? If so, what are the steps?
2. If we mention that you can deploy the registry config file via skuba, what are the steps to do so?

**Comment by JanZerebecki** [comment]
1. After `skuba cluster init my-cluster` a user can add/edit the following files in the `my-cluster` directory. They will be copied during `skuba node bootstrap`. Each addons/crio.conf.d/*.conf file will be copied to /etc/crio/crio.conf.d/ on each node. If it exists a file addons/containers/registries.conf it will be copied to /etc/containers/registries.conf on each node.
2. Place the file my-cluster/addons/containers/registries.conf according to 1. and with the content as described in https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_configuring_container_registries_for_cri_o .

**Comment by r0ckarong** [comment]
@ereslibre What other items can be customized this way and can they be updated just like the other kustomize workflow once the cluster is running?

**Comment by JanZerebecki** [comment]
The files are also copied in the same way during `skuba node upgrade apply` and `skuba node join`.

Not sure what "updated just like the other kustomize workflow" refers to, is that already documented somewhere?

**Comment by r0ckarong** [comment]
> Not sure what "updated just like the other kustomize workflow" refers to, is that already documented somewhere?

Not really, we have various places in the deployment instructions that refer how you can modify various aspects using kustomize but I don't think we fully described this functionality. Part of the PR for closing this issue would be a generalized description how kustomize works and how it can be used. For that I need some more info which kinds of changes can be made.

So far we have the files for kured and dex from `adoc/deployment-bootstrap.adoc`, then the registries.conf and crio.conf.d files, all the base addons. I just haven't fully understoof what else can be overwritten.

**Comment by JanZerebecki** [comment]
I don't think changing the configuration without an upgrade was thought of, but may just work the same way, but I have not tested that.

The docs for crio.conf.d is at https://github.com/cri-o/cri-o/blob/master/docs/crio.conf.5.md or `man crio.conf` on the installed system.

There is no additional config copied from the addons directory like what I already listed above. But there is some functionality I'm not familiar with in https://github.com/SUSE/skuba/blob/master/internal/pkg/skuba/addons/addons.go that refers to the addons directory. That is probably the namesake of the directory and the configuration files are just using the addons directory for a different purpose.

**Comment by r0ckarong** [comment]
@kkaempf @jordimassaguerpla @ereslibre Who can clarify that addons directory usage?

**Comment by jenting** [comment]
> @JanZerebecki Some questions:
> 
> 1. How would a user "use" the addons directory during deployment? Will they put addons/configs there and then be able to do something in skuba to deploy these? If so, what are the steps?

Generally, the user would prepare the kustomize patch to overwrite the default base addon manifest configuration.
There is some example to overwrite the dex OIDC connector in the doc already.

> 2. If we mention that you can deploy the registry config file via skuba, what are the steps to do so?
