### ISSUE TITLE
Document Istio

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#915]
Istio is a service mesh component for securing, connecting, and monitoring microservices. 

@manuelbuil is the coordinator of the release of Istio in CaaSP
official documentation: https://istio.io/latest/docs/concepts/what-is-istio/
internal docs: https://confluence.suse.com/display/CaaSP/Istio

For starters we need the following input: 

1. Intro
    What is it? What are it's functions? What does it add do CaaSP?
3. Installation (specific to CaaSP) 
4. Usage/Debug
5. Uninstall 

Open questions: 
When is it scheduled to be released? 
How to integrate it into the Admin Guide?

**Comment by nkoranova** [comment]
https://confluence.suse.com/pages/viewpage.action?pageId=532906191

**Comment by manuelbuil** [comment]
https://github.com/SUSE/doc-caasp/pull/936

**Comment by r0ckarong** [comment]
CaaSP is in maintenance and only hi-prio security fixes are going to be added.
