### ISSUE TITLE
Re-add PR #923 (Enhance skuba addon upgrade plan)

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#938]
Prematurely merged #923 and reverted. Needs to be added back.

**Comment by jordimassaguerpla** [comment]
Putting the on hold label: Merge when the feature is ready to be released (probably first maintenance update).

**Comment by jenting** [comment]
Ref to https://github.com/SUSE/avant-garde/issues/1765

**Comment by jenting** [comment]
This is ready to be reviewed https://github.com/SUSE/avant-garde/issues/1765#issuecomment-707826526

**Comment by jenting** [comment]
@r0ckarong please help on adding this, thank you :bow:

**Comment by r0ckarong** [comment]
Done with https://github.com/SUSE/doc-caasp/commit/2519e1ebd1e6f648f766d855ac8e5e59dd88ecd4 and prepared with https://github.com/SUSE/doc-caasp/commit/245f751d375397bcedbe531711abd4831cc2cb72
