### ISSUE TITLE
remove not 5.0.0 features

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#939]
Hi,
features in skuba master branch are not all in 5.0.0, only those present in release-caasp-5.0.0, which was branched when we built the Release Candidate.

I went through the latest commits and added the label remove_from_5.0.0 to those that need to be removed for 5.0.0.

https://github.com/SUSE/doc-caasp/pulls?q=is%3Apr+is%3Aclosed+label%3Aremove_from_5.0.0

Please either revert them or create a release-caasp-5.0.0 branch without them.

thanks

**Comment by r0ckarong** [comment]
Reverted the specified PRs.
