### ISSUE TITLE
[doc] 6.4.3.7  Deploying Stratos

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#953]
6.4.3.7  Deploying Stratos:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_deploying_stratos

Step 1 is no longer true. Now you get a screen asking you if you want to use UAA or create an account. If you create a default account, it will not use the password in the values file.

Also, should you go one step further and tell them how to connect Stratos to CaaSP because that isn't done automatically or at least point them directly to the howto for that in the CAP documentation?

**Comment by r0ckarong** [comment]
I have no experience with either CAP or Stratos. Who can help me here with how this should be done? 

@tgeek77 Can you provide me with these additional steps that now would be correct?

From what I understand the CAP docs describe how to deploy on CaaSP but I don't know enough about it to judge if it's enough to just link the instructions or if those are too specific for general use cases. 

@kkaempf Who can tell me more about this?
