### ISSUE TITLE
[doc] 5.6  Configuring an External LDAP Server

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-caasp#966]
5.6  Configuring an External LDAP Server:

https://documentation.suse.com/suse-caasp/4.2/html/caasp-admin/_security.html#_configuring_an_external_ldap_server

It seems external LDAP server is required to enable administrator to add multiple users to the CaaSP cluster for authentication. This means it should be stated as as system requirement if the users want to add new user account? Currently the enterprise users who evaluate the CaaSP found this part confusing and not clear enough to prepare for production readiness.

**Comment by r0ckarong** [comment]
@innobead Could you help me with this? Thanks.
