### ISSUE TITLE
[CAP on CaaSP] Figure out load balancer / ingress combination for on-prem

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#970]
From @alexarnoldy

We recently went through a round of testing with CAP installed on CaaSP with Nutanix as the infrastructure provider. One of the biggest problems we encountered wasn't even about interfacing with Nutanix (though that did take a while to work out).

The problem we found is that the preferred method of deploying CAP requires an ingress controller to manage an application load balancer. Unfortunately, there's nothing in the CaaSP or CAP deployment docs that show how to do that with an on-premise installation.

The CAP deployment doc points to the HAProxy and Nginx load balancer portions of the CaaSP deployment doc. The problem there is, I can't find any ingress controller that will interface with either of those LBs. The CAP doc says the Nginx Ingress Controller is the only one that has been verified to be compatible with CAP. However, the only on-premise load balancer that the Nginx Ingress Controller will interface with is MetalLB.

I've been working with Louis Paul, Claudio Serrano, and Andrew Gracey to figure out how to bridge that gap.

Please have a look at these two docs that we've put together. The first one really could go in either deployment guide, but if we were to adapt it (1) for use in the CaaSP deployment guide, it would allow for the ingress controller + load balancer to be used for other applications when CaaSP is deployed without a cloud-like application load balancer available. MetalLB is still on CaaSP Engineering's To-do list so initially we would have to recommend that it be used in Pre-Production stages.

The second doc (2) is much more basic. It primarily shows how to programmatically build up a minimum kubecf-config-values.yaml file. One of the problems we ran into in deploying CAP was getting that file formatted correctly. It's a very manual, and error prone, task to get the spacing right on each line of the certificates and private keys.

These docs aren't meant to be the answer, but rather start a conversation about how we might resolve this very noticeable gap in our product set.

[1] https://github.com/alexarnoldy/CaaSP/blob/master/Nutanix/Nginx_Ingress_Controller_and_MetalLB.adoc
[2] https://github.com/alexarnoldy/CaaSP/blob/master/Nutanix/Prepare_for_CAP_Installation_on_CaaSP.adoc

**Comment by r0ckarong** [comment]
@qnetter @kkaempf @ereslibre What can we do about this from our side? The instructions must be adjusted on the CAP end but is there a supported scenario? What does it look like and how can it be done? Is this anything we can do?

/ cc @alexarnoldy

**Comment by dirkmueller** [comment]
Whats not working with ingress-nginx ? that should be working with caasp and CAP on nutanix.

**Comment by manuelbuil** [comment]
metalLB or any other load-balancer solution to provide an external IP to the ingress controller is not going to be supported in CaaSP (at least as of today)

**Comment by r0ckarong** [comment]
Given the current situation and resources, this won't be possible to tackle further at the moment.

**Comment by alexarnoldy** [comment]
I understand completely. I appreciate you letting me know.

Best,

--Alex.


________________________________
