### ISSUE TITLE
[doc] 1.2.6.1  Mirror Configuration

### ISSUE THREAD

**Issue by dff1980** [SUSE/doc-caasp#973]
1.2.6.1  Mirror Configuration:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/index.html#airgap-container_registry-mirror

"egistry.suse.com/caasp/v4.5/etcd" instead "registry.suse.com/caasp/v4.5/etcd"
In a table in a row "KUBEADM | etcd | egistry.suse.com/caasp/v4.5/etcd"

**Comment by r0ckarong** [comment]
Fixed with 73526e0
