### ISSUE TITLE
[doc] 3.2.1  Initializing the Cluster

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-caasp#980]
3.2.1  Initializing the Cluster:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_initializing_the_cluster

The init command is missing "--cloud-provider aws" as it's needed to use the AWS CPI

**Comment by jenting** [comment]
We have it at https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-deployment/#_amazon_web_services_aws_cpi
