### ISSUE TITLE
[doc] 4.2.1  Deploying the Cluster Nodes

### ISSUE THREAD

**Issue by gfigueira** [SUSE/doc-caasp#983]
4.2.1  Deploying the Cluster Nodes:

https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_deploying_the_cluster_nodes

Down in this section, there is an "Important" point about noting down the ips/fdqns of the resources. This is right after the "terraform appy" step. Isn't it redundant to have this note here? After the terraform apply you will see all the info you need.

**Comment by r0ckarong** [comment]
This box just explains how you can find the IPs for the nodes you deployed again. It's best practice to have some sort of "operations manual" that documents everything about the software you deployed and that would include the IPs for the nodes. If you don't have that you might need to find the IPs again and this is the quick way to do it.
