### ISSUE TITLE
[doc] 6.9.4  Monitoring Certificates -> ${RELEASE_NAME}

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#993]
6.9.4  Monitoring Certificates:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_monitoring_certificates

--> seems that the variable RELEASE_NAME is not defined..

**Comment by r0ckarong** [comment]
@cclhsu I believe you wrote most of the monitoring docs originally. Is `${RELEASE_NAME}` a placeholder for the respective commands or should this have been exported to an environment variable somewhere? I can't find a variable declaration anywhere.

**Comment by cclhsu** [comment]
> @cclhsu I believe you wrote most of the monitoring docs originally. Is `${RELEASE_NAME}` a placeholder for the respective commands or should this have been exported to an environment variable somewhere? I can't find a variable declaration anywhere.

I am not sure original owner is, but `RELEASE_NAME` is  just a bash variable with user defined name for helm deployment.

**Comment by r0ckarong** [comment]
> > @cclhsu I believe you wrote most of the monitoring docs originally. Is `${RELEASE_NAME}` a placeholder for the respective commands or should this have been exported to an environment variable somewhere? I can't find a variable declaration anywhere.
> 
> I am not sure original owner is, but `RELEASE_NAME` is just a bash variable with user defined name for helm deployment.

And this is the name you later use to easier access a given helm deployment, right? Then I should change this to something more sensible.

**Comment by r0ckarong** [comment]
The reason this was used is that helm (unhelpfully) chose to re-coin the term "release" as the instance of an installed chart that is actively maintained in the cluster (basically, what "deployment" is in Kubernetes terms). This means you can give each installation a separate name and this is what $RELEASE_NAME is referring to here. Not even an environment variable but a placeholder for the name you pick for this chart installation.
